import Foundation

/// One entry in the bundled flag catalog.
///
/// `askable` is false for a handful of dependencies whose official flag is
/// byte-identical to their parent state's (Bouvet Island and Svalbard fly the
/// Norwegian flag, Saint Martin the French tricolour, the U.S. Minor Outlying
/// Islands the Stars and Stripes). They stay in the catalog so the images ship,
/// but they are never asked and never offered as an answer choice.
///
/// `confusable` lists codes whose flag is close enough at phone size that
/// offering them together would be a coin flip rather than a question. The list
/// was measured, not guessed: every pair with a mean per-channel difference
/// below 12 on a 24x16 downsample of the shipped artwork.
struct FlagEntry: Sendable {
    let code: String
    let name: String
    let difficulty: TriviaDifficulty
    let askable: Bool
    let confusable: Set<String>

    var asset: String { "flag-\(code.lowercased())" }

    init(_ code: String, _ name: String, _ difficulty: TriviaDifficulty,
         askable: Bool = true, confusable: Set<String> = []) {
        self.code = code
        self.name = name
        self.difficulty = difficulty
        self.askable = askable
        self.confusable = confusable
    }
}

enum FlagCatalog {
    /// All 249 flags shipped in the asset catalog, ordered by difficulty then name.
    static let all: [FlagEntry] = [
        FlagEntry("AR", "Argentina", .easy),
        FlagEntry("AU", "Australia", .easy, confusable: ["NZ"]),
        FlagEntry("AT", "Austria", .easy),
        FlagEntry("BE", "Belgium", .easy),
        FlagEntry("BR", "Brazil", .easy),
        FlagEntry("CA", "Canada", .easy),
        FlagEntry("CL", "Chile", .easy),
        FlagEntry("CN", "China", .easy),
        FlagEntry("CO", "Colombia", .easy),
        FlagEntry("CU", "Cuba", .easy),
        FlagEntry("CZ", "Czechia", .easy),
        FlagEntry("DK", "Denmark", .easy),
        FlagEntry("EG", "Egypt", .easy, confusable: ["IQ", "YE"]),
        FlagEntry("FI", "Finland", .easy),
        FlagEntry("FR", "France", .easy),
        FlagEntry("DE", "Germany", .easy),
        FlagEntry("GR", "Greece", .easy),
        FlagEntry("IS", "Iceland", .easy),
        FlagEntry("IN", "India", .easy),
        FlagEntry("ID", "Indonesia", .easy),
        FlagEntry("IE", "Ireland", .easy),
        FlagEntry("IL", "Israel", .easy),
        FlagEntry("IT", "Italy", .easy),
        FlagEntry("JM", "Jamaica", .easy),
        FlagEntry("JP", "Japan", .easy),
        FlagEntry("KE", "Kenya", .easy),
        FlagEntry("MX", "Mexico", .easy),
        FlagEntry("MA", "Morocco", .easy),
        FlagEntry("NL", "Netherlands", .easy),
        FlagEntry("NZ", "New Zealand", .easy, confusable: ["AU", "CK", "GS", "KY", "MS", "PN", "SH", "VG"]),
        FlagEntry("NG", "Nigeria", .easy),
        FlagEntry("NO", "Norway", .easy),
        FlagEntry("PK", "Pakistan", .easy),
        FlagEntry("PE", "Peru", .easy),
        FlagEntry("PH", "Philippines", .easy),
        FlagEntry("PL", "Poland", .easy),
        FlagEntry("PT", "Portugal", .easy),
        FlagEntry("RU", "Russia", .easy),
        FlagEntry("SA", "Saudi Arabia", .easy),
        FlagEntry("ZA", "South Africa", .easy),
        FlagEntry("KR", "South Korea", .easy),
        FlagEntry("ES", "Spain", .easy),
        FlagEntry("SE", "Sweden", .easy),
        FlagEntry("CH", "Switzerland", .easy),
        FlagEntry("TH", "Thailand", .easy),
        FlagEntry("TR", "Turkey", .easy),
        FlagEntry("UA", "Ukraine", .easy),
        FlagEntry("GB", "United Kingdom", .easy),
        FlagEntry("US", "United States", .easy),
        FlagEntry("VN", "Vietnam", .easy, confusable: ["KG"]),
        FlagEntry("AF", "Afghanistan", .medium),
        FlagEntry("AL", "Albania", .medium),
        FlagEntry("DZ", "Algeria", .medium),
        FlagEntry("AD", "Andorra", .medium),
        FlagEntry("AO", "Angola", .medium),
        FlagEntry("AM", "Armenia", .medium),
        FlagEntry("AZ", "Azerbaijan", .medium),
        FlagEntry("BS", "Bahamas", .medium),
        FlagEntry("BH", "Bahrain", .medium),
        FlagEntry("BD", "Bangladesh", .medium),
        FlagEntry("BB", "Barbados", .medium),
        FlagEntry("BY", "Belarus", .medium),
        FlagEntry("BO", "Bolivia", .medium),
        FlagEntry("BA", "Bosnia and Herzegovina", .medium),
        FlagEntry("BW", "Botswana", .medium),
        FlagEntry("BN", "Brunei", .medium),
        FlagEntry("BG", "Bulgaria", .medium),
        FlagEntry("KH", "Cambodia", .medium),
        FlagEntry("CM", "Cameroon", .medium),
        FlagEntry("CR", "Costa Rica", .medium),
        FlagEntry("HR", "Croatia", .medium),
        FlagEntry("CY", "Cyprus", .medium),
        FlagEntry("DO", "Dominican Republic", .medium),
        FlagEntry("EC", "Ecuador", .medium),
        FlagEntry("SV", "El Salvador", .medium),
        FlagEntry("EE", "Estonia", .medium),
        FlagEntry("ET", "Ethiopia", .medium),
        FlagEntry("FJ", "Fiji", .medium),
        FlagEntry("GE", "Georgia", .medium),
        FlagEntry("GH", "Ghana", .medium),
        FlagEntry("GT", "Guatemala", .medium),
        FlagEntry("HT", "Haiti", .medium),
        FlagEntry("HN", "Honduras", .medium),
        FlagEntry("HU", "Hungary", .medium),
        FlagEntry("IR", "Iran", .medium),
        FlagEntry("IQ", "Iraq", .medium, confusable: ["EG", "YE"]),
        FlagEntry("CI", "Ivory Coast", .medium),
        FlagEntry("JO", "Jordan", .medium),
        FlagEntry("KZ", "Kazakhstan", .medium),
        FlagEntry("KW", "Kuwait", .medium),
        FlagEntry("KG", "Kyrgyzstan", .medium, confusable: ["VN"]),
        FlagEntry("LA", "Laos", .medium),
        FlagEntry("LV", "Latvia", .medium),
        FlagEntry("LB", "Lebanon", .medium, confusable: ["PF"]),
        FlagEntry("LY", "Libya", .medium),
        FlagEntry("LI", "Liechtenstein", .medium),
        FlagEntry("LT", "Lithuania", .medium),
        FlagEntry("LU", "Luxembourg", .medium),
        FlagEntry("MG", "Madagascar", .medium),
        FlagEntry("MY", "Malaysia", .medium),
        FlagEntry("MT", "Malta", .medium),
        FlagEntry("MD", "Moldova", .medium),
        FlagEntry("MC", "Monaco", .medium),
        FlagEntry("MN", "Mongolia", .medium),
        FlagEntry("ME", "Montenegro", .medium),
        FlagEntry("MZ", "Mozambique", .medium),
        FlagEntry("MM", "Myanmar", .medium),
        FlagEntry("NA", "Namibia", .medium),
        FlagEntry("NP", "Nepal", .medium),
        FlagEntry("NI", "Nicaragua", .medium),
        FlagEntry("KP", "North Korea", .medium),
        FlagEntry("MK", "North Macedonia", .medium),
        FlagEntry("OM", "Oman", .medium),
        FlagEntry("PA", "Panama", .medium),
        FlagEntry("PG", "Papua New Guinea", .medium),
        FlagEntry("PY", "Paraguay", .medium),
        FlagEntry("QA", "Qatar", .medium),
        FlagEntry("RO", "Romania", .medium, confusable: ["TD"]),
        FlagEntry("SM", "San Marino", .medium),
        FlagEntry("SN", "Senegal", .medium),
        FlagEntry("RS", "Serbia", .medium),
        FlagEntry("SG", "Singapore", .medium),
        FlagEntry("SK", "Slovakia", .medium),
        FlagEntry("SI", "Slovenia", .medium),
        FlagEntry("LK", "Sri Lanka", .medium),
        FlagEntry("SD", "Sudan", .medium),
        FlagEntry("SY", "Syria", .medium),
        FlagEntry("TW", "Taiwan", .medium),
        FlagEntry("TJ", "Tajikistan", .medium),
        FlagEntry("TZ", "Tanzania", .medium),
        FlagEntry("TT", "Trinidad and Tobago", .medium),
        FlagEntry("TN", "Tunisia", .medium),
        FlagEntry("TM", "Turkmenistan", .medium),
        FlagEntry("UG", "Uganda", .medium),
        FlagEntry("AE", "United Arab Emirates", .medium),
        FlagEntry("UY", "Uruguay", .medium),
        FlagEntry("UZ", "Uzbekistan", .medium),
        FlagEntry("VA", "Vatican City", .medium),
        FlagEntry("VE", "Venezuela", .medium),
        FlagEntry("YE", "Yemen", .medium, confusable: ["EG", "IQ"]),
        FlagEntry("ZM", "Zambia", .medium),
        FlagEntry("ZW", "Zimbabwe", .medium),
        FlagEntry("AS", "American Samoa", .hard),
        FlagEntry("AI", "Anguilla", .hard, confusable: ["FK", "KY", "MS", "SH", "TC"]),
        FlagEntry("AQ", "Antarctica", .hard),
        FlagEntry("AG", "Antigua and Barbuda", .hard),
        FlagEntry("AW", "Aruba", .hard),
        FlagEntry("BZ", "Belize", .hard),
        FlagEntry("BJ", "Benin", .hard),
        FlagEntry("BM", "Bermuda", .hard),
        FlagEntry("BT", "Bhutan", .hard),
        FlagEntry("BV", "Bouvet Island", .hard, askable: false),
        FlagEntry("IO", "British Indian Ocean Territory", .hard),
        FlagEntry("VG", "British Virgin Islands", .hard,
                  confusable: ["FK", "GS", "KY", "MS", "NZ", "PN", "SH", "TC"]),
        FlagEntry("BF", "Burkina Faso", .hard),
        FlagEntry("BI", "Burundi", .hard),
        FlagEntry("CV", "Cape Verde", .hard),
        FlagEntry("BQ", "Caribbean Netherlands", .hard),
        FlagEntry("KY", "Cayman Islands", .hard, confusable: ["AI", "FK", "GS", "MS", "NZ", "PN", "SH", "TC", "VG"]),
        FlagEntry("CF", "Central African Republic", .hard),
        FlagEntry("TD", "Chad", .hard, confusable: ["RO"]),
        FlagEntry("CX", "Christmas Island", .hard),
        FlagEntry("CC", "Cocos (Keeling) Islands", .hard),
        FlagEntry("KM", "Comoros", .hard),
        FlagEntry("CK", "Cook Islands", .hard, confusable: ["NZ"]),
        FlagEntry("CW", "Curaçao", .hard),
        FlagEntry("CD", "Democratic Republic of the Congo", .hard),
        FlagEntry("DJ", "Djibouti", .hard),
        FlagEntry("DM", "Dominica", .hard),
        FlagEntry("TL", "East Timor", .hard),
        FlagEntry("GQ", "Equatorial Guinea", .hard),
        FlagEntry("ER", "Eritrea", .hard),
        FlagEntry("SZ", "Eswatini", .hard),
        FlagEntry("FK", "Falkland Islands", .hard, confusable: ["AI", "GS", "KY", "MS", "SH", "VG"]),
        FlagEntry("FO", "Faroe Islands", .hard),
        FlagEntry("GF", "French Guiana", .hard),
        FlagEntry("PF", "French Polynesia", .hard, confusable: ["LB"]),
        FlagEntry("TF", "French Southern and Antarctic Lands", .hard),
        FlagEntry("GA", "Gabon", .hard),
        FlagEntry("GM", "Gambia", .hard),
        FlagEntry("GI", "Gibraltar", .hard),
        FlagEntry("GL", "Greenland", .hard),
        FlagEntry("GD", "Grenada", .hard),
        FlagEntry("GP", "Guadeloupe", .hard),
        FlagEntry("GU", "Guam", .hard),
        FlagEntry("GG", "Guernsey", .hard),
        FlagEntry("GN", "Guinea", .hard),
        FlagEntry("GW", "Guinea-Bissau", .hard),
        FlagEntry("GY", "Guyana", .hard),
        FlagEntry("HM", "Heard Island and McDonald Islands", .hard),
        FlagEntry("HK", "Hong Kong", .hard),
        FlagEntry("IM", "Isle of Man", .hard),
        FlagEntry("JE", "Jersey", .hard),
        FlagEntry("KI", "Kiribati", .hard),
        FlagEntry("LS", "Lesotho", .hard),
        FlagEntry("LR", "Liberia", .hard),
        FlagEntry("MO", "Macau", .hard),
        FlagEntry("MW", "Malawi", .hard),
        FlagEntry("MV", "Maldives", .hard),
        FlagEntry("ML", "Mali", .hard),
        FlagEntry("MH", "Marshall Islands", .hard),
        FlagEntry("MQ", "Martinique", .hard),
        FlagEntry("MR", "Mauritania", .hard),
        FlagEntry("MU", "Mauritius", .hard),
        FlagEntry("YT", "Mayotte", .hard),
        FlagEntry("FM", "Micronesia", .hard),
        FlagEntry("MS", "Montserrat", .hard, confusable: ["AI", "FK", "GS", "KY", "NZ", "PN", "SH", "TC", "VG"]),
        FlagEntry("NR", "Nauru", .hard),
        FlagEntry("NC", "New Caledonia", .hard),
        FlagEntry("NE", "Niger", .hard),
        FlagEntry("NU", "Niue", .hard),
        FlagEntry("NF", "Norfolk Island", .hard),
        FlagEntry("MP", "Northern Mariana Islands", .hard),
        FlagEntry("PW", "Palau", .hard),
        FlagEntry("PS", "Palestine", .hard, confusable: ["EH"]),
        FlagEntry("PN", "Pitcairn Islands", .hard, confusable: ["GS", "KY", "MS", "NZ", "SH", "VG"]),
        FlagEntry("PR", "Puerto Rico", .hard),
        FlagEntry("CG", "Republic of the Congo", .hard),
        FlagEntry("RW", "Rwanda", .hard),
        FlagEntry("RE", "Réunion", .hard),
        FlagEntry("BL", "Saint Barthélemy", .hard),
        FlagEntry("SH", "Saint Helena", .hard, confusable: ["AI", "FK", "GS", "KY", "MS", "NZ", "PN", "TC", "VG"]),
        FlagEntry("KN", "Saint Kitts and Nevis", .hard),
        FlagEntry("LC", "Saint Lucia", .hard),
        FlagEntry("MF", "Saint Martin", .hard, askable: false),
        FlagEntry("PM", "Saint Pierre and Miquelon", .hard),
        FlagEntry("VC", "Saint Vincent and the Grenadines", .hard),
        FlagEntry("WS", "Samoa", .hard),
        FlagEntry("SC", "Seychelles", .hard),
        FlagEntry("SL", "Sierra Leone", .hard),
        FlagEntry("SX", "Sint Maarten", .hard),
        FlagEntry("SB", "Solomon Islands", .hard),
        FlagEntry("SO", "Somalia", .hard),
        FlagEntry("GS", "South Georgia and the South Sandwich Islands", .hard,
                  confusable: ["FK", "KY", "MS", "NZ", "PN", "SH", "VG"]),
        FlagEntry("SS", "South Sudan", .hard),
        FlagEntry("SR", "Suriname", .hard),
        FlagEntry("SJ", "Svalbard and Jan Mayen", .hard, askable: false),
        FlagEntry("ST", "São Tomé and Príncipe", .hard),
        FlagEntry("TG", "Togo", .hard),
        FlagEntry("TK", "Tokelau", .hard),
        FlagEntry("TO", "Tonga", .hard),
        FlagEntry("TC", "Turks and Caicos Islands", .hard, confusable: ["AI", "KY", "MS", "SH", "VG"]),
        FlagEntry("TV", "Tuvalu", .hard),
        FlagEntry("UM", "United States Minor Outlying Islands", .hard, askable: false),
        FlagEntry("VI", "United States Virgin Islands", .hard),
        FlagEntry("VU", "Vanuatu", .hard),
        FlagEntry("WF", "Wallis and Futuna", .hard),
        FlagEntry("EH", "Western Sahara", .hard, confusable: ["PS"]),
        FlagEntry("AX", "Åland Islands", .hard),
    ]

    /// The flags that are actually asked about.
    static let askable: [FlagEntry] = all.filter(\.askable)
}
