import Foundation

/// Short, stable facts shown after a flag answer is revealed.
///
/// These avoid time-sensitive statistics and political officeholders so the
/// explanations remain useful between content-review passes.
enum FlagFacts {
    static let byCode: [String: String] = [
        "AR": "Tango developed along the Río de la Plata in Buenos Aires and neighboring Montevideo.",
        "AU": "The Great Barrier Reef is the largest coral-reef system on Earth.",
        "AT": "Wolfgang Amadeus Mozart was born in Salzburg in 1756.",
        "BE": "The saxophone was invented by Belgian instrument maker Adolphe Sax.",
        "BR": "Most of the Amazon rainforest lies within Brazil.",
        "CA": "Canada has the longest coastline of any country.",
        "CL": "Chile's Atacama is one of the driest non-polar deserts on Earth.",
        "CN": "China's Grand Canal is the world's longest human-made waterway.",
        "CO": "Colombia is the only South American country with both Caribbean and Pacific coasts.",
        "CU": "Cuba is the largest island in the Caribbean.",
        "CZ": "Prague's medieval astronomical clock has been operating since 1410.",
        "DK": "LEGO was invented in the Danish town of Billund.",
        "EG": "The Great Pyramid of Giza is the only surviving Wonder of the Ancient World.",
        "FI": "Finland is famous for its thousands of lakes and deeply rooted sauna culture.",
        "FR": "France helped create the metric system during the French Revolution.",
        "DE": "Johannes Gutenberg developed movable-type printing in Mainz.",
        "GR": "The ancient Olympic Games began at Olympia in Greece.",
        "IS": "Geothermal energy heats most homes in Iceland.",
        "IN": "The game of chess developed from an early Indian game called chaturanga.",
        "ID": "Komodo dragons live naturally on only a handful of Indonesian islands.",
        "IE": "Many Halloween traditions trace their roots to the Gaelic festival of Samhain.",
        "IL": "The shore of the Dead Sea is Earth's lowest exposed land elevation.",
        "IT": "Mount Etna in Sicily is one of Europe's most active volcanoes.",
        "JM": "Reggae music developed in Jamaica in the late 1960s.",
        "JP": "Japan introduced the world's first high-speed bullet-train line in 1964.",
        "KE": "The Great Rift Valley crosses Kenya from north to south.",
        "MX": "Cacao was treasured by ancient Mesoamerican cultures long before modern chocolate.",
        "MA": "Morocco contains both Atlantic and Mediterranean coasts as well as part of the Sahara.",
        "NL": "Large parts of the Netherlands were reclaimed from water using dikes and pumps.",
        "NZ": "New Zealand became the first self-governing country to grant women the vote, in 1893.",
        "NG": "Nigeria's Nollywood is one of the world's most prolific film industries.",
        "NO": "The Nobel Peace Prize is awarded in Oslo; the other Nobel Prizes are awarded in Stockholm.",
        "PK": "K2, the world's second-highest mountain, stands on Pakistan's northern frontier.",
        "PE": "Machu Picchu was built by the Inca high in the Andes.",
        "PH": "The Philippines is an archipelago of more than 7,600 islands.",
        "PL": "Astronomer Nicolaus Copernicus was born in the Polish city of Toruń.",
        "PT": "Portugal and England formed an alliance in 1386 that still links the two countries.",
        "RU": "Russia stretches across eleven time zones.",
        "SA": "Saudi Arabia has no permanent rivers.",
        "ZA": "South Africa divides its national government among three capital cities.",
        "KR": "The Korean alphabet, Hangul, was created under King Sejong in the fifteenth century.",
        "ES": "The modern novel is often traced to Miguel de Cervantes's Don Quixote.",
        "SE": "The Celsius temperature scale is named for Swedish astronomer Anders Celsius.",
        "CH": "Switzerland has four national languages: German, French, Italian, and Romansh.",
        "TH": "Thailand is the only Southeast Asian country never formally colonized by a European power.",
        "TR": "Istanbul spans both Europe and Asia across the Bosporus.",
        "UA": "Kyiv's Saint Sophia Cathedral dates to the eleventh century.",
        "GB": "The historic Greenwich meridian is marked at the Royal Observatory in London.",
        "US": "Yellowstone, established in 1872, is widely regarded as the world's first national park.",
        "VN": "Vietnam's Sơn Đoòng is the world's largest known cave passage by volume.",

        "AL": "Thousands of concrete bunkers remain from Albania's decades of communist isolation.",
        "DZ": "Algeria is Africa's largest country by land area.",
        "AD": "Andorra is jointly headed by two co-princes: a Spanish bishop and the president of France.",
        "AO": "The giant sable antelope is found naturally only in Angola.",
        "AM": "Armenia traditionally dates its adoption of Christianity as a state religion to 301.",
        "AZ": "Azerbaijan's natural gas flames helped inspire its nickname, the Land of Fire.",
        "BS": "A colony of swimming pigs has made the Exuma islands famous.",
        "BH": "Bahrain was a center of the ancient Dilmun civilization and Persian Gulf trade.",
        "BD": "Bangladesh sits on the vast delta formed by the Ganges, Brahmaputra, and Meghna rivers.",
        "BB": "Barbados has a centuries-old rum-making tradition and is often called the spirit's birthplace.",
        "BY": "Belarus shares Białowieża Forest, one of Europe's last large primeval forests, with Poland.",
        "BO": "Bolivia recognizes Sucre as its constitutional capital while the government sits in La Paz.",
        "BA": "Bosnia and Herzegovina contains Perućica, one of Europe's surviving primeval forests.",
        "BW": "Botswana's Okavango River spreads into an inland delta instead of reaching the sea.",
        "BN": "Brunei's Istana Nurul Iman is one of the world's largest residential palaces.",
        "BG": "The early Cyrillic alphabet was developed in the First Bulgarian Empire.",
        "KH": "Angkor Wat is the world's largest religious monument.",
        "CM": "Cameroon is nicknamed Africa in Miniature for its varied climates and landscapes.",
        "CR": "More than a quarter of Costa Rica's land is protected in parks or reserves.",
        "HR": "The modern necktie traces its name and style to seventeenth-century Croatian soldiers.",
        "CY": "Halloumi cheese originated in Cyprus.",
        "DO": "The Dominican Republic shares the island of Hispaniola with Haiti.",
        "EC": "Ecuador takes its name from the Spanish word for equator.",
        "SV": "El Salvador is the smallest country on the mainland of the Americas.",
        "EE": "Estonia pioneered nationwide online voting in public elections.",
        "ET": "Coffee's wild ancestors originated in the highlands of Ethiopia.",
        "FJ": "Fiji includes more than 300 islands, though most people live on the two largest.",
        "GE": "Archaeological evidence in Georgia shows wine-making traditions about eight thousand years old.",
        "GH": "Ghana was formerly called the Gold Coast and remains famous for cacao production.",
        "GT": "Lake Atitlán fills a volcanic caldera surrounded by three volcanoes.",
        "HT": "Haiti became the world's first independent Black republic in 1804.",
        "HN": "The Maya city of Copán is renowned for its carved stone monuments and hieroglyphic stairway.",
        "HU": "The Rubik's Cube was invented by Hungarian professor Ernő Rubik.",
        "IR": "Ancient Persian engineers used windcatchers to cool buildings without electricity.",
        "IQ": "Ancient Mesopotamia grew between the Tigris and Euphrates rivers in present-day Iraq.",
        "CI": "The immense Basilica of Our Lady of Peace stands in the capital, Yamoussoukro.",
        "JO": "Petra's monumental façades were carved directly into rose-colored sandstone cliffs.",
        "KZ": "Kazakhstan is the world's largest landlocked country.",
        "KW": "Kuwait City grew around a natural harbor that supported regional sea trade.",
        "KG": "The Tian Shan mountains cover most of Kyrgyzstan.",
        "LA": "Laos is Southeast Asia's only landlocked country.",
        "LV": "Latvia's Venta Rapid is one of Europe's widest natural waterfalls.",
        "LB": "Lebanon's cedar trees have been celebrated since ancient times.",
        "LY": "The Sahara covers most of Libya, leaving the population concentrated near the Mediterranean.",
        "LI": "Liechtenstein and Uzbekistan are the world's only doubly landlocked countries.",
        "LT": "Lithuania was among the last European states to officially adopt Christianity.",
        "LU": "Luxembourg is the world's only sovereign grand duchy.",
        "MG": "Most of Madagascar's native plants and animals are found nowhere else on Earth.",
        "MY": "Malaysia's Gunung Mulu National Park contains enormous caves and limestone pinnacles.",
        "MT": "Malta's megalithic temples are older than the Egyptian pyramids.",
        "MD": "Moldova's Mileștii Mici wine cellar has galleries stretching for many kilometres.",
        "MC": "Monaco is the world's second-smallest sovereign country, after Vatican City.",
        "MN": "Mongolia is the world's least densely populated sovereign country.",
        "ME": "Montenegro's Bay of Kotor winds between steep mountains like a fjord.",
        "MZ": "Mozambique's Bazaruto Archipelago shelters rare dugongs.",
        "MM": "The plains of Bagan contain thousands of surviving Buddhist temples and pagodas.",
        "NA": "The Namib is one of the world's oldest deserts.",
        "NP": "Nepal contains eight of the world's fourteen mountains higher than 8,000 metres.",
        "NI": "Bull sharks can travel from the Caribbean Sea into freshwater Lake Nicaragua.",
        "KP": "Mount Paektu, a volcanic caldera mountain, is the country's highest point.",
        "MK": "Lake Ohrid is one of Europe's oldest and deepest lakes.",
        "OM": "Oman was a major center of the ancient frankincense trade.",
        "PA": "The Panama Canal allows ships to cross between the Atlantic and Pacific oceans.",
        "PG": "More than 800 languages are spoken in Papua New Guinea.",
        "PY": "Guaraní is an official language of Paraguay and is spoken by much of the population.",
        "QA": "Qatar's Khor Al Adaid is a rare inland sea where dunes meet tidal water.",
        "RO": "The Danube Delta is one of Europe's largest and best-preserved river deltas.",
        "SM": "San Marino traces its founding tradition to the year 301.",
        "SN": "Senegal's Cap-Vert peninsula is the westernmost point of mainland Africa.",
        "RS": "The word vampire entered several Western European languages through Serbian folklore.",
        "SG": "Singapore has four official languages: Malay, Mandarin, Tamil, and English.",
        "SK": "Bratislava is the only national capital that borders both Austria and Hungary.",
        "SI": "More than half of Slovenia is covered by forest.",
        "LK": "Sri Lanka elected the world's first woman prime minister in 1960.",
        "SD": "Sudan contains more ancient pyramids than Egypt, mostly from the Kingdom of Kush.",
        "SY": "The ancient caravan city of Palmyra linked Mediterranean and Asian trade routes.",
        "TW": "Many Indigenous languages of Taiwan belong to the Austronesian family spoken across the Pacific.",
        "TJ": "The high Pamir Mountains dominate eastern Tajikistan.",
        "TZ": "Mount Kilimanjaro, Africa's highest mountain, rises in Tanzania.",
        "TT": "Steelpan music originated in Trinidad and Tobago in the twentieth century.",
        "TN": "The ruins of ancient Carthage stand near modern Tunis.",
        "TM": "The Darvaza gas crater has burned in the Karakum Desert for decades.",
        "UG": "The White Nile flows north from Lake Victoria through Uganda.",
        "AE": "The United Arab Emirates is a federation of seven emirates.",
        "UY": "Uruguay hosted and won the first men's FIFA World Cup in 1930.",
        "UZ": "Uzbekistan is one of only two doubly landlocked countries.",
        "VA": "Vatican City is the world's smallest sovereign state by both area and population.",
        "VE": "Venezuela's Angel Falls is the world's highest uninterrupted waterfall.",
        "YE": "Socotra is famous for dragon's-blood trees and wildlife found nowhere else.",
        "ZM": "Victoria Falls lies on the Zambezi River between Zambia and Zimbabwe.",
        "ZW": "The stone ruins of Great Zimbabwe gave the modern country its name.",

        "AS": "Traditional life in American Samoa is shaped by fa'a Samoa, the Samoan way of life.",
        "AI": "Anguilla was named for its long, eel-like shape.",
        "AQ": "Antarctica is the coldest, driest, and windiest continent.",
        "AG": "Barbuda hosts one of the Caribbean's largest magnificent frigatebird colonies.",
        "AW": "Aruba's trade winds bend its famous divi-divi trees toward the southwest.",
        "BZ": "Belize is the only Central American country whose official language is English.",
        "BJ": "Vodun originated in this region and is officially recognized in Benin.",
        "BM": "Bermuda shorts paired with knee socks are accepted business attire on the islands.",
        "BT": "Bhutan is known for measuring progress through Gross National Happiness.",
        "IO": "Diego Garcia is the largest island in the Chagos Archipelago.",
        "VG": "The British Virgin Islands are known for sheltered channels that make them a major sailing destination.",
        "BF": "Burkina Faso's name means Land of Upright People.",
        "BI": "Burundi's royal drumming tradition is recognized by UNESCO.",
        "CV": "Morna, a style made famous by Cesária Évora, is central to Cabo Verdean music.",
        "BQ": "Bonaire's salt pans and flamingo sanctuary color parts of the island pink.",
        "KY": "Stingray City began where fishers cleaned their catch and attracted southern stingrays.",
        "CF": "The Central African Republic lies near the geographic heart of the African continent.",
        "TD": "The country takes its name from Lake Chad on its western border.",
        "CX": "Millions of red crabs cross Christmas Island during their annual migration to the sea.",
        "CC": "Only two of the Cocos Islands' twenty-seven coral islands are inhabited.",
        "KM": "Comoros is nicknamed the Perfume Islands for fragrant crops such as ylang-ylang.",
        "CK": "The Cook Islands' fifteen islands are scattered across nearly two million square kilometres of ocean.",
        "CW": "Blue Curaçao liqueur is flavored with peel from the island's bitter laraha orange.",
        "CD": "The Congo rainforest is the world's second-largest tropical rainforest after the Amazon.",
        "DJ": "Lake Assal is Africa's lowest point and one of the world's saltiest lakes.",
        "DM": "Dominica's volcanic landscape includes the steaming Boiling Lake.",
        "TL": "Timor-Leste restored its independence in 2002 after a long independence struggle.",
        "GQ": "Equatorial Guinea is the only sovereign African country where Spanish is an official language.",
        "ER": "The Dahlak Archipelago contains more than one hundred islands in the Red Sea.",
        "SZ": "Eswatini's annual Umhlanga reed dance is one of its best-known cultural events.",
        "FK": "The Falkland Islands support enormous colonies of penguins and other seabirds.",
        "FO": "The Faroe Islands' name comes from an Old Norse phrase meaning Sheep Islands.",
        "GF": "Europe's main spaceport launches rockets from Kourou in French Guiana.",
        "PF": "French Polynesia includes 118 islands spread across a vast area of the South Pacific.",
        "TF": "The French Southern and Antarctic Lands have no permanent civilian population.",
        "GA": "Gabon created thirteen national parks in 2002 to protect rainforest and wildlife.",
        "GM": "The Gambia forms a narrow strip of land around the Gambia River.",
        "GI": "Gibraltar's Barbary macaques are Europe's only wild monkey population.",
        "GL": "Greenland is the world's largest island that is not a continent.",
        "GD": "Grenada is nicknamed the Spice Isle for crops such as nutmeg and mace.",
        "GP": "Guadeloupe's two main islands form a shape often compared to a butterfly.",
        "GU": "Guam is often called Where America's Day Begins because of its western Pacific time zone.",
        "GG": "Guernsey issues its own pound, which circulates alongside British currency.",
        "GN": "Several major West African rivers, including the Niger, rise in Guinea's highlands.",
        "GW": "The Bijagós Archipelago is a UNESCO biosphere reserve of islands and mangroves.",
        "GY": "Guyana is the only country on mainland South America with English as its official language.",
        "HK": "Mountain trails and country parks cover much of Hong Kong despite its dense skyline.",
        "IM": "The Isle of Man TT is one of the world's oldest and fastest motorcycle races.",
        "JE": "The Jersey dairy breed originated on this Channel Island.",
        "KI": "Kiribati is the only country with land in all four hemispheres.",
        "LS": "Every part of Lesotho lies more than 1,000 metres above sea level.",
        "LR": "Liberia was founded in the nineteenth century as a settlement for formerly enslaved people from the United States.",
        "MO": "Macau blends centuries of Chinese and Portuguese architecture and cuisine.",
        "MW": "Lake Malawi contains more fish species than any other lake.",
        "MV": "The Maldives is the world's lowest-lying country.",
        "ML": "Timbuktu became a celebrated center of scholarship and Saharan trade.",
        "MH": "The bikini swimsuit was named after Bikini Atoll.",
        "MQ": "Mount Pelée's 1902 eruption destroyed the city of Saint-Pierre.",
        "MR": "Mauritania's iron-ore railway operates some of the world's longest freight trains.",
        "MU": "The extinct dodo lived only on Mauritius.",
        "YT": "Mayotte sits inside one of the world's largest enclosed lagoons.",
        "FM": "The island of Yap is famous for traditional stone money called rai.",
        "MS": "Eruptions of the Soufrière Hills volcano buried much of Montserrat's former capital, Plymouth.",
        "NR": "Nauru is the world's smallest island republic.",
        "NE": "Niger is named for the Niger River, which crosses its southwest corner.",
        "NU": "Niue is one of the world's largest raised coral islands.",
        "NF": "The distinctive Norfolk Island pine is native to this small Pacific island.",
        "MP": "The Northern Mariana Islands lie beside the Mariana Trench, Earth's deepest ocean trench.",
        "PW": "Palau's Jellyfish Lake is famous for its population of golden jellyfish.",
        "PS": "Olive cultivation has shaped Palestinian agriculture and culture for thousands of years.",
        "PN": "Most Pitcairn Islanders descend from the Bounty mutineers and their Polynesian companions.",
        "PR": "The tiny coquí frog is a beloved symbol of Puerto Rico.",
        "CG": "Brazzaville and Kinshasa face one another across the Congo River.",
        "RW": "Rwanda is nicknamed the Land of a Thousand Hills.",
        "RE": "Piton de la Fournaise on Réunion is one of the world's most active volcanoes.",
        "BL": "Saint Barthélemy was named for Christopher Columbus's brother Bartolomeo.",
        "SH": "Napoleon spent his final years in exile on Saint Helena.",
        "KN": "Saint Kitts and Nevis is the smallest sovereign state in the Western Hemisphere.",
        "LC": "Saint Lucia was named for Saint Lucy of Syracuse, whose feast day is celebrated as the island's National Day.",
        "PM": "Saint Pierre and Miquelon sits just south of Newfoundland and retains a distinctly French culture.",
        "VC": "Saint Vincent's botanical garden, founded in 1765, is among the oldest in the Western Hemisphere.",
        "WS": "Samoa's traditional tattooing practice is called tatau and remains an important cultural art.",
        "SC": "The coco de mer palm of Seychelles produces the world's largest seed.",
        "SL": "The name Sierra Leone comes from a Portuguese phrase meaning Lion Mountains.",
        "SX": "Sint Maarten shares the island of Saint Martin with the French collectivity of Saint-Martin.",
        "SB": "The Solomon Islands were named by an explorer who hoped they held King Solomon's legendary gold.",
        "SO": "Somalia has the longest coastline on mainland Africa.",
        "GS": "South Georgia has no permanent residents but supports immense penguin colonies.",
        "SS": "South Sudan became independent in 2011.",
        "SR": "More than nine-tenths of Suriname is covered by forest.",
        "ST": "The equator passes just south of São Tomé through the tiny islet of Rolas.",
        "TG": "Togo is a long, narrow country stretching from the Gulf of Guinea toward the Sahel.",
        "TK": "Tokelau has no airport, so visitors arrive by ship from Samoa.",
        "TO": "Tonga is the Pacific's only remaining Indigenous monarchy.",
        "TC": "The shallow Caicos Banks create the islands' vivid turquoise water.",
        "TV": "Tuvalu's .tv internet domain is popular with television and streaming businesses.",
        "VI": "Cars in the U.S. Virgin Islands drive on the left even though most have left-hand steering.",
        "VU": "Vanuatu's land-diving tradition helped inspire modern bungee jumping.",
        "WF": "Wallis and Futuna maintains three customary Polynesian kingdoms alongside French administration.",
        "AX": "Åland is an autonomous, demilitarized, Swedish-speaking region of Finland."
    ]
}
