import Foundation

public enum QuestionBank {
    public static let all: [TriviaQuestion] = {
        var items: [TriviaQuestion] = []
        func add(_ category: TriviaCategory, _ prompt: String, visual: String? = nil, _ answers: [String], _ correct: Int, _ explanation: String) {
            items.append(TriviaQuestion(id: "\(category.rawValue)-\(items.filter { $0.category == category }.count + 1)", category: category, prompt: prompt, visual: visual, answers: answers, correctAnswerIndex: correct, explanation: explanation))
        }

        add(.football, "How many points is a touchdown worth?", ["3", "6", "7", "8"], 1, "A touchdown earns six points; the extra point is a separate play.")
        add(.football, "How many players from one team are on the field at once?", ["9", "10", "11", "12"], 2, "Each team fields eleven players during a play.")
        add(.football, "What is the NFL championship game called?", ["Rose Bowl", "Super Bowl", "World Series", "Stanley Cup"], 1, "The Super Bowl has decided the NFL champion since the 1966 season.")
        add(.football, "How many yards are needed for a first down?", ["5", "8", "10", "15"], 2, "An offense normally has four downs to gain ten yards.")
        add(.football, "Which position usually throws the ball?", ["Quarterback", "Center", "Safety", "Kicker"], 0, "The quarterback directs the offense and usually passes the ball.")
        add(.football, "What is a score by the defense in its own end zone called?", ["Touchback", "Safety", "Sack", "Blitz"], 1, "A safety is worth two points.")
        add(.football, "How long is an NFL field between goal lines?", ["80 yards", "90 yards", "100 yards", "120 yards"], 2, "The playing field is 100 yards, plus two 10-yard end zones.")
        add(.football, "Which player snaps the ball?", ["Center", "Tight end", "Cornerback", "Punter"], 0, "The center starts most plays by snapping to the quarterback.")
        add(.football, "How many quarters are in a regulation game?", ["2", "3", "4", "5"], 2, "Regulation football games are split into four quarters.")
        add(.football, "What is it called when the quarterback is tackled behind the line?", ["Pick", "Sack", "Fumble", "Huddle"], 1, "Tackling a passer behind the line of scrimmage is a sack.")
        add(.football, "A field goal is normally worth how many points?", ["1", "2", "3", "6"], 2, "A successful field goal scores three points.")
        add(.football, "Which unit tries to stop the opposing offense?", ["Defense", "Special teams", "Practice squad", "Officials"], 0, "The defense prevents the other team from advancing and scoring.")

        add(.soccer, "How many players does each team start on the field?", ["9", "10", "11", "12"], 2, "A side starts with eleven players, including its goalkeeper.")
        add(.soccer, "What color card sends a player off?", ["Blue", "Green", "Yellow", "Red"], 3, "A red card means the player must leave the match.")
        add(.soccer, "How long is a standard match before added time?", ["60 minutes", "80 minutes", "90 minutes", "100 minutes"], 2, "Two 45-minute halves make 90 minutes.")
        add(.soccer, "Who may handle the ball inside their own penalty area?", ["Captain", "Goalkeeper", "Any defender", "Striker"], 1, "The goalkeeper may use their hands within their own penalty area.")
        add(.soccer, "What restarts play after the ball crosses the touchline?", ["Throw-in", "Drop ball", "Goal kick", "Penalty"], 0, "The opponents of the last player to touch it take a throw-in.")
        add(.soccer, "How often is the men's FIFA World Cup normally held?", ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"], 2, "The tournament normally takes place every four years.")
        add(.soccer, "What is three goals by one player called?", ["Triple play", "Hat-trick", "Clean sheet", "Treble"], 1, "Three goals in one match are known as a hat-trick.")
        add(.soccer, "Which country won the first men's World Cup in 1930?", ["Brazil", "Italy", "Argentina", "Uruguay"], 3, "Host nation Uruguay won the inaugural tournament.")
        add(.soccer, "What is a game with no goals conceded called?", ["Clean sheet", "Nil draw", "Shut play", "Blank kick"], 0, "A goalkeeper or team that concedes no goals keeps a clean sheet.")
        add(.soccer, "Where is a penalty kick taken from?", ["Center circle", "Six-yard box", "Penalty mark", "Corner arc"], 2, "Penalty kicks are taken from the marked spot in the penalty area.")
        add(.soccer, "Which body governs world soccer?", ["UEFA", "FIFA", "IOC", "NFL"], 1, "FIFA is the international governing body.")
        add(.soccer, "What body part may an outfield player not deliberately use?", ["Head", "Chest", "Foot", "Hand"], 3, "Deliberate handball by an outfield player is an offense.")

        add(.flags, "Which country does this flag represent?", visual: "🇨🇦", ["Canada", "Austria", "Denmark", "Japan"], 0, "Canada adopted its maple-leaf flag in 1965.")
        add(.flags, "Which country does this flag represent?", visual: "🇯🇵", ["Bangladesh", "Japan", "Poland", "Indonesia"], 1, "Japan's sun disc is called the Hinomaru.")
        add(.flags, "Which country does this flag represent?", visual: "🇦🇺", ["Australia", "New Zealand", "United Kingdom", "Fiji"], 0, "Australia's flag combines the Union Jack with stars including the Southern Cross.")
        add(.flags, "Which country does this flag represent?", visual: "🇧🇷", ["Bolivia", "Brazil", "Jamaica", "Ghana"], 1, "Brazil's flag centers a blue globe inside a yellow diamond.")
        add(.flags, "Which country does this flag represent?", visual: "🇳🇵", ["Nepal", "Bhutan", "Switzerland", "Qatar"], 0, "Nepal has the world's only non-rectangular national flag.")
        add(.flags, "Which country does this flag represent?", visual: "🇱🇧", ["Cyprus", "Lebanon", "Canada", "Belize"], 1, "The cedar is a longstanding symbol of Lebanon.")
        add(.flags, "Which country does this flag represent?", visual: "🇫🇷", ["France", "Netherlands", "Russia", "Luxembourg"], 0, "France's vertical blue, white, and red flag is the Tricolore.")
        add(.flags, "Which country does this flag represent?", visual: "🇺🇸", ["Liberia", "Malaysia", "United States", "Chile"], 2, "The United States flag has 50 stars and 13 stripes.")
        add(.flags, "Which country does this flag represent?", visual: "🇨🇭", ["England", "Georgia", "Switzerland", "Finland"], 2, "Switzerland's square flag carries a bold white cross.")
        add(.flags, "Which country does this flag represent?", visual: "🇧🇹", ["Bhutan", "India", "Mongolia", "Vietnam"], 0, "Bhutan's Druk, or Thunder Dragon, spans the flag.")
        add(.flags, "Which country does this flag represent?", visual: "🇺🇦", ["Ukraine", "Sweden", "Kazakhstan", "Palau"], 0, "Ukraine uses equal horizontal bands of blue over yellow.")
        add(.flags, "Which country does this flag represent?", visual: "🇭🇷", ["Croatia", "Serbia", "Slovenia", "Slovakia"], 0, "Croatia's coat of arms begins with its distinctive checkerboard.")

        add(.history, "Who was the first president of the United States?", ["Thomas Jefferson", "George Washington", "John Adams", "Abraham Lincoln"], 1, "George Washington served from 1789 to 1797.")
        add(.history, "The ancient city of Rome was founded on which river?", ["Nile", "Seine", "Tiber", "Danube"], 2, "Rome grew beside the Tiber River in central Italy.")
        add(.history, "In which year did World War II end?", ["1943", "1944", "1945", "1946"], 2, "The war ended in 1945 after six years of global conflict.")
        add(.history, "Which civilization built Machu Picchu?", ["Maya", "Aztec", "Inca", "Olmec"], 2, "The Inca built the mountain citadel in the 15th century.")
        add(.history, "The Magna Carta was sealed in which country?", ["France", "England", "Spain", "Germany"], 1, "King John sealed it at Runnymede, England, in 1215.")
        add(.history, "Who discovered penicillin?", ["Marie Curie", "Louis Pasteur", "Alexander Fleming", "Isaac Newton"], 2, "Alexander Fleming observed penicillin's antibacterial effect in 1928.")
        add(.history, "Which empire used roads called the Royal Road?", ["Persian", "Roman", "Ottoman", "Mughal"], 0, "The Achaemenid Persian Empire maintained the Royal Road.")
        add(.history, "Who wrote the 95 Theses?", ["Martin Luther", "Galileo", "Voltaire", "Socrates"], 0, "Martin Luther's 1517 document helped launch the Reformation.")
        add(.history, "Which wall fell in 1989?", ["Hadrian's Wall", "Great Wall", "Berlin Wall", "Wailing Wall"], 2, "The opening of the Berlin Wall symbolized the Cold War's end.")
        add(.history, "Who was known as the Maid of Orléans?", ["Cleopatra", "Joan of Arc", "Boudica", "Catherine the Great"], 1, "Joan of Arc helped inspire French forces during the Hundred Years' War.")
        add(.history, "Ancient Egyptian writing is called what?", ["Cuneiform", "Latin", "Hieroglyphics", "Runes"], 2, "Egyptian scribes used hieroglyphic symbols for monumental texts.")
        add(.history, "Which explorer's expedition first circumnavigated Earth?", ["Columbus", "Magellan", "Cook", "Polo"], 1, "Magellan led the expedition, completed by Juan Sebastián Elcano.")

        add(.science, "What planet is known as the Red Planet?", ["Venus", "Mars", "Jupiter", "Mercury"], 1, "Iron minerals in Martian soil give Mars its reddish color.")
        add(.science, "What is the chemical symbol for gold?", ["Ag", "Gd", "Au", "Go"], 2, "Au comes from the Latin word aurum.")
        add(.science, "How many bones are in a typical adult human body?", ["186", "206", "226", "256"], 1, "Most adults have 206 bones.")
        add(.science, "What gas do plants absorb during photosynthesis?", ["Oxygen", "Nitrogen", "Hydrogen", "Carbon dioxide"], 3, "Plants use carbon dioxide and release oxygen.")
        add(.science, "What is the largest planet in our solar system?", ["Saturn", "Earth", "Jupiter", "Neptune"], 2, "Jupiter is more massive than all other planets combined.")
        add(.science, "At sea level, water boils at what Celsius temperature?", ["90°", "100°", "110°", "212°"], 1, "At standard pressure, water boils at 100°C.")
        add(.science, "What force keeps planets in orbit?", ["Magnetism", "Friction", "Gravity", "Electricity"], 2, "Gravity attracts planets toward the Sun while they move forward.")
        add(.science, "What is the center of an atom called?", ["Nucleus", "Orbit", "Cell", "Core beam"], 0, "The nucleus contains protons and neutrons.")
        add(.science, "Which organ pumps blood through the body?", ["Liver", "Lung", "Heart", "Kidney"], 2, "The heart drives blood through the circulatory system.")
        add(.science, "What is Earth's natural satellite?", ["Titan", "The Moon", "Europa", "Phobos"], 1, "The Moon is Earth's only natural satellite.")
        add(.science, "What is the hardest natural material?", ["Quartz", "Iron", "Diamond", "Granite"], 2, "Diamond ranks 10 on the Mohs hardness scale.")
        add(.science, "Which particle has a negative charge?", ["Proton", "Neutron", "Electron", "Photon"], 2, "Electrons carry negative electric charge.")

        add(.movies, "Who directed Jaws?", ["George Lucas", "Steven Spielberg", "James Cameron", "Martin Scorsese"], 1, "Steven Spielberg directed the 1975 thriller.")
        add(.movies, "Which film features the kingdom of Arendelle?", ["Moana", "Frozen", "Brave", "Tangled"], 1, "Arendelle is the home of sisters Anna and Elsa in Frozen.")
        add(.movies, "What color pill does Neo take in The Matrix?", ["Blue", "Green", "Red", "White"], 2, "Neo chooses the red pill and learns the truth.")
        add(.movies, "Which movie series features a DeLorean time machine?", ["Star Wars", "Back to the Future", "Terminator", "Indiana Jones"], 1, "Doc Brown turns a DeLorean into a time machine.")
        add(.movies, "Who is Simba's father in The Lion King?", ["Scar", "Rafiki", "Mufasa", "Timon"], 2, "Mufasa is the king of the Pride Lands and Simba's father.")
        add(.movies, "Which actor played the title role in Rocky?", ["Sylvester Stallone", "Arnold Schwarzenegger", "Bruce Willis", "Tom Cruise"], 0, "Sylvester Stallone wrote and starred in Rocky.")
        add(.movies, "What is the name of the cowboy in Toy Story?", ["Buzz", "Woody", "Rex", "Slinky"], 1, "Sheriff Woody is Andy's favorite toy.")
        add(.movies, "Which movie includes the line about needing a bigger boat?", ["Titanic", "Jaws", "Finding Nemo", "Cast Away"], 1, "The famous reaction comes after the shark appears in Jaws.")
        add(.movies, "Which fictional metal powers Black Panther's suit?", ["Adamantium", "Kryptonite", "Vibranium", "Unobtainium"], 2, "Wakanda's technology is built around vibranium.")
        add(.movies, "What kind of fish is Nemo?", ["Clownfish", "Blue tang", "Angelfish", "Goldfish"], 0, "Nemo and his father Marlin are clownfish.")
        add(.movies, "Which film won the first Academy Award for Best Picture?", ["Metropolis", "Wings", "The Jazz Singer", "Sunrise"], 1, "Wings received the award at the first ceremony.")
        add(.movies, "Who composed the iconic Star Wars score?", ["Hans Zimmer", "John Williams", "Ennio Morricone", "Howard Shore"], 1, "John Williams composed the saga's celebrated orchestral themes.")
        return items
    }()
}
