import Foundation

enum AnimalsQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("What is the largest living animal?",
                     ["The African elephant", "The blue whale", "The giraffe", "The whale shark"], 1,
                     "A blue whale can exceed thirty metres in length."),
        QuestionSeed("Which is the fastest land animal over a short distance?",
                     ["The lion", "The cheetah", "The horse", "The greyhound"], 1,
                     "Cheetahs can reach around 100 kilometres per hour but tire within seconds."),
        QuestionSeed("What is the tallest living animal?",
                     ["The elephant", "The giraffe", "The ostrich", "The camel"], 1,
                     "An adult male giraffe can stand over five metres tall."),
        QuestionSeed("Which animal is known as man's best friend?",
                     ["The cat", "The dog", "The horse", "The parrot"], 1,
                     "Dogs were the first animal species to be domesticated."),
        QuestionSeed("What do you call a baby cat?",
                     ["A cub", "A kitten", "A puppy", "A calf"], 1,
                     "A baby dog is a puppy and a baby lion is a cub."),
        QuestionSeed("Which bird is famous for being unable to fly and living in Antarctica?",
                     ["The albatross", "The penguin", "The puffin", "The seagull"], 1,
                     "Penguins use their wings as flippers to swim rather than fly."),
        QuestionSeed("How many humps does a dromedary camel have?",
                     ["None", "One", "Two", "Three"], 1,
                     "Bactrian camels have two humps."),
        QuestionSeed("Which animal is the largest big cat?",
                     ["The lion", "The tiger", "The leopard", "The jaguar"], 1,
                     "Siberian tigers are the largest of all."),
        QuestionSeed("What do bees make?",
                     ["Silk", "Honey", "Wax paper", "Amber"], 1,
                     "They also produce beeswax, which they use to build the comb."),
        QuestionSeed("Which sea creature has eight arms?",
                     ["The squid", "The octopus", "The jellyfish", "The starfish"], 1,
                     "Squid have eight arms plus two longer tentacles."),
        QuestionSeed("What is a group of lions called?",
                     ["A herd", "A pride", "A pack", "A flock"], 1,
                     "Wolves travel in packs and birds gather in flocks."),
        QuestionSeed("Which animal is known for changing colour?",
                     ["The chameleon", "The iguana", "The gecko", "The tortoise"], 0,
                     "Colour change is used for temperature regulation and signalling more than camouflage."),
        QuestionSeed("What kind of animal is a frog?",
                     ["A reptile", "An amphibian", "A mammal", "A fish"], 1,
                     "Amphibians typically begin life in water and breathe partly through their skin."),
        QuestionSeed("Which animal carries its young in a pouch?",
                     ["The kangaroo", "The zebra", "The rhinoceros", "The hippopotamus"], 0,
                     "Marsupials give birth to very undeveloped young that finish growing in the pouch."),
        QuestionSeed("How many legs does an insect have?",
                     ["Four", "Six", "Eight", "Ten"], 1,
                     "Six legs and three body segments define insects."),
        QuestionSeed("Which bird is a symbol of wisdom?",
                     ["The owl", "The crow", "The dove", "The eagle"], 0,
                     "The association goes back to the owl of the Greek goddess Athena."),
        QuestionSeed("What is the largest species of bear?",
                     ["The black bear", "The polar bear", "The sun bear", "The panda"], 1,
                     "Polar bears and the largest brown bears are comparable in size."),
        QuestionSeed("Which animal produces wool?",
                     ["The cow", "The sheep", "The pig", "The goat"], 1,
                     "Goats produce mohair and cashmere, which are different fibres."),
        QuestionSeed("What do herbivores eat?",
                     ["Meat", "Plants", "Both meat and plants", "Insects only"], 1,
                     "Carnivores eat meat and omnivores eat both."),
        QuestionSeed("Which animal is known for its black and white stripes?",
                     ["The zebra", "The tapir", "The okapi", "The badger"], 0,
                     "Every zebra's stripe pattern is unique."),
        QuestionSeed("What is a young dog called?",
                     ["A cub", "A puppy", "A kit", "A foal"], 1,
                     "A foal is a young horse and a kit is a young fox or rabbit."),
        QuestionSeed("Which animal is the tallest bird?",
                     ["The emu", "The ostrich", "The cassowary", "The stork"], 1,
                     "Ostriches also lay the largest eggs of any living bird."),
        QuestionSeed("Which mammal can truly fly?",
                     ["The flying squirrel", "The bat", "The sugar glider", "The colugo"], 1,
                     "The others glide rather than achieve powered flight."),
        QuestionSeed("What is a group of fish called?",
                     ["A herd", "A school", "A pack", "A pride"], 1,
                     "A tightly coordinated school is different from a looser shoal."),
        QuestionSeed("Which animal has the longest neck?",
                     ["The camel", "The giraffe", "The llama", "The ostrich"], 1,
                     "Despite its length, a giraffe's neck has the same seven vertebrae as a human's."),
        QuestionSeed("Which insect produces silk used in textiles?",
                     ["The silkworm moth", "The honeybee", "The dragonfly", "The beetle"], 0,
                     "The silk is spun by the caterpillar to build its cocoon."),
        QuestionSeed("What do we call an animal active mainly at night?",
                     ["Diurnal", "Nocturnal", "Crepuscular", "Migratory"], 1,
                     "Crepuscular animals are most active at dawn and dusk."),
        QuestionSeed("Which reptile is known for its hard shell?",
                     ["The snake", "The turtle", "The lizard", "The crocodile"], 1,
                     "The shell is fused to the turtle's skeleton, so it cannot leave it."),
        QuestionSeed("Which animal is famous for building dams?",
                     ["The otter", "The beaver", "The muskrat", "The platypus"], 1,
                     "Beaver dams create ponds that protect the entrances to their lodges."),
        QuestionSeed("What colour are most flamingos, and why?",
                     ["Pink, from pigments in their food", "White, from their feathers", "Grey, from age", "Red, from sunlight"], 0,
                     "Carotenoids in algae and shrimp turn their feathers pink over time."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("Which animal has the longest gestation period among land mammals?",
                     ["The elephant", "The rhinoceros", "The giraffe", "The hippopotamus"], 0,
                     "African elephants carry their young for about twenty-two months."),
        QuestionSeed("What is a group of crows called?",
                     ["A murder", "A gaggle", "A parliament", "A murmuration"], 0,
                     "A parliament is owls and a murmuration is starlings."),
        QuestionSeed("Which mammal lays eggs?",
                     ["The platypus", "The armadillo", "The sloth", "The anteater"], 0,
                     "Platypuses and echidnas are the only egg-laying mammals, called monotremes."),
        QuestionSeed("How many hearts does an octopus have?",
                     ["One", "Two", "Three", "Four"], 2,
                     "Two pump blood to the gills and one pumps it to the rest of the body."),
        QuestionSeed("Which animal has the most powerful bite force?",
                     ["The saltwater crocodile", "The lion", "The great white shark", "The hyena"], 0,
                     "Measured bite forces in large saltwater crocodiles exceed those of any other living animal."),
        QuestionSeed("What is the only continent without native snakes?",
                     ["Australia", "Antarctica", "Europe", "South America"], 1,
                     "Antarctica's climate is far too cold for reptiles."),
        QuestionSeed("Which bird can fly backwards?",
                     ["The hummingbird", "The swift", "The kingfisher", "The sparrow"], 0,
                     "Its figure-eight wing motion generates lift on both strokes."),
        QuestionSeed("What is the largest species of shark?",
                     ["The great white", "The whale shark", "The tiger shark", "The basking shark"], 1,
                     "Whale sharks are filter feeders that eat plankton and small fish."),
        QuestionSeed("How long can a camel go without drinking water?",
                     ["A few hours", "About a day", "Over a week", "A full year"], 2,
                     "Camels can lose a large share of their body water and rehydrate rapidly."),
        QuestionSeed("What is 'indeterminate growth', seen in many reptiles and fish?",
                     ["Continuing to grow slowly throughout adult life", "Growing only in summer", "Stopping growth at maturity", "Shrinking with age"], 0,
                     "Mammals and birds, by contrast, stop growing once they reach adult size."),
        QuestionSeed("What is a group of geese in flight called?",
                     ["A skein", "A gaggle", "A herd", "A colony"], 0,
                     "On the ground the same birds are called a gaggle."),
        QuestionSeed("Which animal is the loudest on Earth relative to its size?",
                     ["The pistol shrimp", "The howler monkey", "The blue whale", "The cicada"], 0,
                     "Its snapping claw creates a cavitation bubble whose collapse is extremely loud."),
        QuestionSeed("What is the primary diet of a koala?",
                     ["Eucalyptus leaves", "Bamboo", "Insects", "Fruit"], 0,
                     "Eucalyptus is toxic to most animals and very low in nutrition."),
        QuestionSeed("Which sea creature can regenerate lost limbs?",
                     ["The starfish", "The jellyfish", "The clam", "The sea horse"], 0,
                     "Some species can regrow an entire body from a single arm and part of the central disc."),
        QuestionSeed("What is an animal that eats both plants and meat called?",
                     ["A herbivore", "An omnivore", "A carnivore", "A scavenger"], 1,
                     "Bears, pigs, and humans are omnivores."),
        QuestionSeed("Which bird has the largest wingspan?",
                     ["The wandering albatross", "The condor", "The eagle", "The pelican"], 0,
                     "Its wingspan can exceed three metres."),
        QuestionSeed("What is metamorphosis in insects?",
                     ["A transformation through distinct life stages", "Seasonal migration", "Shedding of skin only", "Colour change"], 0,
                     "Butterflies undergo complete metamorphosis: egg, larva, pupa, adult."),
        QuestionSeed("Which animal has fingerprints nearly indistinguishable from a human's?",
                     ["The koala", "The chimpanzee", "The gorilla", "The orangutan"], 0,
                     "Koala fingerprints have been mistaken for human ones under a microscope."),
        QuestionSeed("How do snakes primarily detect prey in the dark?",
                     ["Heat-sensing pits and chemical cues", "Echolocation", "Ultraviolet vision", "Electric fields"], 0,
                     "Pit vipers sense infrared, and the flicking tongue carries scent to a sensory organ."),
        QuestionSeed("Which animal sleeps standing up?",
                     ["The horse", "The dog", "The rabbit", "The pig"], 0,
                     "A locking mechanism in the legs lets horses doze without collapsing."),
        QuestionSeed("What is the smallest bird in the world?",
                     ["The bee hummingbird", "The wren", "The goldcrest", "The finch"], 0,
                     "It weighs less than two grams and is found in Cuba."),
        QuestionSeed("Which animal produces the substance called venom by injection?",
                     ["Snakes and spiders", "All reptiles", "Only insects", "Only fish"], 0,
                     "Venom is injected; poison is absorbed or ingested."),
        QuestionSeed("What is a 'joey'?",
                     ["A young kangaroo", "A young owl", "A young fox", "A young deer"], 0,
                     "The term covers the young of most marsupials."),
        QuestionSeed("Which animal migrates the longest distance annually?",
                     ["The Arctic tern", "The monarch butterfly", "The caribou", "The humpback whale"], 0,
                     "It flies roughly between the Arctic and the Antarctic each year."),
        QuestionSeed("What is a 'pod'?",
                     ["A group of whales or dolphins", "A group of lions", "A group of birds", "A group of wolves"], 0,
                     "Dolphins often travel in pods of a dozen or more."),
        QuestionSeed("Which animal has blue blood?",
                     ["The horseshoe crab", "The salmon", "The frog", "The snake"], 0,
                     "Its blood uses copper-based hemocyanin rather than iron-based haemoglobin."),
        QuestionSeed("What do we call the seasonal movement of animals to another region?",
                     ["Migration", "Hibernation", "Estivation", "Molting"], 0,
                     "Hibernation is a dormant winter state, not a journey."),
        QuestionSeed("Which big cat cannot roar?",
                     ["The cheetah", "The lion", "The tiger", "The leopard"], 0,
                     "Cheetahs purr and chirp instead, because of a differently structured hyoid."),
        QuestionSeed("What is the largest rodent in the world?",
                     ["The capybara", "The beaver", "The porcupine", "The muskrat"], 0,
                     "Capybaras are native to South America and are semi-aquatic."),
        QuestionSeed("How do bats navigate in the dark?",
                     ["Echolocation", "Infrared vision", "Magnetic sense only", "Scent trails"], 0,
                     "They emit calls and interpret the returning echoes."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("What is the only known biologically immortal animal?",
                     ["Turritopsis dohrnii, a jellyfish", "The Greenland shark", "The bowhead whale", "The tortoise"], 0,
                     "It can revert to an earlier life stage rather than dying of old age."),
        QuestionSeed("What is a 'monotreme'?",
                     ["An egg-laying mammal", "A marsupial", "A flightless bird", "A cold-blooded mammal"], 0,
                     "Only the platypus and the echidnas remain."),
        QuestionSeed("Which animal has the largest eyes of any living creature?",
                     ["The colossal squid", "The blue whale", "The ostrich", "The horse"], 0,
                     "Its eyes can be nearly thirty centimetres across."),
        QuestionSeed("What is 'eusociality'?",
                     ["A social structure with cooperative brood care and division of labour", "Solitary living", "Seasonal pairing", "Migration in flocks"], 0,
                     "Ants, termites, and some bees and wasps are eusocial."),
        QuestionSeed("Which animal can survive being completely dried out and rehydrated?",
                     ["The tardigrade", "The earthworm", "The snail", "The newt"], 0,
                     "Tardigrades enter a dormant state called cryptobiosis."),
        QuestionSeed("What is 'convergent evolution' in animals exemplified by?",
                     ["Dolphins and sharks evolving similar body shapes", "Cats and dogs sharing ancestors", "Birds inheriting wings from dinosaurs", "Whales returning to the sea"], 0,
                     "One is a mammal and the other a fish, but both evolved for fast swimming."),
        QuestionSeed("Which sense do sharks use to detect electrical fields?",
                     ["The ampullae of Lorenzini", "The lateral line only", "Echolocation", "Olfaction"], 0,
                     "These jelly-filled pores detect the faint fields produced by muscle activity."),
        QuestionSeed("What is a 'keystone species'?",
                     ["A species whose removal drastically changes its ecosystem", "The most numerous species", "The largest predator", "An endangered species"], 0,
                     "Sea otters are a classic example because they control sea urchin populations."),
        QuestionSeed("Which animal group are cetaceans?",
                     ["Whales, dolphins, and porpoises", "Seals and sea lions", "Sharks and rays", "Turtles"], 0,
                     "Cetaceans are mammals that returned fully to aquatic life."),
        QuestionSeed("What is 'brood parasitism'?",
                     ["Laying eggs in another species' nest", "Eating one's own young", "Parasites living on nestlings", "Sharing a nest cooperatively"], 0,
                     "Cuckoos are the best-known practitioners."),
        QuestionSeed("What does an animal's chromosome count tell you about its complexity?",
                     ["Essentially nothing", "It scales directly with complexity", "It equals the number of organs", "It doubles each generation"], 0,
                     "Some butterflies carry far more chromosomes than humans do."),
        QuestionSeed("What does 'endothermic' mean?",
                     ["Generating body heat internally", "Relying on external heat", "Living underground", "Being nocturnal"], 0,
                     "Mammals and birds are endotherms; most reptiles are ectotherms."),
        QuestionSeed("What is the function of a cephalopod's chromatophores?",
                     ["Rapid colour and pattern change", "Producing ink", "Jet propulsion", "Detecting light"], 0,
                     "Muscles expand and contract pigment sacs almost instantly."),
        QuestionSeed("Which animal's teeth never stop growing?",
                     ["Rodents", "Cats", "Cows", "Bears"], 0,
                     "Continuous gnawing keeps rodent incisors worn down to a usable length."),
        QuestionSeed("What is 'aposematism'?",
                     ["Warning coloration signalling that prey is dangerous", "Camouflage", "Mimicking a mate", "Playing dead"], 0,
                     "Poison dart frogs and monarch butterflies both advertise their toxicity."),
        QuestionSeed("Which mammal has the longest lifespan?",
                     ["The bowhead whale", "The elephant", "The human", "The horse"], 0,
                     "Bowhead whales are estimated to live beyond two hundred years."),
        QuestionSeed("What is 'Batesian mimicry'?",
                     ["A harmless species imitating a dangerous one", "Two toxic species converging", "Camouflage against a background", "Mimicking a predator's call"], 0,
                     "Müllerian mimicry, by contrast, involves two genuinely defended species resembling each other."),
        QuestionSeed("What is the purpose of a whale's baleen?",
                     ["Filtering small prey from seawater", "Crushing shells", "Producing sound", "Storing oxygen"], 0,
                     "Baleen plates are made of keratin, the same protein as hair and nails."),
        QuestionSeed("Which animals form the class Chondrichthyes?",
                     ["Cartilaginous fish such as sharks and rays", "Bony fish", "Amphibians", "Marine mammals"], 0,
                     "Their skeletons are cartilage rather than bone."),
        QuestionSeed("What is 'diapause' in insects?",
                     ["A suspended development state during harsh conditions", "A mating ritual", "A moulting stage", "A migration phase"], 0,
                     "It lets a species wait out winter or drought at a fixed life stage."),
        QuestionSeed("Which animal produces the strongest known natural silk?",
                     ["The Darwin's bark spider", "The silkworm", "The caddisfly", "The weaver ant"], 0,
                     "Its webs can span rivers and are exceptionally tough."),
        QuestionSeed("What is 'countershading'?",
                     ["Dark above and light below to reduce visibility", "Bright warning colours", "Seasonal coat change", "Iridescent patterning"], 0,
                     "It counteracts the shadow cast by overhead light, flattening an animal's outline."),
        QuestionSeed("Which group does a sea star belong to?",
                     ["Echinoderms", "Molluscs", "Crustaceans", "Cnidarians"], 0,
                     "Echinoderms have radial symmetry and a water vascular system."),
        QuestionSeed("What is a 'ruminant'?",
                     ["An animal that ferments food in a multi-chambered stomach", "A nocturnal grazer", "A burrowing herbivore", "An egg-laying mammal"], 0,
                     "Cattle, sheep, goats, and deer are ruminants."),
        QuestionSeed("Which animal has the densest fur of any species?",
                     ["The sea otter", "The polar bear", "The arctic fox", "The chinchilla"], 0,
                     "Sea otters lack blubber, so their fur must trap air for insulation."),
        QuestionSeed("What is 'philopatry'?",
                     ["The tendency to return to or stay near a birthplace", "Long-distance migration", "Territorial aggression", "Group hunting"], 0,
                     "Salmon returning to their natal stream is a striking example."),
        QuestionSeed("Which venomous mammal uses spurs on its hind legs?",
                     ["The male platypus", "The shrew", "The slow loris", "The vampire bat"], 0,
                     "The venom is painful to humans but not usually life-threatening."),
        QuestionSeed("What is a 'trophic cascade'?",
                     ["Knock-on ecosystem effects from a change at one feeding level", "A migration route", "A food shortage", "A breeding cycle"], 0,
                     "The return of wolves to Yellowstone is the most cited case study."),
        QuestionSeed("Which sense is most developed in a star-nosed mole?",
                     ["Touch", "Sight", "Hearing", "Taste"], 0,
                     "Its twenty-two fleshy appendages are among the most sensitive touch organs known."),
        QuestionSeed("What does 'oviparous' mean?",
                     ["Producing young by laying eggs", "Giving live birth", "Carrying young in a pouch", "Reproducing asexually"], 0,
                     "Viviparous animals give birth to live young."),
    ]
}
