import Foundation

enum AnimalsQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("What is the largest living animal?",
                     ["The African elephant", "The blue whale", "The giraffe", "The whale shark"], 1,
                     "A blue whale can exceed thirty metres in length."),
        QuestionSeed("Which is the fastest land animal over a short distance?",
                     ["The lion", "The cheetah", "The horse", "The greyhound"], 1,
                     "Cheetahs can reach around 100 kilometres per hour but tire within seconds."),
        QuestionSeed("What is the tallest living animal?",
                     ["The elephant", "The giraffe", "The ostrich", "The camel"], 1,
                     "An adult male giraffe can stand over five metres tall."),
        QuestionSeed("Which animal is known as man's best friend?",
                     ["The cat", "The dog", "The horse", "The parrot"], 1,
                     "Dogs were domesticated at least fifteen thousand years ago and are widely considered the earliest domesticated animal species."),
        QuestionSeed("What do you call a baby cat?",
                     ["A cub", "A kitten", "A puppy", "A calf"], 1,
                     "A baby dog is a puppy and a baby lion is a cub."),
        QuestionSeed("Which bird is famous for being unable to fly and living in Antarctica?",
                     ["The albatross", "The penguin", "The puffin", "The seagull"], 1,
                     "Penguins use their wings as flippers to swim rather than fly."),
        QuestionSeed("How many humps does a dromedary camel have?",
                     ["None", "One", "Two", "Three"], 1,
                     "Bactrian camels have two humps."),
        QuestionSeed("Which animal is the largest big cat?",
                     ["The lion", "The tiger", "The leopard", "The jaguar"], 1,
                     "Siberian tigers are the largest of all."),
        QuestionSeed("What do bees make?",
                     ["Silk", "Honey", "Wax paper", "Amber"], 1,
                     "They also produce beeswax, which they use to build the comb."),
        QuestionSeed("Which sea creature has eight arms?",
                     ["The squid", "The octopus", "The jellyfish", "The starfish"], 1,
                     "Squid have eight arms plus two longer tentacles."),
        QuestionSeed("What is a group of lions called?",
                     ["A herd", "A pride", "A pack", "A flock"], 1,
                     "Wolves travel in packs and birds gather in flocks."),
        QuestionSeed("Which animal is known for changing colour?",
                     ["The chameleon", "The iguana", "The gecko", "The tortoise"], 0,
                     "Colour change is used for temperature regulation and signalling more than camouflage."),
        QuestionSeed("What kind of animal is a frog?",
                     ["A reptile", "An amphibian", "A mammal", "A fish"], 1,
                     "Amphibians typically begin life in water and breathe partly through their skin."),
        QuestionSeed("Which animal carries its young in a pouch?",
                     ["The kangaroo", "The zebra", "The rhinoceros", "The hippopotamus"], 0,
                     "Marsupials give birth to very undeveloped young that finish growing in the pouch."),
        QuestionSeed("How many legs does an insect have?",
                     ["Four", "Six", "Eight", "Ten"], 1,
                     "Six legs and three body segments define insects."),
        QuestionSeed("Which bird is a symbol of wisdom?",
                     ["The owl", "The crow", "The dove", "The eagle"], 0,
                     "The association goes back to the owl of the Greek goddess Athena."),
        QuestionSeed("What is the largest species of bear?",
                     ["The black bear", "The polar bear", "The sun bear", "The panda"], 1,
                     "Polar bears and the largest brown bears are comparable in size."),
        QuestionSeed("Which animal is most commonly raised for wool used in clothing?",
                     ["The cow", "The sheep", "The pig", "The chicken"], 1,
                     "Sheep supply most clothing wool; goats and alpacas also produce valuable textile fibres."),
        QuestionSeed("What do herbivores eat?",
                     ["Meat", "Plants", "Both meat and plants", "Insects only"], 1,
                     "Carnivores eat meat and omnivores eat both."),
        QuestionSeed("Which animal is known for its black and white stripes?",
                     ["The zebra", "The tapir", "The okapi", "The badger"], 0,
                     "Every zebra's stripe pattern is unique."),
        QuestionSeed("What is a young dog called?",
                     ["A cub", "A puppy", "A kit", "A foal"], 1,
                     "A foal is a young horse and a kit is a young fox or rabbit."),
        QuestionSeed("Which animal is the tallest bird?",
                     ["The emu", "The ostrich", "The cassowary", "The stork"], 1,
                     "Ostriches also lay the largest eggs of any living bird."),
        QuestionSeed("Which mammal can truly fly?",
                     ["The flying squirrel", "The bat", "The sugar glider", "The colugo"], 1,
                     "The others glide rather than achieve powered flight."),
        QuestionSeed("What is a group of fish called?",
                     ["A herd", "A school", "A pack", "A pride"], 1,
                     "A tightly coordinated school is different from a looser shoal."),
        QuestionSeed("Which animal has the longest neck?",
                     ["The camel", "The giraffe", "The llama", "The ostrich"], 1,
                     "Despite its length, a giraffe's neck has the same seven vertebrae as a human's."),
        QuestionSeed("Which insect produces silk used in textiles?",
                     ["The silkworm moth", "The honeybee", "The dragonfly", "The beetle"], 0,
                     "The silk is spun by the caterpillar to build its cocoon."),
        QuestionSeed("What do we call an animal active mainly at night?",
                     ["Diurnal", "Nocturnal", "Crepuscular", "Migratory"], 1,
                     "Crepuscular animals are most active at dawn and dusk."),
        QuestionSeed("Which reptile is known for its hard shell?",
                     ["The snake", "The turtle", "The lizard", "The crocodile"], 1,
                     "The shell is fused to the turtle's skeleton, so it cannot leave it."),
        QuestionSeed("Which animal is famous for building dams?",
                     ["The otter", "The beaver", "The muskrat", "The platypus"], 1,
                     "Beaver dams create ponds that protect the entrances to their lodges."),
        QuestionSeed("What colour are most flamingos, and why?",
                     ["Pink, from pigments in their food", "White, from their feathers", "Grey, from age", "Red, from sunlight"], 0,
                     "Carotenoids in algae and shrimp turn their feathers pink over time."),
        QuestionSeed("What is a young sheep called?",
                     ["A lamb", "A calf", "A foal", "A kid"], 0,
                     "A kid is a young goat, while calf and foal refer to young cattle and horses."),
        QuestionSeed("Which animal is the largest living land animal?",
                     ["The white rhinoceros", "The African bush elephant", "The hippopotamus", "The giraffe"], 1,
                     "Large male African bush elephants can weigh more than six tonnes."),
        QuestionSeed("Which organs allow most fish to extract oxygen from water?",
                     ["Lungs", "Gills", "Spiracles", "Air sacs"], 1,
                     "Water passing over the gills exchanges oxygen and carbon dioxide with the blood."),
        QuestionSeed("What covers a bird's body and helps provide insulation?",
                     ["Scales", "Fur", "Feathers", "Quills"], 2,
                     "Feathers trap air for warmth and also form the flight surfaces of most birds."),
        QuestionSeed("What is a large social group of ants called?",
                     ["A colony", "A school", "A pride", "A pod"], 0,
                     "An ant colony may contain workers, soldiers, reproductive queens, and developing young."),
        QuestionSeed("What defining food do female mammals produce for their young?",
                     ["Nectar", "Milk", "Pollen", "Yolk"], 1,
                     "Mammary glands produce milk, the trait for which mammals are named."),
        QuestionSeed("Which adult animal commonly begins life as a tadpole?",
                     ["A frog", "A lizard", "A turtle", "A mouse"], 0,
                     "A tadpole develops limbs and lungs as it undergoes metamorphosis into an adult frog."),
        QuestionSeed("Which animal is the largest living primate?",
                     ["The orangutan", "The chimpanzee", "The gorilla", "The mandrill"], 2,
                     "Adult male gorillas are the largest primates and can weigh well over 150 kilograms."),
        QuestionSeed("Which of these animals belongs to the canine family?",
                     ["The wolf", "The hyena", "The mongoose", "The meerkat"], 0,
                     "Wolves belong to Canidae, the same family as dogs, foxes, and jackals."),
        QuestionSeed("Which structure does an elephant use to smell, drink, and grasp objects?",
                     ["Its tusk", "Its trunk", "Its ear", "Its tail"], 1,
                     "An elephant's trunk is a muscular fusion of its nose and upper lip."),
        QuestionSeed("What is a group of birds flying together called?",
                     ["A flock", "A herd", "A swarm", "A litter"], 0,
                     "Birds traveling together are called a flock, whether pigeons in a park or migrating geese."),
        QuestionSeed("Which large African animal spends its days submerged in rivers?",
                     ["The hippopotamus", "The rhinoceros", "The manatee", "The water buffalo"], 0,
                     "The hippopotamus spends its days in African rivers and grazes on land after dark."),
        QuestionSeed("Which bird is known for its ability to mimic speech?",
                     ["The parrot", "The sparrow", "The pigeon", "The kingfisher"], 0,
                     "The parrot can mimic human speech and a wide range of other sounds."),
        QuestionSeed("Which animal uses a long sticky tongue to catch ants?",
                     ["The anteater", "The armadillo", "The pangolin", "The sloth"], 0,
                     "An anteater's tongue can flick out many times a second to gather ants and termites."),
        QuestionSeed("Which animal is known as the ship of the desert?",
                     ["The camel", "The donkey", "The llama", "The dromedary horse"], 0,
                     "The camel is called the ship of the desert for carrying loads across sand."),
        QuestionSeed("What is a baby horse called?",
                     ["A foal", "A calf", "A cub", "A kid"], 0,
                     "A foal is a horse under one year old, and can usually stand within hours."),
        QuestionSeed("Which shelled ocean animal is known for walking sideways?",
                     ["The crab", "The lobster", "The shrimp", "The clam"], 0,
                     "A crab's legs bend sideways, so moving across the sand that way is simply more efficient."),
        QuestionSeed("Which creature spins a silk web to catch its prey?",
                     ["The spider", "The beetle", "The cricket", "The moth"], 0,
                     "A spider spins silk into a web and waits for insects to become trapped in it."),
        QuestionSeed("What is a group of wolves called?",
                     ["A pack", "A herd", "A flock", "A congregation"], 0,
                     "A group of wolves is called a pack, usually led by a breeding pair."),
        QuestionSeed("Which bird fans a colorful train of feathers to display?",
                     ["The peacock", "The pheasant", "The turkey", "The swan"], 0,
                     "A male peacock fans a long train of iridescent feathers to attract a peahen."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("Which animal has the longest gestation period among land mammals?",
                     ["The elephant", "The rhinoceros", "The giraffe", "The hippopotamus"], 0,
                     "African elephants carry their young for about twenty-two months."),
        QuestionSeed("What is a group of crows called?",
                     ["A murder", "A gaggle", "A parliament", "A murmuration"], 0,
                     "A parliament is owls and a murmuration is starlings."),
        QuestionSeed("Which mammal lays eggs?",
                     ["The platypus", "The armadillo", "The sloth", "The anteater"], 0,
                     "Platypuses and echidnas are the only egg-laying mammals, called monotremes."),
        QuestionSeed("How many hearts does an octopus have?",
                     ["One", "Two", "Three", "Four"], 2,
                     "Two pump blood to the gills and one pumps it to the rest of the body."),
        QuestionSeed("Which living animal has the strongest bite force measured directly?",
                     ["The saltwater crocodile", "The lion", "The great white shark", "The hyena"], 0,
                     "Large saltwater crocodiles have produced the greatest directly measured bite forces among living animals."),
        QuestionSeed("What is the only continent without native snakes?",
                     ["Australia", "Antarctica", "Europe", "South America"], 1,
                     "Antarctica's climate is far too cold for reptiles."),
        QuestionSeed("Which bird can fly backwards?",
                     ["The hummingbird", "The swift", "The kingfisher", "The sparrow"], 0,
                     "Its figure-eight wing motion generates lift on both strokes."),
        QuestionSeed("What is the largest species of shark?",
                     ["The great white", "The whale shark", "The tiger shark", "The basking shark"], 1,
                     "Whale sharks are filter feeders that eat plankton and small fish."),
        QuestionSeed("Which adaptation helps camels survive for days in very dry conditions?",
                     ["Tolerating substantial water loss", "Storing water inside their humps", "Absorbing water through their feet", "Stopping all breathing"], 0,
                     "Camels tolerate substantial dehydration and can rehydrate rapidly; their humps store fat rather than water."),
        QuestionSeed("What is 'indeterminate growth', seen in many reptiles and fish?",
                     ["Continuing to grow slowly throughout adult life", "Growing rapidly during warm months and stopping completely each winter", "Reaching a genetically fixed adult size and then ceasing all growth", "Becoming progressively smaller as stored energy is used during aging"], 0,
                     "Mammals and birds, by contrast, stop growing once they reach adult size."),
        QuestionSeed("What is a group of geese in flight called?",
                     ["A skein", "A gaggle", "A herd", "A colony"], 0,
                     "On the ground the same birds are called a gaggle."),
        QuestionSeed("Which animal has been recorded as exceptionally loud relative to its body size?",
                     ["The lesser water boatman", "The pistol shrimp", "The howler monkey", "The cicada"], 0,
                     "Male lesser water boatmen produce underwater courtship calls measured near 79 decibels despite being only a few millimetres long."),
        QuestionSeed("What is the primary diet of a koala?",
                     ["Eucalyptus leaves", "Bamboo", "Insects", "Fruit"], 0,
                     "Eucalyptus is toxic to most animals and very low in nutrition."),
        QuestionSeed("Which sea creature can regenerate lost limbs?",
                     ["The starfish", "The jellyfish", "The clam", "The sea horse"], 0,
                     "Some species can regrow an entire body from a single arm and part of the central disc."),
        QuestionSeed("What is an animal that eats both plants and meat called?",
                     ["A herbivore", "An omnivore", "A carnivore", "A scavenger"], 1,
                     "Bears, pigs, and humans are omnivores."),
        QuestionSeed("Which bird has the largest wingspan?",
                     ["The wandering albatross", "The condor", "The eagle", "The pelican"], 0,
                     "Its wingspan can exceed three metres."),
        QuestionSeed("What is metamorphosis in insects?",
                     ["A transformation through distinct life stages", "The regular seasonal movement between feeding and breeding habitats", "The periodic replacement of an insect's cuticle without other changes", "A reversible shift in body colour caused by temperature or background"], 0,
                     "Butterflies undergo complete metamorphosis: egg, larva, pupa, adult."),
        QuestionSeed("Which animal has fingerprints that closely resemble human fingerprints?",
                     ["The koala", "The chimpanzee", "The gorilla", "The orangutan"], 0,
                     "Koalas independently evolved fingertip ridges that can look remarkably similar to human fingerprints."),
        QuestionSeed("How can pit vipers detect warm-blooded prey in darkness?",
                     ["Infrared-sensing facial pits", "Echolocation", "Ultraviolet vision", "Electric fields"], 0,
                     "Pit vipers use heat-sensitive facial pits, while snakes more generally use chemical cues gathered by the tongue."),
        QuestionSeed("Which animal sleeps standing up?",
                     ["The horse", "The dog", "The rabbit", "The pig"], 0,
                     "A locking mechanism in the legs lets horses doze without collapsing."),
        QuestionSeed("What is the smallest bird in the world?",
                     ["The bee hummingbird", "The wren", "The goldcrest", "The finch"], 0,
                     "It weighs less than two grams and is found in Cuba."),
        QuestionSeed("What distinguishes venom from poison?",
                     ["Venom is delivered into tissue by a bite or sting", "Venom is harmless when injected", "Poison is produced only by plants", "Venom is swallowed, while poison must enter through a bite or sting"], 0,
                     "Venom is actively delivered into another animal, while poison is absorbed, inhaled, or ingested."),
        QuestionSeed("What is a 'joey'?",
                     ["A young kangaroo", "A young owl", "A young fox", "A young deer"], 0,
                     "The term covers the young of most marsupials."),
        QuestionSeed("Which animal migrates the longest distance annually?",
                     ["The Arctic tern", "The monarch butterfly", "The caribou", "The humpback whale"], 0,
                     "It flies roughly between the Arctic and the Antarctic each year."),
        QuestionSeed("What is a 'pod'?",
                     ["A group of whales or dolphins", "A group of lions", "A group of birds", "A group of wolves"], 0,
                     "Dolphins often travel in pods of a dozen or more."),
        QuestionSeed("Which animal has blue blood?",
                     ["The horseshoe crab", "The salmon", "The frog", "The snake"], 0,
                     "Its blood uses copper-based hemocyanin rather than iron-based haemoglobin."),
        QuestionSeed("What do we call the seasonal movement of animals to another region?",
                     ["Migration", "Hibernation", "Estivation", "Molting"], 0,
                     "Hibernation is a dormant winter state, not a journey."),
        QuestionSeed("Which big cat cannot roar?",
                     ["The cheetah", "The lion", "The tiger", "The leopard"], 0,
                     "Cheetahs purr and chirp instead, because of a differently structured hyoid."),
        QuestionSeed("What is the largest rodent in the world?",
                     ["The capybara", "The beaver", "The porcupine", "The muskrat"], 0,
                     "Capybaras are native to South America and are semi-aquatic."),
        QuestionSeed("How do bats navigate in the dark?",
                     ["Echolocation", "Infrared vision", "Magnetic sense only", "Scent trails"], 0,
                     "They emit calls and interpret the returning echoes."),
        QuestionSeed("Which species is the largest living penguin?",
                     ["The king penguin", "The emperor penguin", "The southern rockhopper penguin", "The Adélie penguin"], 1,
                     "Emperor penguins can stand more than a metre tall and breed during the Antarctic winter."),
        QuestionSeed("Which parent carries developing seahorse young in a brood pouch?",
                     ["The male", "The female", "Both parents in turn", "Neither parent"], 0,
                     "The female deposits eggs into the male's pouch, where he fertilizes and carries them."),
        QuestionSeed("Which marine mammals use clicks and returning echoes to locate objects?",
                     ["Sea otters", "Dolphins", "Manatees", "Walruses"], 1,
                     "Toothed whales such as dolphins use echolocation to navigate and hunt."),
        QuestionSeed("What material makes up most of a rhinoceros horn?",
                     ["Bone", "Ivory", "Keratin", "Cartilage"], 2,
                     "Keratin is also the main structural protein in human hair and fingernails."),
        QuestionSeed("What microscopic structures help many geckos cling to smooth surfaces?",
                     ["Dense rows of curved microscopic claws", "A thin continuous film of adhesive mucus", "Millions of tiny toe hairs", "Clusters of small muscular suction discs"], 2,
                     "Branching toe hairs called setae create weak molecular attractions with the surface."),
        QuestionSeed("What can incubation temperature influence in many crocodilian eggs?",
                     ["The hatchlings' sex", "The number of limbs", "The shell colour", "Whether scales form"], 0,
                     "Temperature-dependent sex determination occurs during a critical period of embryo development."),
        QuestionSeed("How does a whale shark obtain most of its food?",
                     ["By filter feeding", "By grazing sea grass", "By cracking shells", "By ambushing seals"], 0,
                     "Whale sharks strain plankton and small animals from water despite being the largest living fish."),
        QuestionSeed("What is the usual role of the matriarch in an elephant family group?",
                     ["Leading the herd using accumulated knowledge", "Protecting a permanent nesting site from rival family groups", "Coordinating hunts for large prey across the herd's territory", "Excavating communal underground shelters during the dry season"], 0,
                     "The matriarch is generally the oldest female and helps guide the herd to food and water."),
        QuestionSeed("Why does an arctic fox grow a white winter coat in snowy regions?",
                     ["To attract prey", "For camouflage and insulation", "To reflect moonlight", "To mark breeding status"], 1,
                     "Its dense seasonal coat blends with snow and reduces heat loss; the summer coat is usually darker."),
        QuestionSeed("What technique lets albatrosses travel long distances while rarely flapping?",
                     ["Dynamic soaring", "Hovering", "Thermal burrowing", "Underwater gliding"], 0,
                     "Dynamic soaring extracts energy from differences in wind speed just above the ocean."),
        QuestionSeed("What is a group of hyenas called?",
                     ["A cackle", "A pack", "A congregation", "A troop"], 0,
                     "A group of hyenas is called a cackle, named for the sound they make together."),
        QuestionSeed("Which amphibian survives winter by letting its body freeze?",
                     ["The wood frog", "The garter snake", "The brown bear", "The arctic hare"], 0,
                     "A wood frog lets much of its body freeze each winter, then thaws back to life."),
        QuestionSeed("What is a group of owls called?",
                     ["A parliament", "A congress", "A conspiracy", "A council"], 0,
                     "English collective nouns call a group of owls a parliament, a term from medieval literature."),
        QuestionSeed("What makes up almost the entire diet of a giant panda?",
                     ["Bamboo", "Eucalyptus", "Acacia leaves", "Berries"], 0,
                     "Giant pandas eat bamboo almost exclusively, spending much of the day chewing to get enough calories."),
        QuestionSeed("What is a group of jellyfish called?",
                     ["A smack", "A bloom", "A cluster", "A swarm"], 0,
                     "A group of jellyfish is properly called a smack, one of the stranger English collective nouns."),
        QuestionSeed("Which sense is exceptionally strong in sharks?",
                     ["Smell", "Hearing", "Taste", "Color perception"], 0,
                     "Sharks have an exceptional sense of smell, detecting traces of blood in water."),
        QuestionSeed("What is autotomy, a defense used by many lizards?",
                     ["Deliberately shedding a body part", "Inflating the body to look larger", "Changing skin color to match surroundings", "Playing dead until danger passes"], 0,
                     "Autotomy lets an animal deliberately shed a tail or other body part, distracting a predator while it escapes."),
        QuestionSeed("Which bird builds the heaviest nest of any species?",
                     ["The bald eagle", "The stork", "The osprey", "The sociable weaver"], 0,
                     "A bald eagle pair adds to the same nest yearly until it weighs over a ton."),
        QuestionSeed("What is unusual about the way most marsupials are born?",
                     ["Their young are extremely undeveloped", "Their young hatch from hard-shelled eggs", "Their young can walk within minutes", "Their young are born with a full coat"], 0,
                     "Most marsupials give birth after a short pregnancy to tiny, undeveloped young that continue growing while attached to a teat."),
        QuestionSeed("Which bird is fastest in level flight?",
                     ["The common swift", "The peregrine falcon", "The albatross", "The frigatebird"], 0,
                     "The common swift holds the record for level flight, distinct from the peregrine's diving speed."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("Which animal is famous for reversing from its adult medusa stage to a juvenile polyp stage?",
                     ["Turritopsis dohrnii, a jellyfish", "The Greenland shark", "Balaena mysticetus, the bowhead whale", "The giant tortoise"], 0,
                     "Turritopsis dohrnii can reverse its life cycle, but it can still die from disease, injury, or predation."),
        QuestionSeed("What is a 'monotreme'?",
                     ["An egg-laying mammal", "A marsupial", "A flightless bird", "A cold-blooded mammal"], 0,
                     "Only the platypus and the echidnas remain."),
        QuestionSeed("Which animal has the largest eyes of any living creature?",
                     ["The colossal squid", "The blue whale", "The ostrich", "The horse"], 0,
                     "Its eyes can be nearly thirty centimetres across."),
        QuestionSeed("What is 'eusociality'?",
                     ["A social structure with cooperative brood care and division of labour", "An adult lifestyle in which individuals forage and reproduce entirely alone", "Seasonal pairing", "A coordinated movement in which a group travels between seasonal habitats"], 0,
                     "Ants, termites, and some bees and wasps are eusocial."),
        QuestionSeed("Which animal can survive being completely dried out and rehydrated?",
                     ["The tardigrade", "The earthworm", "The snail", "The newt"], 0,
                     "Tardigrades enter a dormant state called cryptobiosis."),
        QuestionSeed("What is 'convergent evolution' in animals exemplified by?",
                     ["Dolphins and sharks evolving similar body shapes", "Domestic cats and dogs retaining traits inherited from a recent ancestor", "Modern birds receiving fully developed wings directly from dinosaurs", "Whale ancestors gradually adapting from terrestrial life back to the ocean"], 0,
                     "One is a mammal and the other a fish, but both evolved for fast swimming."),
        QuestionSeed("Which sensory structures let sharks detect weak electrical fields?",
                     ["Ampullae of Lorenzini", "Lateral-line canals", "Jacobson's organs", "Tympanic membranes"], 0,
                     "The ampullae of Lorenzini are jelly-filled pores that detect faint electrical fields produced by muscle activity."),
        QuestionSeed("What is a 'keystone species'?",
                     ["A species whose removal drastically changes its ecosystem", "The species with the greatest population in a biological community", "The largest predator", "An endangered species"], 0,
                     "Sea otters are a classic example because they control sea urchin populations."),
        QuestionSeed("Which animal group are cetaceans?",
                     ["Whales, dolphins, and porpoises", "Seals and sea lions", "Sharks and rays", "Sea turtles, land tortoises, and freshwater terrapins"], 0,
                     "Cetaceans are mammals that returned fully to aquatic life."),
        QuestionSeed("What is 'brood parasitism'?",
                     ["Laying eggs in another species' nest", "Eating one's own young", "Living as a parasite on newly hatched nestlings", "Sharing a nest cooperatively"], 0,
                     "Cuckoos are the best-known practitioners."),
        QuestionSeed("What does an animal's chromosome count tell you about its complexity?",
                     ["Essentially nothing", "It scales directly with complexity", "It equals the number of organs", "It doubles each generation"], 0,
                     "Some butterflies carry far more chromosomes than humans do."),
        QuestionSeed("What does 'endothermic' mean?",
                     ["Generating body heat internally", "Relying on external heat", "Living underground", "Being nocturnal"], 0,
                     "Mammals and birds are endotherms; most reptiles are ectotherms."),
        QuestionSeed("What is the function of a cephalopod's chromatophores?",
                     ["Rapid colour and pattern change", "Releasing a cloud of defensive ink into the water", "Driving water through the siphon for propulsion", "Detecting light"], 0,
                     "Muscles expand and contract pigment sacs almost instantly."),
        QuestionSeed("Which teeth grow continuously in rodents?",
                     ["The incisors", "The canines", "The premolars", "All teeth"], 0,
                     "Continuous gnawing wears rodent incisors down as they grow."),
        QuestionSeed("What is 'aposematism'?",
                     ["Warning coloration signalling that prey is dangerous", "Blending an animal's outline into its surrounding habitat", "Mimicking a mate", "Remaining motionless to resemble an animal that has died"], 0,
                     "Poison dart frogs and monarch butterflies both advertise their toxicity."),
        QuestionSeed("Which mammal has the longest lifespan?",
                     ["The bowhead whale", "The elephant", "The human", "The horse"], 0,
                     "Bowhead whales are estimated to live beyond two hundred years."),
        QuestionSeed("What is 'Batesian mimicry'?",
                     ["A harmless species imitating a dangerous one", "Two dangerous species evolving the same warning pattern", "An animal matching the colour and texture of its habitat", "An animal copying the alarm call made by its predator"], 0,
                     "Müllerian mimicry, by contrast, involves two genuinely defended species resembling each other."),
        QuestionSeed("What is the purpose of a whale's baleen?",
                     ["Filtering small prey from seawater", "Crushing hard-shelled prey before it is swallowed", "Producing low-frequency calls heard across long distances", "Storing extra oxygen for dives beneath the ocean surface"], 0,
                     "Baleen plates are made of keratin, the same protein as hair and nails."),
        QuestionSeed("Which animals form the class Chondrichthyes?",
                     ["Cartilaginous fish such as sharks and rays", "Ray-finned and lobe-finned fish with skeletons made of bone", "Frogs, salamanders, and caecilians with aquatic larvae", "Whales, seals, and sirenians that spend their lives in water"], 0,
                     "Their skeletons are cartilage rather than bone."),
        QuestionSeed("What is 'diapause' in insects?",
                     ["A suspended development state during harsh conditions", "An elaborate courtship display performed before insects mate", "A transitional stage in which a larva sheds its outer covering", "A seasonal movement from one habitat to another for reproduction"], 0,
                     "It lets a species wait out winter or drought at a fixed life stage."),
        QuestionSeed("Which animal produces natural silk noted for exceptional toughness?",
                     ["Darwin's bark spider", "The silkworm", "The caddisfly", "The weaver ant"], 0,
                     "Darwin's bark-spider silk absorbs exceptional energy before breaking, a property called toughness."),
        QuestionSeed("What is 'countershading'?",
                     ["Dark above and light below to reduce visibility", "Bright warning colours", "Replacing a coat or plumage to match a different season", "Iridescent patterning"], 0,
                     "It counteracts the shadow cast by overhead light, flattening an animal's outline."),
        QuestionSeed("Which group does a sea star belong to?",
                     ["Echinoderms", "Molluscs", "Crustaceans", "Cnidarians"], 0,
                     "Echinoderms have radial symmetry and a water vascular system."),
        QuestionSeed("What is a 'ruminant'?",
                     ["An animal that ferments food in a multi-chambered stomach", "An animal that feeds mainly at night on grasses and other plants", "A herbivore adapted to dig extensive tunnels below the ground", "A mammal that reproduces by laying eggs instead of bearing live young"], 0,
                     "Cattle, sheep, goats, and deer are ruminants."),
        QuestionSeed("Which animal has the densest fur of any species?",
                     ["The sea otter", "The polar bear", "The arctic fox", "The chinchilla"], 0,
                     "Sea otters lack blubber, so their fur must trap air for insulation."),
        QuestionSeed("What is 'philopatry'?",
                     ["The tendency to return to or stay near a birthplace", "Long-distance migration", "Defending a fixed home range against members of the same species", "Coordinating with other individuals to surround and capture prey"], 0,
                     "Salmon returning to their natal stream is a striking example."),
        QuestionSeed("Which venomous mammal uses spurs on its hind legs?",
                     ["The male platypus", "The shrew", "The slow loris", "The vampire bat"], 0,
                     "The venom is painful to humans but not usually life-threatening."),
        QuestionSeed("What is a 'trophic cascade'?",
                     ["Knock-on ecosystem effects from a change at one feeding level", "A migration route", "A temporary decline in available food across an entire ecosystem", "A breeding cycle"], 0,
                     "The return of wolves to Yellowstone is the most cited case study."),
        QuestionSeed("Which sense is most developed in a star-nosed mole?",
                     ["Touch", "Sight", "Hearing", "Taste"], 0,
                     "Its twenty-two fleshy appendages are among the most sensitive touch organs known."),
        QuestionSeed("What does 'oviparous' mean?",
                     ["Producing young by laying eggs", "Giving live birth", "Carrying young in a pouch", "Reproducing asexually"], 0,
                     "Viviparous animals give birth to live young."),
        QuestionSeed("What are the stinging cells of jellyfish and corals called?",
                     ["Choanocytes", "Cnidocytes", "Osteocytes", "Chromatophores"], 1,
                     "Cnidocytes contain capsules called nematocysts that discharge a barbed thread."),
        QuestionSeed("What does the vomeronasal, or Jacobson's, organ primarily detect?",
                     ["Water pressure", "Chemical signals", "Ultraviolet light", "Electrical fields"], 1,
                     "Many reptiles and mammals use it to analyse pheromones and other chemical cues."),
        QuestionSeed("What information does a fish's lateral-line system detect?",
                     ["Changes in nearby water movement", "The colour of distant objects", "Air pressure above water", "Blood oxygen level"], 0,
                     "Sensory hair cells along the body respond to vibrations and pressure changes in the water."),
        QuestionSeed("Which metal is present in the oxygen-carrying pigment hemocyanin?",
                     ["Iron", "Copper", "Magnesium", "Zinc"], 1,
                     "Copper-containing hemocyanin gives the blood of many molluscs and arthropods a blue appearance when oxygenated."),
        QuestionSeed("Why do many birds and reptiles excrete nitrogen mainly as uric acid?",
                     ["It conserves water", "It produces body heat", "It dissolves shells", "It stores oxygen"], 0,
                     "Uric acid can leave the body as a concentrated paste, requiring less water than urea or ammonia."),
        QuestionSeed("Which organ produces the loud calling sound of most cicadas?",
                     ["A syrinx", "A tymbal", "A resonating beak", "A stridulating wing"], 1,
                     "Muscles rapidly buckle ribbed membranes called tymbals on the abdomen."),
        QuestionSeed("What is the spermaceti organ in a sperm whale chiefly involved in?",
                     ["Producing milk", "Sound production and focusing", "Filtering plankton", "Regulating salt intake"], 1,
                     "The large oil-filled structure helps generate and direct powerful echolocation clicks."),
        QuestionSeed("What is aestivation?",
                     ["Dormancy during hot or dry conditions", "Migration to breeding grounds", "Replacing short summer fur with a thicker insulating winter coat", "Entering a brief daily period of reduced metabolism after sunset"], 0,
                     "Aestivation reduces metabolism and water loss when heat or drought makes activity dangerous."),
        QuestionSeed("Which animals belong to the mammalian group Xenarthra?",
                     ["Sloths, anteaters, and armadillos", "Whales, dolphins, and porpoises", "Horses, tapirs, and rhinoceroses", "Rabbits, hares, and pikas"], 0,
                     "Xenarthrans share distinctive extra articulations in the lower spine."),
        QuestionSeed("What is the tapetum lucidum found in many nocturnal animals?",
                     ["A reflective layer behind the retina", "A membrane over the ear", "A specialized skin gland that releases chemicals used in marking", "A facial organ that detects infrared radiation from warm prey"], 0,
                     "It reflects light back through the retina, improving dim-light vision and causing eyeshine."),
    ]
}
