import Foundation

enum ArtQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("Which Renaissance artist painted the Mona Lisa?",
                     ["Leonardo da Vinci", "Michelangelo", "Raphael", "Sandro Botticelli"], 0,
                     "Leonardo da Vinci painted the Mona Lisa during the Italian Renaissance."),
        QuestionSeed("Who painted The Starry Night?",
                     ["Claude Monet", "Vincent van Gogh", "Paul Cézanne", "Edgar Degas"], 1,
                     "Vincent van Gogh painted The Starry Night in 1889 while staying at Saint-Rémy."),
        QuestionSeed("Which artist painted melting clocks in The Persistence of Memory?",
                     ["René Magritte", "Salvador Dalí", "Joan Miró", "Max Ernst"], 1,
                     "Salvador Dalí's small Surrealist painting places soft watches in an uncanny landscape."),
        QuestionSeed("Who painted Guernica?",
                     ["Pablo Picasso", "Diego Rivera", "Henri Matisse", "Georges Braque"], 0,
                     "Pablo Picasso painted Guernica in response to the 1937 bombing of the Basque town."),
        QuestionSeed("Who sculpted the Renaissance marble David in Florence?",
                     ["Donatello", "Michelangelo", "Bernini", "Ghiberti"], 1,
                     "Michelangelo carved David from a single block of marble in the early sixteenth century."),
        QuestionSeed("Who created the sculpture The Thinker?",
                     ["Auguste Rodin", "Henry Moore", "Alberto Giacometti", "Constantin Brâncuși"], 0,
                     "Auguste Rodin first conceived The Thinker as part of his larger Gates of Hell project."),
        QuestionSeed("Who painted Girl with a Pearl Earring?",
                     ["Pieter de Hooch", "Johannes Vermeer", "Gabriël Metsu", "Gerard ter Borch"], 1,
                     "Johannes Vermeer's painting is a tronie, a study of a character rather than a commissioned portrait."),
        QuestionSeed("Who painted American Gothic?",
                     ["Edward Hopper", "Grant Wood", "Thomas Hart Benton", "Andrew Wyeth"], 1,
                     "Grant Wood modeled the two figures on his sister and his dentist."),
        QuestionSeed("Who created The Scream?",
                     ["Edvard Munch", "Gustav Klimt", "Egon Schiele", "Paul Klee"], 0,
                     "Edvard Munch made several painted and printed versions of The Scream."),
        QuestionSeed("Which artist is famous for a series of water-lily paintings?",
                     ["Claude Monet", "Pierre-Auguste Renoir", "Camille Pissarro", "Alfred Sisley"], 0,
                     "Claude Monet painted water lilies in the garden he developed at Giverny."),
        QuestionSeed("Who made the Campbell's Soup Cans artwork?",
                     ["Andy Warhol", "Roy Lichtenstein", "Jasper Johns", "Robert Rauschenberg"], 0,
                     "Andy Warhol exhibited thirty-two canvases of Campbell's soup varieties in 1962."),
        QuestionSeed("Which Japanese artist created The Great Wave off Kanagawa?",
                     ["Hokusai", "Hiroshige", "Utamaro", "Kuniyoshi"], 0,
                     "Hokusai designed The Great Wave as a woodblock print in his Thirty-six Views of Mount Fuji series."),
        QuestionSeed("Who painted the ceiling of the Sistine Chapel?",
                     ["Raphael", "Michelangelo", "Titian", "Caravaggio"], 1,
                     "Michelangelo painted the Sistine Chapel ceiling between 1508 and 1512."),
        QuestionSeed("Who painted The Last Supper in Milan's Santa Maria delle Grazie?",
                     ["Leonardo da Vinci", "Jacopo Tintoretto", "Paolo Veronese", "Domenico Ghirlandaio"], 0,
                     "Leonardo painted The Last Supper on a wall of Santa Maria delle Grazie."),
        QuestionSeed("What type of artwork is the Venus de Milo?",
                     ["A marble sculpture", "An oil painting", "A bronze relief", "A floor mosaic"], 0,
                     "The Venus de Milo is an ancient Greek marble statue, probably representing Aphrodite."),
        QuestionSeed("In which country is the Taj Mahal?",
                     ["India", "Pakistan", "Turkey", "Iran"], 0,
                     "The Taj Mahal is a seventeenth-century marble mausoleum in Agra, India."),
        QuestionSeed("Which city is home to the Eiffel Tower?",
                     ["Paris", "Brussels", "Vienna", "Madrid"], 0,
                     "The Eiffel Tower was built in Paris for the 1889 Exposition Universelle."),
        QuestionSeed("In which city is the Colosseum?",
                     ["Athens", "Rome", "Naples", "Milan"], 1,
                     "The Colosseum is a Roman amphitheater begun under Emperor Vespasian."),
        QuestionSeed("Which ancient city is home to the Parthenon?",
                     ["Athens", "Sparta", "Corinth", "Delphi"], 0,
                     "The Parthenon crowns the Acropolis of Athens and was dedicated to Athena."),
        QuestionSeed("For which pharaoh was the Great Pyramid of Giza built?",
                     ["Khufu", "Tutankhamun", "Ramesses II", "Akhenaten"], 0,
                     "The largest pyramid at Giza was built as the tomb of Pharaoh Khufu."),
        QuestionSeed("In which country is the Sydney Opera House?",
                     ["Australia", "New Zealand", "Canada", "South Africa"], 0,
                     "The Sydney Opera House stands on Bennelong Point in Sydney Harbour, Australia."),
        QuestionSeed("Which Italian city has a famous Leaning Tower?",
                     ["Pisa", "Florence", "Verona", "Turin"], 0,
                     "The Leaning Tower of Pisa is the freestanding bell tower of the city's cathedral."),
        QuestionSeed("In which city is the Burj Khalifa?",
                     ["Dubai", "Doha", "Riyadh", "Abu Dhabi"], 0,
                     "The Burj Khalifa rises above Dubai in the United Arab Emirates."),
        QuestionSeed("Which architect is most associated with Barcelona's Sagrada Família?",
                     ["Antoni Gaudí", "Santiago Calatrava", "Ludwig Mies van der Rohe", "Rafael Moneo"], 0,
                     "Antoni Gaudí transformed the Sagrada Família project with his organic geometric designs."),
        QuestionSeed("Which metal forms the outer surface of the Statue of Liberty?",
                     ["Copper", "Bronze", "Iron", "Aluminum"], 0,
                     "Thin copper sheets form the statue's exterior and have weathered to a green patina."),
        QuestionSeed("Which type of arch is strongly associated with Gothic architecture?",
                     ["A pointed arch", "A horseshoe arch", "A flat arch", "A round Roman arch"], 0,
                     "Pointed arches help direct loads downward and are a defining feature of Gothic churches."),
        QuestionSeed("What is a rounded roof structure called?",
                     ["A dome", "A spire", "A lintel", "A buttress"], 0,
                     "A dome covers a space with a rounded vault, often over a circular or polygonal plan."),
        QuestionSeed("What is a fresco painted onto?",
                     ["Wet plaster", "Dry canvas", "Polished metal", "Carved wood"], 0,
                     "In true fresco, water-based pigment bonds with a fresh layer of wet plaster as it dries."),
        QuestionSeed("What is a mosaic made from?",
                     ["Small pieces joined into an image", "One continuous sheet of metal", "Layers of transparent fabric", "Lines scratched into wet clay"], 0,
                     "Mosaics arrange small pieces of stone, glass, ceramic, or other material into a design."),
        QuestionSeed("What is a portrait?",
                     ["An image of a person", "A picture of scenery", "A study of objects", "A building plan"], 0,
                     "A portrait represents a particular person or group and often emphasizes identity or character."),
        QuestionSeed("What does a landscape artwork primarily depict?",
                     ["Natural scenery", "A seated person", "Household objects", "Letterforms"], 0,
                     "Landscape art focuses on scenery such as land, water, sky, and vegetation."),
        QuestionSeed("What does a still life usually depict?",
                     ["Arranged objects", "A moving crowd", "A historical battle", "An imaginary city"], 0,
                     "A still life studies arranged objects such as fruit, flowers, vessels, or books."),
        QuestionSeed("What is a self-portrait?",
                     ["An artist's image of themself", "A portrait without a sitter", "A copy made by a student", "A painting owned by its subject"], 0,
                     "A self-portrait is an artist's representation of their own appearance or identity."),
        QuestionSeed("Which kind of artwork has three physical dimensions?",
                     ["A sculpture", "A drawing", "A photograph", "A print"], 0,
                     "Sculpture occupies three-dimensional space and may be carved, modeled, cast, or assembled."),
        QuestionSeed("What does an architect design?",
                     ["Buildings and spaces", "Musical scores", "Costumes only", "Printed novels"], 0,
                     "Architects plan buildings and spaces while balancing structure, use, materials, and appearance."),
        QuestionSeed("What is watercolor paint thinned primarily with?",
                     ["Water", "Linseed oil", "Wax", "Egg yolk"], 0,
                     "Watercolor suspends pigment in a water-soluble binder and is diluted with water."),
        QuestionSeed("In traditional painting, which set contains the three primary colors?",
                     ["Red, yellow, and blue", "Orange, green, and violet", "Red, green, and blue", "Black, white, and gray"], 0,
                     "The traditional RYB model treats red, yellow, and blue as primary mixing colors."),
        QuestionSeed("What does linear perspective help an artist create?",
                     ["The illusion of depth", "A rough stone texture", "A brighter pigment", "A perfectly circular canvas"], 0,
                     "Linear perspective makes parallel lines appear to converge, creating spatial depth on a flat surface."),
        QuestionSeed("Which surface is commonly stretched over a wooden frame for painting?",
                     ["Canvas", "Marble", "Copper wire", "Wet plaster"], 0,
                     "Painters commonly stretch woven canvas over a wooden support called a stretcher."),
        QuestionSeed("What does an art conservator primarily do?",
                     ["Document and preserve artworks", "Set prices for auction houses", "Plan exhibitions for museums", "Create replicas for gift shops"], 0,
                     "Conservators examine, document, stabilize, and treat artworks to preserve them."),
        QuestionSeed("In traditional paint mixing, which two primary colors make green?",
                     ["Blue and yellow", "Red and blue", "Red and yellow", "Black and white"], 0,
                     "In the traditional red-yellow-blue model used for paint, blue and yellow pigments combine to make green."),
        QuestionSeed("Who painted the Dutch group portrait known as The Night Watch?",
                     ["Rembrandt", "Johannes Vermeer", "Peter Paul Rubens", "Frans Hals"], 0,
                     "Rembrandt completed the huge militia portrait in 1642, and it now anchors the Rijksmuseum in Amsterdam."),
        QuestionSeed("What color do artists get by mixing red and white paint?",
                     ["Pink", "Purple", "Orange", "Brown"], 0,
                     "Adding white lightens red into pink, and the more white you add the paler the tint."),
        QuestionSeed("Which tool do painters use to hold and mix their colors?",
                     ["Palette", "Drawing board", "Sketchbook", "Easel"], 0,
                     "A palette gives the painter a flat surface for blending pigments before they reach the canvas."),
        QuestionSeed("In which museum is the Mona Lisa displayed?",
                     ["The Louvre", "The Uffizi Gallery", "The British Museum", "The Prado"], 0,
                     "The Louvre in Paris has held the painting since the French Revolution, and shows it behind protective glass."),
        QuestionSeed("Which material is traditionally used to make stained glass windows?",
                     ["Colored glass", "Painted wood", "Polished marble", "Woven fabric"], 0,
                     "Stained glass windows are built from pieces of colored glass held together by strips of lead."),
        QuestionSeed("What is the art of beautiful handwriting called?",
                     ["Calligraphy", "Typography", "Illustration", "Printmaking"], 0,
                     "Calligraphy treats letterforms as art, using controlled brush or pen strokes to shape each character."),
        QuestionSeed("What is a museum curator's main job?",
                     ["Organizes exhibitions", "Repairs damaged paintings", "Designs museum buildings", "Sets ticket prices"], 0,
                     "A curator organizes exhibitions, choosing which works appear together and writing the labels that explain them."),
        QuestionSeed("Which shape forms the base of a traditional Egyptian pyramid?",
                     ["A square", "A circle", "A triangle", "A hexagon"], 0,
                     "Each Egyptian pyramid rises from a square base, with four triangular faces meeting at a single point."),
        QuestionSeed("Which city is home to the Statue of Liberty?",
                     ["New York", "Boston", "Philadelphia", "Chicago"], 0,
                     "The statue stands on Liberty Island in New York Harbor, greeting ships entering the city."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("Which movement emphasized fleeting light and visible brushwork?",
                     ["Impressionism", "Neoclassicism", "Futurism", "Minimalism"], 0,
                     "Impressionists often painted modern life and changing outdoor light with broken, visible strokes."),
        QuestionSeed("Which movement fragmented subjects into geometric forms and multiple viewpoints?",
                     ["Cubism", "Romanticism", "Realism", "Symbolism"], 0,
                     "Pablo Picasso and Georges Braque developed Cubism in the early twentieth century."),
        QuestionSeed("Which movement explored dreams, chance, and the unconscious?",
                     ["Surrealism", "Constructivism", "Pointillism", "Regionalism"], 0,
                     "Surrealists drew on dreams and unexpected combinations to challenge ordinary perception."),
        QuestionSeed("In which country did the Renaissance first take shape?",
                     ["Italy", "France", "England", "Germany"], 0,
                     "Italian cities such as Florence fostered the artistic changes now called the Renaissance."),
        QuestionSeed("Which style is known for theatrical movement, strong contrasts, and elaborate decoration?",
                     ["Baroque", "Romanesque", "De Stijl", "Minimalism"], 0,
                     "Baroque art and architecture often use drama, movement, and rich surfaces to engage viewers."),
        QuestionSeed("Which eighteenth-century style favored playful ornament and pastel elegance?",
                     ["Rococo", "Brutalism", "Gothic Revival", "Fauvism"], 0,
                     "Rococo developed from the Baroque with lighter colors, asymmetry, and intimate decorative themes."),
        QuestionSeed("Which style is recognized by flowing lines and plant-like ornament?",
                     ["Art Nouveau", "Art Deco", "Bauhaus", "Suprematism"], 0,
                     "Art Nouveau joined architecture, graphics, furniture, and decorative arts through organic lines."),
        QuestionSeed("In which country was the Bauhaus founded?",
                     ["Germany", "Austria", "The Netherlands", "Switzerland"], 0,
                     "Walter Gropius founded the Bauhaus school in Weimar, Germany, in 1919."),
        QuestionSeed("Which city became the center of Abstract Expressionism?",
                     ["New York", "Paris", "Berlin", "Mexico City"], 0,
                     "Abstract Expressionism shifted the international art world's focus toward postwar New York."),
        QuestionSeed("What subject matter did Pop artists often borrow?",
                     ["Mass media and consumer goods", "Medieval devotional scenes", "Ancient funerary rituals", "Untouched wilderness only"], 0,
                     "Pop art repurposed advertising, comics, celebrities, packaging, and other mass-culture imagery."),
        QuestionSeed("Who painted The Two Fridas?",
                     ["Frida Kahlo", "Remedios Varo", "Leonora Carrington", "María Izquierdo"], 0,
                     "Frida Kahlo's double self-portrait presents two joined figures with exposed hearts."),
        QuestionSeed("Which American artist is known for enlarged paintings of flowers and the Southwest?",
                     ["Georgia O'Keeffe", "Helen Frankenthaler", "Lee Krasner", "Elaine de Kooning"], 0,
                     "Georgia O'Keeffe painted magnified flowers, bones, and New Mexico landscapes."),
        QuestionSeed("Which artist combined text, crowns, and expressive figures in 1980s New York?",
                     ["Jean-Michel Basquiat", "Keith Haring", "Julian Schnabel", "David Salle"], 0,
                     "Jean-Michel Basquiat layered words, diagrams, anatomy, and crown motifs in his paintings."),
        QuestionSeed("Which contemporary artist is known for immersive rooms covered in polka dots?",
                     ["Yayoi Kusama", "Yoko Ono", "Mariko Mori", "Chiharu Shiota"], 0,
                     "Yayoi Kusama uses repeated dots, mirrors, and lights to create immersive environments."),
        QuestionSeed("Which artist is especially known for narrative story quilts?",
                     ["Faith Ringgold", "Betye Saar", "Alma Thomas", "Lorna Simpson"], 0,
                     "Faith Ringgold combined painted images, fabric, and text in story quilts about history and identity."),
        QuestionSeed("The Thinker originated as part of which larger Rodin project?",
                     ["The Gates of Hell", "The Burghers of Calais", "The Age of Bronze", "Monument to Balzac"], 0,
                     "Rodin designed The Thinker to sit above the doorway of The Gates of Hell."),
        QuestionSeed("Who created the streamlined sculpture Bird in Space?",
                     ["Constantin Brâncuși", "Umberto Boccioni", "Alexander Calder", "Jean Arp"], 0,
                     "Brâncuși reduced the bird to an elongated polished form suggesting upward movement."),
        QuestionSeed("Who sculpted The Ecstasy of Saint Teresa?",
                     ["Gian Lorenzo Bernini", "Antonio Canova", "Benvenuto Cellini", "Lorenzo Ghiberti"], 0,
                     "Bernini integrated sculpture, architecture, and hidden light in the Cornaro Chapel."),
        QuestionSeed("Who painted The Kiss with a gold-patterned surface?",
                     ["Gustav Klimt", "Egon Schiele", "Oskar Kokoschka", "Franz Marc"], 0,
                     "Gustav Klimt's The Kiss belongs to the artist's celebrated Golden Phase."),
        QuestionSeed("Which British painter is known for atmospheric light in works such as Rain, Steam and Speed?",
                     ["J. M. W. Turner", "John Constable", "William Blake", "Thomas Gainsborough"], 0,
                     "Turner dissolved forms into light, weather, smoke, and motion in his later landscapes."),
        QuestionSeed("Which Mexican artist painted large public murals about history and labor?",
                     ["Diego Rivera", "Rufino Tamayo", "José Guadalupe Posada", "Manuel Álvarez Bravo"], 0,
                     "Diego Rivera helped establish Mexican muralism through monumental public narratives."),
        QuestionSeed("Who designed the Vietnam Veterans Memorial in Washington, D.C.?",
                     ["Maya Lin", "Beverly Pepper", "Louise Nevelson", "Anne Truitt"], 0,
                     "Maya Lin's design uses two polished black-granite walls inscribed with the names of the dead."),
        QuestionSeed("Who designed the glass pyramid at the Louvre?",
                     ["I. M. Pei", "Philip Johnson", "Renzo Piano", "Norman Foster"], 0,
                     "I. M. Pei's glass-and-metal pyramid opened as the Louvre's main entrance in 1989."),
        QuestionSeed("Which architect designed Fallingwater?",
                     ["Frank Lloyd Wright", "Louis Kahn", "Eero Saarinen", "Richard Neutra"], 0,
                     "Frank Lloyd Wright cantilevered Fallingwater above a Pennsylvania waterfall."),
        QuestionSeed("Which architect designed Villa Savoye near Paris?",
                     ["Le Corbusier", "Alvar Aalto", "Walter Gropius", "Marcel Breuer"], 0,
                     "Villa Savoye demonstrates Le Corbusier's five points of modern architecture."),
        QuestionSeed("Which architect designed the Heydar Aliyev Center in Baku?",
                     ["Zaha Hadid", "Jeanne Gang", "Kazuyo Sejima", "Lina Bo Bardi"], 0,
                     "Zaha Hadid Architects designed the center's sweeping, continuous exterior and interior surfaces."),
        QuestionSeed("In which present-day city is Hagia Sophia?",
                     ["Istanbul", "Athens", "Jerusalem", "Alexandria"], 0,
                     "Hagia Sophia was built in Constantinople, now Istanbul, under Emperor Justinian I."),
        QuestionSeed("In which country is the temple complex Angkor Wat?",
                     ["Cambodia", "Thailand", "Laos", "Myanmar"], 0,
                     "Angkor Wat was built in the Khmer Empire and appears on Cambodia's national flag."),
        QuestionSeed("Petra is famous for buildings carved into rock in which country?",
                     ["Jordan", "Lebanon", "Egypt", "Oman"], 0,
                     "The Nabataeans carved monumental façades into sandstone cliffs at Petra in Jordan."),
        QuestionSeed("The stone architecture of Machu Picchu was created by which civilization?",
                     ["The Inca", "The Maya", "The Moche", "The Tiwanaku"], 0,
                     "The Inca constructed Machu Picchu high in the Andes during the fifteenth century."),
        QuestionSeed("Which city contains the Forbidden City palace complex?",
                     ["Beijing", "Nanjing", "Xi'an", "Hangzhou"], 0,
                     "The Forbidden City served as the imperial palace in Beijing from the Ming through Qing dynasties."),
        QuestionSeed("In which Spanish city is the Alhambra?",
                     ["Granada", "Seville", "Córdoba", "Toledo"], 0,
                     "The Alhambra is a palace and fortress complex overlooking Granada."),
        QuestionSeed("Which architectural style best describes Chartres Cathedral?",
                     ["Gothic", "Baroque", "Neoclassical", "Byzantine"], 0,
                     "Chartres Cathedral is renowned for Gothic structure, sculpture, and stained glass."),
        QuestionSeed("What is the purpose of a flying buttress?",
                     ["Carry outward wall thrust", "Collect rainwater", "Support a spiral staircase", "Frame the main doorway"], 0,
                     "A flying buttress transfers roof and vault forces to an exterior pier."),
        QuestionSeed("What does contrapposto describe in a standing figure?",
                     ["Weight shifted onto one leg", "Arms raised above the head", "A perfectly frontal pose", "Knees bent at equal angles"], 0,
                     "Contrapposto shifts weight to one leg, creating an asymmetrical but balanced posture."),
        QuestionSeed("What is chiaroscuro?",
                     ["Modeling with light and shadow", "Painting with unmixed dots", "Carving into colored stone", "Joining metal without heat"], 0,
                     "Chiaroscuro uses transitions between light and dark to model volume and create drama."),
        QuestionSeed("What is impasto?",
                     ["Thickly applied paint", "A print made from limestone", "Pigment mixed with wet plaster", "A drawing made with silver wire"], 0,
                     "Impasto leaves paint thick enough for brush or palette-knife marks to remain visible."),
        QuestionSeed("How many panels does a triptych have?",
                     ["Two", "Three", "Four", "Five"], 1,
                     "A triptych is composed of three connected panels, often with hinged outer wings."),
        QuestionSeed("Which surface is traditionally used for lithography?",
                     ["A flat stone", "A carved wood block", "A silk screen", "An engraved copper plate"], 0,
                     "Traditional lithography uses the repulsion of grease and water on a flat limestone surface."),
        QuestionSeed("What does a kiln provide for ceramics?",
                     ["Controlled high heat", "Continuous flowing water", "Pressurized cold air", "Ultraviolet light"], 0,
                     "A kiln fires clay and glazes at controlled temperatures to create durable ceramic material."),
        QuestionSeed("Which artist duo wrapped the Reichstag and the Pont Neuf in fabric?",
                     ["Christo and Jeanne-Claude", "Gilbert and George", "Bernd and Hilla Becher", "Claes Oldenburg and Coosje van Bruggen"], 0,
                     "Christo and Jeanne-Claude wrapped the Reichstag and Pont Neuf in fabric as monumental temporary public artworks."),
        QuestionSeed("Which movement answered World War I with deliberately absurd, anti-art works?",
                     ["Dada", "Futurism", "Symbolism", "Neoclassicism"], 0,
                     "Dada answered the war's senselessness with nonsense, chance, and readymades that mocked the idea of masterpieces."),
        QuestionSeed("Who created the readymade sculpture Fountain?",
                     ["Marcel Duchamp", "Constantin Brancusi", "Man Ray", "Alberto Giacometti"], 0,
                     "Marcel Duchamp submitted a signed porcelain urinal in 1917, forcing a debate about what counts as art."),
        QuestionSeed("Which pigment gave Renaissance painters their costliest deep blue?",
                     ["Ultramarine", "Vermilion", "Yellow ochre", "Lead white"], 0,
                     "Ultramarine was ground from lapis lazuli shipped across the sea, costing more than gold by weight."),
        QuestionSeed("Which artist is known for drip paintings made on canvas laid flat?",
                     ["Jackson Pollock", "Willem de Kooning", "Mark Rothko", "Robert Rauschenberg"], 0,
                     "Jackson Pollock poured and flung household paint, letting the whole body's motion record itself on canvas."),
        QuestionSeed("What does the lost-wax process produce?",
                     ["A bronze cast", "A marble carving", "A fired clay pot", "A woodcut print"], 0,
                     "Molten bronze replaces a melted wax model, so the cast copies every detail the sculptor shaped."),
        QuestionSeed("Which 1960s movement reduced artworks to simple repeated geometric units?",
                     ["Minimalism", "Expressionism", "Romanticism", "Photorealism"], 0,
                     "Minimalism stripped away gesture and symbolism, leaving plain industrial forms arranged in clear repeating order."),
        QuestionSeed("In which country did the woodblock print style ukiyo-e develop?",
                     ["Japan", "China", "Korea", "Vietnam"], 0,
                     "Ukiyo-e prints of actors, courtesans, and landscapes flourished in Japan during the Edo period."),
        QuestionSeed("What is a supporting column carved as a draped female figure called?",
                     ["A caryatid", "A pilaster", "An obelisk", "A pediment"], 0,
                     "A caryatid carries the entablature on her head, most famously on the Erechtheion in Athens."),
        QuestionSeed("Which painting technique builds tone from tiny dots of pure color?",
                     ["Pointillism", "Sfumato", "Grisaille", "Trompe l'oeil"], 0,
                     "Pointillism relies on the eye to blend adjacent dots, a method Georges Seurat developed systematically."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("Who painted Las Meninas?",
                     ["Diego Velázquez", "Francisco de Zurbarán", "Bartolomé Murillo", "Jusepe de Ribera"], 0,
                     "Diego Velázquez placed himself, the royal family, and the viewer in a complex play of sightlines."),
        QuestionSeed("Who painted Olympia, first exhibited at the 1865 Paris Salon?",
                     ["Édouard Manet", "Gustave Courbet", "Edgar Degas", "Henri Fantin-Latour"], 0,
                     "Édouard Manet's confrontational modern nude provoked controversy at the 1865 Salon."),
        QuestionSeed("Who painted The Raft of the Medusa?",
                     ["Théodore Géricault", "Eugène Delacroix", "Jean-Auguste-Dominique Ingres", "Jacques-Louis David"], 0,
                     "Géricault based the monumental painting on survivors of a notorious 1816 shipwreck."),
        QuestionSeed("Who painted the Arnolfini Portrait?",
                     ["Jan van Eyck", "Rogier van der Weyden", "Hans Memling", "Robert Campin"], 0,
                     "Jan van Eyck signed the richly detailed double portrait dated 1434."),
        QuestionSeed("Who painted the Isenheim Altarpiece?",
                     ["Matthias Grünewald", "Albrecht Dürer", "Lucas Cranach the Elder", "Hans Holbein the Younger"], 0,
                     "Matthias Grünewald painted the altarpiece's intense scenes for a hospital monastery at Isenheim."),
        QuestionSeed("Which artist created Black Square?",
                     ["Kazimir Malevich", "Wassily Kandinsky", "El Lissitzky", "Alexander Rodchenko"], 0,
                     "Kazimir Malevich made Black Square an emblem of his Suprematist movement."),
        QuestionSeed("Which artist exhibited a urinal titled Fountain in 1917?",
                     ["Marcel Duchamp", "Man Ray", "Francis Picabia", "Jean Arp"], 0,
                     "Marcel Duchamp submitted the readymade Fountain under the name R. Mutt."),
        QuestionSeed("Who painted Broadway Boogie Woogie?",
                     ["Piet Mondrian", "Theo van Doesburg", "Paul Klee", "Sonia Delaunay"], 0,
                     "Piet Mondrian translated Manhattan's street grid and musical rhythm into colored blocks."),
        QuestionSeed("Which artist painted Number 5, 1948?",
                     ["Jackson Pollock", "Willem de Kooning", "Franz Kline", "Clyfford Still"], 0,
                     "Jackson Pollock layered poured and dripped paint across the large fiberboard surface."),
        QuestionSeed("Who created the earthwork Spiral Jetty?",
                     ["Robert Smithson", "Michael Heizer", "Walter De Maria", "Richard Long"], 0,
                     "Robert Smithson built Spiral Jetty from basalt and earth in Utah's Great Salt Lake."),
        QuestionSeed("Who created the installation Sunflower Seeds from millions of porcelain pieces?",
                     ["Ai Weiwei", "Cai Guo-Qiang", "Xu Bing", "Huang Yong Ping"], 0,
                     "Ai Weiwei commissioned individually crafted porcelain sunflower seeds for Tate Modern's Turbine Hall."),
        QuestionSeed("Who created the installation The Dinner Party?",
                     ["Judy Chicago", "Miriam Schapiro", "Barbara Kruger", "Jenny Holzer"], 0,
                     "Judy Chicago's triangular ceremonial table commemorates women from history and mythology."),
        QuestionSeed("Which artist is known for hanging sculptures made from bottle caps and copper wire?",
                     ["El Anatsui", "Yinka Shonibare", "Ibrahim Mahama", "William Kentridge"], 0,
                     "El Anatsui assembles discarded metal closures into vast, flexible works resembling textiles."),
        QuestionSeed("Which artist is known for large black-paper silhouettes examining race and history?",
                     ["Kara Walker", "Lorna Simpson", "Carrie Mae Weems", "Kerry James Marshall"], 0,
                     "Kara Walker uses the silhouette tradition to stage unsettling scenes about slavery and power."),
        QuestionSeed("Which Swedish artist made early abstract series intended for a future temple?",
                     ["Hilma af Klint", "Sigrid Hjertén", "Hanna Pauli", "Agnes Cleve"], 0,
                     "Hilma af Klint created large abstract cycles years before abstraction became internationally prominent."),
        QuestionSeed("The objects called the Benin Bronzes were primarily made for which kingdom?",
                     ["The Kingdom of Benin", "The Mali Empire", "The Kingdom of Kongo", "The Ashanti Empire"], 0,
                     "Royal guilds made brass plaques and sculptures for the palace in Benin City."),
        QuestionSeed("The naturalistic brass and terracotta heads from Ifẹ are associated with which people?",
                     ["Yoruba", "Akan", "Edo", "Dogon"], 0,
                     "Artists of the Yoruba city of Ifẹ produced highly naturalistic royal heads from about the twelfth century."),
        QuestionSeed("Which ruler's tomb was guarded by the Terracotta Army?",
                     ["Qin Shi Huang", "Emperor Wu of Han", "Kublai Khan", "Emperor Taizong"], 0,
                     "Thousands of terracotta figures were buried near the mausoleum of China's first emperor, Qin Shi Huang."),
        QuestionSeed("What does the Japanese term ukiyo-e mean?",
                     ["Pictures of the floating world", "Paintings of the imperial court", "Records of ancient battles", "Images made without outlines"], 0,
                     "Ukiyo-e prints depicted the 'floating world' of entertainment, beauty, travel, and urban life."),
        QuestionSeed("Which technique creates soft, smoky transitions without hard outlines?",
                     ["Sfumato", "Impasto", "Hatching", "Frottage"], 0,
                     "Sfumato layers subtle tones to blur edges, a technique strongly associated with Leonardo."),
        QuestionSeed("What distinguishes tenebrism?",
                     ["Extreme light-dark contrast", "Tiny dots of pure color", "Raised bands of gold leaf", "Shallow carved outlines"], 0,
                     "Tenebrism places brightly lit forms against dominant darkness for heightened drama."),
        QuestionSeed("What does foreshortening do?",
                     ["Compresses forms projecting into depth", "Makes distant colors more saturated", "Repeats a motif at equal intervals", "Joins two views at a central seam"], 0,
                     "Foreshortening alters proportions so a form extending toward or away from the viewer appears convincing."),
        QuestionSeed("Which binder is used in encaustic painting?",
                     ["Heated wax", "Egg yolk", "Linseed oil", "Wet lime plaster"], 0,
                     "Encaustic painting suspends pigment in heated wax that hardens as it cools."),
        QuestionSeed("What is lost-wax casting used to make?",
                     ["A hollow or solid metal form", "A woven textile pattern", "A limestone print", "A stained-glass panel"], 0,
                     "The process replaces a modeled wax form with molten metal inside a heat-resistant mold."),
        QuestionSeed("What is grisaille?",
                     ["Painting mainly in shades of gray", "Glazing pottery with metallic salts", "Carving figures in very low relief", "Drawing with red chalk alone"], 0,
                     "Grisaille uses a monochrome gray palette, sometimes to imitate sculpture."),
        QuestionSeed("What is evidence of an artist's earlier alteration beneath a painting called?",
                     ["A pentimento", "A craquelure", "A cartouche", "A watermark"], 0,
                     "A pentimento appears when an underlying change in the composition becomes visible."),
        QuestionSeed("What does an artwork's provenance document?",
                     ["Its history of ownership", "Its chemical pigment recipe", "Its original lighting design", "Its frame's decorative pattern"], 0,
                     "Provenance traces ownership and custody and can help establish authenticity and legal title."),
        QuestionSeed("What is iconoclasm?",
                     ["The destruction or rejection of sacred images", "The study of signatures on paintings", "The copying of ancient architectural orders", "The use of icons in computer interfaces"], 0,
                     "Religious or political iconoclasm attacks images considered improper, dangerous, or idolatrous."),
        QuestionSeed("What is the projecting semicircular or polygonal end of a church called?",
                     ["An apse", "A narthex", "A transept", "A cloister"], 0,
                     "An apse commonly terminates the sanctuary end of a church and may contain the altar."),
        QuestionSeed("What architectural device supports a dome over a square room?",
                     ["A pendentive", "An archivolt", "A pilaster", "A clerestory"], 0,
                     "Curved triangular pendentives transition from a square bay to the circular base of a dome."),
        QuestionSeed("What is entasis in classical architecture?",
                     ["A slight swelling in a column shaft", "A triangular temple pediment", "A carved band above a doorway", "A recessed panel in a ceiling"], 0,
                     "Entasis subtly curves a column's profile and counters the illusion of inward concavity."),
        QuestionSeed("What is a voussoir?",
                     ["A wedge-shaped block in an arch", "A horizontal beam over columns", "A carved capital with scrolls", "A stone gutter at a roof edge"], 0,
                     "Voussoirs are wedge-shaped units whose compression forms a masonry arch."),
        QuestionSeed("What is an oculus?",
                     ["A circular opening", "A spiral stair", "A ribbed vault", "A hidden chamber"], 0,
                     "An oculus is a round opening in a wall or dome, such as the one in the Pantheon."),
        QuestionSeed("What are muqarnas?",
                     ["Tiered ornamental niches", "Freestanding prayer towers", "Painted ceramic floor tiles", "Walled palace gardens"], 0,
                     "Muqarnas form intricate, tiered transitions in domes, vaults, portals, and cornices in Islamic architecture."),
        QuestionSeed("What defines a hypostyle hall?",
                     ["A roof supported by many columns", "A dome resting on four arches", "An open court surrounded by houses", "A single nave without supports"], 0,
                     "A hypostyle hall uses numerous closely spaced columns to carry its roof."),
        QuestionSeed("Which material is especially associated with Brutalist architecture?",
                     ["Exposed concrete", "Polished marble", "Painted timber", "Glazed terracotta"], 0,
                     "Brutalism often emphasizes massive forms, structural legibility, and exposed raw concrete."),
        QuestionSeed("Which movement favors fragmented, non-rectilinear architectural forms?",
                     ["Deconstructivism", "Palladianism", "Beaux-Arts", "Arts and Crafts"], 0,
                     "Deconstructivist architecture uses apparent instability, collision, distortion, and fragmented geometry."),
        QuestionSeed("Which feature is characteristic of Frank Lloyd Wright's Prairie style?",
                     ["Strong horizontal lines", "Pointed Gothic spires", "Classical temple fronts", "Mirrored curtain walls"], 0,
                     "Prairie houses use low roofs, broad eaves, open plans, and horizontal emphasis."),
        QuestionSeed("Which combination best describes the International Style?",
                     ["Glass, steel, and little applied ornament", "Brick arches and carved gargoyles", "Adobe walls and timber vigas", "Domes, mosaics, and gold backgrounds"], 0,
                     "International Style buildings favor simple volumes, modern materials, and minimal applied decoration."),
        QuestionSeed("What is post-and-lintel construction?",
                     ["A horizontal beam carried by vertical supports", "A vault formed from wedge-shaped stones", "A shell cast as one continuous curve", "A wall reinforced by diagonal cables"], 0,
                     "Post-and-lintel construction spans two upright supports with a horizontal member.")
    ]
}
