import Foundation

enum BasketballQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("How many points is a free throw worth?",
                     ["1", "2", "3", "4"], 0,
                     "Free throws are worth a single point each and are taken from the foul line."),
        QuestionSeed("How many players from one team are on the court at once?",
                     ["4", "5", "6", "7"], 1,
                     "Five per side, which is why the sport is sometimes called five-on-five."),
        QuestionSeed("How high is a regulation basketball rim?",
                     ["8 feet", "9 feet", "10 feet", "12 feet"], 2,
                     "Ten feet has been the standard height since the game was invented in 1891."),
        QuestionSeed("How many points is a shot from beyond the arc worth?",
                     ["1", "2", "3", "4"], 2,
                     "The three-point line rewards longer attempts and has reshaped modern offenses."),
        QuestionSeed("What violation is called for moving with the ball without dribbling?",
                     ["Traveling", "Charging", "Goaltending", "Screening"], 0,
                     "Taking too many steps without a dribble is a traveling violation and turns the ball over."),
        QuestionSeed("Which player typically directs the offense?",
                     ["Center", "Point guard", "Power forward", "Small forward"], 1,
                     "The point guard brings the ball up the floor and organizes the set."),
        QuestionSeed("How many quarters are in an NBA game?",
                     ["2", "3", "4", "5"], 2,
                     "Four twelve-minute quarters, for forty-eight minutes of regulation."),
        QuestionSeed("What is it called when a player grabs the ball after a missed shot?",
                     ["Assist", "Rebound", "Steal", "Block"], 1,
                     "Rebounds are tracked as offensive or defensive depending on which team grabs them."),
        QuestionSeed("What is a pass that leads directly to a basket called?",
                     ["Assist", "Carry", "Turnover", "Screen"], 0,
                     "The passer is credited with an assist when the teammate scores without creating the shot alone."),
        QuestionSeed("Which league awards the Larry O'Brien Trophy?",
                     ["WNBA", "NCAA", "NBA", "FIBA"], 2,
                     "The Larry O'Brien Championship Trophy goes to the NBA champion each June."),
        QuestionSeed("How long is the NBA shot clock?",
                     ["20 seconds", "24 seconds", "30 seconds", "35 seconds"], 1,
                     "Twenty-four seconds; the clock was introduced in 1954 to speed the game up."),
        QuestionSeed("What is bouncing the ball while moving called?",
                     ["Dribbling", "Posting", "Boxing out", "Cutting"], 0,
                     "A player must dribble to move with the ball rather than carry it."),
        QuestionSeed("What is it called when a player scores by putting the ball straight down through the hoop?",
                     ["A layup", "A dunk", "A tip-in", "A floater"], 1,
                     "A dunk is still worth two points, the same as any other shot inside the arc."),
        QuestionSeed("What is a personal foul?",
                     ["Illegal contact with an opponent", "Stepping out of bounds", "Holding the ball too long", "A missed free throw"], 0,
                     "Accumulating too many personal fouls forces a player out of the game."),
        QuestionSeed("Which body governs international basketball?",
                     ["FIFA", "FIBA", "IOC", "UEFA"], 1,
                     "FIBA organizes the Basketball World Cup and the sport's Olympic competition."),
        QuestionSeed("What is the name for taking the ball away from an opponent?",
                     ["A block", "A steal", "A rebound", "A screen"], 1,
                     "Steals are counted as turnovers for the team that loses possession."),
        QuestionSeed("How many points is a shot from inside the arc worth?",
                     ["1", "2", "3", "4"], 1,
                     "Any field goal inside the three-point line counts for two."),
        QuestionSeed("What is the tallest position usually called?",
                     ["Center", "Point guard", "Shooting guard", "Small forward"], 0,
                     "The center generally plays nearest the basket at both ends."),
        QuestionSeed("What is it called when a defender legally stops a shot in mid-air?",
                     ["A block", "A charge", "A steal", "A foul"], 0,
                     "Blocking the ball on its way up is legal; touching it on the way down is goaltending."),
        QuestionSeed("What ends a quarter in basketball?",
                     ["The buzzer", "A whistle from the coach", "A made basket", "The shot clock"], 0,
                     "The horn sounds when the game clock reaches zero."),
        QuestionSeed("What is the painted area near the basket commonly called?",
                     ["The key", "The arc", "The wing", "The corner"], 0,
                     "It is also called the lane or the paint, and offensive players cannot linger there."),
        QuestionSeed("Which country invented basketball?",
                     ["Canada", "United States", "United Kingdom", "France"], 1,
                     "James Naismith, a Canadian, invented the game in Springfield, Massachusetts in 1891."),
        QuestionSeed("How many referees officiate a typical NBA game?",
                     ["One", "Two", "Three", "Five"], 2,
                     "Three officials share responsibility for different areas of the floor."),
        QuestionSeed("What is a 'double-double'?",
                     ["Two players scoring twenty", "Reaching double figures in two statistical categories", "Two overtimes", "Two technical fouls"], 1,
                     "Ten or more in two categories, most often points and rebounds."),
        QuestionSeed("What happens when the ball goes out of bounds?",
                     ["A jump ball", "The other team throws it in", "A free throw", "A held ball"], 1,
                     "Possession goes to the team that did not touch it last before it left the floor."),
        QuestionSeed("What is the term for a shot taken close to the rim off the backboard?",
                     ["A layup", "A hook", "A fadeaway", "A jumper"], 0,
                     "Layups are the highest-percentage shot in the game."),
        QuestionSeed("How wide is a regulation NBA court?",
                     ["40 feet", "50 feet", "60 feet", "70 feet"], 1,
                     "An NBA court measures 94 feet by 50 feet."),
        QuestionSeed("What is a 'turnover'?",
                     ["A scored basket", "Losing possession to the other team", "A substitution", "A timeout"], 1,
                     "Turnovers come from steals, bad passes, and violations."),
        QuestionSeed("What is the women's professional league in the United States called?",
                     ["WNBA", "NWSL", "LPGA", "NPB"], 0,
                     "The WNBA began play in 1997."),
        QuestionSeed("What does a player do when they 'box out'?",
                     ["Position themselves to secure a rebound", "Guard the inbounds pass", "Set an illegal screen", "Call a timeout"], 0,
                     "Boxing out uses body position to keep an opponent away from the ball."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("How long is a quarter in an NBA game?",
                     ["8 minutes", "10 minutes", "12 minutes", "15 minutes"], 2,
                     "Twelve minutes per quarter; international FIBA games use ten."),
        QuestionSeed("How far is the NBA three-point line at the top of the arc?",
                     ["21 feet", "22 feet", "23 feet 9 inches", "25 feet"], 2,
                     "It shortens to 22 feet in the corners, which is why corner threes are prized."),
        QuestionSeed("What is a 'triple-double'?",
                     ["Three overtimes", "Double figures in three statistical categories", "Three straight three-pointers", "Three team fouls"], 1,
                     "Points, rebounds, and assists is the most common combination."),
        QuestionSeed("How many fouls before an NBA player is disqualified?",
                     ["Four", "Five", "Six", "Seven"], 2,
                     "Six personal fouls sends an NBA player to the bench; college basketball uses five."),
        QuestionSeed("What is the three-second violation?",
                     ["Holding the ball too long", "An offensive player standing in the lane too long", "Taking too long to inbound", "Delaying a free throw"], 1,
                     "The rule keeps big men from camping directly under the basket."),
        QuestionSeed("Which position is traditionally the team's best outside shooter?",
                     ["Center", "Shooting guard", "Power forward", "Point guard"], 1,
                     "The shooting guard, sometimes called the two guard, works off screens for jump shots."),
        QuestionSeed("What is 'goaltending'?",
                     ["Blocking a shot on its downward flight", "Guarding the inbounder", "Fouling a shooter", "Defending the paint"], 0,
                     "The basket counts automatically when goaltending is called."),
        QuestionSeed("How many timeouts does an NBA team get per game?",
                     ["Four", "Five", "Seven", "Nine"], 2,
                     "Seven, with limits on how many can be carried into the final minutes."),
        QuestionSeed("What is a 'pick and roll'?",
                     ["A screen followed by the screener cutting to the basket", "A defensive switch", "A type of rebound", "An inbounds play only"], 0,
                     "It remains the most common action in professional basketball."),
        QuestionSeed("Which league does the March Madness tournament belong to?",
                     ["NBA", "NCAA", "FIBA", "EuroLeague"], 1,
                     "The NCAA Division I tournament is played each March in the United States."),
        QuestionSeed("How long is overtime in the NBA?",
                     ["3 minutes", "5 minutes", "8 minutes", "10 minutes"], 1,
                     "Five-minute periods repeat until one team leads at the buzzer."),
        QuestionSeed("What is the 'bonus' or 'penalty' situation?",
                     ["Extra points for long shots", "Free throws awarded once a team commits enough fouls", "A double-scoring period", "An extra timeout"], 1,
                     "Once the team foul limit is reached, every subsequent foul sends the opponent to the line."),
        QuestionSeed("What is a 'charge'?",
                     ["An offensive foul for running into a set defender", "A fast break", "A defensive three seconds", "An illegal screen"], 0,
                     "The defender must have established legal position before contact."),
        QuestionSeed("How many players may a team have on its active NBA roster for a game?",
                     ["Ten", "Thirteen", "Sixteen", "Twenty"], 1,
                     "Teams dress up to thirteen players from a larger full roster."),
        QuestionSeed("What is a 'fast break'?",
                     ["A quick timeout", "Pushing the ball upcourt before the defense sets", "A halftime interval", "A shot clock reset"], 1,
                     "Fast breaks convert defensive rebounds and steals into easy baskets."),
        QuestionSeed("Which trophy is awarded to the NBA Finals Most Valuable Player?",
                     ["The Bill Russell Trophy", "The Larry O'Brien Trophy", "The Naismith Trophy", "The Maurice Podoloff Trophy"], 0,
                     "The Finals MVP award was renamed for Bill Russell in 2009."),
        QuestionSeed("What does a 'technical foul' penalize?",
                     ["Unsportsmanlike conduct or procedural violations", "Contact while shooting", "Traveling", "A shot clock violation"], 0,
                     "Technicals award a free throw to the other team without a change of possession."),
        QuestionSeed("What is 'zone defense'?",
                     ["Guarding an area rather than a specific player", "Double-teaming the ball", "Full-court man coverage", "A defensive timeout"], 0,
                     "Zone was illegal in the NBA for decades before defensive rules changed in 2001."),
        QuestionSeed("What is the width of the NBA lane, or key?",
                     ["12 feet", "16 feet", "19 feet", "24 feet"], 1,
                     "The NBA lane is sixteen feet wide; college uses twelve."),
        QuestionSeed("What is an 'and-one'?",
                     ["A basket plus a foul, earning one free throw", "A one-point lead", "The first overtime", "A single technical"], 0,
                     "The shot counts and the shooter gets one attempt to complete a three-point play."),
        QuestionSeed("What is 'the paint' named after?",
                     ["The painted rectangle of the free-throw lane", "The team colors", "A sponsor", "The court finish"], 0,
                     "The lane is painted a contrasting color on most courts."),
        QuestionSeed("How many seconds does a team have to advance the ball past midcourt?",
                     ["Five", "Six", "Eight", "Ten"], 2,
                     "Eight seconds in the NBA; the college and FIBA rules differ slightly."),
        QuestionSeed("What is a 'backcourt violation'?",
                     ["Returning the ball behind midcourt after crossing it", "Fouling in the backcourt", "An illegal inbound", "Guarding too closely"], 0,
                     "Also called over-and-back, it hands possession to the other team."),
        QuestionSeed("Which basketball competition is held every four years alongside the Olympics cycle?",
                     ["The FIBA Basketball World Cup", "The EuroLeague Final Four", "The NBA Cup", "The Commonwealth Games"], 0,
                     "The World Cup is FIBA's flagship national-team tournament."),
        QuestionSeed("What is 'the post'?",
                     ["The area near the basket where big men operate", "The scorer's table", "The backboard support", "The bench area"], 0,
                     "Low post is near the basket; high post is closer to the free-throw line."),
        QuestionSeed("What is an 'alley-oop'?",
                     ["A lob pass finished at the rim before landing", "A behind-the-back dribble", "A defensive rotation", "A long three"], 0,
                     "The passer throws to a spot rather than to a player's hands."),
        QuestionSeed("How many points did the NBA's single-game scoring record set in 1962 total?",
                     ["73", "81", "100", "112"], 2,
                     "Wilt Chamberlain scored 100 points against the New York Knicks in Hershey, Pennsylvania."),
        QuestionSeed("What is a 'screen'?",
                     ["A legal block to free a teammate", "A blocked shot", "A defensive scheme", "A shot clock device"], 0,
                     "The screener must be stationary or the referee will call an illegal screen."),
        QuestionSeed("What does 'DNP' mean on a box score?",
                     ["Did Not Play", "Defensive Non-Participant", "Defensive Net Points", "Drive Not Permitted"], 0,
                     "It usually appears alongside a reason, such as coach's decision or injury."),
        QuestionSeed("What is the diameter of a regulation basketball hoop?",
                     ["16 inches", "18 inches", "20 inches", "24 inches"], 1,
                     "Eighteen inches, which is a little under twice the diameter of the ball."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("What was basketball originally played with instead of a hoop?",
                     ["A wooden crate", "A peach basket", "A metal ring", "A barrel"], 1,
                     "Naismith nailed peach baskets to the gymnasium balcony; someone had to retrieve the ball each time."),
        QuestionSeed("How many original rules did James Naismith write for the game?",
                     ["Nine", "Thirteen", "Eighteen", "Twenty-four"], 1,
                     "Naismith's thirteen rules were posted in the gymnasium in December 1891."),
        QuestionSeed("What is the 'defensive three seconds' rule?",
                     ["A defender cannot stay in the lane without guarding someone", "A defender must switch every three seconds", "A shot clock rule", "A rule about closing out"], 0,
                     "Introduced in 2001, it discourages parking a shot blocker under the rim."),
        QuestionSeed("What is a 'Euro step'?",
                     ["Two lateral steps to avoid a defender after picking up the dribble", "A screen from the side", "A type of zone", "A three-point shot from the corner"], 0,
                     "It is legal because the steps come after the dribble ends, within the allowed gather."),
        QuestionSeed("Which statistic measures points produced per 100 possessions?",
                     ["Offensive rating", "Player efficiency rating", "True shooting percentage", "Usage rate"], 0,
                     "Pace-adjusted ratings let teams from different eras be compared fairly."),
        QuestionSeed("What does 'true shooting percentage' account for that field goal percentage does not?",
                     ["Free throws and three-pointers", "Rebounds", "Assists", "Turnovers"], 0,
                     "It weights the different point values so a three-heavy shooter is not undervalued."),
        QuestionSeed("What was the NBA's predecessor league called before the 1949 merger?",
                     ["The Basketball Association of America", "The American Basketball Association", "The National Basketball League only", "The Continental League"], 0,
                     "The BAA merged with the National Basketball League to form the NBA."),
        QuestionSeed("Which league introduced the three-point line to American professional basketball first?",
                     ["The NBA", "The ABA", "The NCAA", "The NBL"], 1,
                     "The American Basketball Association used it from 1967; the NBA adopted it in 1979."),
        QuestionSeed("What is a 'hedge' in pick-and-roll defense?",
                     ["The screener's defender stepping out to slow the ball handler", "Switching every screen", "Trapping the corner", "Dropping to the rim"], 0,
                     "Hedging buys time for the on-ball defender to recover over the screen."),
        QuestionSeed("How many seconds does a player have to inbound the ball?",
                     ["Three", "Five", "Eight", "Ten"], 1,
                     "Five seconds, and defensive pressure on the inbounder is a common late-game tactic."),
        QuestionSeed("What does the term 'usage rate' estimate?",
                     ["The share of team possessions a player finishes", "Minutes played", "Shooting accuracy", "Defensive impact"], 0,
                     "High-usage players end a large share of possessions with a shot, free throws, or a turnover."),
        QuestionSeed("What is 'the restricted area' under the basket?",
                     ["An arc where a defender cannot draw a charge", "The team bench zone", "The area behind the backboard", "The coach's box"], 0,
                     "Inside the four-foot arc, contact is a blocking foul rather than a charge."),
        QuestionSeed("Which team won the first NBA championship in 1947?",
                     ["Philadelphia Warriors", "Boston Celtics", "Minneapolis Lakers", "New York Knicks"], 0,
                     "The Philadelphia Warriors won the inaugural BAA title, recognized today as an NBA championship."),
        QuestionSeed("What is 'the mid-level exception' in NBA contracts?",
                     ["A salary cap tool for signing a free agent above the minimum", "A trade rule", "A draft position", "A luxury tax bracket"], 0,
                     "It lets teams over the cap add a player at roughly the league average salary."),
        QuestionSeed("What is a 'flagrant foul'?",
                     ["Unnecessary or excessive contact", "A foul away from the ball", "A sixth personal foul", "A foul on the inbound"], 0,
                     "Flagrant fouls are graded one or two, and a flagrant two brings immediate ejection."),
        QuestionSeed("What is 'the triangle offense' built around?",
                     ["Spacing formed by three players on one side of the floor", "Three-point shooting only", "A three-guard lineup", "Three defensive zones"], 0,
                     "The system emphasizes reading the defense rather than running set plays."),
        QuestionSeed("What is the FIBA shot clock length?",
                     ["20 seconds", "24 seconds", "30 seconds", "35 seconds"], 1,
                     "FIBA matches the NBA at twenty-four seconds, with a fourteen-second reset on offensive rebounds."),
        QuestionSeed("What is an 'illegal defense' violation historically associated with?",
                     ["Zone defense in the pre-2001 NBA", "Fouling out", "Late substitutions", "Improper uniforms"], 0,
                     "Before 2001 the NBA required man-to-man principles and penalized zone alignments."),
        QuestionSeed("What is 'the gather step'?",
                     ["The step taken as a player collects the ball to end the dribble", "The first step of a fast break", "A defensive slide", "The step onto the free-throw line"], 0,
                     "The gather is not counted as one of the two steps a player may take."),
        QuestionSeed("Which award is given to the top NCAA men's player each year?",
                     ["The Naismith Trophy", "The Larry O'Brien Trophy", "The Heisman Trophy", "The Podoloff Cup"], 0,
                     "It is named after the game's inventor, James Naismith."),
        QuestionSeed("How wide is a FIBA court compared with an NBA court?",
                     ["Wider", "Narrower", "Identical", "Variable by venue"], 1,
                     "FIBA courts are 28 by 15 metres, slightly shorter and narrower than the NBA's 94 by 50 feet."),
        QuestionSeed("What is 'the corner three' valued for?",
                     ["It is the shortest three-point shot", "It is worth four points", "It cannot be blocked", "It stops the clock"], 0,
                     "The line is 22 feet in the corners rather than 23 feet 9 inches at the top."),
        QuestionSeed("What does 'switching' mean defensively?",
                     ["Two defenders trading assignments on a screen", "Changing from zone to man", "Substituting players", "Rotating the ball"], 0,
                     "Switch-heavy defenses need players who can guard several positions."),
        QuestionSeed("What is a 'heat check'?",
                     ["A difficult shot taken after several makes in a row", "A timeout for cooling down", "A temperature rule", "A referee's review"], 0,
                     "The term describes a player testing whether a hot streak is still running."),
        QuestionSeed("What is the NBA's 'luxury tax'?",
                     ["A penalty paid by teams whose payroll exceeds a threshold", "A ticket surcharge", "A fine for technical fouls", "An arena levy"], 0,
                     "The tax is designed to discourage the wealthiest teams from outspending the rest of the league."),
        QuestionSeed("What does 'PER' stand for?",
                     ["Player Efficiency Rating", "Points Earned Ratio", "Possession Efficiency Ranking", "Personal Effort Rating"], 0,
                     "PER condenses a player's box-score production into a single pace-adjusted number."),
        QuestionSeed("What is 'the two-for-one' strategy?",
                     ["Shooting early enough to get one more possession before a period ends", "Trading two players for one", "A double technical", "Two free throws for one foul"], 0,
                     "Teams shoot with roughly thirty seconds left so they get the last shot as well."),
        QuestionSeed("What is 'small ball'?",
                     ["Playing without a traditional center for speed and spacing", "A youth format", "A smaller regulation ball", "A half-court game"], 0,
                     "It trades rim protection and rebounding for shooting and quickness."),
        QuestionSeed("Which country won the first Olympic basketball gold medal in 1936?",
                     ["United States", "Canada", "Germany", "Mexico"], 0,
                     "The final was played outdoors on a dirt court in heavy rain in Berlin."),
        QuestionSeed("What is 'the Hack-a-Shaq' tactic?",
                     ["Deliberately fouling a poor free-throw shooter", "A defensive press", "A shot-blocking scheme", "An inbounds play"], 0,
                     "The strategy is named for Shaquille O'Neal, whose free-throw struggles invited it."),
    ]
}
