import Foundation

enum BasketballQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("How many points is a free throw worth?",
                     ["1", "2", "3", "4"], 0,
                     "Free throws are worth a single point each and are taken from the foul line."),
        QuestionSeed("How many players from one team are on the court at once?",
                     ["4", "5", "6", "7"], 1,
                     "Five per side, which is why the sport is sometimes called five-on-five."),
        QuestionSeed("How high is a regulation basketball rim?",
                     ["8 feet", "9 feet", "10 feet", "12 feet"], 2,
                     "Ten feet has been the standard height since the game was invented in 1891."),
        QuestionSeed("How many points is a shot from beyond the arc worth?",
                     ["1", "2", "3", "4"], 2,
                     "The three-point line rewards longer attempts and has reshaped modern offenses."),
        QuestionSeed("What violation is called for moving with the ball without dribbling?",
                     ["Traveling", "Charging", "Goaltending", "Screening"], 0,
                     "Taking too many steps without a dribble is a traveling violation and turns the ball over."),
        QuestionSeed("Which player typically directs the offense?",
                     ["Center", "Point guard", "Power forward", "Small forward"], 1,
                     "The point guard brings the ball up the floor and organizes the set."),
        QuestionSeed("How many quarters are in an NBA game?",
                     ["2", "3", "4", "5"], 2,
                     "Four twelve-minute quarters, for forty-eight minutes of regulation."),
        QuestionSeed("What is it called when a player grabs the ball after a missed shot?",
                     ["Assist", "Rebound", "Steal", "Block"], 1,
                     "Rebounds are tracked as offensive or defensive depending on which team grabs them."),
        QuestionSeed("What is a pass that leads directly to a basket called?",
                     ["Assist", "Carry", "Turnover", "Screen"], 0,
                     "The passer is credited with an assist when the teammate scores without creating the shot alone."),
        QuestionSeed("Which league awards the Larry O'Brien Trophy?",
                     ["WNBA", "NCAA", "NBA", "FIBA"], 2,
                     "The Larry O'Brien Championship Trophy goes to the NBA champion each June."),
        QuestionSeed("How long is the NBA shot clock?",
                     ["20 seconds", "24 seconds", "30 seconds", "35 seconds"], 1,
                     "Twenty-four seconds; the clock was introduced in 1954 to speed the game up."),
        QuestionSeed("What is bouncing the ball while moving called?",
                     ["Dribbling", "Posting", "Boxing out", "Cutting"], 0,
                     "A player must dribble to move with the ball rather than carry it."),
        QuestionSeed("What is it called when a player scores by putting the ball straight down through the hoop?",
                     ["A layup", "A dunk", "A tip-in", "A floater"], 1,
                     "A dunk is still worth two points, the same as any other shot inside the arc."),
        QuestionSeed("What is a personal foul?",
                     ["Illegal contact with an opponent", "Stepping out of bounds", "Holding the ball too long", "A missed free throw"], 0,
                     "Accumulating too many personal fouls forces a player out of the game."),
        QuestionSeed("Which body governs international basketball?",
                     ["FIFA", "FIBA", "IOC", "UEFA"], 1,
                     "FIBA organizes the Basketball World Cup and the sport's Olympic competition."),
        QuestionSeed("What is the name for taking the ball away from an opponent?",
                     ["A block", "A steal", "A rebound", "A screen"], 1,
                     "Steals are counted as turnovers for the team that loses possession."),
        QuestionSeed("How many points is a shot from inside the arc worth?",
                     ["1", "2", "3", "4"], 1,
                     "Any field goal inside the three-point line counts for two."),
        QuestionSeed("What is the tallest position usually called?",
                     ["Center", "Point guard", "Shooting guard", "Small forward"], 0,
                     "The center generally plays nearest the basket at both ends."),
        QuestionSeed("What is it called when a defender legally stops a shot in mid-air?",
                     ["A block", "A charge", "A steal", "A foul"], 0,
                     "Blocking the ball on its way up is legal; touching it on the way down is goaltending."),
        QuestionSeed("What ends a quarter in basketball?",
                     ["The buzzer", "A whistle from the coach", "A made basket", "The shot clock"], 0,
                     "The horn sounds when the game clock reaches zero."),
        QuestionSeed("What is the painted area near the basket commonly called?",
                     ["The key", "The arc", "The wing", "The corner"], 0,
                     "It is also called the lane or the paint, and offensive players cannot linger there."),
        QuestionSeed("Which country invented basketball?",
                     ["Canada", "United States", "United Kingdom", "France"], 1,
                     "James Naismith, a Canadian, invented the game in Springfield, Massachusetts in 1891."),
        QuestionSeed("How many referees officiate a typical NBA game?",
                     ["One", "Two", "Three", "Five"], 2,
                     "Three officials share responsibility for different areas of the floor."),
        QuestionSeed("What is a 'double-double'?",
                     ["Two players scoring twenty", "Reaching double figures in two statistical categories", "Two overtimes", "Two technical fouls"], 1,
                     "Ten or more in two categories, most often points and rebounds."),
        QuestionSeed("What happens when the ball goes out of bounds?",
                     ["A jump ball", "The other team throws it in", "A free throw", "A held ball"], 1,
                     "Possession goes to the team that did not touch it last before it left the floor."),
        QuestionSeed("What is the term for a shot taken close to the rim off the backboard?",
                     ["A layup", "A hook", "A fadeaway", "A jumper"], 0,
                     "Layups are the highest-percentage shot in the game."),
        QuestionSeed("How wide is a regulation NBA court?",
                     ["40 feet", "50 feet", "60 feet", "70 feet"], 1,
                     "An NBA court measures 94 feet by 50 feet."),
        QuestionSeed("What is a 'turnover'?",
                     ["A scored basket", "Losing possession to the other team", "A substitution", "A timeout"], 1,
                     "Turnovers come from steals, bad passes, and violations."),
        QuestionSeed("What is the women's professional league in the United States called?",
                     ["WNBA", "NWSL", "LPGA", "NPB"], 0,
                     "The WNBA began play in 1997."),
        QuestionSeed("What does a player do when they 'box out'?",
                     ["Position themselves to secure a rebound", "Guard the inbounds pass", "Set an illegal screen", "Call a timeout"], 0,
                     "Boxing out uses body position to keep an opponent away from the ball."),
        QuestionSeed("What is an 'air ball'?",
                     ["A shot that misses the rim and backboard", "A pass thrown above the defence", "A ball knocked out of bounds", "A shot taken while jumping"], 0,
                     "Crowds often chant 'air ball' after a shot reaches neither the rim nor the backboard."),
        QuestionSeed("What makes a shot a 'bank shot'?",
                     ["It is taken before the buzzer", "It uses the backboard", "It is shot with one hand", "It follows a timeout"], 1,
                     "A bank shot rebounds from the backboard into the basket."),
        QuestionSeed("What violation occurs when a player dribbles, stops, and then dribbles again?",
                     ["A palming or carrying violation", "Double dribble", "Goaltending", "Charging"], 1,
                     "Once a player ends a dribble and controls the ball, starting another dribble is illegal."),
        QuestionSeed("What is a shot made just before the game clock expires commonly called?",
                     ["A buzzer-beater", "A bank shot", "A putback", "A hook shot"], 0,
                     "A buzzer-beater leaves the shooter's hand before time expires and may score after the horn sounds."),
        QuestionSeed("What may a player do while keeping one pivot foot planted?",
                     ["Turn to pass or shoot", "Begin a second dribble", "Take unlimited steps", "Stand outside the court"], 0,
                     "The player may rotate around the pivot foot without committing a traveling violation."),
        QuestionSeed("How does an NBA game begin?",
                     ["With a jump ball", "With a free throw", "With a coin toss", "With an inbound from the baseline"], 0,
                     "An official tosses the ball between two opponents in the centre circle for the opening tip."),
        QuestionSeed("What are players waiting off the court to enter the game commonly called?",
                     ["Substitutes", "Captains", "Officials", "Screeners"], 0,
                     "Substitutes sit on the bench until they legally check into the game."),
        QuestionSeed("What is the rectangular board behind the basketball hoop called?",
                     ["The backboard", "The baseline", "The scorer's table", "The shot clock"], 0,
                     "The rim is attached to the backboard, which players can use to bank in shots."),
        QuestionSeed("Which line divides a basketball court into frontcourt and backcourt?",
                     ["The free-throw line", "The baseline", "The midcourt line", "The three-point line"], 2,
                     "The midcourt line runs through the centre circle and separates the two halves of the floor."),
        QuestionSeed("What is the pass used to resume play from outside the boundary called?",
                     ["A full-court outlet pass", "An inbound pass", "A bounce pass", "A skip pass"], 1,
                     "The inbounder must release the ball onto the court within the allowed count."),
        QuestionSeed("Which NBA team plays its home games at Madison Square Garden?",
                     ["The New York Knicks", "The Brooklyn Nets", "The Boston Celtics", "The Philadelphia 76ers"], 0,
                     "The New York Knicks have played at Madison Square Garden since the arena opened."),
        QuestionSeed("How far is the free-throw line from the backboard in the NBA?",
                     ["Twelve feet", "Fifteen feet", "Eighteen feet", "Twenty-two feet"], 1,
                     "The free-throw line sits fifteen feet from the backboard on every regulation court."),
        QuestionSeed("What is the NBA championship series called?",
                     ["The NBA Finals", "The Title Series", "The Champions Cup", "The Basketball Classic"], 0,
                     "The NBA Finals decide the league champion each season in a best-of-seven series."),
        QuestionSeed("What color is a standard basketball?",
                     ["Orange", "Brown", "Yellow", "Burgundy"], 0,
                     "A standard basketball is orange with black seams, chosen for visibility on court."),
        QuestionSeed("How many free throws follow a foul on a three-point shot attempt?",
                     ["One", "Two", "Three", "Four or more"], 2,
                     "A shooter fouled attempting a three-pointer receives three free throws."),
        QuestionSeed("What happens if an NBA game is tied when regulation ends?",
                     ["Overtime is played", "The game is a draw", "A free-throw contest decides", "The higher seed advances"], 0,
                     "Overtime is played, and further periods follow until one team leads at the buzzer."),
        QuestionSeed("What is the arc beyond which shots count for three points called?",
                     ["The three-point line", "The perimeter arc", "The outer boundary", "The scoring semicircle"], 0,
                     "The three-point line marks the distance beyond which a made basket counts three."),
        QuestionSeed("What is the NBA's midseason exhibition of its best players called?",
                     ["The All-Star Game", "The Showcase Game", "The Legends Match", "The Midseason Classic"], 0,
                     "The All-Star Game gathers the league's most popular and productive players midseason."),
        QuestionSeed("What does a coach call to stop play and instruct the team?",
                     ["A timeout", "A stoppage", "An interval", "An adjournment"], 0,
                     "A timeout stops play so a coach can instruct the team and rest players."),
        QuestionSeed("How many points is a basket worth if the shooter is behind the arc?",
                     ["One", "Two", "Three", "Seven"], 2,
                     "A basket from behind the arc counts three points rather than the usual two."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("How long is a quarter in an NBA game?",
                     ["8 minutes", "10 minutes", "12 minutes", "15 minutes"], 2,
                     "Twelve minutes per quarter; international FIBA games use ten."),
        QuestionSeed("How far is the NBA three-point line at the top of the arc?",
                     ["21 feet", "22 feet", "23 feet 9 inches", "25 feet"], 2,
                     "It shortens to 22 feet in the corners, which is why corner threes are prized."),
        QuestionSeed("What is a 'triple-double'?",
                     ["Playing three complete overtime periods in the same contest", "Double figures in three statistical categories", "Making three consecutive three-point field goals without a miss", "Committing three team fouls during a single offensive possession"], 1,
                     "Points, rebounds, and assists is the most common combination."),
        QuestionSeed("How many fouls before an NBA player is disqualified?",
                     ["Four", "Five", "Six", "Seven"], 2,
                     "Six personal fouls sends an NBA player to the bench; college basketball uses five."),
        QuestionSeed("What is the three-second violation?",
                     ["Holding the ball too long", "An offensive player standing in the lane too long", "Taking too long to inbound", "A free-throw shooter delaying too long before attempting the shot"], 1,
                     "The rule keeps big men from camping directly under the basket."),
        QuestionSeed("Which position is traditionally the team's best outside shooter?",
                     ["Center", "Shooting guard", "Power forward", "Point guard"], 1,
                     "The shooting guard, sometimes called the two guard, works off screens for jump shots."),
        QuestionSeed("Touching a shot after it begins descending toward the rim is normally called what?",
                     ["Goaltending", "A held ball", "A reach-in foul", "A backcourt violation"], 0,
                     "This is one form of defensive goaltending; professional rules also prohibit certain touches around the rim and backboard."),
        QuestionSeed("How many timeouts does an NBA team get per game?",
                     ["Four", "Five", "Seven", "Nine"], 2,
                     "Seven, with limits on how many can be carried into the final minutes."),
        QuestionSeed("What is a 'pick and roll'?",
                     ["A screen followed by the screener cutting to the basket", "Two defenders exchanging their assigned players during a screen", "A type of rebound", "An inbounds play only"], 0,
                     "It remains the most common action in professional basketball."),
        QuestionSeed("Which league does the March Madness tournament belong to?",
                     ["NBA", "NCAA", "FIBA", "EuroLeague"], 1,
                     "The NCAA Division I tournament is played each March in the United States."),
        QuestionSeed("How long is overtime in the NBA?",
                     ["3 minutes", "5 minutes", "8 minutes", "10 minutes"], 1,
                     "Five-minute periods repeat until one team leads at the buzzer."),
        QuestionSeed("What is the 'bonus' or 'penalty' situation?",
                     ["Extra points for long shots", "Free throws awarded after enough team fouls", "A period in which every successful basket counts for twice its value", "An additional timeout granted after a team wins a replay challenge"], 1,
                     "After the team-foul limit is reached, most later defensive fouls result in free throws; team-control fouls are an important exception."),
        QuestionSeed("What is a 'charge'?",
                     ["An offensive foul for running into a set defender", "A transition attack launched before the opposing defense can get set", "A defensive three seconds", "An illegal screen set while the screener is still moving into contact"], 0,
                     "The defender must have established legal position before contact."),
        QuestionSeed("What is the regular-season maximum for an NBA team's Active List under current roster rules?",
                     ["Ten players", "Thirteen players", "Fifteen players", "Eighteen players"], 2,
                     "The regular-season Active List generally contains twelve to fifteen players, with separate rules for inactive and two-way players."),
        QuestionSeed("What is a 'fast break'?",
                     ["Calling an immediate timeout before the opponent can inbound the ball", "Pushing the ball upcourt before the defense sets", "A halftime interval", "A shot clock reset"], 1,
                     "Fast breaks convert defensive rebounds and steals into easy baskets."),
        QuestionSeed("Which trophy is awarded to the NBA Finals Most Valuable Player?",
                     ["The Bill Russell Trophy", "The Larry O'Brien Trophy", "The Naismith Trophy", "The Maurice Podoloff Trophy"], 0,
                     "The Finals MVP award was renamed for Bill Russell in 2009."),
        QuestionSeed("What does a 'technical foul' penalize?",
                     ["Unsportsmanlike conduct or procedural violations", "Contact while shooting", "Moving one or both feet illegally while controlling a live basketball", "Failing to release a field-goal attempt before the shot clock expires"], 0,
                     "Technicals award a free throw to the other team without a change of possession."),
        QuestionSeed("What is 'zone defense'?",
                     ["Guarding an area rather than a specific player", "Sending two defenders to pressure the player who currently has the ball", "Assigning each defender one opponent for the entire length of the court", "Stopping play so the coaching staff can change the team's defensive plan"], 0,
                     "Zone was illegal in the NBA for decades before defensive rules changed in 2001."),
        QuestionSeed("What is the width of the NBA lane, or key?",
                     ["12 feet", "16 feet", "19 feet", "24 feet"], 1,
                     "The NBA lane is sixteen feet wide; college uses twelve."),
        QuestionSeed("What is an 'and-one'?",
                     ["A basket plus a foul, earning one free throw", "A basket that gives one team exactly a one-point advantage", "The first additional period played after regulation ends in a tie", "A single technical foul assessed without any accompanying ejection"], 0,
                     "The shot counts and the shooter gets one attempt to complete a three-point play."),
        QuestionSeed("What is 'the paint' named after?",
                     ["The painted rectangle of the free-throw lane", "The two team colours originally used to decorate that part of the floor", "A sponsor's logo that was traditionally placed inside the lane", "The glossy finish applied to protect the hardwood beneath the baskets"], 0,
                     "The lane is painted a contrasting color on most courts."),
        QuestionSeed("How many seconds does a team have to advance the ball past midcourt?",
                     ["Five", "Six", "Eight", "Ten"], 2,
                     "Eight seconds in the NBA; the college and FIBA rules differ slightly."),
        QuestionSeed("What is a 'backcourt violation'?",
                     ["Returning the ball behind midcourt after crossing it", "Fouling in the backcourt", "An illegal inbound", "Defending an opponent too closely without allowing room to turn"], 0,
                     "Also called over-and-back, it hands possession to the other team."),
        QuestionSeed("What is FIBA's flagship global tournament for national basketball teams?",
                     ["The FIBA Basketball World Cup", "The EuroLeague Final Four", "The NBA Cup", "The Commonwealth Games"], 0,
                     "The FIBA Basketball World Cup is held every four years and crowns a national-team world champion."),
        QuestionSeed("What is 'the post'?",
                     ["The area near the basket where big men operate", "The scorer's table", "The backboard support", "The sideline seating area reserved for players and coaching staff"], 0,
                     "Low post is near the basket; high post is closer to the free-throw line."),
        QuestionSeed("What is an 'alley-oop'?",
                     ["A lob pass finished at the rim before landing", "A behind-the-back dribble", "A coordinated defensive movement toward an open offensive player", "A long-distance field-goal attempt taken several feet beyond the arc"], 0,
                     "The passer throws to a spot rather than to a player's hands."),
        QuestionSeed("How many points did the NBA's single-game scoring record set in 1962 total?",
                     ["73", "81", "100", "112"], 2,
                     "Wilt Chamberlain scored 100 points against the New York Knicks in Hershey, Pennsylvania."),
        QuestionSeed("What is a 'screen'?",
                     ["A legal block to free a teammate", "A defender knocking an opponent's shot away before it reaches the rim", "A defensive scheme", "The electronic device that counts down the time allowed for a possession"], 0,
                     "The screener must be stationary or the referee will call an illegal screen."),
        QuestionSeed("What does 'DNP' mean on a box score?",
                     ["Did Not Play", "Defensive Non-Participant", "Defensive Net Points", "Drive Not Permitted"], 0,
                     "It usually appears alongside a reason, such as coach's decision or injury."),
        QuestionSeed("What is the diameter of a regulation basketball hoop?",
                     ["16 inches", "18 inches", "20 inches", "24 inches"], 1,
                     "Eighteen inches, which is a little under twice the diameter of the ball."),
        QuestionSeed("What is an offensive rebound?",
                     ["Recovering a missed shot by one's own team", "Intercepting a pass thrown by an opponent before it reaches its target", "Deflecting an opponent's shot out of bounds before it reaches the rim", "Controlling the ball after the referee tosses the opening jump ball"], 0,
                     "An offensive rebound extends the possession and often creates a close second-chance attempt."),
        QuestionSeed("What does the term 'sixth man' describe?",
                     ["The lead referee", "A key reserve who comes off the bench", "A team's mascot", "An extra defender in practice"], 1,
                     "A sixth man is usually the first or most influential substitute despite not starting."),
        QuestionSeed("What is a full-court press?",
                     ["Pressure defence applied across the whole floor", "An offence using five shooters", "A shot from beyond half court", "A formal media interview conducted with players immediately after a game"], 0,
                     "The defence contests ball movement immediately after the inbound instead of retreating to half court."),
        QuestionSeed("What distinguishes a no-look pass?",
                     ["The passer looks away from the intended receiver", "The pass travels through the air without first bouncing on the court", "The player releases the ball with both hands at the same moment", "The ball crosses behind the baseline before reaching the receiver"], 0,
                     "Looking elsewhere can misdirect defenders while the pass goes to the actual target."),
        QuestionSeed("What is a double-team?",
                     ["Two defenders guarding one opponent", "Two players setting one screen", "Two consecutive substitutions", "A team playing two centres"], 0,
                     "A double-team increases pressure on the ball but leaves another offensive player less closely guarded."),
        QuestionSeed("What does the 'weak side' mean in half-court basketball?",
                     ["The side away from the ball", "The side with the shorter player", "The team's defensive basket", "The area behind the free-throw line"], 0,
                     "Off-ball cuts and rotations often come from the weak side while attention follows the ball."),
        QuestionSeed("Where is the 'elbow' on a basketball court?",
                     ["Where the free-throw line meets the lane", "The centre of the baseline", "The corner of the three-point arc", "The middle of the backboard"], 0,
                     "There is an elbow at each upper corner of the painted lane."),
        QuestionSeed("What is transition offence?",
                     ["Attacking before the defence is fully set", "Changing from man defence to zone", "Running a play after a timeout", "Substituting all five players"], 0,
                     "Transition offence begins when possession changes and rewards quick advancement of the ball."),
        QuestionSeed("How is regulation time divided in NCAA men's basketball?",
                     ["Two twenty-minute halves", "Four ten-minute quarters", "Four twelve-minute quarters", "Three fifteen-minute periods"], 0,
                     "The men's college game uses two twenty-minute halves, unlike the quarter format used by many other leagues."),
        QuestionSeed("What is a 'floater' or 'runner'?",
                     ["A soft one-handed shot over taller defenders", "A pass that rolls along the floor", "A shot taken after landing", "A defensive slide"], 0,
                     "Guards often release a floater in the lane before a rim protector can challenge at full height."),
        QuestionSeed("What does boxing out describe?",
                     ["Sealing off a rebounder", "Setting a screen on ball", "Trapping in the corner", "Switching a defensive assignment"], 0,
                     "Boxing out means sealing off an opponent with your body so you can claim the rebound."),
        QuestionSeed("What is the restricted area under the basket for?",
                     ["Limiting charge calls", "Marking the jump circle", "Setting inbound positions", "Measuring three-point distance"], 0,
                     "The restricted area limits where a defender can legally draw a charge near the rim."),
        QuestionSeed("What is a pump fake?",
                     ["A shot motion without releasing", "A pass behind the back", "A deliberate missed free throw", "A substitution at the scorer's table"], 0,
                     "A pump fake is a shooting motion without releasing, meant to lift the defender."),
        QuestionSeed("What does an isolation play set up?",
                     ["A one-on-one matchup", "A four-man screen", "A full-court trap", "A deliberate shot-clock violation"], 0,
                     "An isolation play clears space so one attacker faces a single defender one-on-one."),
        QuestionSeed("What is a box-and-one defense?",
                     ["Four in zone, one in man", "Five defenders in man coverage", "A press across the whole court", "Two zones stacked at the arc"], 0,
                     "A box-and-one puts four defenders in zone and one in man coverage on a scorer."),
        QuestionSeed("What does the Naismith Trophy honor?",
                     ["The top college player", "The leading NBA scorer", "The best defensive team", "The longest coaching career"], 0,
                     "The Naismith Trophy honors the top college player, named for the game's inventor."),
        QuestionSeed("What is a hook shot?",
                     ["A sweeping one-handed shot", "A two-handed set shot", "A shot off the backboard", "A running bank from the corner"], 0,
                     "A hook shot is a sweeping one-handed release taken with the body turned sideways."),
        QuestionSeed("What defines man-to-man defense?",
                     ["Each defender guards one opponent", "Defenders cover fixed areas", "All five defenders press the ball", "Defenders rotate every possession"], 0,
                     "In man-to-man defense each defender guards one assigned opponent rather than an area."),
        QuestionSeed("What is a putback in basketball?",
                     ["Scoring straight off an offensive rebound", "Returning the ball to the guard", "Resetting the offense after a full timeout", "Passing backward to restart the play"], 0,
                     "A putback scores immediately off an offensive rebound without bringing the ball out."),
        QuestionSeed("What does the term small ball describe?",
                     ["Using quicker, shorter lineups", "Playing with a smaller ball", "Shortening the shot clock", "Reducing the official court dimensions"], 0,
                     "Small ball describes using quicker, shorter lineups to gain speed and spacing over size."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("What was basketball originally played with instead of a hoop?",
                     ["A wooden crate", "A peach basket", "A metal ring", "A barrel"], 1,
                     "Naismith nailed peach baskets to the gymnasium balcony; someone had to retrieve the ball each time."),
        QuestionSeed("How many original rules did James Naismith write for the game?",
                     ["Nine", "Thirteen", "Eighteen", "Twenty-four"], 1,
                     "Naismith's thirteen rules were posted in the gymnasium in December 1891."),
        QuestionSeed("What is the 'defensive three seconds' rule?",
                     ["A defender cannot stay in the lane without guarding someone", "A defender must switch every three seconds", "The offense must attempt a shot within three seconds of crossing midcourt", "A rule about closing out"], 0,
                     "Introduced in 2001, it discourages parking a shot blocker under the rim."),
        QuestionSeed("What is a 'Euro step'?",
                     ["Two lateral steps to avoid a defender after picking up the dribble", "A sideways screen set by a wing to free the ball handler near the sideline", "A zone alignment assigning one defender to each side of the free-throw lane", "A three-point shot from the corner"], 0,
                     "It is legal because the steps come after the dribble ends, within the allowed gather."),
        QuestionSeed("Which statistic measures points produced per 100 possessions?",
                     ["Offensive rating", "Player efficiency rating", "True shooting percentage", "Usage rate"], 0,
                     "Pace-adjusted ratings let teams from different eras be compared fairly."),
        QuestionSeed("What does 'true shooting percentage' account for that field goal percentage does not?",
                     ["Free throws and three-pointers", "The total number of rebounds a player secures during the game", "Passes that directly create a made basket for a teammate", "Turnovers"], 0,
                     "It weights the different point values so a three-heavy shooter is not undervalued."),
        QuestionSeed("Which league merged with the National Basketball League in 1949 to form the NBA?",
                     ["The Basketball Association of America", "The American Basketball Association", "The Continental Basketball League", "The American Basketball League"], 0,
                     "The BAA and NBL combined in 1949, and the merged organization adopted the National Basketball Association name."),
        QuestionSeed("Which league introduced the three-point line to American professional basketball first?",
                     ["The NBA", "The ABA", "The NCAA", "The NBL"], 1,
                     "The American Basketball Association used it from 1967; the NBA adopted it in 1979."),
        QuestionSeed("What is a 'hedge' in pick-and-roll defense?",
                     ["The screener's defender stepping out to slow the ball handler", "Every defender exchanging assignments as soon as the screen arrives", "Two defenders closing on the ball handler near a sideline or corner", "The big defender remaining near the basket while the guard trails"], 0,
                     "Hedging buys time for the on-ball defender to recover over the screen."),
        QuestionSeed("How many seconds does a player have to inbound the ball?",
                     ["Three", "Five", "Eight", "Ten"], 1,
                     "Five seconds, and defensive pressure on the inbounder is a common late-game tactic."),
        QuestionSeed("What does the term 'usage rate' estimate?",
                     ["The share of team possessions a player finishes", "The percentage of scheduled minutes a player remains on the court", "Shooting accuracy", "An estimate of how many points a player prevents while defending"], 0,
                     "High-usage players end a large share of possessions with a shot, free throws, or a turnover."),
        QuestionSeed("What is the main purpose of the NBA's restricted-area arc?",
                     ["Limiting when a secondary defender can draw a charge", "Marking the team bench zone", "Defining a semicircle from which every dunk attempt must begin", "Restricting offensive rebounds"], 0,
                     "A secondary defender generally cannot draw a charge while positioned in the restricted area, although primary-defender and other exceptions apply."),
        QuestionSeed("Which team won the inaugural Basketball Association of America championship in 1947?",
                     ["Philadelphia Warriors", "Boston Celtics", "Minneapolis Lakers", "New York Knicks"], 0,
                     "The Philadelphia Warriors won the first BAA title; the BAA later merged with the NBL to form the NBA."),
        QuestionSeed("What is 'the mid-level exception' in NBA contracts?",
                     ["A salary cap tool for signing a free agent above the minimum", "A restriction requiring teams to match salaries in every player trade", "A draft position awarded to the team in the middle of the standings", "An added tax rate applied to players earning above the league average"], 0,
                     "It lets teams over the cap add a player at roughly the league average salary."),
        QuestionSeed("What is a 'flagrant foul'?",
                     ["Unnecessary or excessive contact", "A foul away from the ball", "A sixth personal foul", "A foul on the inbound"], 0,
                     "Flagrant fouls are graded one or two, and a flagrant two brings immediate ejection."),
        QuestionSeed("What is 'the triangle offense' built around?",
                     ["Spacing formed by three players on one side of the floor", "Generating open shots by keeping three players beyond the three-point arc", "Using three ball-handling guards together on every offensive possession", "Dividing the half court into three fixed zones that players must occupy"], 0,
                     "The system emphasizes reading the defense rather than running set plays."),
        QuestionSeed("What is the FIBA shot clock length?",
                     ["20 seconds", "24 seconds", "30 seconds", "35 seconds"], 1,
                     "FIBA matches the NBA at twenty-four seconds, with a fourteen-second reset on offensive rebounds."),
        QuestionSeed("What is an 'illegal defense' violation historically associated with?",
                     ["Zone defense in the pre-2001 NBA", "A player leaving the game after committing a sixth personal foul", "A substitute entering after the ball has already been put into play", "A player wearing equipment that was not recorded in the scorebook"], 0,
                     "Before 2001 the NBA required man-to-man principles and penalized zone alignments."),
        QuestionSeed("What is 'the gather step'?",
                     ["The step taken as a player collects the ball to end the dribble", "The first stride a player takes after a teammate starts a fast break", "The lateral movement a defender uses to stay in front of a dribbler", "The step that causes a shooter to cross the free-throw line early"], 0,
                     "The gather is not counted as one of the two steps a player may take."),
        QuestionSeed("Which award is given to the top NCAA men's player each year?",
                     ["The Naismith Trophy", "The Larry O'Brien Trophy", "The Heisman Trophy", "The Podoloff Cup"], 0,
                     "It is named after the game's inventor, James Naismith."),
        QuestionSeed("How wide is a FIBA court compared with an NBA court?",
                     ["Wider", "Narrower", "Identical", "Variable by venue"], 1,
                     "FIBA courts are 28 by 15 metres, slightly shorter and narrower than the NBA's 94 by 50 feet."),
        QuestionSeed("What is 'the corner three' valued for?",
                     ["It is the shortest three-point shot", "It is worth four points", "The backboard prevents a defender from blocking it from the side", "The game clock stops automatically whenever the shot is attempted"], 0,
                     "The line is 22 feet in the corners rather than 23 feet 9 inches at the top."),
        QuestionSeed("What does 'switching' mean defensively?",
                     ["Two defenders trading assignments on a screen", "The entire team changing between zone and man-to-man coverage", "A coach replacing one player with another during a dead ball", "The offense moving the ball from the strong side to the opposite wing"], 0,
                     "Switch-heavy defenses need players who can guard several positions."),
        QuestionSeed("What is a 'heat check'?",
                     ["A difficult shot taken after several makes in a row", "A timeout for cooling down", "A temperature rule", "A replay review of whether a shot left the hand before time expired"], 0,
                     "The term describes a player testing whether a hot streak is still running."),
        QuestionSeed("What is the NBA's 'luxury tax'?",
                     ["A penalty paid by teams whose payroll exceeds a threshold", "A ticket surcharge", "A fine for technical fouls", "A municipal tax charged on revenue earned at a professional arena"], 0,
                     "The tax is designed to discourage the wealthiest teams from outspending the rest of the league."),
        QuestionSeed("What does 'PER' stand for?",
                     ["Player Efficiency Rating", "Points Earned Ratio", "Possession Efficiency Ranking", "Personal Effort Rating"], 0,
                     "PER condenses a player's box-score production into a single pace-adjusted number."),
        QuestionSeed("What is 'the two-for-one' strategy?",
                     ["Shooting early enough to get one more possession before a period ends", "Exchanging two rotation players plus draft compensation for one higher-salaried player", "Assessing matching technical fouls against two opponents during the same dead ball", "Awarding two free throws after one non-shooting team foul late in a period"], 0,
                     "Teams shoot with roughly thirty seconds left so they get the last shot as well."),
        QuestionSeed("What is 'small ball'?",
                     ["Playing without a traditional center for speed and spacing", "A youth format", "Using a reduced-size basketball designed for youth competition", "A half-court game"], 0,
                     "It trades rim protection and rebounding for shooting and quickness."),
        QuestionSeed("Which country won the first Olympic basketball gold medal in 1936?",
                     ["United States", "Canada", "Germany", "Mexico"], 0,
                     "The final was played outdoors on a dirt court in heavy rain in Berlin."),
        QuestionSeed("What is 'the Hack-a-Shaq' tactic?",
                     ["Deliberately fouling a poor free-throw shooter", "Trapping the ball handler immediately after every made basket", "A shot-blocking scheme", "Disguising an inbounds play until the official gives the passer the ball"], 0,
                     "The strategy is named for Shaquille O'Neal, whose free-throw struggles invited it."),
        QuestionSeed("What makes a 'Spain pick-and-roll' different from a basic pick-and-roll?",
                     ["A third offensive player back-screens the roll defender", "The screener slips immediately without contacting the on-ball defender", "The action begins from a sideline inbound rather than from a live dribble", "Two guards set consecutive screens for the same low-post player"], 0,
                     "The back screen complicates the defence's coverage of both the rolling big and the perimeter shooter."),
        QuestionSeed("What is 'drop coverage' against a ball screen?",
                     ["The screener's defender retreats toward the basket", "Both defenders trap above the screen", "Every defender switches assignments", "The defence intentionally fouls the screener"], 0,
                     "The retreating big protects the rim while the on-ball defender trails or fights over the screen."),
        QuestionSeed("What does 'ICE' coverage usually try to do against a side pick-and-roll?",
                     ["Force the ball handler toward the baseline", "Force a switch onto the centre", "Trap at half court", "Leave the corner shooter open"], 0,
                     "The on-ball defender denies the middle while the screener's defender contains the baseline drive."),
        QuestionSeed("Where is 'the nail' in basketball terminology?",
                     ["The centre of the free-throw line", "The front of the rim", "The low block", "The sideline at half court"], 0,
                     "The name comes from the small floor marker traditionally placed at the midpoint of the free-throw line."),
        QuestionSeed("What is a 'short roll' after setting a ball screen?",
                     ["Stopping in the lane instead of rolling all the way to the rim", "The ball handler redirects the action toward the sideline instead of the middle", "The screener stops and immediately sets a second screen for a perimeter shooter", "The roller gives the ball back without advancing toward the basket"], 0,
                     "The screener receives the ball in the middle of the floor and can shoot, pass, or continue to the basket."),
        QuestionSeed("What is a 'ghost screen'?",
                     ["A fake screen followed by a quick pop into space", "A screen set behind the backboard", "A screen that moves laterally while the defender tries to pass it", "A screen set after a teammate shoots to free an offensive rebounder"], 0,
                     "The apparent screener slips away before making contact, often creating confusion between defenders."),
        QuestionSeed("Where is the offensive 'dunker spot'?",
                     ["Along the baseline just outside the lane", "At the top of the three-point arc", "At the centre-circle logo", "At the free-throw-line elbow"], 0,
                     "A player stationed there can cut behind the defence for a close finish without crowding the paint."),
        QuestionSeed("What does a 'horns' alignment place near the two elbows?",
                     ["Two offensive players, usually bigs", "Two referees", "Both guards in the corners", "Three defenders in a zone"], 0,
                     "The ball handler starts above the arc with potential screens available on either side."),
        QuestionSeed("What is a staggered screen?",
                     ["Two consecutive off-ball screens for one cutter", "A screen set during a fast break", "Two players screening each other", "A screen followed by an intentional foul"], 0,
                     "The cutter runs past two screeners in sequence, forcing multiple defensive decisions."),
        QuestionSeed("What is an empty-corner pick-and-roll designed to remove?",
                     ["A nearby help defender on the ball side", "The screener from the play", "All weak-side shooters", "The time remaining before the offense is required to attempt a shot"], 0,
                     "Clearing the ball-side corner creates space for the drive and makes rim help travel farther."),
    ]
}
