import Foundation

enum FoodQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("Which vegetable is a key ingredient in tzatziki?",
                     ["Cucumber", "Tomato", "Carrot", "Aubergine"], 0,
                     "Grated cucumber is folded into strained yogurt with garlic, herbs, and olive oil."),
        QuestionSeed("What is the main ingredient in guacamole?",
                     ["Avocado", "Pea", "Courgette", "Broccoli"], 0,
                     "Lime, onion, and coriander are common additions."),
        QuestionSeed("Which country is pizza traditionally from?",
                     ["Greece", "Italy", "Spain", "France"], 1,
                     "Naples is the city most associated with its origins."),
        QuestionSeed("What grain is used to make traditional sushi rice?",
                     ["Long-grain rice", "Short-grain rice", "Wild rice", "Basmati rice"], 1,
                     "Short-grain rice is sticky enough to hold its shape."),
        QuestionSeed("Which spice is the most expensive by weight?",
                     ["Vanilla", "Saffron", "Cardamom", "Cinnamon"], 1,
                     "Each saffron thread is a stigma hand-picked from a crocus flower."),
        QuestionSeed("What is tofu made from?",
                     ["Soybeans", "Chickpeas", "Lentils", "Rice"], 0,
                     "Soy milk is curdled and pressed into blocks, much like cheesemaking."),
        QuestionSeed("Which fruit is known for its strong smell and spiky shell?",
                     ["Durian", "Jackfruit", "Lychee", "Mango"], 0,
                     "Its odour is strong enough that some hotels and transit systems ban it."),
        QuestionSeed("What is the main ingredient in hummus?",
                     ["Chickpeas", "Lentils", "White beans", "Peas"], 0,
                     "Tahini, lemon, and garlic round out the classic recipe."),
        QuestionSeed("Which drink is made from fermented grapes?",
                     ["Beer", "Wine", "Cider", "Sake"], 1,
                     "Beer comes from grain, cider from apples, and sake from rice."),
        QuestionSeed("What is the primary ingredient in bread?",
                     ["Flour", "Sugar", "Butter", "Eggs"], 0,
                     "Flour, water, salt, and a leavening agent make the basic loaf."),
        QuestionSeed("Which nut is used to make marzipan?",
                     ["Almond", "Walnut", "Pecan", "Hazelnut"], 0,
                     "Ground almonds are bound with sugar into a pliable paste."),
        QuestionSeed("What kind of food is cheddar?",
                     ["Cheese", "Bread", "Sausage", "Pastry"], 0,
                     "It is named after a village in Somerset, England."),
        QuestionSeed("Which meal is traditionally eaten in the morning?",
                     ["Breakfast", "Lunch", "Dinner", "Supper"], 0,
                     "The word literally means breaking the overnight fast."),
        QuestionSeed("What is the main ingredient in an omelette?",
                     ["Eggs", "Potatoes", "Cheese", "Flour"], 0,
                     "Beaten eggs are cooked quickly in a pan and folded over a filling."),
        QuestionSeed("Which vegetable is used to make sauerkraut?",
                     ["Cabbage", "Turnip", "Cauliflower", "Kale"], 0,
                     "Shredded cabbage is salted and left to ferment in its own brine."),
        QuestionSeed("What is polenta traditionally made from?",
                     ["Cornmeal", "Rolled oats", "Rye flour", "Pearl barley"], 0,
                     "Polenta is a northern Italian dish made by simmering coarsely ground cornmeal."),
        QuestionSeed("In which country did modern nigiri sushi develop?",
                     ["China", "Japan", "Korea", "Thailand"], 1,
                     "Modern nigiri developed in Edo, now Tokyo, in the nineteenth century; older fermented fish-and-rice traditions existed elsewhere in Asia."),
        QuestionSeed("What is a dried grape called?",
                     ["A raisin", "A prune", "A date", "A fig"], 0,
                     "A raisin is a grape preserved by drying; a prune is a dried plum."),
        QuestionSeed("Which of these is a citrus fruit?",
                     ["Lemon", "Apple", "Pear", "Peach"], 0,
                     "Oranges, limes, and grapefruit are also citrus."),
        QuestionSeed("What is the main ingredient in french fries?",
                     ["Potato", "Sweet potato", "Parsnip", "Yam"], 0,
                     "They are cut, usually soaked, and fried, often twice for crispness."),
        QuestionSeed("Which food is a bagel?",
                     ["A boiled-then-baked bread roll", "A pastry", "A flatbread", "A biscuit"], 0,
                     "Boiling before baking gives the bagel its dense chew and glossy crust."),
        QuestionSeed("What does 'vegan' mean in food terms?",
                     ["Containing no animal products at all", "Containing no meat but allowing dairy", "Low in fat", "Organic"], 0,
                     "Vegetarian diets may still include eggs and dairy."),
        QuestionSeed("Which herb is a defining ingredient in pesto alla genovese?",
                     ["Basil", "Dill", "Tarragon", "Chervil"], 0,
                     "Pesto alla genovese combines basil with pine nuts, garlic, cheese, and olive oil."),
        QuestionSeed("What is the main ingredient in a traditional Greek salad's dressing?",
                     ["Olive oil", "Mayonnaise", "Cream", "Butter"], 0,
                     "Olive oil with a little vinegar or lemon and oregano is typical."),
        QuestionSeed("Which food is made by churning cream?",
                     ["Butter", "Cheese", "Yogurt", "Cream cheese"], 0,
                     "Churning separates butterfat from the buttermilk."),
        QuestionSeed("Which country is the origin of the croissant's modern form?",
                     ["France", "Germany", "Belgium", "Switzerland"], 0,
                     "Its laminated butter dough was developed in France from an Austrian predecessor."),
        QuestionSeed("What is a chilli pepper's heat measured on?",
                     ["The Scoville scale", "The Richter scale", "The Mohs scale", "The Brix scale"], 0,
                     "Brix measures sugar content, not heat."),
        QuestionSeed("Which grain is the main ingredient in traditional pasta?",
                     ["Wheat", "Rice", "Corn", "Barley"], 0,
                     "Durum wheat semolina is used for most dried pasta."),
        QuestionSeed("What is the main flavouring in a classic vanilla ice cream?",
                     ["Vanilla", "Almond", "Coconut", "Caramel"], 0,
                     "Vanilla comes from the cured seed pods of an orchid."),
        QuestionSeed("Which meal course is usually served last?",
                     ["Dessert", "Starter", "Main", "Soup"], 0,
                     "In some traditions cheese is served after dessert or in its place."),
        QuestionSeed("Which fruit is the main ingredient in ketchup?",
                     ["Tomato", "Apple", "Plum", "Cherry"], 0,
                     "Modern tomato ketchup usually also contains vinegar, sugar, salt, and spices."),
        QuestionSeed("What is yogurt made by fermenting?",
                     ["Milk", "Flour", "Fruit juice", "Cooking oil"], 0,
                     "Bacterial cultures convert some of the milk's lactose into lactic acid, thickening it and adding tang."),
        QuestionSeed("Which seaweed is commonly used to wrap sushi rolls?",
                     ["Nori", "Kombu", "Wakame", "Dulse"], 0,
                     "Nori is made from edible red algae that is dried into thin sheets."),
        QuestionSeed("Which grain is the base of risotto?",
                     ["Rice", "Barley", "Oats", "Rye"], 0,
                     "Short- or medium-grain varieties such as Arborio release starch as they cook, creating a creamy texture."),
        QuestionSeed("Maple syrup is made by concentrating the sap of which tree?",
                     ["A maple", "An oak", "A pine", "An olive"], 0,
                     "Sugar maple sap is boiled to remove water and concentrate its sugars."),
        QuestionSeed("Chocolate is produced from the seeds of which plant?",
                     ["Cacao", "Coffee", "Vanilla", "Coconut"], 0,
                     "Cacao beans are fermented, dried, roasted, and processed into cocoa solids and cocoa butter."),
        QuestionSeed("What kind of kernels expand to make popcorn?",
                     ["Corn", "Rice", "Wheat", "Barley"], 0,
                     "Steam builds inside the hard hull until the kernel ruptures and its starch expands."),
        QuestionSeed("What type of food is mozzarella?",
                     ["Cheese", "Bread", "Pasta", "Sausage"], 0,
                     "Traditional mozzarella is a stretched-curd cheese made from buffalo or cow's milk."),
        QuestionSeed("Which fruit gives lemonade its name and main flavour?",
                     ["Lemon", "Lime", "Orange", "Grapefruit"], 0,
                     "Lemon juice is mixed with water and usually sweetened."),
        QuestionSeed("Traditional couscous is made from granules of which wheat product?",
                     ["Semolina", "Bran", "Wheat germ", "Malt"], 0,
                     "Moistened durum-wheat semolina is rolled into tiny granules and steamed."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("What is the process of cooking food slowly in fat called?",
                     ["Confit", "Braising", "Poaching", "Blanching"], 0,
                     "Duck confit is the best-known example."),
        QuestionSeed("Which cheese is traditionally used in a Greek salad?",
                     ["Feta", "Mozzarella", "Halloumi", "Ricotta"], 0,
                     "Genuine feta is made from sheep's milk, sometimes with goat's milk."),
        QuestionSeed("What is 'umami' commonly described as?",
                     ["A savoury taste", "A sour taste", "A bitter taste", "A spicy sensation"], 0,
                     "It was identified in Japan in 1908 and is linked to glutamates."),
        QuestionSeed("Which country does the dish paella come from?",
                     ["Spain", "Portugal", "Italy", "Mexico"], 0,
                     "It originated in the Valencia region."),
        QuestionSeed("What is 'mise en place'?",
                     ["Preparing and arranging ingredients before cooking", "Arranging finished components decoratively on a serving plate", "A French sauce", "A named portion cut from a particular section of a beef carcass"], 0,
                     "The phrase means 'putting in place' and is fundamental to professional kitchens."),
        QuestionSeed("Which fermentation product gives sourdough its tang?",
                     ["Lactic and acetic acids", "Citric acid", "Ascorbic acid", "Malic acid"], 0,
                     "Wild bacteria alongside the yeast produce those acids."),
        QuestionSeed("In classical culinary usage, how do stock and broth usually differ?",
                     ["Stock emphasizes bones; broth emphasizes meat", "Broth is always thickened with starch, while stock is left unthickened", "Stock is made exclusively from vegetables, while broth always uses meat", "Broth is never seasoned during cooking, while stock is heavily salted"], 0,
                     "Bones give classical stock gelatin and body, although commercial and regional uses of the terms often overlap."),
        QuestionSeed("Which spice comes from the bark of a tree?",
                     ["Cinnamon", "Nutmeg", "Clove", "Pepper"], 0,
                     "Cloves are flower buds and nutmeg is a seed."),
        QuestionSeed("What is a 'roux' used for?",
                     ["Thickening sauces", "Sweetening desserts", "Tenderising meat", "Clarifying stock"], 0,
                     "Equal parts fat and flour cooked together form the base of many classic sauces."),
        QuestionSeed("Which country is the origin of kimchi?",
                     ["Korea", "Japan", "China", "Vietnam"], 0,
                     "It refers to a family of fermented vegetable dishes, not one recipe."),
        QuestionSeed("What does 'al dente' describe?",
                     ["Pasta cooked so it still has bite", "Overcooked pasta", "A sauce consistency", "A type of flour"], 0,
                     "The phrase means 'to the tooth' in Italian."),
        QuestionSeed("Which part of the saffron crocus is harvested?",
                     ["The stigmas", "The petals", "The roots", "The leaves"], 0,
                     "Each flower yields only three, which is why saffron is so costly."),
        QuestionSeed("What is 'clarified butter'?",
                     ["Butter with milk solids and water removed", "Butter aerated by beating until it becomes soft and light", "Salted butter", "Butter inoculated with lactic bacteria before it is churned"], 0,
                     "It has a higher smoke point, and ghee is a closely related product."),
        QuestionSeed("Which cuisine is the dish pho from?",
                     ["Vietnamese", "Thai", "Cambodian", "Laotian"], 0,
                     "The broth is typically simmered for hours with charred aromatics."),
        QuestionSeed("What is the Maillard reaction responsible for?",
                     ["Browning and savoury flavour development", "Microbes converting sugars into acids, alcohol, or gas", "Curdling", "Emulsification"], 0,
                     "It is a reaction between amino acids and reducing sugars under heat."),
        QuestionSeed("Which of these is a fortified wine?",
                     ["Port", "Chablis", "Beaujolais", "Riesling"], 0,
                     "Fortification adds spirit, which stops fermentation and raises alcohol content."),
        QuestionSeed("What is 'tempering' chocolate for?",
                     ["Producing a glossy finish and clean snap", "Increasing the sugar content by blending in syrup or sweetener", "Melting it faster", "Extracting most of the cocoa butter from the chocolate mixture"], 0,
                     "Controlled heating and cooling forms the right cocoa butter crystal structure."),
        QuestionSeed("Which pulse is used to make masoor dal?",
                     ["Red lentils", "Chickpeas", "Black gram", "Mung beans"], 0,
                     "Masoor dal is made from red lentils; the broader word dal can refer to many split pulses and the dishes made from them."),
        QuestionSeed("What is an emulsion in cooking?",
                     ["One normally immiscible liquid dispersed in another", "A stock thickened with starch or gelatin until it coats a spoon", "Powdered spices and salt rubbed onto food before it is cooked", "A fermented paste"], 0,
                     "Mayonnaise is a stabilized emulsion, while a basic vinaigrette is usually a temporary one."),
        QuestionSeed("The modern layered moussaka topped with béchamel is most associated with which cuisine?",
                     ["Greek", "Italian", "French", "Spanish"], 0,
                     "Moussaka has many regional forms, but the layered aubergine-and-béchamel version is especially associated with Greece."),
        QuestionSeed("Which technique briefly heats food in boiling water or steam before rapidly cooling it?",
                     ["Blanching", "Braising", "Poaching", "Stewing"], 0,
                     "Blanching briefly heats food and then cools it quickly, often in ice water, to halt further cooking."),
        QuestionSeed("Which grain is used to brew traditional sake?",
                     ["Rice", "Barley", "Wheat", "Millet"], 0,
                     "Polished rice is fermented with a mould called koji."),
        QuestionSeed("What is the difference between baking soda and baking powder?",
                     ["Baking powder already contains an acid", "They are identical", "Baking soda contains an acid", "Baking powder contains yeast"], 0,
                     "Baking soda needs a separate acidic ingredient to activate."),
        QuestionSeed("Which cut of beef is a ribeye taken from?",
                     ["The rib section", "The hindquarter", "The shoulder", "The belly"], 0,
                     "Its marbling comes from the muscle doing relatively little work."),
        QuestionSeed("What is 'sous vide' cooking?",
                     ["Sealing food and cooking it in precisely controlled water", "Cooking over an open flame", "Steaming in bamboo", "Exposing food to cool wood smoke over a period of several hours"], 0,
                     "The French term means 'under vacuum'."),
        QuestionSeed("Which fruit is used to make traditional balsamic vinegar?",
                     ["Grapes", "Apples", "Figs", "Plums"], 0,
                     "Cooked grape must is aged in a series of wooden barrels."),
        QuestionSeed("What is 'proving' or 'proofing' dough?",
                     ["Letting it rise before baking", "Kneading it", "Chilling it", "Rolling it thin"], 0,
                     "Yeast produces carbon dioxide, which expands the gluten network."),
        QuestionSeed("Which nuts are commonly used in traditional regional versions of baklava?",
                     ["Pistachios or walnuts", "Peanuts only", "Cashews only", "Macadamias only"], 0,
                     "Regional versions favor pistachios, walnuts, or sometimes other nuts layered between filo and syrup."),
        QuestionSeed("What is 'curing' meat with salt intended to do?",
                     ["Preserve it by drawing out moisture", "Sweetening the meat's surface by applying a sugar-based glaze", "Softening muscle fibres without materially extending storage life", "Increase fat content"], 0,
                     "Lower water activity makes it much harder for spoilage bacteria to grow."),
        QuestionSeed("Which cooking method uses dry heat in an enclosed oven?",
                     ["Roasting", "Poaching", "Steaming", "Boiling"], 0,
                     "The other three all rely on water or steam."),
        QuestionSeed("Which vegetables make up a classic French mirepoix?",
                     ["Onion, carrot, and celery", "Tomato, pepper, and garlic", "Potato, leek, and cabbage", "Mushroom, fennel, and spinach"], 0,
                     "The aromatic mixture is gently cooked as a flavour base for soups, stocks, sauces, and stews."),
        QuestionSeed("What changes raw fish in a typical ceviche?",
                     ["Acid from citrus juice", "Smoke from hardwood", "Pressure from a weight", "Dry heat from a pan"], 0,
                     "Citrus acid denatures surface proteins, changing their texture, but it does not reliably eliminate every food-safety hazard."),
        QuestionSeed("What is gochujang?",
                     ["A Korean fermented chilli paste", "A Japanese noodle", "A Chinese tea", "A Thai coconut soup"], 0,
                     "The paste traditionally combines chilli powder, fermented soybean, rice, and salt."),
        QuestionSeed("What kind of cheese is paneer?",
                     ["A fresh acid-set cheese", "A blue-veined aged cheese", "A washed-rind cheese", "A stretched-curd cheese"], 0,
                     "Acid curdles hot milk, and the curds are drained and pressed without using rennet."),
        QuestionSeed("What is tahini made from?",
                     ["Ground sesame seeds", "Ground chickpeas", "Crushed olives", "Roasted almonds"], 0,
                     "Tahini adds a rich sesame flavour to hummus, sauces, and sweets."),
        QuestionSeed("What is the main ingredient in polenta?",
                     ["Cornmeal", "Potato", "Rice flour", "Buckwheat"], 0,
                     "The northern Italian dish is cooked by simmering cornmeal in liquid."),
        QuestionSeed("What forms the base of a classic beurre blanc sauce?",
                     ["Butter whisked into a reduced acidic liquid", "Tomatoes simmered with stock and aromatics until reduced", "Egg yolks blended slowly with oil to create an emulsion", "Milk cooked with a butter-and-flour roux until thickened"], 0,
                     "Cold butter is gradually emulsified into a reduction of wine or vinegar and aromatics."),
        QuestionSeed("What is masa harina?",
                     ["Flour made from dried nixtamalized corn", "Coarsely ground rice", "Roasted chickpea flour", "The outer bran layer milled from uncooked wheat kernels"], 0,
                     "Water rehydrates masa harina into dough for foods such as tortillas and tamales."),
        QuestionSeed("What is aquafaba?",
                     ["The cooking liquid from chickpeas or other legumes", "Concentrated saltwater used to preserve fish before smoking", "Clarified butter", "Fermented rice vinegar"], 0,
                     "Its dissolved starches and proteins let it foam and emulsify, so it can replace egg white in some recipes."),
        QuestionSeed("Botanically, which group does the peanut belong to?",
                     ["Legumes", "Tree nuts", "Cereal grains", "Stone fruits"], 0,
                     "Peanuts grow in pods and are relatives of beans and peas, despite their culinary treatment as nuts."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("What are the five mother sauces of French cuisine?",
                     ["Béchamel, velouté, espagnole, hollandaise, tomato", "Béarnaise, aioli, pesto, ragù, jus", "Demi-glace, beurre blanc, mayonnaise, gravy, coulis", "Roux, stock, glace, fumet, consommé"], 0,
                     "Escoffier codified the list, from which most classical sauces are derived."),
        QuestionSeed("What is 'spherification' in modernist cooking?",
                     ["Forming liquid into spheres with a gelled skin", "Incorporating tiny air bubbles into a sauce to lighten its texture", "Freezing ingredients instantly in liquid nitrogen to make a powder", "Placing fruit under vacuum so a flavoured liquid enters its cells"], 0,
                     "Sodium alginate and a calcium bath produce the membrane."),
        QuestionSeed("What does 'terroir' refer to?",
                     ["The environmental factors shaping a food's character", "The barrel specification traditionally used to age a particular wine", "A regional French cheese produced from a protected source of milk", "An earthenware vessel traditionally used for slow braises and stews"], 0,
                     "Soil, climate, and local practice are all considered part of it."),
        QuestionSeed("What is 'koji' and what is it used for?",
                     ["A mould used to ferment sake, miso, and soy sauce", "A Japanese single-bevel knife designed for slicing raw seafood", "A dried seaweed used to season broths and wrap portions of rice", "A short-grain rice variety traditionally reserved for brewing sake"], 0,
                     "Aspergillus oryzae breaks starches into fermentable sugars."),
        QuestionSeed("What is wet-curing food in a salt solution called?",
                     ["Brining", "Dry curing", "Fermenting", "Smoking"], 0,
                     "Brining is a form of wet curing; dry curing applies salt and other curing ingredients without a liquid bath."),
        QuestionSeed("What is 'gluten' formed from?",
                     ["Glutenin and gliadin proteins hydrated and worked", "Starch and water", "Fat coating particles of flour before any liquid is introduced", "Yeast consuming sugar and releasing carbon dioxide throughout the dough"], 0,
                     "Kneading aligns those proteins into an elastic network."),
        QuestionSeed("What does 'AOC' or 'AOP' certification indicate in France?",
                     ["A protected designation tied to origin and method", "A numerical panel score reflecting the overall sensory quality of a product", "A certification that ingredients were grown without prohibited chemicals", "A restaurant rating"], 0,
                     "It governs which products may carry names like Roquefort or Champagne."),
        QuestionSeed("What is 'nixtamalization'?",
                     ["Treating maize with an alkaline solution", "Fermenting rice", "Smoking chillies", "Dehydrating tomatoes slowly in sunlight or a low-temperature oven"], 0,
                     "It improves nutrition and lets the corn form masa dough for tortillas."),
        QuestionSeed("What is the purpose of 'resting' meat after cooking?",
                     ["Letting juices redistribute through the muscle", "Cooling it to a safe temperature", "Adding seasoning", "Firming the crust"], 0,
                     "Cutting immediately lets much of the juice run out onto the board."),
        QuestionSeed("What is a 'consommé'?",
                     ["A clarified stock", "A thick puree", "A cold soup", "A reduction sauce"], 0,
                     "A raft of egg white and mirepoix traps particles as it cooks."),
        QuestionSeed("What is 'sofrito' or 'soffritto' generally used as?",
                     ["An aromatic flavour base of gently cooked vegetables", "A finishing herb oil", "A dessert sauce", "A salted water mixture used to season or preserve food before cooking"], 0,
                     "Onion, carrot, and celery is the classic Italian version."),
        QuestionSeed("What is the difference between Dutch-process and natural cocoa?",
                     ["Dutch-process is alkalised, reducing acidity", "Natural cocoa contains dairy", "Dutch-process is sweetened", "The two names describe identical cocoa processed by the same method"], 0,
                     "The difference matters because it changes which leavening agent works."),
        QuestionSeed("What does 'lactic fermentation' produce in vegetables?",
                     ["Lactic acid that preserves and sours them", "Ethanol formed as yeast consumes vegetable sugars without oxygen", "Carbon dioxide released without any accompanying organic acid", "Acetic acid formed when oxygen-dependent bacteria act on alcohol"], 0,
                     "Sauerkraut and traditional pickles rely on it."),
        QuestionSeed("What is 'ganache' made from?",
                     ["Chocolate and cream", "Butter and sugar", "Egg and flour", "Milk and gelatin"], 0,
                     "The ratio determines whether it sets as a glaze, filling, or truffle."),
        QuestionSeed("What is 'the Scoville scale' originally based on?",
                     ["Dilution until heat was no longer detectable by tasters", "A spectrometer measurement of how strongly a chilli absorbs light", "The mass of capsaicin isolated from a fixed weight of fresh pepper", "The intensity of red colour measured against a standard reference chart"], 0,
                     "Modern measurement uses chromatography and converts the result to Scoville units."),
        QuestionSeed("What does 'carryover cooking' describe?",
                     ["Continued cooking from residual heat after removal", "Reheating leftovers", "Cooking in batches", "Maintaining completed dishes at a stable temperature before service"], 0,
                     "Large roasts can rise several degrees after leaving the oven."),
        QuestionSeed("What is 'kombu' used for in Japanese cooking?",
                     ["Making dashi stock", "Wrapping sushi rolls", "Sweetening sauces", "Thickening soups"], 0,
                     "The kelp contributes glutamates, giving dashi its umami depth."),
        QuestionSeed("What is 'invert sugar'?",
                     ["Sucrose split into glucose and fructose", "A sugar substitute", "Unrefined cane sugar that retains some of its natural molasses", "Powdered sugar"], 0,
                     "It resists crystallisation, which is useful in confectionery and syrups."),
        QuestionSeed("What is 'a bain-marie'?",
                     ["A water bath for gentle, even heating", "A hinged metal mould used to shape a filled pastry", "A heavy copper saucepan designed for confectionery work", "A type of whisk"], 0,
                     "Custards and delicate sauces are cooked this way to avoid curdling."),
        QuestionSeed("What is 'mother' in vinegar production?",
                     ["A bacterial culture that converts alcohol to acetic acid", "A yeast culture introduced to convert fruit sugars into alcohol", "A concentrated flavouring aged before it is added to finished vinegar", "A filtering agent"], 0,
                     "Acetobacter forms the cloudy film or mass in unfiltered vinegar."),
        QuestionSeed("What does 'DOP' on an Italian product signify?",
                     ["Protected designation of origin", "A quality grade", "An organic certification", "An export licence"], 0,
                     "Parmigiano Reggiano and Prosciutto di Parma both carry it."),
        QuestionSeed("What is 'brunoise'?",
                     ["A very fine dice", "A julienne cut", "A chiffonade", "A rough chop"], 0,
                     "It is typically about two millimetres on each side."),
        QuestionSeed("What is 'the cold chain' in food safety?",
                     ["Unbroken refrigeration from production to consumption", "Flash-freezing food quickly enough to form very small ice crystals", "An insulated container designed for long-term storage of frozen food", "A transport contract"], 0,
                     "Any break in it allows bacterial growth that later chilling cannot undo."),
        QuestionSeed("What is 'pectin' used for?",
                     ["Setting jams and jellies", "Tenderising meat", "Clarifying stock", "Leavening bread"], 0,
                     "It occurs naturally in fruit, with apples and citrus peel especially rich in it."),
        QuestionSeed("What is 'a reduction' in sauce making?",
                     ["Simmering to evaporate liquid and concentrate flavour", "Enriching a finished sauce by stirring in cream and cold butter", "Passing a cooked sauce through a fine sieve to remove all solids", "Chilling to thicken"], 0,
                     "It thickens by concentration rather than by adding a thickener."),
        QuestionSeed("What is 'charcuterie' traditionally?",
                     ["Prepared and preserved meat products", "An arranged selection of cheeses served with small accompaniments", "An assortment of breads, rolls, and crackers presented together", "A vegetable terrine"], 0,
                     "The French term originally referred to a pork butcher's shop."),
        QuestionSeed("What is 'hydration' in bread baking expressed as?",
                     ["Water weight as a percentage of flour weight", "The mass of the completed dough including flour, water, salt, and yeast", "The amount of yeast calculated as a percentage of the flour weight", "The total oven time calculated in relation to the finished loaf weight"], 0,
                     "High-hydration doughs are wetter and produce a more open crumb."),
        QuestionSeed("What is 'lees' in winemaking?",
                     ["Sediment of dead yeast and grape solids", "The grape skins left after the pressed juice has been separated", "The toasted interior surface of an oak barrel used for ageing wine", "Bottle sediment only"], 0,
                     "Ageing on the lees adds texture and bready flavours."),
        QuestionSeed("What is 'the smoke point' of an oil?",
                     ["The temperature at which it begins to break down and smoke", "The temperature at which a liquid cooking oil becomes solid", "The point at which heating makes an oil's flavour most pronounced", "The expected storage time before the oil develops a rancid flavour"], 0,
                     "Beyond it the oil develops off flavours and releases irritating compounds."),
        QuestionSeed("What is 'fond' in a pan after searing?",
                     ["The browned residue used to build a sauce", "The rendered fat released from food and collected in the bottom of a pan", "Overheated oil that has developed burnt flavours and must be discarded", "A concentrated liquid prepared by simmering bones and aromatics"], 0,
                     "Deglazing dissolves it into liquid, capturing its concentrated flavour."),
        QuestionSeed("What provides most of the leavening in pâte à choux?",
                     ["Steam", "Baking powder", "Yeast", "Whipped egg whites alone"], 0,
                     "Moisture in the dough turns to steam, inflating the paste before the egg proteins set its structure."),
        QuestionSeed("Which enzyme drives much of the browning in a cut apple exposed to air?",
                     ["Polyphenol oxidase", "Amylase", "Rennet", "Lipase"], 0,
                     "The enzyme oxidizes phenolic compounds after damaged cells expose them to oxygen."),
        QuestionSeed("What is beurre manié?",
                     ["Equal parts soft butter and flour kneaded into a paste", "Butter cooked until its milk solids turn brown and smell nutty", "Butter clarified over low heat", "Butter beaten together with chopped herbs, spices, and seasoning"], 0,
                     "Small pieces can be whisked into a simmering liquid to thicken it near the end of cooking."),
        QuestionSeed("Which two polysaccharides make up most culinary starch?",
                     ["Amylose and amylopectin", "Glucose and fructose", "Cellulose and pectin", "Lactose and galactose"], 0,
                     "Their different branching structures influence gelatinization, firmness, and staling."),
        QuestionSeed("What is an autolyse in bread making?",
                     ["A rest after mixing flour and water before further kneading", "The final fermentation undergone by shaped dough before it enters the oven", "The period in which a freshly baked loaf cools before it can be sliced", "The addition of steam to an oven to help form a thin, crisp crust"], 0,
                     "The rest hydrates flour and allows enzymes to begin modifying starch and proteins."),
        QuestionSeed("What does transglutaminase do to food proteins?",
                     ["Creates cross-links between them", "Converts them into sugar", "Removes every amino acid", "Prevents them from browning"], 0,
                     "The enzyme can strengthen or bind protein gels by forming covalent links between amino-acid side chains."),
        QuestionSeed("What is syneresis in a gel or cultured dairy product?",
                     ["Liquid separating from the solid network", "Air becoming trapped during whipping", "Sugar crystallizing on the surface", "Fat turning rancid"], 0,
                     "The network contracts and expels liquid, as when whey collects on yogurt."),
        QuestionSeed("What does the Bloom strength of gelatin measure?",
                     ["Gel firmness", "Sweetness", "Melting colour", "Acidity"], 0,
                     "A higher Bloom value indicates a stronger gel under standardized test conditions."),
        QuestionSeed("What is rennet used for in cheesemaking?",
                     ["Coagulating milk proteins into curds", "Adding blue mould", "Salting the rind", "Removing lactose through evaporation"], 0,
                     "Its enzymes destabilize casein micelles so the milk separates into curds and whey."),
        QuestionSeed("What is dextrinization?",
                     ["Breaking starch into shorter chains with dry heat", "Fermenting sugar into alcohol", "Coagulating milk with acid", "Air incorporated by beating solid fat with crystalline sugar"], 0,
                     "Dry heating can produce dextrins that contribute colour, flavour, and crisp texture."),
    ]
}
