import Foundation

enum FootballQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("How many points is a touchdown worth?",
                     ["3", "6", "7", "8"], 1,
                     "A touchdown is worth six points. The try that follows it is a separate play."),
        QuestionSeed("How many players from one team are on the field during a play?",
                     ["9", "10", "11", "12"], 2,
                     "Each team lines up eleven players. Having twelve on the field draws a penalty."),
        QuestionSeed("What is the NFL championship game called?",
                     ["The Rose Bowl", "The Super Bowl", "The World Series", "The Stanley Cup"], 1,
                     "The Super Bowl became the NFL's championship game after the AFL–NFL merger took full effect in 1970."),
        QuestionSeed("How many yards must an offense gain to earn a new set of downs?",
                     ["5", "8", "10", "15"], 2,
                     "Ten yards resets the down counter, which is why the chains measure exactly that distance."),
        QuestionSeed("Which position usually throws the ball?",
                     ["Quarterback", "Center", "Safety", "Placekicker"], 0,
                     "The quarterback takes the snap and is the primary passer on almost every offense."),
        QuestionSeed("How many points is a field goal worth?",
                     ["1", "2", "3", "6"], 2,
                     "Kicking the ball through the uprights from scrimmage scores three points."),
        QuestionSeed("How many quarters are in a regulation game?",
                     ["2", "3", "4", "5"], 2,
                     "Four quarters make up regulation. A tie at the end sends the game to overtime."),
        QuestionSeed("Which player snaps the ball to start a play?",
                     ["The center", "The tight end", "The cornerback", "The punter"], 0,
                     "The center is the interior lineman who puts the ball in play on every snap."),
        QuestionSeed("What is it called when the quarterback is tackled behind the line of scrimmage?",
                     ["An interception", "A sack", "A fumble", "A huddle"], 1,
                     "A sack costs the offense yardage and counts against its passing total."),
        QuestionSeed("How long is an NFL field between the two goal lines?",
                     ["80 yards", "90 yards", "100 yards", "120 yards"], 2,
                     "The field of play is 100 yards. Each end zone adds another ten."),
        QuestionSeed("How many points is a safety worth?",
                     ["1", "2", "3", "6"], 1,
                     "A safety is worth two points, and the scoring team also receives the ball on a free kick."),
        QuestionSeed("Which unit tries to stop the opposing offense?",
                     ["The defense", "Special teams", "The practice squad", "The officiating crew"], 0,
                     "The defense takes the field whenever the other team has possession."),
        QuestionSeed("How deep is each end zone?",
                     ["5 yards", "10 yards", "15 yards", "20 yards"], 1,
                     "Both end zones are ten yards deep, making the full field 120 yards end to end."),
        QuestionSeed("How many downs does an offense normally get to gain ten yards?",
                     ["Two", "Three", "Four", "Five"], 2,
                     "Four downs. Teams usually punt on fourth down rather than risk turning the ball over."),
        QuestionSeed("How many points is a successful extra-point kick worth?",
                     ["1", "2", "3", "6"], 0,
                     "The kicked try adds a single point, which is why a touchdown drive often totals seven."),
        QuestionSeed("What is it called when a defender catches a pass intended for the offense?",
                     ["A reception", "An interception", "A completion", "A touchback"], 1,
                     "An interception is an immediate change of possession, and the defender may return it."),
        QuestionSeed("What is the long-standing nickname for the football itself?",
                     ["The pigskin", "The rock", "The apple", "The oval"], 0,
                     "The nickname survives from an era of animal-bladder balls, though modern footballs are cowhide."),
        QuestionSeed("What does it mean to defer after winning the opening coin toss?",
                     ["Choose first at the start of the second half", "Give up all kickoff choices", "Start the game with a penalty", "Let the referee choose both goals"], 0,
                     "A team that defers postpones its first choice until the second half; the opponent chooses first for the opening kickoff."),
        QuestionSeed("Which specialist kicks field goals and extra points?",
                     ["The placekicker", "The long snapper", "The fullback", "The nose tackle"], 0,
                     "The placekicker handles kicks from a hold; the punter is a separate specialist."),
        QuestionSeed("What is it called when a ball carrier loses the ball before being downed?",
                     ["An incompletion", "A fumble", "A sack", "A safety"], 1,
                     "A fumble is a live ball, so either team can recover it."),
        QuestionSeed("Halftime comes after which quarter?",
                     ["The first", "The second", "The third", "The fourth"], 1,
                     "The game breaks at the midpoint, after two quarters."),
        QuestionSeed("How many points is a two-point conversion worth?",
                     ["1", "2", "3", "6"], 1,
                     "Instead of kicking, the offense runs one play from close range for two points."),
        QuestionSeed("What is the imaginary line where each play begins called?",
                     ["The goal line", "The line of scrimmage", "The sideline", "The offensive tackle box"], 1,
                     "Neither team may cross the line of scrimmage before the snap."),
        QuestionSeed("What does an official throwing a yellow flag indicate?",
                     ["A touchdown", "A penalty", "The end of a quarter", "A timeout"], 1,
                     "The yellow flag marks a foul; the official then announces the penalty and its yardage."),
        QuestionSeed("Which position's main job is catching passes downfield?",
                     ["Wide receiver", "Offensive guard", "Defensive tackle", "Long snapper"], 0,
                     "Wide receivers line up split from the formation and run routes to get open."),
        QuestionSeed("What is the trophy awarded to the Super Bowl winner called?",
                     ["The Vince Lombardi Trophy", "The Lamar Hunt Trophy for the AFC champion", "The Halas Trophy", "The Heisman Trophy"], 0,
                     "It is named for the coach whose Green Bay teams won the first two Super Bowls."),
        QuestionSeed("What is the area inside the opponent's 20-yard line commonly called?",
                     ["The red zone", "The paint", "The crease", "The pocket"], 0,
                     "Red-zone efficiency measures how often a team turns those trips into touchdowns."),
        QuestionSeed("On which down does a team usually punt?",
                     ["First", "Second", "Third", "Fourth"], 3,
                     "Punting on fourth down gives the ball away, but pins the opponent farther from the end zone."),
        QuestionSeed("What is the protected area a quarterback drops back into called?",
                     ["The pocket", "The box", "The gap", "The flat"], 0,
                     "Offensive linemen form the pocket to give the passer time to throw."),
        QuestionSeed("How many teams are in the National Football League?",
                     ["24", "28", "32", "36"], 2,
                     "Thirty-two clubs are split evenly between the AFC and the NFC."),
        QuestionSeed("Which play starts each half of a football game?",
                     ["A kickoff", "A punt", "A field goal", "A quarterback sneak"], 0,
                     "A kickoff also follows most scoring plays, subject to the game's timing and overtime rules."),
        QuestionSeed("What is the usual purpose of a punt?",
                     ["To give up possession while moving the opponent farther from the goal", "To attempt a field goal worth three points from the current line of scrimmage", "To place the ball back in play after a touchdown without using a kickoff", "To receive an automatic first down while continuing to possess the ball"], 0,
                     "Teams commonly punt on fourth down when attempting to gain the needed yards would be too risky."),
        QuestionSeed("What is the offensive line's main job on a passing play?",
                     ["Protect the quarterback", "Cover wide receivers", "Return the kick", "Call penalties"], 0,
                     "The linemen form a pocket and block defenders trying to reach the passer."),
        QuestionSeed("What is a huddle?",
                     ["A brief gathering where players receive the play call", "A pile formed after every tackle", "The officials' replay review", "A coordinated end-zone celebration performed after a team scores"], 0,
                     "The quarterback usually relays the play and snap count before the players approach the line."),
        QuestionSeed("What scores when a player possessing the ball reaches the opponent's end zone?",
                     ["A touchdown", "A safety", "A field goal", "A touchback"], 0,
                     "The ball must break the plane of the goal line while legally possessed for a touchdown."),
        QuestionSeed("Which piece of equipment primarily protects a football player's head?",
                     ["The helmet", "The shoulder pad", "The mouthguard", "The thigh pad"], 0,
                     "A helmet includes a hard shell, padding, chinstrap, and usually a face mask."),
        QuestionSeed("What does a kick returner try to do?",
                     ["Advance a kickoff or punt after receiving it", "Deliver the snap accurately to the holder during a field-goal attempt", "Prevent only the opposing placekicker from reaching a loose football", "Catch the long snap and hold the football steady for the team's punter"], 0,
                     "The returner's field position determines where the offence begins its possession."),
        QuestionSeed("What does the goal line separate?",
                     ["The field of play from the end zone", "The two halves of the field", "The sideline from the bench", "The offence from the defence"], 0,
                     "The front edge of the goal line is the plane the ball must reach for a touchdown."),
        QuestionSeed("What is an incomplete pass?",
                     ["A forward pass that is not legally caught", "A pass caught behind the line", "A handoff to a running back", "A lateral recovered by the defence"], 0,
                     "An incomplete forward pass falls dead and the next down begins from the previous line of scrimmage, subject to penalties."),
        QuestionSeed("What is a handoff?",
                     ["Transferring the ball directly from one teammate to another", "Throwing a forward pass after crossing the line of scrimmage", "Kicking the ball to the opponent after the offense scores a touchdown", "Snapping the ball directly from the centre to the team's punter"], 0,
                     "The quarterback commonly places the ball into a running back's arms on a rushing play."),
        QuestionSeed("What does NFL stand for?",
                     ["National Football League", "National Field League", "Northern Football League", "National Federation of Leagues"], 0,
                     "The National Football League has operated under that name since 1922."),
        QuestionSeed("How many yards apart are the marked yard lines on a field?",
                     ["Two", "Five", "Ten", "Twenty-five"], 1,
                     "Yard lines are marked every five yards, with printed numbers every ten yards."),
        QuestionSeed("Which NFL team's helmet carries a single blue star?",
                     ["The Dallas Cowboys", "The Chicago Bears", "The Detroit Lions", "The Pittsburgh Steelers"], 0,
                     "The Dallas Cowboys have worn the blue star on their helmets for decades."),
        QuestionSeed("Which official leads the on-field crew in an NFL game?",
                     ["The referee", "The umpire", "The side judge", "The field marshal"], 0,
                     "The referee holds final authority and announces penalties to the stadium."),
        QuestionSeed("What is the NFL's annual all-star game called?",
                     ["The Pro Bowl", "The Star Game", "The Gridiron Cup", "The All-America Bowl"], 0,
                     "The Pro Bowl gathers players voted the best at their positions each season."),
        QuestionSeed("What do the teams do at the end of the first quarter?",
                     ["Switch ends of the field", "Restart the game clock", "Hold another coin toss", "Take an extended intermission"], 0,
                     "Teams switch ends of the field after the first and third quarters."),
        QuestionSeed("What does a coach throw onto the field to challenge a ruling?",
                     ["A red flag", "A white towel", "A yellow marker", "A numbered placard"], 0,
                     "A coach throws a red flag to ask officials to review the previous play."),
        QuestionSeed("How many points come from a touchdown plus a successful extra point?",
                     ["Six", "Seven", "Eight", "Nine"], 1,
                     "A touchdown is six points and the extra-point kick adds one, making seven."),
        QuestionSeed("What shape is a football?",
                     ["A prolate spheroid", "A perfect sphere", "A flattened disc", "A rounded cylinder"], 0,
                     "A football is a prolate spheroid, pointed at both ends for throwing and carrying."),
        QuestionSeed("What is the result when an NFL game ends with the score level?",
                     ["A tie", "A void", "A shared victory", "A double forfeit"], 0,
                     "A tie is recorded when regulation and overtime both end with the score level."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("What is the standard NFL yardage penalty for offensive holding?",
                     ["5 yards", "10 yards", "15 yards", "20 yards"], 1,
                     "Offensive holding normally carries a ten-yard penalty, although enforcement depends on where the foul and play occur."),
        QuestionSeed("What happens on a safety after the two points are awarded?",
                     ["The scoring team kicks off", "The scoring team receives a free kick", "Play restarts at midfield", "The quarter ends"], 1,
                     "The team that was scored upon must free kick the ball back to the team that scored."),
        QuestionSeed("Which award goes to the most outstanding player in U.S. college football?",
                     ["The Heisman Trophy", "The Maxwell Award", "The Butkus Award", "The Outland Trophy"], 0,
                     "The Heisman has been presented annually since 1935."),
        QuestionSeed("What is the offensive formation with the quarterback a few yards behind center called?",
                     ["Under center", "The shotgun", "The wildcat", "The pistol"], 1,
                     "The shotgun gives the passer a head start reading the defense before the rush arrives."),
        QuestionSeed("Under the normal NFL play-clock rule, when does a 40-second clock begin?",
                     ["When the previous play ends", "When the referee spots the ball", "When the offense breaks its huddle", "When the center grips the ball"], 0,
                     "The 40-second clock normally starts when the previous play ends; a 25-second clock follows specified administrative stoppages."),
        QuestionSeed("What penalty is called when a defender contacts a receiver illegally before the ball arrives?",
                     ["Illegal formation", "Pass interference", "Encroachment", "Delay of game"], 1,
                     "In the NFL, defensive pass interference is a spot foul, so it can move the ball a long way."),
        QuestionSeed("Which two conferences make up the NFL?",
                     ["East and West", "AFC and NFC", "National and American League", "Premier and Championship"], 1,
                     "The American and National Football Conferences date from the 1970 merger."),
        QuestionSeed("What is a running back's primary responsibility on a handoff?",
                     ["Blocking the edge", "Carrying the ball", "Covering a receiver", "Snapping the ball"], 1,
                     "The back takes the exchange from the quarterback and runs behind his blockers."),
        QuestionSeed("How wide is an NFL field?",
                     ["120 feet", "160 feet", "180 feet", "200 feet"], 1,
                     "A regulation field is 160 feet, or 53 1/3 yards, wide."),
        QuestionSeed("What does a defensive coordinator do?",
                     ["Call defensive plays", "Manage the salary cap", "Coach the kickers", "Handle player contracts"], 0,
                     "The coordinator designs the scheme and signals in the call on each defensive snap."),
        QuestionSeed("What is it called when the defense scores by returning an interception to the end zone?",
                     ["A pick six", "A hat trick", "A grand slam", "A double play"], 0,
                     "The name comes from the six points the return is worth."),
        QuestionSeed("Which position lines up closest to the offensive tackle and can both block and catch?",
                     ["Tight end", "Slot corner", "Free safety", "Fullback"], 0,
                     "The tight end is a hybrid: an extra blocker on running plays and a receiving target on passes."),
        QuestionSeed("What is the foul when a defensive player crosses the line of scrimmage before the snap?",
                     ["Holding", "Offside", "Clipping", "Tripping"], 1,
                     "NFL defensive offside is normally a live-ball five-yard foul, so the offense may sometimes choose the result of the play instead."),
        QuestionSeed("How many officials work a standard NFL game?",
                     ["Three", "Five", "Seven", "Nine"], 2,
                     "Seven officials each have distinct coverage areas and responsibilities."),
        QuestionSeed("What does 'third and long' describe?",
                     ["A field-goal attempt taken from an unusually great distance", "Third down with many yards still needed", "The final possession played before the third quarter comes to an end", "A kickoff carried a long distance before the returner is tackled"], 1,
                     "It is a passing situation, so defenses often bring extra pass rushers."),
        QuestionSeed("Which team plays its home games at Lambeau Field?",
                     ["Chicago Bears", "Green Bay Packers", "Minnesota Vikings", "Detroit Lions"], 1,
                     "Lambeau Field has been the Packers' home since 1957."),
        QuestionSeed("Which pass play invites the rush before throwing short to a receiver behind blockers?",
                     ["A screen", "A post", "A slant", "A fade"], 0,
                     "On a designed screen, blockers release into space ahead of the receiver; merely catching a pass behind the line does not make it a screen."),
        QuestionSeed("What is the maximum NFL game-day Active List size when at least eight offensive linemen are active?",
                     ["46 players", "47 players", "48 players", "53 players"], 2,
                     "The game-day Active List may contain forty-eight players when eight offensive linemen are active; otherwise the limit is forty-seven."),
        QuestionSeed("What kickoff is deliberately shortened because the kicking team hopes to recover it?",
                     ["A deliberately short squib kick", "An onside kick", "A fair catch", "A touchback"], 1,
                     "An onside kick sacrifices distance to give the kicking team a chance to recover and retain possession."),
        QuestionSeed("If a kickoff goes through the end zone untouched, what is the result?",
                     ["A safety", "A touchback", "A first down at midfield", "A replay of the kick"], 1,
                     "A touchback spots the ball at a fixed yard line rather than where it stopped."),
        QuestionSeed("What is the defensive alignment with four linemen and three linebackers called?",
                     ["The 3-4", "The 4-3", "The nickel", "The dime"], 1,
                     "The numbers count linemen first, then linebackers."),
        QuestionSeed("What does the term 'audible' mean?",
                     ["A crowd noise penalty", "Changing the play at the line", "A referee's announcement", "A timeout call"], 1,
                     "The quarterback reads the defense and calls a different play before the snap."),
        QuestionSeed("What is the maximum number of timeouts a team gets per half?",
                     ["One", "Two", "Three", "Four"], 2,
                     "Three per half, and they do not carry over from the first half to the second."),
        QuestionSeed("Which position is responsible for delivering the ball on punts and field goals?",
                     ["The long snapper", "The holder", "The gunner", "The upback"], 0,
                     "The long snapper makes a much longer and more difficult snap than the center does."),
        QuestionSeed("What is 'clock management' primarily about?",
                     ["Scheduling practices", "Using time strategically late in a half", "Timing the play clock", "Setting the halftime length"], 1,
                     "Spiking the ball, running out of bounds, and calling timeouts all bend the game clock."),
        QuestionSeed("How far back are the goalposts from the goal line in the NFL?",
                     ["At the goal line", "At the back of the end zone", "Ten yards behind the end zone", "On the sideline"], 1,
                     "The posts sit on the end line, so a 20-yard field goal is really a 37-yard kick."),
        QuestionSeed("What is the annual event where teams select new college players called?",
                     ["The Combine", "The Draft", "Free agency", "The Senior Bowl"], 1,
                     "The draft order is generally the reverse of the previous season's standings."),
        QuestionSeed("What is a 'blitz'?",
                     ["A long touchdown pass", "Sending extra rushers at the quarterback", "An offense beginning each play without gathering in a huddle", "A surprise punt attempted before the defense expects the kick"], 1,
                     "Blitzing trades coverage defenders for pressure, so it is a calculated risk."),
        QuestionSeed("What does 'special teams' refer to?",
                     ["The units on kicks and punts", "The injured reserve list", "The coaching staff", "The starting offense"], 0,
                     "Special teams handle kickoffs, punts, field goals, and the returns of each."),
        QuestionSeed("Which league merged with the NFL in 1970?",
                     ["The AFL", "The USFL", "The XFL", "The CFL"], 0,
                     "The American Football League's ten clubs joined, creating the AFC and NFC structure."),
        QuestionSeed("What is a quarterback sneak?",
                     ["A short run directly behind the centre", "A hidden-ball trick on a kickoff", "A deep pass after a fake punt", "A reverse by a wide receiver"], 0,
                     "The quarterback takes the snap and immediately drives forward, usually in short-yardage situations."),
        QuestionSeed("What does play-action attempt to make the defence believe?",
                     ["That the offence is running the ball", "That a punt is coming", "That the quarterback will spike the ball", "That the offence called timeout"], 0,
                     "A convincing run fake can draw defenders forward and open passing lanes behind them."),
        QuestionSeed("What does a punt returner signal by making a valid fair-catch signal?",
                     ["They will not advance the caught kick", "They want the kick replayed", "The ball should be placed at midfield", "They are declining possession"], 0,
                     "The receiver gives up the right to return the kick and receives protection while completing the catch."),
        QuestionSeed("What is a slant route?",
                     ["A quick diagonal cut toward the middle", "A deep route straight downfield", "A turn back toward the sideline", "A route ending behind the quarterback"], 0,
                     "The receiver attacks inside leverage and gives the passer a fast target between defenders."),
        QuestionSeed("How many defensive backs are normally on the field in a dime package?",
                     ["Four", "Five", "Six", "Seven"], 2,
                     "The dime adds a sixth defensive back, just as a nickel package adds a fifth."),
        QuestionSeed("What is a touchback?",
                     ["A dead ball awarded to the receiving team at a rules-designated spot", "A defensive player recovering the ball and carrying it into the end zone", "A punt controlled by a player from the team that originally kicked it", "A completed pass caught by a receiver positioned behind the quarterback"], 0,
                     "Touchbacks commonly occur when a kick enters the receiving team's end zone and is not returned."),
        QuestionSeed("What does the chain crew measure?",
                     ["The line to gain for a first down", "The width of the field", "The height of the goalposts", "The remaining game time"], 0,
                     "The two poles are connected by a ten-yard chain used when a close first-down measurement is needed."),
        QuestionSeed("What is a quarterback scramble?",
                     ["An improvised run after a pass play breaks down", "A designed handoff to the fullback", "A quarterback kneeling immediately after the snap to end the game", "A lateral during a kickoff return"], 0,
                     "The quarterback leaves the intended passing structure to evade pressure or exploit open space."),
        QuestionSeed("What is a draw play designed to resemble at first?",
                     ["A pass play", "A punt", "A quarterback kneel", "A field-goal attempt"], 0,
                     "The initial pass protection encourages defenders to rush upfield before the delayed handoff or run."),
        QuestionSeed("What is a quarterback's cadence?",
                     ["The spoken rhythm and signals used before the snap", "The ordered combination of routes assigned to eligible receivers", "The order of substitutions", "The pace of the game clock"], 0,
                     "Cadence coordinates the snap and can be varied to expose or draw movement from the defence."),
        QuestionSeed("What is the two-minute warning?",
                     ["An automatic timeout near the end of a half", "A penalty for delaying the game", "A signal to begin overtime", "A mandatory equipment check before the final drive"], 0,
                     "The two-minute warning stops the clock automatically near the end of each half."),
        QuestionSeed("What is a nickel package in football?",
                     ["Five defensive backs on the field", "Five offensive linemen blocking together", "A five-yard penalty", "Five receivers in formation"], 0,
                     "A nickel package puts five defensive backs on the field against passing formations."),
        QuestionSeed("What is play action in football?",
                     ["A fake handoff before a pass", "A run up the middle", "A pre-snap shift by receivers", "A defensive blitz call"], 0,
                     "A play-action fake handoff freezes linebackers, opening space behind them for a pass downfield."),
        QuestionSeed("What does roughing the passer penalize?",
                     ["Hitting the quarterback after he throws", "Blocking below the waist", "Holding a receiver well beyond the line", "Crossing the line early"], 0,
                     "Roughing the passer penalizes hitting the quarterback after he has released the ball."),
        QuestionSeed("What does a false start penalize?",
                     ["An offensive player moving before the snap", "A defender jumping offside", "A late substitution", "A missed blocking assignment on special teams"], 0,
                     "A false start is called when an offensive player moves before the snap."),
        QuestionSeed("What is a pylon on a football field?",
                     ["An orange marker at each end-zone corner", "A padded base wrapped around each goalpost", "A yard-line indicator", "A sideline camera mount"], 0,
                     "A pylon is the orange marker standing at each corner of the end zone."),
        QuestionSeed("What does the center do to begin each play?",
                     ["Snaps the ball", "Blocks the safety", "Calls the defense", "Catches the pass"], 0,
                     "The center snaps the ball back to start every play, then blocks the defender in front."),
        QuestionSeed("What is a spike in football?",
                     ["Throwing the ball down to stop the clock", "A high kickoff return along the sideline", "A blitz from the slot", "A blocked field goal"], 0,
                     "A spike throws the ball straight down to stop the clock without risking a play."),
        QuestionSeed("What does the term trenches describe in football?",
                     ["The battle between the lines", "The sideline coaching and equipment area", "The end-zone pylons", "The locker room tunnel"], 0,
                     "The trenches describe the battle between offensive and defensive lines at the scrimmage."),
        QuestionSeed("What is icing the kicker?",
                     ["Calling timeout just before a kick", "Blocking a field goal attempt cleanly", "Kicking into a strong wind", "Replacing the placeholder"], 0,
                     "Icing the kicker means calling a timeout just before the kick to unsettle him."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("In what year was the first AFL–NFL World Championship Game played?",
                     ["1963", "1967", "1970", "1975"], 1,
                     "It was played in January 1967 following the 1966 season and was retroactively named Super Bowl I."),
        QuestionSeed("What is the 'tuck rule' historically associated with?",
                     ["Kickoff placement", "Whether a quarterback's motion is a pass or a fumble", "Helmet fitting", "The regulations controlling the dimensions of numbers on a uniform"], 1,
                     "The rule governed when a passer's arm motion ended; the NFL repealed it in 2013."),
        QuestionSeed("How many players may be in motion at the snap in the NFL?",
                     ["None", "One", "Two", "Any number"], 1,
                     "Only one offensive player may be moving, and not toward the line of scrimmage."),
        QuestionSeed("Which team was the first to complete a perfect season including the Super Bowl?",
                     ["1972 Miami Dolphins", "1985 Chicago Bears", "2007 New England Patriots", "1978 Pittsburgh Steelers"], 0,
                     "Miami finished 17-0. New England went 18-0 in 2007 before losing the Super Bowl."),
        QuestionSeed("What is an 'illegal formation' penalty usually caused by?",
                     ["Too few players on the line of scrimmage", "The offense failing to begin the snap before the play clock reaches zero", "An eligible receiver entering without first reporting an unusual jersey number", "The offense leaving its huddle with twelve players still on the field"], 0,
                     "The offense must have at least seven players on the line at the snap."),
        QuestionSeed("What does the acronym 'PAT' stand for?",
                     ["Pass Attempt Total", "Point After Touchdown", "Play Action Throw", "Punt And Tackle"], 1,
                     "The point after touchdown can be attempted as a kick or as a two-point play."),
        QuestionSeed("Which position group does the term 'the trenches' refer to?",
                     ["Receivers and cornerbacks", "Offensive and defensive linemen", "Kickers and punters", "Safeties and linebackers"], 1,
                     "The phrase describes the close-quarters blocking battle at the line of scrimmage."),
        QuestionSeed("How is a muffed punt different from a fumble?",
                     ["It cannot be recovered", "The returner never established possession", "It happens only in overtime", "It automatically scores two points"], 1,
                     "A muff occurs before possession is established. Either team may recover it; the receiving team may advance its recovery, while the kicking team generally may not advance a recovered scrimmage kick."),
        QuestionSeed("What is the 'Cover 2' defense named for?",
                     ["Two down linemen", "Two deep safeties", "Two-point conversions", "Second-down calls"], 1,
                     "Two safeties split the deep field in half, with corners handling the flats underneath."),
        QuestionSeed("What is 'intentional grounding'?",
                     ["Throwing the ball directly into the ground after the snap to stop the clock", "Throwing away a pass under pressure with no eligible receiver nearby", "Kneeling to end a game", "A blocked field goal"], 1,
                     "It costs a loss of down and yardage, though a passer outside the pocket has more latitude."),
        QuestionSeed("What is the maximum length of an NFL overtime period in the regular season?",
                     ["5 minutes", "10 minutes", "15 minutes", "Until someone scores"], 1,
                     "Regular-season overtime runs ten minutes and can end in a tie; playoff overtime continues until a winner emerges."),
        QuestionSeed("Which defensive scheme uses five defensive backs?",
                     ["Nickel", "Dime", "Quarter", "Prevent"], 0,
                     "Nickel adds a fifth defensive back; dime adds a sixth."),
        QuestionSeed("What is the term for an offensive lineman pulling across the formation to block?",
                     ["Chipping", "Pulling", "Stunting", "Shading"], 1,
                     "A pulling guard leaves his gap and leads the play around the edge."),
        QuestionSeed("Where is the Pro Football Hall of Fame located?",
                     ["Canton, Ohio", "Springfield, Massachusetts", "Cooperstown, New York", "Chicago, Illinois"], 0,
                     "Canton hosted the 1920 meeting where the league that became the NFL was organized."),
        QuestionSeed("What is a 'safety' as a position responsible for?",
                     ["Snapping on punts", "Playing the deepest part of the defense", "Blocking the edge rusher", "Kicking off"], 1,
                     "Free and strong safeties are the last line of defense against deep passes and long runs."),
        QuestionSeed("What does the 'West Coast offense' emphasize?",
                     ["Deep vertical throws", "Short, timing-based passes", "Running the ball almost exclusively", "Frequent onside kicks"], 1,
                     "Short high-percentage throws function as an extension of the running game."),
        QuestionSeed("How many points did the highest-scoring team in a single NFL game record?",
                     ["52", "62", "72", "82"], 2,
                     "Washington scored 72 against the New York Giants in 1966."),
        QuestionSeed("What is a 'chip block'?",
                     ["A block by a back or tight end before releasing into a route", "A block below the waist", "A block on special teams", "Striking an opponent from behind above the level of the waist"], 0,
                     "The brief contact slows an edge rusher without committing the blocker to full protection."),
        QuestionSeed("What does 'RPO' stand for in modern offensive terminology?",
                     ["Run Pass Option", "Receiver Pull Out", "Rush Protection Order", "Return Play Option"], 0,
                     "The quarterback reads a defender after the snap and decides whether to hand off or throw."),
        QuestionSeed("Which NFL foul normally carries both a 15-yard penalty and an automatic first down?",
                     ["False start", "Offensive holding", "Roughing the passer", "Delay of game"], 2,
                     "Roughing the passer normally costs fifteen yards and awards the offense an automatic first down."),
        QuestionSeed("What is the 'franchise tag'?",
                     ["A commemorative patch displaying the club's logo on every jersey", "A one-year contract designation for a pending free agent", "A sponsorship agreement granting a company the naming rights to a stadium", "A transaction exchanging a future draft selection for a current player"], 1,
                     "It keeps a player under contract for a season at a salary tied to the top players at his position."),
        QuestionSeed("What is 'Cover 0'?",
                     ["Man coverage with no deep safety help", "A deep zone alignment designed to prevent a late long completion", "A goal-line stand", "A zone coverage combined with an unexpected rush by a linebacker"], 0,
                     "With every defender in man coverage, an all-out blitz has no safety net behind it."),
        QuestionSeed("Which trophy is awarded to the NFC champion?",
                     ["The Lamar Hunt Trophy", "The George Halas Trophy", "The Vince Lombardi Trophy", "The Ed Thorp Memorial Trophy"], 1,
                     "The Halas Trophy goes to the NFC; the AFC champion receives the Lamar Hunt Trophy."),
        QuestionSeed("What is the 'neutral zone'?",
                     ["The space between the sidelines", "The width of the ball at the line of scrimmage", "The end zone", "The area behind the goalposts"], 1,
                     "It is only as wide as the football itself, and only the center may be in it before the snap."),
        QuestionSeed("What does a 'zone blitz' combine?",
                     ["Man coverage and a blitz", "Zone coverage with unexpected rushers", "Two safeties blitzing", "A blitz on special teams"], 1,
                     "A lineman drops into coverage while a linebacker or defensive back rushes instead."),
        QuestionSeed("During the normal coach-challenge window, when must the challenge flag be thrown?",
                     ["Before the next snap", "Before the end of the quarter", "Any time in the same half", "Only during a timeout"], 0,
                     "A coach must challenge before the next snap. In the final two minutes and overtime, reviews are initiated by the replay official instead."),
        QuestionSeed("What is 'the Immaculate Reception' remembered as?",
                     ["A famous deflected catch by Franco Harris", "A record punt return", "A special-teams play that blocked a potential game-winning field goal", "A safety scored on the final play to decide a championship game"], 0,
                     "The 1972 playoff play remains one of the most debated in league history."),
        QuestionSeed("What is the term for a defensive back who covers the slot receiver?",
                     ["Nickelback", "Edge rusher", "Mike linebacker", "Strong safety"], 0,
                     "The nickelback enters as the fifth defensive back to match an extra receiver."),
        QuestionSeed("What is a football 'Hail Mary' named for?",
                     ["A prayer, describing a desperate long pass", "A former coach named Mary who was believed to have popularized the play", "A Texas stadium where desperate long passes were first attempted", "The Marist College offense"], 0,
                     "The religious phrase appeared in football earlier, but Roger Staubach's comment after a 1975 playoff game popularized its modern passing meaning."),
        QuestionSeed("What is an 'eligible receiver' determined by?",
                     ["Jersey number and position on the line", "Height", "Seniority", "Coach's designation only"], 0,
                     "Numbering rules and whether a player is on the end of the line or in the backfield decide eligibility."),
        QuestionSeed("Where does the quarterback align in a pistol formation?",
                     ["A few yards behind centre with a running back directly behind", "Directly under centre with one running back aligned on either side", "At wide receiver while another offensive player receives the snap", "Seven yards behind centre with no running back anywhere behind"], 0,
                     "The pistol combines some downhill running angles of an under-centre offence with shotgun-style space."),
        QuestionSeed("Where does a defensive lineman in a three-technique alignment line up?",
                     ["On the outside shoulder of an offensive guard", "Head-up on the centre", "Outside the tight end", "Directly over a wide receiver"], 0,
                     "Technique numbers describe a defender's shade relative to offensive linemen."),
        QuestionSeed("Which linebacker is traditionally called the 'Mike'?",
                     ["The middle linebacker", "The weak-side linebacker", "The strong-side linebacker", "The edge cornerback"], 0,
                     "Traditional terminology labels the middle, strong-side, and weak-side linebackers Mike, Sam, and Will."),
        QuestionSeed("What is the core of the passing concept called 'mesh'?",
                     ["Two shallow crossing routes that pass close together", "Four receivers running vertically to stretch every deep defender", "A running back screen", "A fade route paired with a slant"], 0,
                     "The intersecting routes create traffic for man defenders and settle into open areas against zone coverage."),
        QuestionSeed("What distinguishes Tampa 2 from a basic Cover 2 zone?",
                     ["The middle linebacker carries deep down the centre", "Both outside cornerbacks rushing the passer from opposite edges", "One safety rotating to the deep middle while the other moves underneath", "Every eligible receiver being covered by one assigned defender"], 0,
                     "The linebacker's deep drop helps close the vulnerable seam between the two high safeties."),
        QuestionSeed("Where is the A-gap on the offensive line?",
                     ["Between the centre and a guard", "Between a guard and tackle", "Outside the tight end", "Between two wide receivers"], 0,
                     "There is an A-gap on each side of the centre; the next gaps outward are B and C."),
        QuestionSeed("What is a trap block designed to do?",
                     ["Let a defender penetrate before a blocker strikes from the side", "Hold two defenders at once", "Block only defensive backs", "A coverage player being directed toward the sideline during a punt"], 0,
                     "The apparent opening invites the target upfield while a pulling lineman attacks from an unexpected angle."),
        QuestionSeed("What does an edge defender's 'contain' responsibility mean?",
                     ["Preventing the ball carrier from escaping outside", "Covering the deepest receiver", "Forcing every play toward the sideline", "Guarding the centre of the end zone"], 0,
                     "Maintaining outside leverage turns the runner back toward pursuing teammates."),
        QuestionSeed("What is a pooch punt?",
                     ["A deliberately short, high punt intended to limit a return", "A punt kicked after crossing the line", "A punt returned for a touchdown", "A low, bouncing kickoff deliberately driven along the surface of the field"], 0,
                     "It sacrifices distance for placement and hang time, often when a full punt might reach the end zone."),
        QuestionSeed("What is a 'robber' defender assigned to do in pass coverage?",
                     ["Read the quarterback and jump routes in an intermediate zone", "Rush from the edge on every play", "Cover the deepest half of the field", "Follow the running back in man coverage only"], 0,
                     "A robber often lurks beneath deeper coverage, looking to undercut crossing or in-breaking routes."),
    ]
}
