import Foundation

enum FootballQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("How many points is a touchdown worth?",
                     ["3", "6", "7", "8"], 1,
                     "A touchdown is worth six points. The try that follows it is a separate play."),
        QuestionSeed("How many players from one team are on the field during a play?",
                     ["9", "10", "11", "12"], 2,
                     "Each team lines up eleven players. Having twelve on the field draws a penalty."),
        QuestionSeed("What is the NFL championship game called?",
                     ["The Rose Bowl", "The Super Bowl", "The World Series", "The Stanley Cup"], 1,
                     "The Super Bowl became the NFL's championship game after the AFL–NFL merger took full effect in 1970."),
        QuestionSeed("How many yards must an offense gain to earn a new set of downs?",
                     ["5", "8", "10", "15"], 2,
                     "Ten yards resets the down counter, which is why the chains measure exactly that distance."),
        QuestionSeed("Which position usually throws the ball?",
                     ["Quarterback", "Center", "Safety", "Placekicker"], 0,
                     "The quarterback takes the snap and is the primary passer on almost every offense."),
        QuestionSeed("How many points is a field goal worth?",
                     ["1", "2", "3", "6"], 2,
                     "Kicking the ball through the uprights from scrimmage scores three points."),
        QuestionSeed("How many quarters are in a regulation game?",
                     ["2", "3", "4", "5"], 2,
                     "Four quarters make up regulation. A tie at the end sends the game to overtime."),
        QuestionSeed("Which player snaps the ball to start a play?",
                     ["The center", "The tight end", "The cornerback", "The punter"], 0,
                     "The center is the interior lineman who puts the ball in play on every snap."),
        QuestionSeed("What is it called when the quarterback is tackled behind the line of scrimmage?",
                     ["An interception", "A sack", "A fumble", "A huddle"], 1,
                     "A sack costs the offense yardage and counts against its passing total."),
        QuestionSeed("How long is an NFL field between the two goal lines?",
                     ["80 yards", "90 yards", "100 yards", "120 yards"], 2,
                     "The field of play is 100 yards. Each end zone adds another ten."),
        QuestionSeed("How many points is a safety worth?",
                     ["1", "2", "3", "6"], 1,
                     "A safety is worth two points, and the scoring team also receives the ball on a free kick."),
        QuestionSeed("Which unit tries to stop the opposing offense?",
                     ["The defense", "Special teams", "The practice squad", "The officiating crew"], 0,
                     "The defense takes the field whenever the other team has possession."),
        QuestionSeed("How deep is each end zone?",
                     ["5 yards", "10 yards", "15 yards", "20 yards"], 1,
                     "Both end zones are ten yards deep, making the full field 120 yards end to end."),
        QuestionSeed("How many downs does an offense normally get to gain ten yards?",
                     ["Two", "Three", "Four", "Five"], 2,
                     "Four downs. Teams usually punt on fourth down rather than risk turning the ball over."),
        QuestionSeed("How many points is a successful extra-point kick worth?",
                     ["1", "2", "3", "6"], 0,
                     "The kicked try adds a single point, which is why a touchdown drive often totals seven."),
        QuestionSeed("What is it called when a defender catches a pass intended for the offense?",
                     ["A reception", "An interception", "A completion", "A touchback"], 1,
                     "An interception is an immediate change of possession, and the defender may return it."),
        QuestionSeed("What is the long-standing nickname for the football itself?",
                     ["The pigskin", "The rock", "The apple", "The oval"], 0,
                     "The nickname survives from an era of animal-bladder balls, though modern footballs are cowhide."),
        QuestionSeed("What does it mean to defer after winning the opening coin toss?",
                     ["Choose first at the start of the second half", "Give up all kickoff choices", "Start the game with a penalty", "Let the referee choose both goals"], 0,
                     "A team that defers postpones its first choice until the second half; the opponent chooses first for the opening kickoff."),
        QuestionSeed("Which specialist kicks field goals and extra points?",
                     ["The placekicker", "The long snapper", "The fullback", "The nose tackle"], 0,
                     "The placekicker handles kicks from a hold; the punter is a separate specialist."),
        QuestionSeed("What is it called when a ball carrier loses the ball before being downed?",
                     ["An incompletion", "A fumble", "A sack", "A safety"], 1,
                     "A fumble is a live ball, so either team can recover it."),
        QuestionSeed("Halftime comes after which quarter?",
                     ["The first", "The second", "The third", "The fourth"], 1,
                     "The game breaks at the midpoint, after two quarters."),
        QuestionSeed("How many points is a two-point conversion worth?",
                     ["1", "2", "3", "6"], 1,
                     "Instead of kicking, the offense runs one play from close range for two points."),
        QuestionSeed("What is the imaginary line where each play begins called?",
                     ["The goal line", "The line of scrimmage", "The sideline", "The hash mark"], 1,
                     "Neither team may cross the line of scrimmage before the snap."),
        QuestionSeed("What does an official throwing a yellow flag indicate?",
                     ["A touchdown", "A penalty", "The end of a quarter", "A timeout"], 1,
                     "The yellow flag marks a foul; the official then announces the penalty and its yardage."),
        QuestionSeed("Which position's main job is catching passes downfield?",
                     ["Wide receiver", "Offensive guard", "Defensive tackle", "Long snapper"], 0,
                     "Wide receivers line up split from the formation and run routes to get open."),
        QuestionSeed("What is the trophy awarded to the Super Bowl winner called?",
                     ["The Vince Lombardi Trophy", "The Commissioner's Cup", "The Halas Trophy", "The Heisman Trophy"], 0,
                     "It is named for the coach whose Green Bay teams won the first two Super Bowls."),
        QuestionSeed("What is the area inside the opponent's 20-yard line commonly called?",
                     ["The red zone", "The paint", "The crease", "The pocket"], 0,
                     "Red-zone efficiency measures how often a team turns those trips into touchdowns."),
        QuestionSeed("On which down does a team usually punt?",
                     ["First", "Second", "Third", "Fourth"], 3,
                     "Punting on fourth down gives the ball away, but pins the opponent farther from the end zone."),
        QuestionSeed("What is the protected area a quarterback drops back into called?",
                     ["The pocket", "The box", "The gap", "The flat"], 0,
                     "Offensive linemen form the pocket to give the passer time to throw."),
        QuestionSeed("How many teams are in the National Football League?",
                     ["24", "28", "32", "36"], 2,
                     "Thirty-two clubs are split evenly between the AFC and the NFC."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("What is the standard NFL yardage penalty for offensive holding?",
                     ["5 yards", "10 yards", "15 yards", "20 yards"], 1,
                     "Offensive holding normally carries a ten-yard penalty, although enforcement depends on where the foul and play occur."),
        QuestionSeed("What happens on a safety after the two points are awarded?",
                     ["The scoring team kicks off", "The scoring team receives a free kick", "Play restarts at midfield", "The quarter ends"], 1,
                     "The team that was scored upon must free kick the ball back to the team that scored."),
        QuestionSeed("Which award goes to the most outstanding player in U.S. college football?",
                     ["The Heisman Trophy", "The Maxwell Award", "The Butkus Award", "The Outland Trophy"], 0,
                     "The Heisman has been presented annually since 1935."),
        QuestionSeed("What is the offensive formation with the quarterback a few yards behind center called?",
                     ["Under center", "The shotgun", "The wildcat", "The pistol"], 1,
                     "The shotgun gives the passer a head start reading the defense before the rush arrives."),
        QuestionSeed("How long is the play clock in the NFL after the ball is spotted?",
                     ["25 seconds", "30 seconds", "40 seconds", "45 seconds"], 2,
                     "Forty seconds runs from the end of the previous play; a 25-second clock is used after certain stoppages."),
        QuestionSeed("What penalty is called when a defender contacts a receiver illegally before the ball arrives?",
                     ["Illegal formation", "Pass interference", "Encroachment", "Delay of game"], 1,
                     "In the NFL, defensive pass interference is a spot foul, so it can move the ball a long way."),
        QuestionSeed("Which two conferences make up the NFL?",
                     ["East and West", "AFC and NFC", "National and American League", "Premier and Championship"], 1,
                     "The American and National Football Conferences date from the 1970 merger."),
        QuestionSeed("What is a running back's primary responsibility on a handoff?",
                     ["Blocking the edge", "Carrying the ball", "Covering a receiver", "Snapping the ball"], 1,
                     "The back takes the exchange from the quarterback and runs behind his blockers."),
        QuestionSeed("How wide is an NFL field?",
                     ["120 feet", "160 feet", "180 feet", "200 feet"], 1,
                     "A regulation field is 160 feet, or 53 1/3 yards, wide."),
        QuestionSeed("What does a defensive coordinator do?",
                     ["Call defensive plays", "Manage the salary cap", "Coach the kickers", "Handle player contracts"], 0,
                     "The coordinator designs the scheme and signals in the call on each defensive snap."),
        QuestionSeed("What is it called when the defense scores by returning an interception to the end zone?",
                     ["A pick six", "A hat trick", "A grand slam", "A double play"], 0,
                     "The name comes from the six points the return is worth."),
        QuestionSeed("Which position lines up closest to the offensive tackle and can both block and catch?",
                     ["Tight end", "Slot corner", "Free safety", "Fullback"], 0,
                     "The tight end is a hybrid: an extra blocker on running plays and a receiving target on passes."),
        QuestionSeed("What is the foul when a defensive player crosses the line of scrimmage before the snap?",
                     ["Holding", "Offside", "Clipping", "Tripping"], 1,
                     "NFL defensive offside is normally a live-ball five-yard foul, so the offense may sometimes choose the result of the play instead."),
        QuestionSeed("How many officials work a standard NFL game?",
                     ["Three", "Five", "Seven", "Nine"], 2,
                     "Seven officials each have distinct coverage areas and responsibilities."),
        QuestionSeed("What does 'third and long' describe?",
                     ["A long field goal attempt", "Third down with many yards still needed", "The third quarter", "A long kickoff return"], 1,
                     "It is a passing situation, so defenses often bring extra pass rushers."),
        QuestionSeed("Which team plays its home games at Lambeau Field?",
                     ["Chicago Bears", "Green Bay Packers", "Minnesota Vikings", "Detroit Lions"], 1,
                     "Lambeau Field has been the Packers' home since 1957."),
        QuestionSeed("Which pass play invites the rush before throwing short to a receiver behind blockers?",
                     ["A screen", "A post", "A slant", "A fade"], 0,
                     "On a designed screen, blockers release into space ahead of the receiver; merely catching a pass behind the line does not make it a screen."),
        QuestionSeed("What is the maximum NFL game-day Active List size when at least eight offensive linemen are active?",
                     ["46 players", "47 players", "48 players", "53 players"], 2,
                     "The game-day Active List may contain forty-eight players when eight offensive linemen are active; otherwise the limit is forty-seven."),
        QuestionSeed("What kickoff is deliberately shortened because the kicking team hopes to recover it?",
                     ["A squib kick", "An onside kick", "A fair catch", "A touchback"], 1,
                     "An onside kick sacrifices distance to give the kicking team a chance to recover and retain possession."),
        QuestionSeed("If a kickoff goes through the end zone untouched, what is the result?",
                     ["A safety", "A touchback", "A first down at midfield", "A replay of the kick"], 1,
                     "A touchback spots the ball at a fixed yard line rather than where it stopped."),
        QuestionSeed("What is the defensive alignment with four linemen and three linebackers called?",
                     ["The 3-4", "The 4-3", "The nickel", "The dime"], 1,
                     "The numbers count linemen first, then linebackers."),
        QuestionSeed("What does the term 'audible' mean?",
                     ["A crowd noise penalty", "Changing the play at the line", "A referee's announcement", "A timeout call"], 1,
                     "The quarterback reads the defense and calls a different play before the snap."),
        QuestionSeed("What is the maximum number of timeouts a team gets per half?",
                     ["One", "Two", "Three", "Four"], 2,
                     "Three per half, and they do not carry over from the first half to the second."),
        QuestionSeed("Which position is responsible for delivering the ball on punts and field goals?",
                     ["The long snapper", "The holder", "The gunner", "The upback"], 0,
                     "The long snapper makes a much longer and more difficult snap than the center does."),
        QuestionSeed("What is 'clock management' primarily about?",
                     ["Scheduling practices", "Using time strategically late in a half", "Timing the play clock", "Setting the halftime length"], 1,
                     "Spiking the ball, running out of bounds, and calling timeouts all bend the game clock."),
        QuestionSeed("How far back are the goalposts from the goal line in the NFL?",
                     ["At the goal line", "At the back of the end zone", "Ten yards behind the end zone", "On the sideline"], 1,
                     "The posts sit on the end line, so a 20-yard field goal is really a 37-yard kick."),
        QuestionSeed("What is the annual event where teams select new college players called?",
                     ["The Combine", "The Draft", "Free agency", "The Senior Bowl"], 1,
                     "The draft order is generally the reverse of the previous season's standings."),
        QuestionSeed("What is a 'blitz'?",
                     ["A long touchdown pass", "Sending extra rushers at the quarterback", "A no-huddle offense", "A quick kick"], 1,
                     "Blitzing trades coverage defenders for pressure, so it is a calculated risk."),
        QuestionSeed("What does 'special teams' refer to?",
                     ["The units on kicks and punts", "The injured reserve list", "The coaching staff", "The starting offense"], 0,
                     "Special teams handle kickoffs, punts, field goals, and the returns of each."),
        QuestionSeed("Which league merged with the NFL in 1970?",
                     ["The AFL", "The USFL", "The XFL", "The CFL"], 0,
                     "The American Football League's ten clubs joined, creating the AFC and NFC structure."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("In what year was the first AFL–NFL World Championship Game played?",
                     ["1963", "1967", "1970", "1975"], 1,
                     "It was played in January 1967 following the 1966 season and was retroactively named Super Bowl I."),
        QuestionSeed("What is the 'tuck rule' historically associated with?",
                     ["Kickoff placement", "Whether a quarterback's motion is a pass or a fumble", "Helmet fitting", "Uniform length"], 1,
                     "The rule governed when a passer's arm motion ended; the NFL repealed it in 2013."),
        QuestionSeed("How many players may be in motion at the snap in the NFL?",
                     ["None", "One", "Two", "Any number"], 1,
                     "Only one offensive player may be moving, and not toward the line of scrimmage."),
        QuestionSeed("Which team was the first to complete a perfect season including the Super Bowl?",
                     ["1972 Miami Dolphins", "1985 Chicago Bears", "2007 New England Patriots", "1978 Pittsburgh Steelers"], 0,
                     "Miami finished 17-0. New England went 18-0 in 2007 before losing the Super Bowl."),
        QuestionSeed("What is an 'illegal formation' penalty usually caused by?",
                     ["Too few players on the line of scrimmage", "A late snap", "An uncovered kicker", "A missed huddle"], 0,
                     "The offense must have at least seven players on the line at the snap."),
        QuestionSeed("What does the acronym 'PAT' stand for?",
                     ["Pass Attempt Total", "Point After Touchdown", "Play Action Throw", "Punt And Tackle"], 1,
                     "The point after touchdown can be attempted as a kick or as a two-point play."),
        QuestionSeed("Which position group does the term 'the trenches' refer to?",
                     ["Receivers and cornerbacks", "Offensive and defensive linemen", "Kickers and punters", "Safeties and linebackers"], 1,
                     "The phrase describes the close-quarters blocking battle at the line of scrimmage."),
        QuestionSeed("How is a muffed punt different from a fumble?",
                     ["It cannot be recovered", "The returner never established possession", "It happens only in overtime", "It automatically scores two points"], 1,
                     "A muff occurs before possession is established. Either team may recover it; the receiving team may advance its recovery, while the kicking team generally may not advance a recovered scrimmage kick."),
        QuestionSeed("What is the 'Cover 2' defense named for?",
                     ["Two down linemen", "Two deep safeties", "Two-point conversions", "Second-down calls"], 1,
                     "Two safeties split the deep field in half, with corners handling the flats underneath."),
        QuestionSeed("What is 'intentional grounding'?",
                     ["Spiking to stop the clock", "Throwing away a pass under pressure with no eligible receiver nearby", "Kneeling to end a game", "A blocked field goal"], 1,
                     "It costs a loss of down and yardage, though a passer outside the pocket has more latitude."),
        QuestionSeed("What is the maximum length of an NFL overtime period in the regular season?",
                     ["5 minutes", "10 minutes", "15 minutes", "Until someone scores"], 1,
                     "Regular-season overtime runs ten minutes and can end in a tie; playoff overtime continues until a winner emerges."),
        QuestionSeed("Which defensive scheme uses five defensive backs?",
                     ["Nickel", "Dime", "Quarter", "Prevent"], 0,
                     "Nickel adds a fifth defensive back; dime adds a sixth."),
        QuestionSeed("What is the term for an offensive lineman pulling across the formation to block?",
                     ["Chipping", "Pulling", "Stunting", "Shading"], 1,
                     "A pulling guard leaves his gap and leads the play around the edge."),
        QuestionSeed("Where is the Pro Football Hall of Fame located?",
                     ["Canton, Ohio", "Springfield, Massachusetts", "Cooperstown, New York", "Chicago, Illinois"], 0,
                     "Canton hosted the 1920 meeting where the league that became the NFL was organized."),
        QuestionSeed("What is a 'safety' as a position responsible for?",
                     ["Snapping on punts", "Playing the deepest part of the defense", "Blocking the edge rusher", "Kicking off"], 1,
                     "Free and strong safeties are the last line of defense against deep passes and long runs."),
        QuestionSeed("What does the 'West Coast offense' emphasize?",
                     ["Deep vertical throws", "Short, timing-based passes", "Running the ball almost exclusively", "Frequent onside kicks"], 1,
                     "Short high-percentage throws function as an extension of the running game."),
        QuestionSeed("How many points did the highest-scoring team in a single NFL game record?",
                     ["52", "62", "72", "82"], 2,
                     "Washington scored 72 against the New York Giants in 1966."),
        QuestionSeed("What is a 'chip block'?",
                     ["A block by a back or tight end before releasing into a route", "A block below the waist", "A block on special teams", "An illegal block from behind"], 0,
                     "The brief contact slows an edge rusher without committing the blocker to full protection."),
        QuestionSeed("What does 'RPO' stand for in modern offensive terminology?",
                     ["Run Pass Option", "Receiver Pull Out", "Rush Protection Order", "Return Play Option"], 0,
                     "The quarterback reads a defender after the snap and decides whether to hand off or throw."),
        QuestionSeed("Which penalty carries the largest standard yardage in the NFL?",
                     ["False start", "Holding", "Roughing the passer", "Delay of game"], 2,
                     "Roughing the passer is a fifteen-yard personal foul and an automatic first down."),
        QuestionSeed("What is the 'franchise tag'?",
                     ["A jersey patch", "A one-year contract designation for a pending free agent", "A stadium naming right", "A draft pick trade"], 1,
                     "It keeps a player under contract for a season at a salary tied to the top players at his position."),
        QuestionSeed("What is 'Cover 0'?",
                     ["Man coverage with no deep safety help", "A prevent defense", "A goal-line stand", "A zone blitz"], 0,
                     "With every defender in man coverage, an all-out blitz has no safety net behind it."),
        QuestionSeed("Which trophy is awarded to the NFC champion?",
                     ["The Lamar Hunt Trophy", "The George Halas Trophy", "The Vince Lombardi Trophy", "The Ed Thorp Memorial Trophy"], 1,
                     "The Halas Trophy goes to the NFC; the AFC champion receives the Lamar Hunt Trophy."),
        QuestionSeed("What is the 'neutral zone'?",
                     ["The space between the sidelines", "The width of the ball at the line of scrimmage", "The end zone", "The area behind the goalposts"], 1,
                     "It is only as wide as the football itself, and only the center may be in it before the snap."),
        QuestionSeed("What does a 'zone blitz' combine?",
                     ["Man coverage and a blitz", "Zone coverage with unexpected rushers", "Two safeties blitzing", "A blitz on special teams"], 1,
                     "A lineman drops into coverage while a linebacker or defensive back rushes instead."),
        QuestionSeed("During the normal coach-challenge window, when must the challenge flag be thrown?",
                     ["Before the next snap", "Before the end of the quarter", "Any time in the same half", "Only during a timeout"], 0,
                     "A coach must challenge before the next snap. In the final two minutes and overtime, reviews are initiated by the replay official instead."),
        QuestionSeed("What is 'the Immaculate Reception' remembered as?",
                     ["A famous deflected catch by Franco Harris", "A record punt return", "A blocked field goal", "A last-second safety"], 0,
                     "The 1972 playoff play remains one of the most debated in league history."),
        QuestionSeed("What is the term for a defensive back who covers the slot receiver?",
                     ["Nickelback", "Edge rusher", "Mike linebacker", "Strong safety"], 0,
                     "The nickelback enters as the fifth defensive back to match an extra receiver."),
        QuestionSeed("What is a football 'Hail Mary' named for?",
                     ["A prayer, describing a desperate long pass", "A coach named Mary", "A stadium in Texas", "The Marist College offense"], 0,
                     "The religious phrase appeared in football earlier, but Roger Staubach's comment after a 1975 playoff game popularized its modern passing meaning."),
        QuestionSeed("What is an 'eligible receiver' determined by?",
                     ["Jersey number and position on the line", "Height", "Seniority", "Coach's designation only"], 0,
                     "Numbering rules and whether a player is on the end of the line or in the backfield decide eligibility."),
    ]
}
