import Foundation

enum GeographyQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("What is the capital of France?",
                     ["Lyon", "Marseille", "Paris", "Nice"], 2,
                     "Paris is France's political and cultural center and has served as the country's enduring capital since the late Middle Ages."),
        QuestionSeed("Which is the largest ocean on Earth?",
                     ["Atlantic", "Indian", "Arctic", "Pacific"], 3,
                     "The Pacific covers about a third of Earth's surface."),
        QuestionSeed("Which continent is Egypt mostly located on?",
                     ["Asia", "Africa", "Europe", "Oceania"], 1,
                     "The Sinai Peninsula lies in Asia, but most of Egypt is African."),
        QuestionSeed("What is the longest river in South America?",
                     ["The Paraná", "The Amazon", "The Orinoco", "The Magdalena"], 1,
                     "The Amazon also carries more water than any other river on Earth."),
        QuestionSeed("Which country is home to the Eiffel Tower?",
                     ["Italy", "Spain", "France", "Belgium"], 2,
                     "It was built for the 1889 World's Fair in Paris."),
        QuestionSeed("What is the largest country by land area?",
                     ["Canada", "China", "Russia", "United States"], 2,
                     "Russia spans eleven time zones and two continents."),
        QuestionSeed("Which desert is the largest hot desert in the world?",
                     ["The Gobi", "The Sahara", "The Kalahari", "The Atacama"], 1,
                     "The Sahara covers much of North Africa, roughly the size of the United States."),
        QuestionSeed("Mount Everest lies on the border of Nepal and which country?",
                     ["India", "China", "Bhutan", "Pakistan"], 1,
                     "The northern side sits in the Tibet Autonomous Region of China."),
        QuestionSeed("Which country has the most people?",
                     ["China", "India", "United States", "Indonesia"], 1,
                     "India passed China as the most populous country in 2023."),
        QuestionSeed("What is the capital of Japan?",
                     ["Osaka", "Kyoto", "Tokyo", "Nagoya"], 2,
                     "Kyoto was the imperial capital until 1868, when the court moved to Tokyo."),
        QuestionSeed("Which continent is the coldest?",
                     ["Europe", "Asia", "Antarctica", "North America"], 2,
                     "Antarctica holds the record for the lowest natural temperature ever measured."),
        QuestionSeed("Which sea separates Europe from Africa?",
                     ["The Black Sea", "The Mediterranean Sea", "The Baltic Sea", "The Red Sea"], 1,
                     "The Strait of Gibraltar is only about nine miles wide at its narrowest."),
        QuestionSeed("Which country is shaped like a boot?",
                     ["Greece", "Italy", "Portugal", "Croatia"], 1,
                     "Sicily sits just off the toe of the Italian peninsula."),
        QuestionSeed("What is the capital of Canada?",
                     ["Toronto", "Vancouver", "Ottawa", "Montreal"], 2,
                     "Ottawa was chosen in 1857 as a compromise between competing cities."),
        QuestionSeed("Which US state is the largest by area?",
                     ["Texas", "California", "Alaska", "Montana"], 2,
                     "Alaska is more than twice the size of Texas."),
        QuestionSeed("Which mountain range separates France and Spain?",
                     ["The Alps", "The Pyrenees", "The Apennines", "The Carpathians"], 1,
                     "Andorra sits high in the Pyrenees between the two countries."),
        QuestionSeed("What is the capital of Australia?",
                     ["Sydney", "Melbourne", "Canberra", "Perth"], 2,
                     "Canberra was purpose-built as a compromise between Sydney and Melbourne."),
        QuestionSeed("Which is the smallest continent?",
                     ["Europe", "Antarctica", "South America", "Australia"], 3,
                     "Australia is sometimes grouped with nearby islands as Oceania."),
        QuestionSeed("Which river flows through London?",
                     ["The Seine", "The Thames", "The Rhine", "The Danube"], 1,
                     "The Thames is tidal through London and rises and falls several metres."),
        QuestionSeed("Which country contains the Amazon rainforest's largest share?",
                     ["Peru", "Colombia", "Brazil", "Venezuela"], 2,
                     "Roughly sixty percent of the rainforest lies within Brazil."),
        QuestionSeed("What is the capital of Italy?",
                     ["Milan", "Rome", "Naples", "Turin"], 1,
                     "Vatican City is an independent state entirely within Rome."),
        QuestionSeed("Which imaginary line divides Earth into northern and southern halves?",
                     ["The prime meridian", "The equator", "The Tropic of Cancer", "The international date line"], 1,
                     "The equator sits at zero degrees latitude."),
        QuestionSeed("Which country is known as the Land of the Rising Sun?",
                     ["China", "Japan", "South Korea", "Thailand"], 1,
                     "The name reflects Japan's position east of the Asian mainland."),
        QuestionSeed("What is the largest island in the world?",
                     ["Madagascar", "Borneo", "Greenland", "New Guinea"], 2,
                     "Australia is larger but is classed as a continental landmass."),
        QuestionSeed("Which two countries share the longest international border?",
                     ["United States and Mexico", "Canada and United States", "Russia and China", "Argentina and Chile"], 1,
                     "The Canada-United States border runs about 5,525 miles including Alaska."),
        QuestionSeed("Which ocean lies east of the United States?",
                     ["Pacific", "Atlantic", "Indian", "Arctic"], 1,
                     "The Pacific lies to the west."),
        QuestionSeed("What is the capital of Germany?",
                     ["Munich", "Hamburg", "Berlin", "Frankfurt"], 2,
                     "Bonn served as the West German capital until reunification."),
        QuestionSeed("Which country contains more lake area than any other?",
                     ["Russia", "Canada", "Finland", "United States"], 1,
                     "Canada contains more total lake area than any other country and holds a large share of the world's fresh surface water."),
        QuestionSeed("Which continent has the most countries?",
                     ["Asia", "Africa", "Europe", "South America"], 1,
                     "Africa has fifty-four internationally recognized sovereign states."),
        QuestionSeed("Which US city is known as the Windy City?",
                     ["New York", "Chicago", "Boston", "Detroit"], 1,
                     "The nickname's origin is debated but has been attached to Chicago since the 1800s."),
        QuestionSeed("What is the capital of Spain?",
                     ["Barcelona", "Madrid", "Seville", "Valencia"], 1,
                     "Madrid lies near the geographic centre of mainland Spain."),
        QuestionSeed("What is the capital of Mexico?",
                     ["Guadalajara", "Monterrey", "Mexico City", "Cancún"], 2,
                     "Mexico City was built around the site of the Aztec capital Tenochtitlan."),
        QuestionSeed("Which river flows through Paris?",
                     ["The Seine", "The Rhône", "The Loire", "The Rhine"], 0,
                     "The Seine divides central Paris into the Left Bank and Right Bank."),
        QuestionSeed("What is the capital of South Korea?",
                     ["Busan", "Seoul", "Incheon", "Daegu"], 1,
                     "Seoul stands on the Han River in the northwest of the country."),
        QuestionSeed("What is the capital of India?",
                     ["Mumbai", "Kolkata", "New Delhi", "Bengaluru"], 2,
                     "New Delhi forms part of the larger National Capital Territory of Delhi."),
        QuestionSeed("Which ocean lies between Africa, Asia, and Australia?",
                     ["The Atlantic Ocean", "The Pacific Ocean", "The Indian Ocean", "The Arctic Ocean"], 2,
                     "The Indian Ocean is bounded by Africa to the west and Australia to the east."),
        QuestionSeed("On which continent are the Alps located?",
                     ["Europe", "Asia", "North America", "South America"], 0,
                     "The mountain chain arcs across eight European countries."),
        QuestionSeed("The Great Lakes form part of the border between the United States and which country?",
                     ["Mexico", "Canada", "Russia", "Greenland"], 1,
                     "Four of the five Great Lakes straddle the international boundary; Lake Michigan lies entirely within the United States."),
        QuestionSeed("On which continent is Brazil located?",
                     ["Africa", "South America", "North America", "Asia"], 1,
                     "Brazil occupies nearly half of South America's land area."),
        QuestionSeed("Mount Fuji is located in which country?",
                     ["China", "Japan", "South Korea", "Indonesia"], 1,
                     "The symmetrical volcano rises west of Tokyo and is Japan's highest mountain."),
        QuestionSeed("What is the capital of Greece?",
                     ["Athens", "Thessaloniki", "Sparta", "Crete"], 0,
                     "Athens has been Greece's capital since 1834 and still centers on the ancient Acropolis."),
        QuestionSeed("What is the capital of Thailand?",
                     ["Bangkok", "Chiang Mai", "Phuket", "Hanoi"], 0,
                     "Bangkok sits on the Chao Phraya River and is Thailand's largest city and capital."),
        QuestionSeed("Which river is the longest in Africa?",
                     ["The Nile", "The Congo", "The Niger", "The Zambezi"], 0,
                     "The Nile runs north through northeast Africa into the Mediterranean, the continent's longest river."),
        QuestionSeed("Which mountain range separates Europe from Asia?",
                     ["The Urals", "The Alps", "The Andes", "The Carpathians"], 0,
                     "The Urals run north to south and mark the traditional border of Europe and Asia."),
        QuestionSeed("How many continents are usually counted?",
                     ["Seven", "Five", "Six", "Eight"], 0,
                     "Most English-language teaching counts seven continents, from Africa and Asia through to South America."),
        QuestionSeed("Which ocean is the smallest?",
                     ["The Arctic Ocean", "The Southern Ocean", "The Indian Ocean", "The Atlantic Ocean"], 0,
                     "The Arctic Ocean is the smallest and shallowest, covered by sea ice for much of the year."),
        QuestionSeed("Which mountain is the highest in Africa?",
                     ["Mount Kilimanjaro", "Mount Kenya", "Mount Elgon", "The Rwenzori Mountains"], 0,
                     "Mount Kilimanjaro rises about 5,895 meters in Tanzania, the highest free-standing mountain in Africa."),
        QuestionSeed("What is the capital of Kenya?",
                     ["Nairobi", "Mombasa", "Kisumu", "Nakuru"], 0,
                     "Nairobi grew from a railway depot into Kenya's capital and largest city."),
        QuestionSeed("Which country is famous for the fjords along its western coast?",
                     ["Norway", "Sweden", "Denmark", "Finland"], 0,
                     "Norway's western coast is cut by deep glacial fjords such as the Sognefjord and Geirangerfjord."),
        QuestionSeed("Which US state is made up entirely of islands?",
                     ["Hawaii", "Alaska", "Rhode Island", "Florida"], 0,
                     "Hawaii is the only US state made up entirely of islands, formed by volcanic hotspot activity."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("What is the capital of Turkey?",
                     ["Istanbul", "Ankara", "Izmir", "Bursa"], 1,
                     "Ankara replaced Istanbul as the capital in 1923."),
        QuestionSeed("Which country is landlocked and entirely surrounded by South Africa?",
                     ["Eswatini", "Lesotho", "Botswana", "Zimbabwe"], 1,
                     "Lesotho is one of only three countries entirely enclosed by another."),
        QuestionSeed("Which strait separates Asia from North America?",
                     ["The Bering Strait", "The Strait of Malacca", "The Bosphorus", "The Strait of Hormuz"], 0,
                     "At its narrowest the Bering Strait is about fifty-five miles wide."),
        QuestionSeed("What is the deepest known point in the ocean called?",
                     ["Challenger Deep", "The Mariana Trench", "The Puerto Rico Trench", "Horizon Deep"], 0,
                     "Challenger Deep lies within the Mariana Trench, nearly eleven kilometres below sea level."),
        QuestionSeed("Which African state defeated an Italian invasion at the Battle of Adwa in 1896?",
                     ["Ethiopia", "Ghana", "Kenya", "Senegal"], 0,
                     "Ethiopia's victory at Adwa preserved its independence during most of the Scramble for Africa, although Italy occupied it from 1936 to 1941."),
        QuestionSeed("Which country has the longest coastline?",
                     ["Russia", "Canada", "Indonesia", "Australia"], 1,
                     "Canada's Arctic archipelago accounts for much of its enormous coastline."),
        QuestionSeed("What is the capital of Brazil?",
                     ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], 2,
                     "Brasília was purpose-built inland and became the capital in 1960."),
        QuestionSeed("Which listed body of water is famously about ten times saltier than the ocean?",
                     ["The Dead Sea", "The Red Sea", "The Caspian Sea", "The Black Sea"], 0,
                     "The Dead Sea is extremely saline, although several smaller hypersaline lakes and ponds are saltier."),
        QuestionSeed("Which mountain range runs along the western edge of South America?",
                     ["The Rockies", "The Andes", "The Atlas", "The Urals"], 1,
                     "The Andes is the longest continental mountain range in the world."),
        QuestionSeed("Which country is both in Europe and Asia and has Istanbul on the divide?",
                     ["Greece", "Turkey", "Russia", "Georgia"], 1,
                     "The Bosphorus strait runs through Istanbul, separating the two continents."),
        QuestionSeed("What is the capital of Argentina?",
                     ["Córdoba", "Buenos Aires", "Rosario", "Mendoza"], 1,
                     "Buenos Aires sits on the estuary of the Río de la Plata."),
        QuestionSeed("Which line of longitude is defined as zero degrees?",
                     ["The equator", "The prime meridian", "The date line", "The tropic line"], 1,
                     "It passes through Greenwich in London by international convention."),
        QuestionSeed("Which lake is the main reservoir feeding the White Nile?",
                     ["Lake Chad", "Lake Victoria", "Lake Tanganyika", "Lake Turkana"], 1,
                     "The White Nile leaves Lake Victoria at Jinja in Uganda; its most distant headwaters lie farther south."),
        QuestionSeed("What is the largest freshwater lake by surface area?",
                     ["Lake Baikal", "Lake Superior", "Lake Victoria", "Lake Michigan"], 1,
                     "Lake Baikal holds more water but Lake Superior covers more surface."),
        QuestionSeed("Which country contains the volcanic Sunda Arc, including Krakatau and Mount Merapi?",
                     ["Japan", "Indonesia", "Chile", "Iceland"], 1,
                     "Indonesia lies where several tectonic plates meet and contains many active volcanoes along the Sunda Arc."),
        QuestionSeed("What is the capital of Egypt?",
                     ["Alexandria", "Cairo", "Giza", "Luxor"], 1,
                     "Cairo is the largest city in the Arab world."),
        QuestionSeed("Which peninsula is Spain and Portugal located on?",
                     ["The Balkan Peninsula", "The Iberian Peninsula", "The Apennine Peninsula", "The Anatolian Peninsula"], 1,
                     "Iberia is separated from the rest of Europe by the Pyrenees."),
        QuestionSeed("Which canal connects the Atlantic and Pacific Oceans?",
                     ["The Suez Canal", "The Panama Canal", "The Erie Canal", "The Kiel Canal"], 1,
                     "It opened in 1914 and cuts thousands of miles from the voyage around South America."),
        QuestionSeed("Which country is the only one to occupy an entire continent?",
                     ["Greenland", "Australia", "Madagascar", "Iceland"], 1,
                     "Australia is both a country and a continental landmass."),
        QuestionSeed("What is the highest waterfall in the world?",
                     ["Niagara Falls", "Angel Falls", "Victoria Falls", "Iguazu Falls"], 1,
                     "Angel Falls in Venezuela drops nearly a kilometre."),
        QuestionSeed("Which US state has the most coastline?",
                     ["Florida", "California", "Alaska", "Texas"], 2,
                     "Alaska's coastline exceeds that of all other states combined."),
        QuestionSeed("Which country is Mount Kilimanjaro in?",
                     ["Kenya", "Tanzania", "Uganda", "Ethiopia"], 1,
                     "It is the highest mountain in Africa and a free-standing volcano."),
        QuestionSeed("What is the Sámi cultural region across northern Norway, Sweden, Finland, and Russia called?",
                     ["Sápmi", "Jutland", "Karelia", "Silesia"], 0,
                     "Sápmi is the traditional homeland of the Sámi people and crosses four modern national borders."),
        QuestionSeed("Which body of water lies between Saudi Arabia and Africa?",
                     ["The Persian Gulf", "The Red Sea", "The Arabian Sea", "The Gulf of Aden"], 1,
                     "The Suez Canal connects the Red Sea to the Mediterranean."),
        QuestionSeed("What is the capital of South Africa where the executive branch sits?",
                     ["Cape Town", "Pretoria", "Johannesburg", "Durban"], 1,
                     "South Africa has three capitals: Pretoria, Cape Town, and Bloemfontein."),
        QuestionSeed("Which archipelago is Charles Darwin most associated with?",
                     ["The Galápagos", "The Azores", "The Canaries", "The Maldives"], 0,
                     "His 1835 visit informed his thinking on natural selection."),
        QuestionSeed("Which country is directly south of the United States?",
                     ["Guatemala", "Mexico", "Cuba", "Belize"], 1,
                     "The two countries share a border of about 1,950 miles."),
        QuestionSeed("What is a fjord?",
                     ["A deep glacially carved coastal inlet", "A volcanic crater lake", "A desert basin", "A river delta"], 0,
                     "Norway's coastline is famous for them."),
        QuestionSeed("Which two continents are conventionally divided by the Ural Mountains?",
                     ["Europe and Asia", "Europe and Africa", "Asia and Africa", "Europe and North America"], 0,
                     "The Urals are conventionally taken as the boundary between Europe and Asia."),
        QuestionSeed("Which country's capital is Wellington?",
                     ["Australia", "New Zealand", "Fiji", "Papua New Guinea"], 1,
                     "Auckland is larger, but Wellington has been the capital since 1865."),
        QuestionSeed("What is the capital of Mongolia?",
                     ["Astana", "Ulaanbaatar", "Bishkek", "Tashkent"], 1,
                     "Ulaanbaatar lies in the Tuul River valley and is Mongolia's dominant urban centre."),
        QuestionSeed("Which river flows through Budapest?",
                     ["The Danube", "The Elbe", "The Vistula", "The Dnieper"], 0,
                     "The Danube separates historic Buda on the west bank from Pest on the east bank."),
        QuestionSeed("Salar de Uyuni, the world's largest salt flat, is in which country?",
                     ["Bolivia", "Chile", "Argentina", "Peru"], 0,
                     "The salt crust covers part of a high plateau left by prehistoric lakes."),
        QuestionSeed("The Mediterranean island of Corsica belongs to which country?",
                     ["Italy", "France", "Spain", "Greece"], 1,
                     "The Mediterranean island lies southeast of mainland France and west of Italy."),
        QuestionSeed("What landforms does the Strait of Malacca separate?",
                     ["The Malay Peninsula and Sumatra", "India and Sri Lanka", "Java and Borneo", "Arabia and Africa"], 0,
                     "The narrow route links the Indian Ocean with the South China Sea and is a major shipping corridor."),
        QuestionSeed("Lake Titicaca lies on the border of Peru and which country?",
                     ["Bolivia", "Ecuador", "Chile", "Brazil"], 0,
                     "The high-altitude lake sits in the Andes at more than 3,800 metres above sea level."),
        QuestionSeed("What is the capital of Namibia?",
                     ["Gaborone", "Windhoek", "Lusaka", "Maputo"], 1,
                     "Windhoek is located on Namibia's central plateau."),
        QuestionSeed("The Matterhorn stands on the border between Switzerland and which country?",
                     ["France", "Austria", "Italy", "Germany"], 2,
                     "The mountain rises above Zermatt in Switzerland and Breuil-Cervinia in Italy."),
        QuestionSeed("Which major Southeast Asian river flows from the Tibetan Plateau toward the South China Sea?",
                     ["The Mekong", "The Irrawaddy", "The Salween", "The Chao Phraya"], 0,
                     "The Mekong passes through or along six countries before forming a delta in Vietnam."),
        QuestionSeed("The Cape of Good Hope is in which country?",
                     ["South Africa", "Namibia", "Mozambique", "Madagascar"], 0,
                     "It lies on the Cape Peninsula south of Cape Town, though Cape Agulhas is Africa's southernmost point."),
        QuestionSeed("Which strait separates Europe from Asia at Istanbul?",
                     ["The Bosphorus", "The Dardanelles", "The Strait of Hormuz", "The Strait of Malacca"], 0,
                     "The Bosphorus runs through Istanbul, separating the European and Asian sides of the city."),
        QuestionSeed("Which African country has the largest population?",
                     ["Nigeria", "Ethiopia", "Egypt", "South Africa"], 0,
                     "Nigeria's population passed 200 million, making it Africa's most populous country by a wide margin."),
        QuestionSeed("Which inland sea shrank after Soviet irrigation diverted its rivers?",
                     ["The Aral Sea", "The Caspian Sea", "The Black Sea", "The Azov Sea"], 0,
                     "Diverting the rivers feeding the Aral Sea for cotton left most of its bed dry."),
        QuestionSeed("Which desert is the largest cold desert on Earth?",
                     ["Antarctica", "The Gobi", "Patagonia", "The Great Basin"], 0,
                     "Antarctica is technically the largest desert, receiving very little precipitation each year."),
        QuestionSeed("Which is the largest African country by area?",
                     ["Algeria", "Sudan", "Democratic Republic of the Congo", "Chad"], 0,
                     "Algeria became Africa's largest country by area after South Sudan's independence divided Sudan in 2011."),
        QuestionSeed("Which capital city sits at the highest elevation?",
                     ["La Paz", "Quito", "Kathmandu", "Mexico City"], 0,
                     "La Paz in Bolivia is the highest capital city, sitting above 3,600 meters."),
        QuestionSeed("Which canal links the Mediterranean to the Red Sea?",
                     ["The Suez Canal", "The Kiel Canal", "The Corinth Canal", "The Grand Canal"], 0,
                     "The Suez Canal opened in 1869, cutting the sea route from Europe to Asia dramatically."),
        QuestionSeed("Which mountain range contains K2?",
                     ["The Karakoram", "The Himalayas", "The Hindu Kush", "The Pamirs"], 0,
                     "K2 stands in the Karakoram range on the border between Pakistan and China."),
        QuestionSeed("Which peninsula reaches into the Mediterranean and contains Rome?",
                     ["The Italian Peninsula", "The Balkan Peninsula", "The Anatolian Peninsula", "The Crimean Peninsula"], 0,
                     "The Italian Peninsula reaches southeast into the Mediterranean, carrying Rome, Naples, and the Apennine mountains."),
        QuestionSeed("What is the highest mountain in North America?",
                     ["Denali", "Mount Logan", "Mount Whitney", "Pico de Orizaba"], 0,
                     "Denali in Alaska rises higher than any other peak in North America."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("Which three countries are entirely enclosed by a single other country?",
                     ["Lesotho, San Marino, Vatican City", "Andorra, Monaco, Malta", "Nepal, Bhutan, Laos", "Luxembourg, Liechtenstein, Andorra"], 0,
                     "Lesotho is surrounded by South Africa; San Marino and Vatican City by Italy."),
        QuestionSeed("What is the only sea without a coastline?",
                     ["The Sargasso Sea", "The Coral Sea", "The Barents Sea", "The Timor Sea"], 0,
                     "It is bounded by ocean currents rather than land."),
        QuestionSeed("Which country has the most time zones including its territories?",
                     ["Russia", "France", "United States", "China"], 1,
                     "France's overseas departments and territories spread it across a dozen zones."),
        QuestionSeed("What is a country with no coastline and surrounded only by landlocked countries called?",
                     ["Doubly landlocked", "Sub-continental", "Interior state", "Enclave state"], 0,
                     "Uzbekistan and Liechtenstein are the only two such countries."),
        QuestionSeed("Which line does the international date line roughly follow?",
                     ["180 degrees longitude", "The equator", "The prime meridian", "The Tropic of Capricorn"], 0,
                     "It deviates around territories so that neighbouring islands share a date."),
        QuestionSeed("Which lake holds the largest volume of fresh water?",
                     ["Lake Baikal", "Lake Superior", "Lake Tanganyika", "Lake Victoria"], 0,
                     "Baikal is also the world's deepest lake, at over 1,600 metres."),
        QuestionSeed("What geological feature is the Great Rift Valley?",
                     ["A continental divergence zone in East Africa", "A continuous chain of folded mountains along a plate collision", "A glacial moraine", "A shallow submerged platform bordering the edge of a continent"], 0,
                     "The African plate is slowly splitting along it."),
        QuestionSeed("Which country contains the geographic point farthest from any ocean?",
                     ["China", "Kazakhstan", "Mongolia", "Russia"], 0,
                     "The Eurasian pole of inaccessibility lies in northwestern China."),
        QuestionSeed("What is an exclave?",
                     ["Territory separated from the main country by other states", "An overseas territory located on an island apart from its governing state", "A disputed border zone", "A possession governed politically by a distant imperial power"], 0,
                     "Kaliningrad is a Russian exclave on the Baltic."),
        QuestionSeed("Which desert is the driest non-polar place on Earth?",
                     ["The Atacama", "The Sahara", "The Namib", "The Gobi"], 0,
                     "Some Atacama weather stations have never recorded measurable rainfall."),
        QuestionSeed("Which strait connects the Mediterranean to the Atlantic?",
                     ["The Strait of Gibraltar", "The Dardanelles", "The Strait of Messina", "The Strait of Otranto"], 0,
                     "It separates Spain from Morocco at Europe's southwestern tip."),
        QuestionSeed("Which South American country is more than 4,300 kilometres long but averages only about 177 kilometres wide?",
                     ["Chile", "Brazil", "Peru", "Argentina"], 0,
                     "Chile forms a narrow strip between the Andes and Pacific from the Atacama Desert toward Patagonia."),
        QuestionSeed("What is the name for a ring-shaped coral reef enclosing a lagoon?",
                     ["An atoll", "A cay", "A shoal", "A spit"], 0,
                     "Atolls form as a volcanic island subsides and the surrounding reef keeps growing."),
        QuestionSeed("Which river forms much of the border between the United States and Mexico?",
                     ["The Rio Grande", "The Colorado", "The Pecos", "The Gila"], 0,
                     "Mexico calls it the Río Bravo del Norte."),
        QuestionSeed("What is the Ring of Fire?",
                     ["A belt of volcanoes and earthquakes around the Pacific", "A zone of crustal stretching running through eastern Africa", "A Mediterranean fault line", "A submarine mountain chain extending down the middle of the Atlantic"], 0,
                     "Around three quarters of the world's active volcanoes lie along it."),
        QuestionSeed("Which two countries share the island of Hispaniola?",
                     ["Haiti and the Dominican Republic", "The Republic of Cuba and the Commonwealth of The Bahamas", "Jamaica and the Republic of Trinidad and Tobago", "Saint Kitts and Nevis"], 0,
                     "It is the second-largest island in the Caribbean."),
        QuestionSeed("What is the Sahel?",
                     ["A semi-arid belt south of the Sahara", "A connected chain of high mountains crossing northern Africa", "A network of rivers and drainage basins in central Africa", "A low-lying fertile plain bordering the Atlantic coast of Africa"], 0,
                     "It forms a transition zone between the desert and the savanna."),
        QuestionSeed("Which country has the highest average elevation?",
                     ["Bhutan", "Nepal", "Tajikistan", "Kyrgyzstan"], 0,
                     "Bhutan's mean elevation exceeds three thousand metres."),
        QuestionSeed("What is a 'thalweg' in geography?",
                     ["The line of lowest elevation along a valley or river channel", "The highest line connecting mountain peaks along the divide between drainage basins", "A persistent flow of seawater moving parallel to a nearby shoreline", "The downslope boundary where a moving glacier ends and begins melting"], 0,
                     "It is often used to define river boundaries between states."),
        QuestionSeed("Which sea is technically the world's largest lake?",
                     ["The Caspian Sea", "The Aral Sea", "The Dead Sea", "The Black Sea"], 0,
                     "It is landlocked, though its legal status has been long disputed."),
        QuestionSeed("What is the term for a narrow strip of land connecting two larger landmasses?",
                     ["An isthmus", "A peninsula", "A cape", "A delta"], 0,
                     "The Isthmus of Panama is the best-known example."),
        QuestionSeed("Which country was formerly known as Upper Volta?",
                     ["Burkina Faso", "Guinea-Bissau", "Niger", "Benin"], 0,
                     "The name changed in 1984 and means 'land of upright people'."),
        QuestionSeed("What is orographic rainfall caused by?",
                     ["Air forced upward over mountains", "Warm, moist air rising by convection over a tropical sea", "Warm and cold air masses meeting along a frontal boundary", "Rising air currents produced by a strong urban heat island"], 0,
                     "It produces the wet windward side and the dry rain shadow beyond."),
        QuestionSeed("What is the world's highest and largest plateau?",
                     ["The Tibetan Plateau", "The Altiplano", "The Colorado Plateau", "The Ethiopian Plateau"], 0,
                     "The Tibetan Plateau covers roughly 2.5 million square kilometres at an average elevation above 4,500 metres."),
        QuestionSeed("What is a 'karst' landscape formed by?",
                     ["Dissolution of soluble rock such as limestone", "Glacial scouring", "Volcanic deposition", "Wind carrying away loose sediment exposed at the surface"], 0,
                     "Caves, sinkholes, and underground rivers are characteristic features."),
        QuestionSeed("Lake Assal, the lowest point in Africa, lies in which country?",
                     ["Ethiopia", "Djibouti", "Eritrea", "Somalia"], 1,
                     "Its shore sits about 155 metres below sea level, in the Afar Depression."),
        QuestionSeed("What does 'antipode' mean?",
                     ["The point on Earth's surface diametrically opposite another", "The geographic pole toward which a magnetic compass is aligned", "The greatest northern or southern latitude reached along a route", "The coastal location experiencing the maximum height of a tide"], 0,
                     "Most land antipodes fall in the ocean, because land is unevenly distributed."),
        QuestionSeed("Which African lake is shared by Kenya, Uganda, and Tanzania?",
                     ["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Turkana"], 0,
                     "It is Africa's largest lake by surface area."),
        QuestionSeed("What is a 'graben' in geology?",
                     ["A block of crust dropped between two faults", "A resistant magma body exposed after the surrounding rock erodes", "A fan-shaped sediment deposit where a stream leaves a mountain valley", "A former shoreline raised above the present level of the sea"], 0,
                     "The raised block on either side is called a horst."),
        QuestionSeed("Which two seas does the Bosphorus connect?",
                     ["The Black Sea and the Sea of Marmara", "The Aegean and the Ionian", "The Red Sea and the Gulf of Aden", "The Baltic and the North Sea"], 0,
                     "The Dardanelles then links the Marmara to the Aegean."),
        QuestionSeed("What is the capital of Burkina Faso?",
                     ["Ouagadougou", "Bamako", "Niamey", "Lomé"], 0,
                     "Ouagadougou became the capital of French Upper Volta and remained the capital after independence."),
        QuestionSeed("The Drakensberg mountain range runs mainly through South Africa and which country?",
                     ["Lesotho", "Botswana", "Zimbabwe", "Eswatini"], 0,
                     "Lesotho's highlands form part of the range, whose name means Dragon Mountains in Afrikaans."),
        QuestionSeed("Which major river crosses the equator twice?",
                     ["The Congo", "The Nile", "The Niger", "The Zambezi"], 0,
                     "The Congo's broad arc carries it across the equator northward and later southward."),
        QuestionSeed("Nakhchivan is an exclave of which country?",
                     ["Azerbaijan", "Armenia", "Georgia", "Iran"], 0,
                     "Armenian territory separates Nakhchivan from the rest of Azerbaijan."),
        QuestionSeed("The Wakhan Corridor is a narrow eastern extension of which country?",
                     ["Afghanistan", "Pakistan", "Tajikistan", "Kyrgyzstan"], 0,
                     "The corridor reaches toward China between Tajikistan and Pakistan."),
        QuestionSeed("The Okavango forms a vast inland delta in which country?",
                     ["Botswana", "Angola", "Zambia", "Namibia"], 0,
                     "Instead of reaching the sea, its water spreads into wetlands in the Kalahari Basin."),
        QuestionSeed("Which two countries contain most of the high plateau called the Altiplano?",
                     ["Bolivia and Peru", "Chile and Argentina", "Ecuador and Colombia", "Brazil and Paraguay"], 0,
                     "The Altiplano lies between eastern and western ranges of the central Andes."),
        QuestionSeed("What bodies of water does the Bab-el-Mandeb strait connect?",
                     ["The Red Sea and the Gulf of Aden", "The Persian Gulf and the Arabian Sea", "The Black Sea and the Mediterranean", "The Baltic Sea and the North Sea"], 0,
                     "The strait narrows the sea route between the Indian Ocean and the Suez Canal."),
        QuestionSeed("The Caprivi Strip is a narrow extension of which country?",
                     ["Namibia", "Botswana", "Angola", "Zambia"], 0,
                     "The corridor was created during German colonial rule to provide access toward the Zambezi River."),
        QuestionSeed("Which countries share the densely populated Fergana Valley?",
                     ["Uzbekistan, Kyrgyzstan, and Tajikistan", "Kazakhstan, Turkmenistan, and Afghanistan", "Iran, Iraq, and Turkey", "India, Nepal, and Bhutan"], 0,
                     "Complex borders divide the Central Asian valley among Uzbekistan, Kyrgyzstan, and Tajikistan."),
    ]
}
