import Foundation

enum GeographyQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("What is the capital of France?",
                     ["Lyon", "Marseille", "Paris", "Nice"], 2,
                     "Paris has been the French capital since the tenth century."),
        QuestionSeed("Which is the largest ocean on Earth?",
                     ["Atlantic", "Indian", "Arctic", "Pacific"], 3,
                     "The Pacific covers about a third of Earth's surface."),
        QuestionSeed("Which continent is Egypt mostly located on?",
                     ["Asia", "Africa", "Europe", "Oceania"], 1,
                     "The Sinai Peninsula lies in Asia, but most of Egypt is African."),
        QuestionSeed("What is the longest river in South America?",
                     ["The Paraná", "The Amazon", "The Orinoco", "The Magdalena"], 1,
                     "The Amazon also carries more water than any other river on Earth."),
        QuestionSeed("Which country is home to the Eiffel Tower?",
                     ["Italy", "Spain", "France", "Belgium"], 2,
                     "It was built for the 1889 World's Fair in Paris."),
        QuestionSeed("What is the largest country by land area?",
                     ["Canada", "China", "Russia", "United States"], 2,
                     "Russia spans eleven time zones and two continents."),
        QuestionSeed("Which desert is the largest hot desert in the world?",
                     ["The Gobi", "The Sahara", "The Kalahari", "The Atacama"], 1,
                     "The Sahara covers much of North Africa, roughly the size of the United States."),
        QuestionSeed("Mount Everest lies on the border of Nepal and which country?",
                     ["India", "China", "Bhutan", "Pakistan"], 1,
                     "The northern side sits in the Tibet Autonomous Region of China."),
        QuestionSeed("Which country has the most people?",
                     ["China", "India", "United States", "Indonesia"], 1,
                     "India passed China as the most populous country in 2023."),
        QuestionSeed("What is the capital of Japan?",
                     ["Osaka", "Kyoto", "Tokyo", "Nagoya"], 2,
                     "Kyoto was the imperial capital until 1868, when the court moved to Tokyo."),
        QuestionSeed("Which continent is the coldest?",
                     ["Europe", "Asia", "Antarctica", "North America"], 2,
                     "Antarctica holds the record for the lowest natural temperature ever measured."),
        QuestionSeed("Which sea separates Europe from Africa?",
                     ["The Black Sea", "The Mediterranean Sea", "The Baltic Sea", "The Red Sea"], 1,
                     "The Strait of Gibraltar is only about nine miles wide at its narrowest."),
        QuestionSeed("Which country is shaped like a boot?",
                     ["Greece", "Italy", "Portugal", "Croatia"], 1,
                     "Sicily sits just off the toe of the Italian peninsula."),
        QuestionSeed("What is the capital of Canada?",
                     ["Toronto", "Vancouver", "Ottawa", "Montreal"], 2,
                     "Ottawa was chosen in 1857 as a compromise between competing cities."),
        QuestionSeed("Which US state is the largest by area?",
                     ["Texas", "California", "Alaska", "Montana"], 2,
                     "Alaska is more than twice the size of Texas."),
        QuestionSeed("Which mountain range separates France and Spain?",
                     ["The Alps", "The Pyrenees", "The Apennines", "The Carpathians"], 1,
                     "Andorra sits high in the Pyrenees between the two countries."),
        QuestionSeed("What is the capital of Australia?",
                     ["Sydney", "Melbourne", "Canberra", "Perth"], 2,
                     "Canberra was purpose-built as a compromise between Sydney and Melbourne."),
        QuestionSeed("Which is the smallest continent?",
                     ["Europe", "Antarctica", "South America", "Australia"], 3,
                     "Australia is sometimes grouped with nearby islands as Oceania."),
        QuestionSeed("Which river flows through London?",
                     ["The Seine", "The Thames", "The Rhine", "The Danube"], 1,
                     "The Thames is tidal through London and rises and falls several metres."),
        QuestionSeed("Which country contains the Amazon rainforest's largest share?",
                     ["Peru", "Colombia", "Brazil", "Venezuela"], 2,
                     "Roughly sixty percent of the rainforest lies within Brazil."),
        QuestionSeed("What is the capital of Italy?",
                     ["Milan", "Rome", "Naples", "Turin"], 1,
                     "Vatican City is an independent state entirely within Rome."),
        QuestionSeed("Which imaginary line divides Earth into northern and southern halves?",
                     ["The prime meridian", "The equator", "The Tropic of Cancer", "The international date line"], 1,
                     "The equator sits at zero degrees latitude."),
        QuestionSeed("Which country is known as the Land of the Rising Sun?",
                     ["China", "Japan", "South Korea", "Thailand"], 1,
                     "The name reflects Japan's position east of the Asian mainland."),
        QuestionSeed("What is the largest island in the world?",
                     ["Madagascar", "Borneo", "Greenland", "New Guinea"], 2,
                     "Australia is larger but is classed as a continental landmass."),
        QuestionSeed("Which two countries share the longest international border?",
                     ["United States and Mexico", "Canada and United States", "Russia and China", "Argentina and Chile"], 1,
                     "The Canada-United States border runs about 5,525 miles including Alaska."),
        QuestionSeed("Which ocean lies east of the United States?",
                     ["Pacific", "Atlantic", "Indian", "Arctic"], 1,
                     "The Pacific lies to the west."),
        QuestionSeed("What is the capital of Germany?",
                     ["Munich", "Hamburg", "Berlin", "Frankfurt"], 2,
                     "Bonn served as the West German capital until reunification."),
        QuestionSeed("Which country has the most natural lakes?",
                     ["Russia", "Canada", "Finland", "United States"], 1,
                     "Canada holds a large share of the world's fresh surface water."),
        QuestionSeed("Which continent has the most countries?",
                     ["Asia", "Africa", "Europe", "South America"], 1,
                     "Africa has fifty-four internationally recognized sovereign states."),
        QuestionSeed("Which US city is known as the Windy City?",
                     ["New York", "Chicago", "Boston", "Detroit"], 1,
                     "The nickname's origin is debated but has been attached to Chicago since the 1800s."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("What is the capital of Turkey?",
                     ["Istanbul", "Ankara", "Izmir", "Bursa"], 1,
                     "Ankara replaced Istanbul as the capital in 1923."),
        QuestionSeed("Which country is landlocked and entirely surrounded by South Africa?",
                     ["Eswatini", "Lesotho", "Botswana", "Zimbabwe"], 1,
                     "Lesotho is one of only three countries entirely enclosed by another."),
        QuestionSeed("Which strait separates Asia from North America?",
                     ["The Bering Strait", "The Strait of Malacca", "The Bosphorus", "The Strait of Hormuz"], 0,
                     "At its narrowest the Bering Strait is about fifty-five miles wide."),
        QuestionSeed("What is the deepest point in the ocean called?",
                     ["The Mariana Trench", "The Puerto Rico Trench", "The Java Trench", "The Tonga Trench"], 0,
                     "Challenger Deep lies nearly eleven kilometres below the surface."),
        QuestionSeed("Which African country was never colonized by a European power?",
                     ["Ethiopia", "Ghana", "Kenya", "Senegal"], 0,
                     "Ethiopia repelled an Italian invasion in 1896, though it was occupied briefly in the 1930s."),
        QuestionSeed("Which country has the longest coastline?",
                     ["Russia", "Canada", "Indonesia", "Australia"], 1,
                     "Canada's Arctic archipelago accounts for much of its enormous coastline."),
        QuestionSeed("What is the capital of Brazil?",
                     ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], 2,
                     "Brasília was purpose-built inland and became the capital in 1960."),
        QuestionSeed("Which sea is the saltiest large body of water on Earth's surface?",
                     ["The Dead Sea", "The Red Sea", "The Caspian Sea", "The Black Sea"], 0,
                     "Its salinity is high enough that swimmers float easily."),
        QuestionSeed("Which mountain range runs along the western edge of South America?",
                     ["The Rockies", "The Andes", "The Atlas", "The Urals"], 1,
                     "The Andes is the longest continental mountain range in the world."),
        QuestionSeed("Which country is both in Europe and Asia and has Istanbul on the divide?",
                     ["Greece", "Turkey", "Russia", "Georgia"], 1,
                     "The Bosphorus strait runs through Istanbul, separating the two continents."),
        QuestionSeed("What is the capital of Argentina?",
                     ["Córdoba", "Buenos Aires", "Rosario", "Mendoza"], 1,
                     "Buenos Aires sits on the estuary of the Río de la Plata."),
        QuestionSeed("Which line of longitude is defined as zero degrees?",
                     ["The equator", "The prime meridian", "The date line", "The tropic line"], 1,
                     "It passes through Greenwich in London by international convention."),
        QuestionSeed("Which lake is the main reservoir feeding the White Nile?",
                     ["Lake Chad", "Lake Victoria", "Lake Tanganyika", "Lake Turkana"], 1,
                     "The White Nile leaves Lake Victoria at Jinja in Uganda; its most distant headwaters lie farther south."),
        QuestionSeed("What is the largest freshwater lake by surface area?",
                     ["Lake Baikal", "Lake Superior", "Lake Victoria", "Lake Michigan"], 1,
                     "Lake Baikal holds more water but Lake Superior covers more surface."),
        QuestionSeed("Which country has the most volcanoes?",
                     ["Japan", "Indonesia", "Chile", "Iceland"], 1,
                     "Indonesia sits along a highly active section of the Pacific Ring of Fire."),
        QuestionSeed("What is the capital of Egypt?",
                     ["Alexandria", "Cairo", "Giza", "Luxor"], 1,
                     "Cairo is the largest city in the Arab world."),
        QuestionSeed("Which peninsula is Spain and Portugal located on?",
                     ["The Balkan Peninsula", "The Iberian Peninsula", "The Apennine Peninsula", "The Anatolian Peninsula"], 1,
                     "Iberia is separated from the rest of Europe by the Pyrenees."),
        QuestionSeed("Which canal connects the Atlantic and Pacific Oceans?",
                     ["The Suez Canal", "The Panama Canal", "The Erie Canal", "The Kiel Canal"], 1,
                     "It opened in 1914 and cuts thousands of miles from the voyage around South America."),
        QuestionSeed("Which country is the only one to occupy an entire continent?",
                     ["Greenland", "Australia", "Madagascar", "Iceland"], 1,
                     "Australia is both a country and a continental landmass."),
        QuestionSeed("What is the highest waterfall in the world?",
                     ["Niagara Falls", "Angel Falls", "Victoria Falls", "Iguazu Falls"], 1,
                     "Angel Falls in Venezuela drops nearly a kilometre."),
        QuestionSeed("Which US state has the most coastline?",
                     ["Florida", "California", "Alaska", "Texas"], 2,
                     "Alaska's coastline exceeds that of all other states combined."),
        QuestionSeed("Which country is Mount Kilimanjaro in?",
                     ["Kenya", "Tanzania", "Uganda", "Ethiopia"], 1,
                     "It is the highest mountain in Africa and a free-standing volcano."),
        QuestionSeed("Which region is known as Scandinavia's northernmost inhabited area?",
                     ["Lapland", "Jutland", "Karelia", "Zealand"], 0,
                     "Lapland spans northern Norway, Sweden, Finland, and part of Russia."),
        QuestionSeed("Which body of water lies between Saudi Arabia and Africa?",
                     ["The Persian Gulf", "The Red Sea", "The Arabian Sea", "The Gulf of Aden"], 1,
                     "The Suez Canal connects the Red Sea to the Mediterranean."),
        QuestionSeed("What is the capital of South Africa where the executive branch sits?",
                     ["Cape Town", "Pretoria", "Johannesburg", "Durban"], 1,
                     "South Africa has three capitals: Pretoria, Cape Town, and Bloemfontein."),
        QuestionSeed("Which archipelago is Charles Darwin most associated with?",
                     ["The Galápagos", "The Azores", "The Canaries", "The Maldives"], 0,
                     "His 1835 visit informed his thinking on natural selection."),
        QuestionSeed("Which country is directly south of the United States?",
                     ["Guatemala", "Mexico", "Cuba", "Belize"], 1,
                     "The two countries share a border of about 1,950 miles."),
        QuestionSeed("What is a fjord?",
                     ["A deep glacially carved coastal inlet", "A volcanic crater lake", "A desert basin", "A river delta"], 0,
                     "Norway's coastline is famous for them."),
        QuestionSeed("Which continent contains the Ural Mountains, a traditional continental divide?",
                     ["Europe and Asia", "Asia only", "Europe only", "Africa"], 0,
                     "The Urals are conventionally taken as the boundary between Europe and Asia."),
        QuestionSeed("Which country's capital is Wellington?",
                     ["Australia", "New Zealand", "Fiji", "Papua New Guinea"], 1,
                     "Auckland is larger, but Wellington has been the capital since 1865."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("Which three countries are entirely enclosed by a single other country?",
                     ["Lesotho, San Marino, Vatican City", "Andorra, Monaco, Malta", "Nepal, Bhutan, Laos", "Luxembourg, Liechtenstein, Andorra"], 0,
                     "Lesotho is surrounded by South Africa; San Marino and Vatican City by Italy."),
        QuestionSeed("What is the only sea without a coastline?",
                     ["The Sargasso Sea", "The Coral Sea", "The Barents Sea", "The Timor Sea"], 0,
                     "It is bounded by ocean currents rather than land."),
        QuestionSeed("Which country has the most time zones including its territories?",
                     ["Russia", "France", "United States", "China"], 1,
                     "France's overseas departments and territories spread it across a dozen zones."),
        QuestionSeed("What is a country with no coastline and surrounded only by landlocked countries called?",
                     ["Doubly landlocked", "Sub-continental", "Interior state", "Enclave state"], 0,
                     "Uzbekistan and Liechtenstein are the only two such countries."),
        QuestionSeed("Which line does the international date line roughly follow?",
                     ["180 degrees longitude", "The equator", "The prime meridian", "The Tropic of Capricorn"], 0,
                     "It deviates around territories so that neighbouring islands share a date."),
        QuestionSeed("Which lake holds the largest volume of fresh water?",
                     ["Lake Baikal", "Lake Superior", "Lake Tanganyika", "Lake Victoria"], 0,
                     "Baikal is also the world's deepest lake, at over 1,600 metres."),
        QuestionSeed("What geological feature is the Great Rift Valley?",
                     ["A continental divergence zone in East Africa", "A mountain chain", "A glacial moraine", "A coastal shelf"], 0,
                     "The African plate is slowly splitting along it."),
        QuestionSeed("Which country contains the geographic point farthest from any ocean?",
                     ["China", "Kazakhstan", "Mongolia", "Russia"], 0,
                     "The Eurasian pole of inaccessibility lies in northwestern China."),
        QuestionSeed("What is an exclave?",
                     ["Territory separated from the main country by other states", "An island territory", "A disputed border zone", "A colonial possession"], 0,
                     "Kaliningrad is a Russian exclave on the Baltic."),
        QuestionSeed("Which desert is the driest non-polar place on Earth?",
                     ["The Atacama", "The Sahara", "The Namib", "The Gobi"], 0,
                     "Some Atacama weather stations have never recorded measurable rainfall."),
        QuestionSeed("Which strait connects the Mediterranean to the Atlantic?",
                     ["The Strait of Gibraltar", "The Dardanelles", "The Strait of Messina", "The Strait of Otranto"], 0,
                     "It separates Spain from Morocco at Europe's southwestern tip."),
        QuestionSeed("Which country's territory crosses the most lines of latitude in the Americas?",
                     ["Chile", "Brazil", "Canada", "Argentina"], 0,
                     "Chile stretches over 4,300 kilometres from the Atacama to Patagonia."),
        QuestionSeed("What is the name for a ring-shaped coral reef enclosing a lagoon?",
                     ["An atoll", "A cay", "A shoal", "A spit"], 0,
                     "Atolls form as a volcanic island subsides and the surrounding reef keeps growing."),
        QuestionSeed("Which river forms much of the border between the United States and Mexico?",
                     ["The Rio Grande", "The Colorado", "The Pecos", "The Gila"], 0,
                     "Mexico calls it the Río Bravo del Norte."),
        QuestionSeed("What is the Ring of Fire?",
                     ["A belt of volcanoes and earthquakes around the Pacific", "An African rift", "A Mediterranean fault line", "An Atlantic ridge"], 0,
                     "Around three quarters of the world's active volcanoes lie along it."),
        QuestionSeed("Which two countries share the island of Hispaniola?",
                     ["Haiti and the Dominican Republic", "Cuba and Jamaica", "Trinidad and Tobago", "Saint Kitts and Nevis"], 0,
                     "It is the second-largest island in the Caribbean."),
        QuestionSeed("What is the Sahel?",
                     ["A semi-arid belt south of the Sahara", "A mountain range", "A river system", "A coastal plain"], 0,
                     "It forms a transition zone between the desert and the savanna."),
        QuestionSeed("Which country has the highest average elevation?",
                     ["Bhutan", "Nepal", "Tajikistan", "Kyrgyzstan"], 0,
                     "Bhutan's mean elevation exceeds three thousand metres."),
        QuestionSeed("What is a 'thalweg' in geography?",
                     ["The line of lowest elevation along a valley or river channel", "A ridge crest", "A coastal current", "A glacial terminus"], 0,
                     "It is often used to define river boundaries between states."),
        QuestionSeed("Which sea is technically the world's largest lake?",
                     ["The Caspian Sea", "The Aral Sea", "The Dead Sea", "The Black Sea"], 0,
                     "It is landlocked, though its legal status has been long disputed."),
        QuestionSeed("What is the term for a narrow strip of land connecting two larger landmasses?",
                     ["An isthmus", "A peninsula", "A cape", "A delta"], 0,
                     "The Isthmus of Panama is the best-known example."),
        QuestionSeed("Which country was formerly known as Upper Volta?",
                     ["Burkina Faso", "Mali", "Niger", "Benin"], 0,
                     "The name changed in 1984 and means 'land of upright people'."),
        QuestionSeed("What is orographic rainfall caused by?",
                     ["Air forced upward over mountains", "Convection over warm seas", "Frontal collision", "Urban heat"], 0,
                     "It produces the wet windward side and the dry rain shadow beyond."),
        QuestionSeed("Which region is known as the Roof of the World?",
                     ["The Tibetan Plateau", "The Andes", "The Alps", "The Ethiopian Highlands"], 0,
                     "It is the highest and largest plateau on Earth."),
        QuestionSeed("What is a 'karst' landscape formed by?",
                     ["Dissolution of soluble rock such as limestone", "Glacial scouring", "Volcanic deposition", "Wind erosion"], 0,
                     "Caves, sinkholes, and underground rivers are characteristic features."),
        QuestionSeed("Lake Assal, the lowest point in Africa, lies in which country?",
                     ["Ethiopia", "Djibouti", "Eritrea", "Somalia"], 1,
                     "Its shore sits about 155 metres below sea level, in the Afar Depression."),
        QuestionSeed("What does 'antipode' mean?",
                     ["The point on Earth's surface diametrically opposite another", "The magnetic pole", "The highest latitude reached", "A tidal maximum"], 0,
                     "Most land antipodes fall in the ocean, because land is unevenly distributed."),
        QuestionSeed("Which African lake is shared by Kenya, Uganda, and Tanzania?",
                     ["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Turkana"], 0,
                     "It is Africa's largest lake by surface area."),
        QuestionSeed("What is a 'graben' in geology?",
                     ["A block of crust dropped between two faults", "A volcanic plug", "A sediment fan", "A raised beach"], 0,
                     "The raised block on either side is called a horst."),
        QuestionSeed("Which two seas does the Bosphorus connect?",
                     ["The Black Sea and the Sea of Marmara", "The Aegean and the Ionian", "The Red Sea and the Gulf of Aden", "The Baltic and the North Sea"], 0,
                     "The Dardanelles then links the Marmara to the Aegean."),
    ]
}
