import Foundation

enum HistoryQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("Who was the first president of the United States?",
                     ["Thomas Jefferson", "George Washington", "John Adams", "Abraham Lincoln"], 1,
                     "Washington served two terms, from 1789 to 1797, and declined a third."),
        QuestionSeed("In which year did the Second World War end?",
                     ["1943", "1944", "1945", "1946"], 2,
                     "Germany surrendered in May 1945 and Japan in September of the same year."),
        QuestionSeed("Which civilization built Machu Picchu?",
                     ["The Maya", "The Aztec", "The Inca", "The Olmec"], 2,
                     "The Inca built the Andean estate in the fifteenth century, probably for the ruler Pachacuti."),
        QuestionSeed("The Magna Carta was sealed in which country?",
                     ["France", "England", "Spain", "Germany"], 1,
                     "King John sealed it at Runnymede in 1215 under pressure from rebellious barons."),
        QuestionSeed("Which wall came down in 1989?",
                     ["Hadrian's Wall", "The Great Wall", "The Berlin Wall", "The Western Wall"], 2,
                     "Its opening on 9 November became the defining image of the Cold War's end."),
        QuestionSeed("Ancient Egyptian monumental writing used which script?",
                     ["Cuneiform", "Latin", "Hieroglyphs", "Runes"], 2,
                     "Egyptians also used the cursive hieratic and demotic scripts for everyday documents."),
        QuestionSeed("Which ancient city was buried by the eruption of Mount Vesuvius in AD 79?",
                     ["Carthage", "Pompeii", "Troy", "Athens"], 1,
                     "Volcanic ash preserved streets, houses, and the shapes of victims for centuries."),
        QuestionSeed("Who led the Soviet Union during most of the Second World War?",
                     ["Vladimir Lenin", "Joseph Stalin", "Nikita Khrushchev", "Leon Trotsky"], 1,
                     "Stalin held power from the late 1920s until his death in 1953."),
        QuestionSeed("Which empire built a road network centred on Rome?",
                     ["The Persian Empire", "The Roman Empire", "The Ottoman Empire", "The Mughal Empire"], 1,
                     "The saying that all roads lead to Rome reflects a genuine radial network."),
        QuestionSeed("Who was the British prime minister for most of the Second World War?",
                     ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Anthony Eden"], 1,
                     "Churchill became prime minister in May 1940 and served until July 1945."),
        QuestionSeed("The Declaration of Independence was adopted in which year?",
                     ["1774", "1776", "1781", "1789"], 1,
                     "The Continental Congress adopted it on 4 July 1776."),
        QuestionSeed("Which country was ruled by pharaohs?",
                     ["Greece", "Egypt", "Persia", "Babylon"], 1,
                     "Pharaoh was the title of ancient Egypt's ruler for roughly three thousand years."),
        QuestionSeed("Who wrote the Ninety-five Theses?",
                     ["Martin Luther", "Galileo Galilei", "Voltaire", "John Calvin"], 0,
                     "Luther's 1517 objections to indulgences helped begin the Protestant Reformation."),
        QuestionSeed("Which ship sank on its maiden voyage in 1912?",
                     ["The Lusitania", "The Titanic", "The Britannic", "The Mauretania"], 1,
                     "The Titanic struck an iceberg in the North Atlantic on 14 April 1912."),
        QuestionSeed("Who was known as the Maid of Orléans?",
                     ["Cleopatra", "Joan of Arc", "Boudica", "Catherine the Great"], 1,
                     "Joan led French forces at Orléans in 1429 during the Hundred Years' War."),
        QuestionSeed("Which structure was built to protect ancient China from northern invasions?",
                     ["The Great Wall", "The Forbidden City", "The Grand Canal", "The Terracotta Army"], 0,
                     "It is not one continuous wall but many fortifications built across several dynasties."),
        QuestionSeed("Which American president issued the Emancipation Proclamation?",
                     ["Andrew Jackson", "Abraham Lincoln", "Ulysses S. Grant", "James Buchanan"], 1,
                     "The 1863 proclamation declared enslaved people in rebelling states to be free."),
        QuestionSeed("The Renaissance began in which country?",
                     ["France", "Italy", "England", "Spain"], 1,
                     "It began in the Italian city-states, with Florence a particularly important centre."),
        QuestionSeed("Which two cities were struck by atomic bombs in 1945?",
                     ["Tokyo and Osaka", "Hiroshima and Nagasaki", "Kyoto and Kobe", "Sapporo and Sendai"], 1,
                     "The bombings took place on 6 and 9 August 1945."),
        QuestionSeed("Who was the first man to walk on the Moon?",
                     ["Buzz Aldrin", "Neil Armstrong", "Michael Collins", "Yuri Gagarin"], 1,
                     "Armstrong stepped onto the surface on 20 July 1969, followed by Buzz Aldrin."),
        QuestionSeed("Which civilization is credited with building the pyramids at Giza?",
                     ["The Sumerians", "The Ancient Egyptians", "The Nubians", "The Hittites"], 1,
                     "The Great Pyramid was built for the pharaoh Khufu around 2560 BC."),
        QuestionSeed("The American Civil War was fought in which century?",
                     ["The 18th", "The 19th", "The 20th", "The 17th"], 1,
                     "It ran from 1861 to 1865."),
        QuestionSeed("Who was the first woman to win a Nobel Prize?",
                     ["Marie Curie", "Rosalind Franklin", "Ada Lovelace", "Florence Nightingale"], 0,
                     "Curie won in Physics in 1903 and later in Chemistry in 1911."),
        QuestionSeed("Which country did Mahatma Gandhi help gain independence?",
                     ["Pakistan", "India", "Bangladesh", "Sri Lanka"], 1,
                     "India became independent from British rule in August 1947."),
        QuestionSeed("The Cold War was mainly between the United States and which country?",
                     ["China", "The Soviet Union", "Germany", "Japan"], 1,
                     "The rivalry lasted from the late 1940s until the Soviet Union dissolved in 1991."),
        QuestionSeed("Which explorer's expedition first sailed around the world?",
                     ["Christopher Columbus", "Ferdinand Magellan", "James Cook", "Marco Polo"], 1,
                     "Magellan died in the Philippines; Juan Sebastián Elcano completed the voyage in 1522."),
        QuestionSeed("Who was the longest-reigning British monarch?",
                     ["Victoria", "Elizabeth II", "George III", "Henry VIII"], 1,
                     "Elizabeth II reigned for seventy years, surpassing Victoria's sixty-three."),
        QuestionSeed("Which war was fought between the North and South in the United States?",
                     ["The Revolutionary War", "The Civil War", "The War of 1812", "The Spanish-American War"], 1,
                     "The Union victory ended slavery and preserved the United States as one country."),
        QuestionSeed("What was the Silk Road?",
                     ["A trade network linking Asia and Europe", "A Roman highway", "A Viking sea route", "An Egyptian canal"], 0,
                     "It carried goods, technology, religion, and disease across Eurasia for centuries."),
        QuestionSeed("Which document begins 'We the People'?",
                     ["The Declaration of Independence", "The United States Constitution", "The Bill of Rights", "The Gettysburg Address"], 1,
                     "The Preamble opens the Constitution, ratified in 1788."),
        QuestionSeed("In which ancient civilization did the Olympic Games begin?",
                     ["Greece", "Rome", "Egypt", "Persia"], 0,
                     "The ancient games were held at Olympia in honour of Zeus."),
        QuestionSeed("In which city can the ancient Colosseum be found?",
                     ["Athens", "Rome", "Istanbul", "Alexandria"], 1,
                     "The Roman amphitheatre opened in the first century AD and hosted public spectacles."),
        QuestionSeed("The samurai were warriors associated with which country?",
                     ["China", "Japan", "India", "Korea"], 1,
                     "Samurai served Japan's military elite for centuries before their legal privileges ended in the nineteenth century."),
        QuestionSeed("What was the capital of the Aztec Empire?",
                     ["Tenochtitlan", "Cusco", "Chichén Itzá", "Teotihuacan"], 0,
                     "Tenochtitlan stood on an island in Lake Texcoco beneath modern Mexico City."),
        QuestionSeed("Stonehenge was built in which present-day country?",
                     ["Ireland", "England", "France", "Denmark"], 1,
                     "The prehistoric monument stands on Salisbury Plain in southern England."),
        QuestionSeed("Ancient Babylon stood in which present-day country?",
                     ["Egypt", "Iraq", "Greece", "Turkey"], 1,
                     "Its ruins lie near the Euphrates south of modern Baghdad."),
        QuestionSeed("Who discovered Tutankhamun's largely intact tomb in 1922?",
                     ["Howard Carter", "Heinrich Schliemann", "Arthur Evans", "Flinders Petrie"], 0,
                     "Carter's excavation in Egypt's Valley of the Kings revealed thousands of objects."),
        QuestionSeed("Who painted the Mona Lisa?",
                     ["Michelangelo", "Raphael", "Leonardo da Vinci", "Titian"], 2,
                     "Leonardo began the portrait during the Italian Renaissance and continued refining it for years."),
        QuestionSeed("Which ancient city is most closely associated with the birth of democracy?",
                     ["Sparta", "Athens", "Carthage", "Babylon"], 1,
                     "Classical Athens developed direct citizen participation, though citizenship excluded much of the population."),
        QuestionSeed("Which machine became a major power source of the Industrial Revolution?",
                     ["The steam engine", "The telegraph", "The printing press", "The radio"], 0,
                     "Improved steam engines powered factories, mines, locomotives, and ships."),
        QuestionSeed("In which year did the First World War begin?",
                     ["1914", "1912", "1918", "1920"], 0,
                     "The First World War began in 1914 after the assassination of Archduke Franz Ferdinand."),
        QuestionSeed("Which ancient people carved the city of Petra?",
                     ["The Nabataeans", "The Phoenicians", "The Assyrians", "The Hittites"], 0,
                     "The Nabataeans carved Petra's tombs and temples into rose-colored sandstone cliffs in what is now Jordan."),
        QuestionSeed("Which empire did the tsars rule?",
                     ["The Russian Empire", "The Ottoman Empire", "The Austrian Empire", "The Persian Empire"], 0,
                     "Tsars ruled the Russian Empire until the revolution of 1917 removed Nicholas the Second."),
        QuestionSeed("Which Macedonian king conquered the Persian Empire?",
                     ["Alexander the Great", "Julius Caesar", "Nebuchadnezzar the Second", "Philip the Second"], 0,
                     "Alexander the Great conquered the Persian Empire before he turned thirty, reaching the edge of India."),
        QuestionSeed("Which Egyptian queen ruled alongside Julius Caesar's Rome?",
                     ["Cleopatra", "Nefertiti", "Hatshepsut", "Queen Berenice"], 0,
                     "Cleopatra was the last active ruler of Ptolemaic Egypt and allied with Julius Caesar."),
        QuestionSeed("Which famous ancient library stood in Egypt?",
                     ["The Library of Alexandria", "The Library of Pergamum", "The Library of Constantinople", "The Library of Nineveh"], 0,
                     "The Library of Alexandria collected scrolls from across the ancient world before declining over several centuries."),
        QuestionSeed("Which document did American colonists adopt in 1776?",
                     ["The Declaration of Independence", "The Bill of Rights", "The Articles of Confederation", "The Treaty of Paris and Versailles"], 0,
                     "The Declaration of Independence was adopted in 1776, announcing separation from Britain."),
        QuestionSeed("Which explorer crossed the Atlantic for Spain in 1492?",
                     ["Christopher Columbus", "Vasco da Gama", "Francisco Pizarro Gonzalez", "Bartolomeu Dias"], 0,
                     "Christopher Columbus crossed the Atlantic in 1492 under Spanish sponsorship and landed in the Caribbean."),
        QuestionSeed("Which Mughal emperor built the Taj Mahal?",
                     ["Shah Jahan", "Akbar", "Jahangir the First", "Babur"], 0,
                     "Shah Jahan built the Taj Mahal at Agra as a tomb for his wife Mumtaz."),
        QuestionSeed("Which country first granted women the national vote?",
                     ["New Zealand", "Australia", "The United Kingdom", "Norway"], 0,
                     "New Zealand granted women the national vote in 1893, ahead of every other self-governing country."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("The Battle of Hastings took place in which year?",
                     ["1066", "1099", "1215", "1348"], 0,
                     "William of Normandy's victory brought Norman rule to England."),
        QuestionSeed("Which treaty formally ended the First World War with Germany?",
                     ["The Treaty of Versailles", "The Treaty of Utrecht", "The Treaty of Ghent", "The Treaty of Tordesillas"], 0,
                     "Signed in 1919, its terms are widely seen as contributing to later instability."),
        QuestionSeed("Who was the first emperor of a unified China?",
                     ["Qin Shi Huang", "Kublai Khan", "Sun Yat-sen", "Wu Zetian"], 0,
                     "He unified the warring states in 221 BC and was buried with the Terracotta Army."),
        QuestionSeed("The Black Death swept Europe in which century?",
                     ["The 12th", "The 14th", "The 16th", "The 17th"], 1,
                     "The pandemic peaked between 1347 and 1351 and killed a large share of Europe's population."),
        QuestionSeed("Which revolution began with the storming of the Bastille?",
                     ["The American Revolution", "The French Revolution", "The Russian Revolution", "The Glorious Revolution"], 1,
                     "The Bastille was stormed on 14 July 1789, still France's national day."),
        QuestionSeed("Who was the first woman to fly solo across the Atlantic?",
                     ["Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Jacqueline Cochran"], 0,
                     "Earhart made the crossing in 1932, five years after Lindbergh."),
        QuestionSeed("Which empire was centred on Constantinople after Rome's western collapse?",
                     ["The Byzantine Empire", "The Holy Roman Empire", "The Persian Empire", "The Carthaginian Empire"], 0,
                     "It survived until the Ottoman conquest of Constantinople in 1453."),
        QuestionSeed("The Rosetta Stone was key to deciphering which writing system?",
                     ["Cuneiform", "Egyptian hieroglyphs", "Linear B", "Mayan glyphs"], 1,
                     "Its parallel Greek text gave Jean-François Champollion the key in the 1820s."),
        QuestionSeed("Which country did the Ottoman Empire primarily occupy at its centre?",
                     ["Modern Turkey", "Modern Iran", "Modern Egypt", "Modern Greece"], 0,
                     "The empire spanned three continents but was governed from Anatolia and Constantinople."),
        QuestionSeed("Who was assassinated in Sarajevo in 1914?",
                     ["Archduke Franz Ferdinand", "Tsar Nicholas II", "Kaiser Wilhelm II", "King Peter I"], 0,
                     "His killing set off the chain of alliances that produced the First World War."),
        QuestionSeed("What was the Marshall Plan?",
                     ["American aid to rebuild post-war Europe", "A British colonial policy", "A Soviet five-year plan", "A NATO defence strategy"], 0,
                     "Launched in 1948, it channelled billions of dollars into Western European recovery."),
        QuestionSeed("Which dynasty ruled China during the construction of much of the surviving Great Wall?",
                     ["The Han", "The Tang", "The Ming", "The Song"], 2,
                     "Most of the wall visitors see today is Ming-era brick and stone."),
        QuestionSeed("The Suez Canal connects the Mediterranean to which body of water?",
                     ["The Black Sea", "The Red Sea", "The Persian Gulf", "The Caspian Sea"], 1,
                     "It opened in 1869 and cut the sea route between Europe and Asia dramatically."),
        QuestionSeed("Who was the Carthaginian general who crossed the Alps with elephants?",
                     ["Hannibal", "Scipio", "Hasdrubal", "Pyrrhus"], 0,
                     "Hannibal's crossing in 218 BC opened the Second Punic War in Italy."),
        QuestionSeed("Which country was ruled by apartheid until the early 1990s?",
                     ["Zimbabwe", "South Africa", "Namibia", "Kenya"], 1,
                     "Nelson Mandela was released in 1990 and elected president in 1994."),
        QuestionSeed("What did the Gutenberg press revolutionize in the fifteenth century?",
                     ["Printing", "Navigation", "Metalworking", "Glassmaking"], 0,
                     "Movable metal type made books far cheaper and helped spread the Reformation."),
        QuestionSeed("The Meiji Restoration transformed which country?",
                     ["China", "Japan", "Korea", "Thailand"], 1,
                     "From 1868 Japan rapidly industrialized and reorganized its government."),
        QuestionSeed("Which US president resigned over the Watergate scandal?",
                     ["Lyndon Johnson", "Richard Nixon", "Gerald Ford", "Jimmy Carter"], 1,
                     "Nixon resigned in August 1974 rather than face near-certain impeachment."),
        QuestionSeed("Who founded the Mongol Empire?",
                     ["Genghis Khan", "Timur, also known as Tamerlane", "Attila", "Batu Khan"], 0,
                     "He unified the Mongol tribes in 1206 and began a vast campaign of conquest."),
        QuestionSeed("The Hundred Years' War was fought between England and which country?",
                     ["Spain", "France", "Scotland", "The Netherlands"], 1,
                     "It ran, with interruptions, from 1337 to 1453."),
        QuestionSeed("Which ancient wonder stood in the harbour of Alexandria?",
                     ["The Colossus of Rhodes", "The Lighthouse of Alexandria", "The Hanging Gardens", "The Temple of Artemis"], 1,
                     "The Pharos guided ships for centuries before earthquakes destroyed it."),
        QuestionSeed("What was the Underground Railroad?",
                     ["A network helping enslaved people escape to freedom", "An experimental underground passenger railway beneath an early American city", "A protected corridor used to move military supplies during wartime", "A system of narrow-gauge rails built to carry ore out of a mine"], 0,
                     "It was a covert network of routes, safe houses, and guides, not an actual railway."),
        QuestionSeed("Which country did Simón Bolívar help liberate from Spanish rule?",
                     ["The Empire of Brazil", "Venezuela", "Mexico", "Cuba"], 1,
                     "Bolívar led independence movements across several South American nations."),
        QuestionSeed("The Nuremberg trials followed which conflict?",
                     ["The First World War", "The Second World War", "The Korean War", "The Vietnam War"], 1,
                     "They established precedents in international criminal law from 1945 onward."),
        QuestionSeed("Which 1494 treaty divided newly claimed lands outside Europe between Spain and Portugal?",
                     ["The Treaty of Tordesillas", "The Treaty of Utrecht", "The Treaty of Versailles", "The Peace of Augsburg"], 0,
                     "The Treaty of Tordesillas drew a north-south line that allocated most of the Americas to Spain and territory including Brazil to Portugal."),
        QuestionSeed("Who was the first female prime minister of the United Kingdom?",
                     ["Margaret Thatcher", "Theresa May", "Barbara Castle", "Shirley Williams"], 0,
                     "Thatcher took office in 1979 and served until 1990."),
        QuestionSeed("What was Prohibition in the United States?",
                     ["A ban on alcohol production and sale", "A ban on immigration", "A wartime rationing scheme", "A tariff policy"], 0,
                     "It ran from 1920 to 1933 under the Eighteenth Amendment."),
        QuestionSeed("The Terracotta Army was discovered in which country?",
                     ["Japan", "China", "Vietnam", "Mongolia"], 1,
                     "Farmers digging a well near Xi'an uncovered the figures in 1974."),
        QuestionSeed("Which city was divided by a wall from 1961 to 1989?",
                     ["Vienna", "Berlin", "Prague", "Budapest"], 1,
                     "The wall separated East and West Berlin for twenty-eight years."),
        QuestionSeed("What did the Wright brothers achieve in 1903?",
                     ["The first powered controlled aeroplane flight", "The first hot-air balloon flight", "The first transatlantic flight", "The first helicopter flight"], 0,
                     "The flight at Kitty Hawk lasted twelve seconds and covered about 120 feet."),
        QuestionSeed("The Peloponnesian War was fought chiefly between which Greek city-states?",
                     ["Athens and Sparta", "Corinth and Thebes", "Argos and Delphi", "Miletus and Ephesus"], 0,
                     "Sparta and its allies defeated the Athenian empire after a conflict lasting from 431 to 404 BC."),
        QuestionSeed("What was the main purpose of the Council of Trent?",
                     ["To direct Catholic reform and answer the Protestant Reformation", "To unite the Roman and Byzantine empires", "To coordinate a European military campaign to recapture Jerusalem", "To dissolve monastic orders and transfer their property to secular rulers"], 0,
                     "Meeting between 1545 and 1563, the council clarified doctrine and reformed church practice."),
        QuestionSeed("From which country did the United States acquire the Louisiana Purchase in 1803?",
                     ["Spain", "France", "Britain", "Mexico"], 1,
                     "The purchase from Napoleonic France roughly doubled the territory of the United States."),
        QuestionSeed("What did England's Glorious Revolution of 1688 establish more firmly?",
                     ["Parliamentary limits on royal power", "Absolute monarchy", "Roman rule", "Independence from Britain"], 0,
                     "The settlement placed William and Mary on the throne and led to the 1689 Bill of Rights."),
        QuestionSeed("Which attempted invasion did England defeat in 1588?",
                     ["The Spanish Armada", "The Norman fleet", "The Dutch East India Company", "The Holy Roman army"], 0,
                     "English attacks, poor weather, and logistical problems forced the Armada to retreat around Britain and Ireland."),
        QuestionSeed("The 1947 partition of British India created India and which other new state?",
                     ["Pakistan", "Bangladesh", "Sri Lanka", "Nepal"], 0,
                     "Pakistan was created in two separated regions; its eastern wing became Bangladesh in 1971."),
        QuestionSeed("What did the Balfour Declaration of 1917 express British support for?",
                     ["A Jewish national home in Palestine", "Indian independence", "Irish reunification", "The restoration of the Ottoman Empire"], 0,
                     "The declaration also stated that the civil and religious rights of existing non-Jewish communities should not be prejudiced."),
        QuestionSeed("The nineteenth-century Opium Wars were fought primarily between Britain and which empire?",
                     ["The Qing Empire", "The Mughal Empire", "The Ottoman Empire", "The Russian Empire"], 0,
                     "The wars forced Qing China to accept unequal treaties and expanded foreign access to Chinese ports."),
        QuestionSeed("Which Frankish leader defeated an Umayyad army near Tours in 732?",
                     ["Charles Martel", "Charlemagne", "Clovis I", "Pepin the Short"], 0,
                     "Charles Martel's victory strengthened his family's power in the Frankish kingdoms."),
        QuestionSeed("The 1848 Seneca Falls Convention focused on which cause?",
                     ["Women's rights", "The abolition of tariffs", "Western settlement", "Religious toleration"], 0,
                     "Its Declaration of Sentiments called for greater civil, social, and political equality."),
        QuestionSeed("Which 1215 charter limited the English king's power?",
                     ["Magna Carta", "The Bill of Rights", "The Petition of Right", "The Act of Union"], 0,
                     "Magna Carta bound King John to law in 1215 and became a touchstone for later constitutions."),
        QuestionSeed("Which empire did Hernan Cortes overthrow in Mexico?",
                     ["The Aztec Empire", "The Inca Empire", "The Maya city-states", "The Olmec Empire"], 0,
                     "Hernan Cortes and allied peoples brought down the Aztec Empire and its capital in 1521."),
        QuestionSeed("Which conflict left Korea divided at the 38th parallel?",
                     ["The Korean War", "The Vietnam War", "The Cold War", "The Sino-Japanese War"], 0,
                     "The Korean War ended in 1953 with an armistice that left the peninsula divided."),
        QuestionSeed("Which pandemic killed tens of millions just after the First World War?",
                     ["The 1918 flu", "The Black Death", "The cholera pandemic", "The Antonine Plague"], 0,
                     "The 1918 flu killed tens of millions worldwide, more than the war that preceded it."),
        QuestionSeed("Which wall-building Roman emperor fortified northern Britain?",
                     ["Hadrian", "Nero", "Trajan", "Vespasian"], 0,
                     "Hadrian ordered the wall across northern Britain that still carries his name."),
        QuestionSeed("Which conference divided post-war Europe among the Allies in 1945?",
                     ["Yalta", "Geneva", "Bretton Woods", "The Hague convention"], 0,
                     "At Yalta in 1945 the Allied leaders agreed how post-war Europe would be divided."),
        QuestionSeed("Which Roman general crossed the Rubicon in 49 BC?",
                     ["Julius Caesar", "Pompey the Great", "Mark Antony", "Sulla"], 0,
                     "Julius Caesar crossed the Rubicon with his army in 49 BC, starting a civil war."),
        QuestionSeed("Which 1648 settlement ended the Thirty Years' War?",
                     ["The Peace of Westphalia", "The Treaty of Utrecht", "The Treaty of Aix-la-Chapelle", "The Congress of Vienna"], 0,
                     "The Peace of Westphalia ended the Thirty Years' War in 1648 and reshaped European sovereignty."),
        QuestionSeed("Which act of Parliament abolished the slave trade in Britain in 1807?",
                     ["The Slave Trade Act", "The Reform Act", "The Corn Laws", "The Navigation Ordinance"], 0,
                     "The Slave Trade Act of 1807 ended British participation in the transatlantic slave trade."),
        QuestionSeed("Which civilization developed cuneiform, one of the earliest writing systems?",
                     ["Sumer", "Phoenicia", "Carthage", "The Indus Valley"], 0,
                     "Sumer developed cuneiform, pressing wedge-shaped marks into clay tablets."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("The Treaty of Tordesillas divided newly explored lands between which two powers?",
                     ["Portugal and Spain", "England and France", "The Netherlands and Portugal", "Spain and France"], 0,
                     "The 1494 treaty drew a meridian dividing claims, which is why Brazil speaks Portuguese."),
        QuestionSeed("Who was the Byzantine emperor who codified Roman law in the sixth century?",
                     ["Justinian I", "Constantine I", "Basil II", "Heraclius"], 0,
                     "The Corpus Juris Civilis shaped legal systems across Europe for centuries."),
        QuestionSeed("The Defenestration of Prague helped trigger which conflict?",
                     ["The Thirty Years' War", "The Seven Years' War", "The Hussite Wars", "The Great Northern War"], 0,
                     "Officials were thrown from a castle window in 1618, opening a devastating European war."),
        QuestionSeed("Which writing system did the Sumerians develop in ancient Mesopotamia?",
                     ["Cuneiform", "Hieroglyphics", "Linear B", "The Phoenician alphabet"], 0,
                     "Sumerian cuneiform was pressed into clay from around 3200 BC and was one of the world's earliest writing systems."),
        QuestionSeed("What was the Congress of Vienna convened to settle?",
                     ["Europe after the Napoleonic Wars", "The partition of Africa", "The end of the Thirty Years' War", "German unification"], 0,
                     "The 1814-15 congress redrew borders and aimed to restore a balance of power."),
        QuestionSeed("Who was the Egyptian queen who ruled as pharaoh in the fifteenth century BC?",
                     ["Hatshepsut", "Nefertiti", "Cleopatra VII", "Nefertari"], 0,
                     "Hatshepsut ruled for roughly two decades and was often depicted in male regalia."),
        QuestionSeed("The Peace of Westphalia in 1648 is often cited as the origin of what concept?",
                     ["State sovereignty", "Universal suffrage", "Free trade", "Trial by jury"], 0,
                     "Westphalia is often portrayed as a milestone in state sovereignty, although historians dispute the simplified idea that it created the modern state system by itself."),
        QuestionSeed("Which empire did Cyrus the Great found?",
                     ["The Achaemenid Persian Empire", "The Parthian Empire", "The Seleucid Empire", "The Sassanid Empire"], 0,
                     "Cyrus's conquests in the sixth century BC created the largest empire of its day."),
        QuestionSeed("What was the Zimmermann Telegram?",
                     ["A German proposal of alliance with Mexico in 1917", "The Russian government's terms for ending its participation in World War I", "A British system for encoding confidential orders sent to its naval fleet", "An Austro-Hungarian ultimatum delivered to Serbia after an assassination"], 0,
                     "Its interception helped push the United States into the First World War."),
        QuestionSeed("Which dynasty preceded the Ming in China?",
                     ["The Yuan", "The Qing", "The Song", "The Tang"], 0,
                     "The Yuan was the Mongol dynasty founded by Kublai Khan."),
        QuestionSeed("The Domesday Book was compiled under which English king?",
                     ["William the Conqueror", "Henry II", "Edward I", "Alfred the Great"], 0,
                     "The 1086 survey recorded landholdings and taxable resources across England."),
        QuestionSeed("What was the Long March in Chinese history?",
                     ["A Communist military retreat in 1934–35", "A Ming naval expedition", "A Qing tax reform", "A Tang trade mission"], 0,
                     "The Red Army's retreat preserved the Communist movement and helped establish Mao Zedong's leadership; traditional distance estimates are disputed."),
        QuestionSeed("Which battle in 1815 ended Napoleon's rule?",
                     ["Waterloo", "Austerlitz", "Trafalgar", "Borodino"], 0,
                     "The defeat in present-day Belgium led to his exile on Saint Helena."),
        QuestionSeed("The Council of Nicaea in AD 325 was convened to address what?",
                     ["Disputes over Christian doctrine", "Roman tax policy", "Barbarian invasions", "The division of the empire"], 0,
                     "It produced the Nicene Creed and addressed the Arian controversy."),
        QuestionSeed("Who emerged as the Haitian Revolution's most prominent early leader?",
                     ["Toussaint Louverture", "Simón Bolívar", "Miguel Hidalgo", "José de San Martín"], 0,
                     "Toussaint Louverture rose to prominence after the 1791 uprising, which initially had other leaders including Dutty Boukman."),
        QuestionSeed("What was the Hanseatic League?",
                     ["A medieval northern European trading confederation", "A coalition of Crusader states coordinating campaigns in the eastern Mediterranean", "A network of Italian banking families financing monarchs and popes", "A Byzantine military order"], 0,
                     "Merchant guilds and market towns dominated Baltic and North Sea trade for centuries."),
        QuestionSeed("Which co-emperors agreed on the policy known as the Edict of Milan in 313?",
                     ["Constantine I and Licinius", "Nero and Galba", "Diocletian and Maximian", "Augustus and Tiberius"], 0,
                     "Constantine and Licinius proclaimed religious toleration and restored confiscated Christian property."),
        QuestionSeed("The Sykes-Picot Agreement proposed dividing which territories into British and French spheres?",
                     ["Ottoman territories in the Middle East", "German colonies in Africa", "The Balkans", "Central Asia"], 0,
                     "The secret 1916 plan influenced later settlements, but mandates, wars, and subsequent agreements produced the region's final borders."),
        QuestionSeed("Which Japanese period was marked by isolation from most foreign contact?",
                     ["The Edo period", "The Heian period", "The Meiji period", "The Nara period"], 0,
                     "The sakoku policy restricted foreign contact from the 1630s until the 1850s."),
        QuestionSeed("What was the Antonine Wall?",
                     ["A Roman frontier wall in what is now Scotland", "A defensive circuit encircling the imperial capital of Rome", "A coastal fortification protecting Constantinople from attack by sea", "A Gallic fortification"], 0,
                     "Built around AD 142, it lay north of the better-known Hadrian's Wall."),
        QuestionSeed("Which 1713 treaty helped end the War of the Spanish Succession?",
                     ["The Treaty of Utrecht", "The Treaty of Ryswick", "The Peace of Augsburg", "The Treaty of Tordesillas"], 0,
                     "The Treaty of Utrecht redistributed European and colonial possessions while recognizing Philip V as king of Spain."),
        QuestionSeed("What was the Trail of Tears?",
                     ["The forced removal of Native American nations from the southeastern US", "An organized Union Army withdrawal after a major defeat in the Civil War", "An overland trail followed by prospectors travelling to western goldfields", "A Confederate supply line"], 0,
                     "Thousands died during the removals of the 1830s, particularly among the Cherokee."),
        QuestionSeed("Which missionary-explorer named Victoria Falls for the British monarch and searched for the Nile's source?",
                     ["David Livingstone", "Henry Morton Stanley", "Richard Francis Burton", "John Hanning Speke"], 0,
                     "David Livingstone's journeys and abolitionist reports became widely known in Victorian Britain."),
        QuestionSeed("What did the Bretton Woods conference establish in 1944?",
                     ["The postwar international monetary system", "A global organization for collective diplomacy and international peacekeeping", "A military alliance linking North America with the nations of western Europe", "A political and economic union binding together the states of postwar Europe"], 0,
                     "It created the IMF and the institution that became the World Bank."),
        QuestionSeed("Which empire did Mansa Musa rule in the fourteenth century?",
                     ["The Mali Empire", "The Songhai Empire", "The Kingdom of Kush", "The Ashanti Empire"], 0,
                     "His pilgrimage to Mecca and its lavish spending became legendary in the medieval world."),
        QuestionSeed("The Boxer Rebellion took place in which country?",
                     ["China", "Japan", "Korea", "The Philippines"], 0,
                     "The anti-foreign uprising of 1899-1901 was suppressed by an eight-nation alliance."),
        QuestionSeed("What was the Code of Hammurabi?",
                     ["An early Babylonian law code", "A Roman census", "An Egyptian religious text", "A Greek constitution"], 0,
                     "Inscribed on a stone stele around 1750 BC, it set penalties for a wide range of offences."),
        QuestionSeed("Which treaty ended the Russo-Japanese War in 1905?",
                     ["The Treaty of Portsmouth", "The Treaty of Shimonoseki", "The Treaty of Nanking", "The Treaty of Brest-Litovsk"], 0,
                     "The U.S.-mediated Treaty of Portsmouth recognized Japan's position in Korea and transferred Russian interests in southern Manchuria."),
        QuestionSeed("What was the Enlightenment principally concerned with?",
                     ["Reason, science, and individual rights", "The renewal of discipline and doctrine inside European monasteries", "Feudal land tenure", "The legal regulation of crafts and commerce by powerful urban guilds"], 0,
                     "Eighteenth-century thinkers challenged inherited authority in politics and religion."),
        QuestionSeed("Which ancient Greek city-state was known for its military discipline?",
                     ["Sparta", "Athens", "Corinth", "Thebes"], 0,
                     "Spartan society organized itself around military training from early childhood."),
        QuestionSeed("The Pragmatic Sanction of 1713 was intended to secure the succession of which ruler?",
                     ["Maria Theresa", "Catherine the Great", "Anne of Britain", "Christina of Sweden"], 0,
                     "Emperor Charles VI sought European acceptance of his daughter's right to inherit the Habsburg lands."),
        QuestionSeed("The Concordat of Worms settled which medieval struggle?",
                     ["The Investiture Controversy", "The Western Schism", "The Albigensian Crusade", "The Hundred Years' War"], 0,
                     "The 1122 agreement divided roles in appointing bishops between emperor and pope."),
        QuestionSeed("The Battle of Talas in 751 was fought between the Abbasid Caliphate and which dynasty?",
                     ["Tang China", "Gupta India", "Sasanian Persia", "Heian Japan"], 0,
                     "Abbasid and allied forces defeated a Tang army near the Talas River in Central Asia."),
        QuestionSeed("Who led the Taiping Rebellion against China's Qing dynasty?",
                     ["Hong Xiuquan", "Sun Yat-sen", "Yuan Shikai", "Zeng Guofan"], 0,
                     "Hong claimed a divine mission and founded the Taiping Heavenly Kingdom in 1851."),
        QuestionSeed("What protection did the Edict of Nantes grant in 1598?",
                     ["Limited rights to French Protestants", "Independence to the Dutch Republic", "Voting rights to French women", "Freedom for enslaved people in French colonies"], 0,
                     "Henry IV used the edict to reduce France's religious conflict; Louis XIV revoked it in 1685."),
        QuestionSeed("What was a satrapy in the Achaemenid Persian Empire?",
                     ["An administrative province", "A royal bodyguard unit", "A religious festival", "A naval formation"], 0,
                     "A satrap governed the province while royal officials and inspectors checked regional power."),
        QuestionSeed("What were the Tanzimat reforms?",
                     ["A nineteenth-century Ottoman modernization programme", "A nineteenth-century Russian rural rebellion against serfdom and taxes", "A Mughal administrative system for assessing and collecting land revenue", "A Japanese isolation policy"], 0,
                     "The reforms reorganized administration, law, taxation, education, and military service."),
        QuestionSeed("Cahokia was the largest known urban centre of which North American culture?",
                     ["The Mississippian culture", "The Ancestral Pueblo culture", "The Dorset culture", "The Clovis culture"], 0,
                     "Its great earthen mounds rose near the Mississippi River across from present-day St. Louis."),
        QuestionSeed("Which treaty ended the Mexican-American War in 1848?",
                     ["The Treaty of Guadalupe Hidalgo", "The Adams-Onís Treaty", "The Treaty of Ghent", "The Gadsden Treaty"], 0,
                     "Mexico recognized the annexation of Texas and ceded a vast northern territory to the United States."),
        QuestionSeed("The Byzantine Iconoclasm controversy centred on what issue?",
                     ["The religious use of sacred images", "The language of imperial law", "The taxation of monasteries", "The location of the capital"], 0,
                     "Supporters and opponents of icons disputed whether their veneration was legitimate or idolatrous."),
    ]
}
