import Foundation

enum LiteratureQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("Who wrote Romeo and Juliet?",
                     ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"], 0,
                     "William Shakespeare wrote the tragedy Romeo and Juliet early in his career."),
        QuestionSeed("Which school does Harry Potter attend?",
                     ["Beauxbatons", "Hogwarts", "Durmstrang", "Ilvermorny"], 1,
                     "Hogwarts School of Witchcraft and Wizardry is the main setting of the Harry Potter series."),
        QuestionSeed("What kind of animal is Charlotte in Charlotte's Web?",
                     ["A pig", "A goose", "A spider", "A sheep"], 2,
                     "Charlotte is the barn spider whose web messages help save Wilbur the pig."),
        QuestionSeed("Who wrote Green Eggs and Ham?",
                     ["Shel Silverstein", "Dr. Seuss", "Maurice Sendak", "E. B. White"], 1,
                     "Dr. Seuss wrote Green Eggs and Ham using a famously limited vocabulary."),
        QuestionSeed("Who wrote the novel 1984?",
                     ["Aldous Huxley", "Ray Bradbury", "George Orwell", "H. G. Wells"], 2,
                     "George Orwell's dystopian novel follows Winston Smith in the totalitarian state of Oceania."),
        QuestionSeed("Who is the central heroine of Pride and Prejudice?",
                     ["Jane Eyre", "Elizabeth Bennet", "Emma Woodhouse", "Jo March"], 1,
                     "Elizabeth Bennet's changing judgment of Mr. Darcy drives Jane Austen's novel."),
        QuestionSeed("What kind of creature is Bilbo Baggins in The Hobbit?",
                     ["An elf", "A dwarf", "A hobbit", "A wizard"], 2,
                     "Bilbo is a comfort-loving hobbit drawn into an adventure with thirteen dwarves."),
        QuestionSeed("What kind of animal is pursued in Moby-Dick?",
                     ["A giant squid", "A white whale", "A sea serpent", "A great shark"], 1,
                     "Captain Ahab obsessively pursues the white sperm whale called Moby Dick."),
        QuestionSeed("Who is the hero of Homer's Odyssey?",
                     ["Achilles", "Odysseus", "Hector", "Theseus"], 1,
                     "Odysseus spends ten years trying to return home to Ithaca after the Trojan War."),
        QuestionSeed("Which animal does Alice follow into Wonderland?",
                     ["A white rabbit", "A striped cat", "A talking mouse", "A blue caterpillar"], 0,
                     "Alice follows the hurried White Rabbit down a hole and into Wonderland."),
        QuestionSeed("What is Sherlock Holmes's profession?",
                     ["A barrister", "A physician", "A detective", "A journalist"], 2,
                     "Sherlock Holmes is a consulting detective who solves cases through close observation and deduction."),
        QuestionSeed("What is the surname of the four sisters in Little Women?",
                     ["March", "Bennet", "Dashwood", "Earnshaw"], 0,
                     "Meg, Jo, Beth, and Amy are the March sisters in Louisa May Alcott's novel."),
        QuestionSeed("Who narrates To Kill a Mockingbird as an adult looking back on childhood?",
                     ["Atticus Finch", "Jem Finch", "Scout Finch", "Dill Harris"], 2,
                     "Jean Louise 'Scout' Finch narrates the story of her childhood in Maycomb, Alabama."),
        QuestionSeed("What piece of furniture leads into Narnia in The Lion, the Witch and the Wardrobe?",
                     ["A wardrobe", "A bookcase", "A mirror", "A writing desk"], 0,
                     "Lucy Pevensie enters Narnia through a wardrobe in the professor's country house."),
        QuestionSeed("What kind of animal is Winnie-the-Pooh?",
                     ["A rabbit", "A bear", "A tiger", "A donkey"], 1,
                     "Winnie-the-Pooh is the honey-loving bear created by A. A. Milne."),
        QuestionSeed("Who brings Frankenstein's creature to life?",
                     ["Henry Jekyll", "Victor Frankenstein", "Jonathan Harker", "Abraham Van Helsing"], 1,
                     "Victor Frankenstein is the scientist; the novel does not give his creature a personal name."),
        QuestionSeed("Katniss Everdeen represents which district in The Hunger Games?",
                     ["District 1", "District 4", "District 7", "District 12"], 3,
                     "Katniss volunteers for the Games as the female tribute from coal-mining District 12."),
        QuestionSeed("Which Greek god is Percy Jackson's father?",
                     ["Apollo", "Ares", "Poseidon", "Hermes"], 2,
                     "Percy learns that he is a demigod son of Poseidon, god of the sea."),
        QuestionSeed("Which road does Dorothy follow in The Wonderful Wizard of Oz?",
                     ["The Yellow Brick Road", "The Great North Road", "The King's Highway", "The Emerald Path"], 0,
                     "Dorothy follows the Yellow Brick Road toward the Emerald City and the Wizard of Oz."),
        QuestionSeed("Where does Peter Pan live?",
                     ["Wonderland", "Neverland", "Oz", "Narnia"], 1,
                     "Peter Pan lives in Neverland, where children do not grow up."),
        QuestionSeed("What does Don Quixote famously mistake for giants?",
                     ["Castle towers", "Windmills", "Mountain peaks", "Sailing ships"], 1,
                     "Don Quixote attacks windmills after imagining that they are threatening giants."),
        QuestionSeed("What kind of fish does Santiago catch in The Old Man and the Sea?",
                     ["A marlin", "A tuna", "A swordfish", "A tarpon"], 0,
                     "Santiago battles an enormous marlin far out in the Gulf Stream."),
        QuestionSeed("Who wrote The Cat in the Hat?",
                     ["Roald Dahl", "Dr. Seuss", "Eric Carle", "Beatrix Potter"], 1,
                     "Dr. Seuss introduced the mischievous Cat in the Hat in 1957."),
        QuestionSeed("Which author created the detective Hercule Poirot?",
                     ["Agatha Christie", "Dorothy L. Sayers", "Arthur Conan Doyle", "Raymond Chandler"], 0,
                     "Agatha Christie created Belgian detective Hercule Poirot for more than thirty novels."),
        QuestionSeed("What is a group of lines in a poem called?",
                     ["A stanza", "A chapter", "A scene", "An index"], 0,
                     "A stanza groups lines in a poem, much as a paragraph groups sentences in prose."),
        QuestionSeed("What kind of book tells the author's own life story?",
                     ["A biography", "An autobiography", "An anthology", "An almanac"], 1,
                     "An autobiography is written by its subject; a biography is written by someone else."),
        QuestionSeed("What is another name an author writes under?",
                     ["A byline", "A pen name", "A subtitle", "A dedication"], 1,
                     "A pen name, also called a pseudonym, lets an author publish under another identity."),
        QuestionSeed("How many works make up a trilogy?",
                     ["Two", "Three", "Four", "Five"], 1,
                     "A trilogy is a set of three connected novels, plays, films, or other works."),
        QuestionSeed("What does a traditional fable usually teach?",
                     ["A moral lesson", "A recipe", "A historical date", "A magic spell"], 0,
                     "Fables use brief stories, often with talking animals, to communicate a moral lesson."),
        QuestionSeed("How many lines does a traditional haiku have?",
                     ["Two", "Three", "Five", "Fourteen"], 1,
                     "A traditional Japanese haiku is arranged in three phrases or lines."),
        QuestionSeed("How many lines are in a sonnet?",
                     ["Eight", "Ten", "Twelve", "Fourteen"], 3,
                     "A sonnet is a fourteen-line poetic form with several established rhyme and meter patterns."),
        QuestionSeed("Who wrote Charlie and the Chocolate Factory?",
                     ["Roald Dahl", "C. S. Lewis", "J. M. Barrie", "Kenneth Grahame"], 0,
                     "Roald Dahl's novel follows Charlie Bucket through Willy Wonka's extraordinary factory."),
        QuestionSeed("What is the main character of a story called?",
                     ["The narrator", "The protagonist", "The editor", "The publisher"], 1,
                     "The protagonist is the principal character whose goals usually drive the story."),
        QuestionSeed("What is a character who opposes the protagonist called?",
                     ["An antagonist", "A narrator", "A confidant", "An understudy"], 0,
                     "An antagonist creates opposition for the protagonist and need not necessarily be a villain."),
        QuestionSeed("What does a story's setting identify?",
                     ["Its time and place", "Its sales figures", "Its chapter count", "Its reading level"], 0,
                     "Setting establishes where and when a story's action occurs."),
        QuestionSeed("What is a book that continues an earlier story called?",
                     ["A sequel", "A preface", "An appendix", "An abridgment"], 0,
                     "A sequel continues characters or events from an earlier work."),
        QuestionSeed("What is a story set before an earlier work called?",
                     ["A sequel", "A prequel", "An epilogue", "An anthology"], 1,
                     "A prequel is created later but takes place before the previously released story."),
        QuestionSeed("Which part of a book lists its chapters and their page numbers?",
                     ["Illustrated glossary", "Alphabetical index", "Table of contents", "Publisher's colophon"], 2,
                     "The table of contents shows the book's major sections in reading order."),
        QuestionSeed("What is a short description printed on a book's cover commonly called?",
                     ["A blurb", "A footnote", "A caption", "A citation"], 0,
                     "A blurb briefly describes or recommends a book for prospective readers."),
        QuestionSeed("Who wrote The Very Hungry Caterpillar?",
                     ["Eric Carle", "Ezra Jack Keats", "Leo Lionni", "Chris Van Allsburg"], 0,
                     "Eric Carle wrote and illustrated The Very Hungry Caterpillar using his distinctive collage style.")
        QuestionSeed("What kind of animal is Aslan in The Chronicles of Narnia?",
                     ["A lion", "A bear", "A wolf", "A stag"], 0,
                     "Aslan the lion rules Narnia and gives his life on the Stone Table for Edmund."),
        QuestionSeed("Who wrote A Christmas Carol?",
                     ["Charles Dickens", "Mark Twain", "Lewis Carroll", "Robert Louis Stevenson"], 0,
                     "Charles Dickens published the ghost story in 1843, and Scrooge entered the language at once."),
        QuestionSeed("How many bears live in the house Goldilocks enters?",
                     ["Three", "Two", "Seven", "Four"], 0,
                     "Three bears return to find their porridge tasted, their chairs used, and Goldilocks asleep upstairs."),
        QuestionSeed("What kind of creature is Smaug in The Hobbit?",
                     ["A dragon", "A giant", "A troll", "A wizard"], 0,
                     "Smaug is the dragon guarding the treasure hoard under the Lonely Mountain in Tolkien's story."),
        QuestionSeed("Which author wrote the Sherlock Holmes stories?",
                     ["Arthur Conan Doyle", "Agatha Christie", "Robert Louis Stevenson", "Edgar Allan Poe"], 0,
                     "Arthur Conan Doyle introduced the detective in 1887 and wrote sixty Holmes stories in total."),
        QuestionSeed("What does the title character of Matilda love most?",
                     ["Reading books", "Playing football", "Baking cakes", "Painting portraits"], 0,
                     "Matilda loves reading, working through the library's books long before she is old enough for school."),
        QuestionSeed("Whose garden does Peter Rabbit sneak into?",
                     ["Mr. McGregor's", "Mr. Tod's", "Mrs. Tiggy-Winkle's", "Squirrel Nutkin's"], 0,
                     "Peter squeezes under the gate into Mr. McGregor's garden and loses his jacket escaping."),
        QuestionSeed("What is a repeated line or section of a poem called?",
                     ["A refrain", "A stanza", "A simile", "A preface"], 0,
                     "A refrain returns at fixed points, giving a poem or song its familiar recurring hook."),
        QuestionSeed("Which Roald Dahl character owns a famous chocolate factory?",
                     ["Willy Wonka", "Mr. Fox", "James Trotter", "Danny's father"], 0,
                     "Willy Wonka hides five golden tickets to choose the children who will tour his factory."),
        QuestionSeed("Which genre tells stories about imagined technology and space travel?",
                     ["Science fiction", "Biography", "Historical romance", "True crime"], 0,
                     "Science fiction builds stories on invented technology, distant planets, and futures that have not happened yet."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("Who wrote Jane Eyre?",
                     ["Emily Brontë", "Charlotte Brontë", "Anne Brontë", "George Eliot"], 1,
                     "Charlotte Brontë published Jane Eyre in 1847 under the pen name Currer Bell."),
        QuestionSeed("Which character is the troubled student at the center of Crime and Punishment?",
                     ["Ivan Karamazov", "Rodion Raskolnikov", "Prince Myshkin", "Yevgeny Bazarov"], 1,
                     "Raskolnikov commits a murder and wrestles with guilt, isolation, and moral responsibility."),
        QuestionSeed("What is the fictional town in One Hundred Years of Solitude?",
                     ["Comala", "Macondo", "Santa María", "Yoknapatawpha"], 1,
                     "The Buendía family founds Macondo, where generations repeat patterns of ambition and solitude."),
        QuestionSeed("Who is the central character of Things Fall Apart?",
                     ["Okonkwo", "Obi Okonkwo", "Ezeulu", "Ikem Osodi"], 0,
                     "Okonkwo is an Igbo leader whose life is disrupted by colonialism and personal rigidity."),
        QuestionSeed("Who wrote The Handmaid's Tale?",
                     ["Ursula K. Le Guin", "Margaret Atwood", "Octavia E. Butler", "Doris Lessing"], 1,
                     "Margaret Atwood published the dystopian novel The Handmaid's Tale in 1985."),
        QuestionSeed("Who wrote Beloved?",
                     ["Alice Walker", "Toni Morrison", "Maya Angelou", "Gloria Naylor"], 1,
                     "Toni Morrison's Beloved confronts the lasting trauma of American slavery."),
        QuestionSeed("Who wrote the 1952 novel Invisible Man?",
                     ["Ralph Ellison", "Richard Wright", "James Baldwin", "Chester Himes"], 0,
                     "Ralph Ellison's unnamed narrator describes being made socially invisible by racism."),
        QuestionSeed("What happens to Gregor Samsa at the start of The Metamorphosis?",
                     ["He loses his memory", "He becomes a giant insect", "He is arrested", "He wakes in another century"], 1,
                     "Gregor wakes to find himself transformed into an enormous insect-like creature."),
        QuestionSeed("During which conflict is Catch-22 primarily set?",
                     ["World War I", "World War II", "The Korean War", "The Vietnam War"], 1,
                     "Joseph Heller's novel follows American airmen stationed in the Mediterranean during World War II."),
        QuestionSeed("Which character becomes 'unstuck in time' in Slaughterhouse-Five?",
                     ["Billy Pilgrim", "Kilgore Trout", "Roland Weary", "Bertram Copeland Rumfoord"], 0,
                     "Billy Pilgrim experiences episodes of his life out of sequence, including the bombing of Dresden."),
        QuestionSeed("What changes instead of Dorian Gray's appearance in The Picture of Dorian Gray?",
                     ["His reflection", "His portrait", "His handwriting", "His shadow"], 1,
                     "Dorian remains outwardly young while his portrait records his age and moral corruption."),
        QuestionSeed("Who is the emotionally detached narrator of The Stranger?",
                     ["Meursault", "Roquentin", "Molho", "Tarrou"], 0,
                     "Meursault narrates Albert Camus's novel in a spare voice marked by emotional detachment."),
        QuestionSeed("Who is the central heroine of Their Eyes Were Watching God?",
                     ["Janie Crawford", "Celie Harris", "Sethe Suggs", "Sula Peace"], 0,
                     "Janie Crawford recounts her search for independence, love, and her own voice."),
        QuestionSeed("Which form does much of The Color Purple use?",
                     ["Diary entries", "Letters", "Newspaper reports", "Court transcripts"], 1,
                     "Alice Walker's novel is largely epistolary, told through Celie's letters."),
        QuestionSeed("Who wrote Midnight's Children?",
                     ["V. S. Naipaul", "Salman Rushdie", "Amitav Ghosh", "Vikram Seth"], 1,
                     "Salman Rushdie links Saleem Sinai's life to India's independence and partition."),
        QuestionSeed("Why is the protagonist of The Namesake named Gogol?",
                     ["For a Russian writer", "For an Indian emperor", "For a family village", "For a Hindu festival"], 0,
                     "Gogol Ganguli is named after Russian writer Nikolai Gogol, whose work matters to his father."),
        QuestionSeed("Which pair travels through the devastated world of The Road?",
                     ["Two brothers", "A father and son", "A mother and daughter", "Two former soldiers"], 1,
                     "Cormac McCarthy's novel follows an unnamed father and son moving through a post-apocalyptic landscape."),
        QuestionSeed("Who narrates The Book Thief?",
                     ["Death", "Liesel", "Hans Hubermann", "Max Vandenburg"], 0,
                     "Death narrates Markus Zusak's novel and observes Liesel Meminger in Nazi Germany."),
        QuestionSeed("In which city is much of The Master and Margarita set?",
                     ["Kyiv", "Moscow", "Prague", "St. Petersburg"], 1,
                     "The devil and his entourage disrupt Soviet Moscow in Mikhail Bulgakov's novel."),
        QuestionSeed("What is the first name of the accused protagonist in Kafka's The Trial?",
                     ["Gregor", "Josef", "Franz", "Karl"], 1,
                     "Josef K. is arrested and prosecuted by an inaccessible authority without learning a clear charge."),
        QuestionSeed("Who is traditionally credited with writing The Tale of Genji?",
                     ["Sei Shōnagon", "Murasaki Shikibu", "Izumi Shikibu", "Ono no Komachi"], 1,
                     "Murasaki Shikibu composed The Tale of Genji at Japan's Heian court."),
        QuestionSeed("The Popol Vuh preserves traditions of which people?",
                     ["The Maya", "The Inca", "The Aztec", "The Taíno"], 0,
                     "The K'iche' Maya Popol Vuh recounts creation, heroic twins, and dynastic origins."),
        QuestionSeed("Who wrote the Persian quatrains commonly known in English as the Rubáiyát?",
                     ["Rumi", "Omar Khayyam", "Hafez", "Ferdowsi"], 1,
                     "Poems attributed to Omar Khayyam became famous in English through Edward FitzGerald's adaptation."),
        QuestionSeed("Who guides Dante through Hell and Purgatory in the Divine Comedy?",
                     ["Virgil", "Homer", "Beatrice", "St. Bernard"], 0,
                     "The Roman poet Virgil guides Dante until Beatrice becomes his guide near Paradise."),
        QuestionSeed("Where are the travelers in The Canterbury Tales headed?",
                     ["Oxford", "Canterbury", "Winchester", "York"], 1,
                     "Chaucer's pilgrims tell stories while traveling to the shrine of Thomas Becket in Canterbury."),
        QuestionSeed("In which language was Beowulf composed?",
                     ["Middle English", "Old English", "Old Norse", "Latin"], 1,
                     "Beowulf is the longest surviving heroic poem in Old English."),
        QuestionSeed("What is blank verse?",
                     ["Unrhymed iambic pentameter", "Rhymed four-line stanzas", "Prose divided into chapters", "Poetry without any rhythm"], 0,
                     "English blank verse normally uses unrhymed iambic pentameter, as in many Shakespeare plays."),
        QuestionSeed("What makes a narrator unreliable?",
                     ["The account cannot be fully trusted", "The narrator appears only once", "The story has no dialogue", "The narrator speaks in verse"], 0,
                     "Bias, limited knowledge, self-deception, or dishonesty can make a narrator's account unreliable."),
        QuestionSeed("What is an epistolary novel?",
                     ["A novel told through documents", "A novel written entirely in rhyme", "A novel without named characters", "A novel adapted from a play"], 0,
                     "Epistolary fiction tells its story through letters, diary entries, emails, or other documents."),
        QuestionSeed("What does the term bildungsroman describe?",
                     ["A coming-of-age novel", "A historical romance", "A detective story", "A verse drama"], 0,
                     "A bildungsroman follows a protagonist's formative years and psychological or moral development."),
        QuestionSeed("Which technique places fantastic events within an otherwise realistic world?",
                     ["Magical realism", "Naturalism", "Social realism", "Documentary prose"], 0,
                     "Magical realism treats extraordinary events as an ordinary part of everyday reality."),
        QuestionSeed("Which technique attempts to reproduce a character's associative flow of thought?",
                     ["Stream of consciousness", "Free indirect discourse", "Dramatic monologue", "Omniscient narration"], 0,
                     "Stream of consciousness imitates the movement and association of thought."),
        QuestionSeed("What is dramatic irony?",
                     ["The audience knows more than a character", "A speaker exaggerates for comic effect", "Two words contradict each other", "A plot ends without resolution"], 0,
                     "Dramatic irony arises when readers or viewers understand something a character does not."),
        QuestionSeed("What is a literary allusion?",
                     ["An indirect reference", "A repeated consonant sound", "A deliberate contradiction", "A detailed stage direction"], 0,
                     "An allusion briefly invokes another work, person, event, or cultural idea."),
        QuestionSeed("What is it called when a sentence continues past the end of a poetic line?",
                     ["Enjambment", "Alliteration", "Caesura", "Refrain"], 0,
                     "Enjambment carries syntax past the end of a poetic line without a terminal pause."),
        QuestionSeed("What organizes recurring patterns of stressed and unstressed syllables in verse?",
                     ["Meter", "Rhyme", "Diction", "Imagery"], 0,
                     "Meter creates recurring rhythmic patterns from stressed and unstressed syllables."),
        QuestionSeed("How many lines are in a couplet?",
                     ["Two", "Three", "Four", "Six"], 0,
                     "A couplet consists of two successive poetic lines, often sharing meter and rhyme."),
        QuestionSeed("Which medal recognizes distinguished American children's literature?",
                     ["The Newbery Medal", "The Caldecott Medal", "The Carnegie Medal for Excellence", "The National Book Award for Poetry"], 0,
                     "The Newbery Medal honors an author; the Caldecott Medal recognizes picture-book illustration."),
        QuestionSeed("Which awards are especially associated with science fiction and fantasy writing?",
                     ["The Hugo Awards", "The Peabody Awards", "The Tony Awards", "The Clio Awards"], 0,
                     "The Hugo Awards recognize science fiction and fantasy across written and dramatic forms."),
        QuestionSeed("Which institution selects the Nobel Prize in Literature?",
                     ["The Swedish Academy", "The Royal Society", "The Académie Française", "The Library of Congress"], 0,
                     "The Swedish Academy selects the recipient of the Nobel Prize in Literature.")
        QuestionSeed("Who wrote Mrs Dalloway?",
                     ["Virginia Woolf", "Katherine Mansfield", "Elizabeth Bowen", "Edith Wharton"], 0,
                     "Virginia Woolf follows a single London day, moving between minds as Clarissa prepares her party."),
        QuestionSeed("Which novel opens with a truth universally acknowledged about single men?",
                     ["Pride and Prejudice", "Sense and Sensibility", "Wuthering Heights", "Middlemarch"], 0,
                     "Pride and Prejudice opens by declaring that a single man with fortune must want a wife."),
        QuestionSeed("Who wrote the play Death of a Salesman?",
                     ["Arthur Miller", "Tennessee Williams", "Eugene O'Neill", "Edward Albee"], 0,
                     "Arthur Miller's 1949 play follows Willy Loman as his belief in easy success collapses."),
        QuestionSeed("Which Russian novel follows Anna's affair with Count Vronsky?",
                     ["Anna Karenina", "Fathers and Sons", "Doctor Zhivago", "Dead Souls"], 0,
                     "Tolstoy's Anna Karenina sets that ruinous affair against Levin's quieter search for a meaningful life."),
        QuestionSeed("Where are the boys stranded in Lord of the Flies?",
                     ["A deserted island", "A boarding school", "A wartime city", "A desert outpost"], 0,
                     "Schoolboys stranded on a deserted island build a society that slides quickly into fear and violence."),
        QuestionSeed("Who wrote the poem The Waste Land?",
                     ["T. S. Eliot", "Ezra Pound", "W. B. Yeats", "Wallace Stevens"], 0,
                     "T. S. Eliot assembled the 1922 poem from fragments, myths, and voices of a broken postwar Europe."),
        QuestionSeed("Which novel is narrated by the butler Stevens?",
                     ["The Remains of the Day", "Atonement", "The French Lieutenant's Woman", "A Passage to India"], 0,
                     "Kazuo Ishiguro lets Stevens narrate The Remains of the Day while missing what he most regrets."),
        QuestionSeed("What does the chorus do in classical Greek drama?",
                     ["Comments on the action", "Plays the leading roles", "Builds the stage sets", "Writes the final act"], 0,
                     "The chorus comments on the action, voicing the community's view of what the characters do."),
        QuestionSeed("Which poet left nearly 1,800 short poems found mostly after her death?",
                     ["Emily Dickinson", "Christina Rossetti", "Elizabeth Barrett Browning", "Marianne Moore"], 0,
                     "Emily Dickinson left bundles of hand-sewn poems that her sister discovered and published posthumously."),
        QuestionSeed("Which term describes a work that mocks another by imitating its style?",
                     ["Parody", "Elegy", "Eulogy", "Anthology"], 0,
                     "A parody copies another work's style closely enough to expose and mock its habits."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("Who wrote Middlemarch?",
                     ["George Eliot", "Elizabeth Gaskell", "Anthony Trollope", "Thomas Hardy"], 0,
                     "George Eliot published Middlemarch in installments in 1871 and 1872."),
        QuestionSeed("Which author wrote Pale Fire, a novel built around a poem and its commentary?",
                     ["Vladimir Nabokov", "Italo Calvino", "Jorge Luis Borges", "Milan Kundera"], 0,
                     "Vladimir Nabokov structures Pale Fire as a 999-line poem surrounded by an editor's notes."),
        QuestionSeed("Which family is at the center of The Sound and the Fury?",
                     ["The Bundrens", "The Compsons", "The Sartorises", "The Sutpens"], 1,
                     "Four sections trace the decline of the Compson family through sharply different perspectives."),
        QuestionSeed("On what date does most of James Joyce's Ulysses take place?",
                     ["16 June 1904", "1 January 1900", "4 July 1910", "11 November 1918"], 0,
                     "Ulysses follows Leopold Bloom through Dublin on 16 June 1904, now celebrated as Bloomsday."),
        QuestionSeed("What is the mysterious object in Jorge Luis Borges's story The Aleph?",
                     ["A point containing every place", "A book that rewrites itself", "A mirror that predicts death", "A map as large as its empire"], 0,
                     "The Aleph is a point in space from which every other point can be seen simultaneously."),
        QuestionSeed("Which narrative address is central to If on a winter's night a traveler?",
                     ["Second person", "First-person plural", "Third-person objective", "Epistolary narration"], 0,
                     "Italo Calvino repeatedly addresses 'you,' the Reader, as interrupted novels accumulate."),
        QuestionSeed("Who is the chief priest at the center of Chinua Achebe's Arrow of God?",
                     ["Ezeulu", "Okonkwo", "Obi", "Odili"], 0,
                     "Ezeulu serves Ulu and struggles with colonial authority and rivalries among the Igbo villages."),
        QuestionSeed("Ngũgĩ wa Thiong'o's Decolonising the Mind argues especially for what?",
                     ["Writing in African languages", "Restoring oral epics to Latin", "Replacing novels with theater", "Ending all literary translation"], 0,
                     "Ngũgĩ connects language choice to culture and colonial power and champions African-language writing."),
        QuestionSeed("Which family anchors Naguib Mahfouz's Cairo Trilogy?",
                     ["The Abd al-Jawad family", "The Buendía family", "The Forsyte family", "The Rougon-Macquart family"], 0,
                     "Three generations of the Abd al-Jawad family reflect social and political change in Cairo."),
        QuestionSeed("Who wrote Snow Country?",
                     ["Yasunari Kawabata", "Jun'ichirō Tanizaki", "Kenzaburō Ōe", "Yukio Mishima"], 0,
                     "Yasunari Kawabata's Snow Country follows an uneasy relationship at a remote hot-spring resort."),
        QuestionSeed("Which Japanese author wrote Kokoro?",
                     ["Natsume Sōseki", "Ryūnosuke Akutagawa", "Kōbō Abe", "Osamu Dazai"], 0,
                     "Natsume Sōseki's Kokoro explores isolation and generational change near the end of the Meiji era."),
        QuestionSeed("Who is the protagonist of Clarice Lispector's The Hour of the Star?",
                     ["Macabéa", "Lóri", "G. H.", "Ana"], 0,
                     "Macabéa is an impoverished typist whose life is mediated by the narrator Rodrigo S. M."),
        QuestionSeed("What fictional Mexican city dominates the final section of Roberto Bolaño's 2666?",
                     ["Santa Teresa", "Comala", "Macondo", "Ciudad Mier"], 0,
                     "Santa Teresa is Bolaño's fictional counterpart to Ciudad Juárez and connects the novel's major sections."),
        QuestionSeed("What unusual span does the title character's life cover in Virginia Woolf's Orlando?",
                     ["Several centuries", "A single afternoon", "Exactly one decade", "Three alternate futures"], 0,
                     "Orlando lives for centuries, changes sex, and moves through successive periods of English history."),
        QuestionSeed("Which fictional region appears throughout William Faulkner's work?",
                     ["Yoknapatawpha County", "Thomas Hardy's Wessex", "Trollope's Barsetshire", "Steinbeck's Salinas Valley"], 0,
                     "Faulkner mapped Yoknapatawpha County as the shared setting for many novels and stories."),
        QuestionSeed("Which food triggers the narrator's rush of memory in In Search of Lost Time?",
                     ["A madeleine", "A macaron", "A croissant", "A financier"], 0,
                     "The taste of a madeleine dipped in tea unexpectedly restores memories of Combray."),
        QuestionSeed("Which rhyme scheme defines terza rima?",
                     ["ABA BCB CDC", "ABAB CDCD", "AABB CCDD", "ABBA ABBA"], 0,
                     "Terza rima links three-line stanzas through an interlocking ABA BCB CDC rhyme scheme."),
        QuestionSeed("How many lines are in a Spenserian stanza?",
                     ["Seven", "Eight", "Nine", "Ten"], 2,
                     "A Spenserian stanza has eight lines of iambic pentameter followed by one alexandrine."),
        QuestionSeed("Which rhyme scheme is characteristic of ottava rima?",
                     ["ABABABCC", "ABBAACCA", "AABCCBDD", "ABCABCAB"], 0,
                     "Ottava rima uses eight hendecasyllabic or iambic lines rhyming ABABABCC."),
        QuestionSeed("What is a caesura?",
                     ["A strong pause within a poetic line", "A repeated word at each line's start", "A poem without a regular meter", "A final unrhymed couplet"], 0,
                     "A caesura is a marked pause within a line, often indicated by punctuation."),
        QuestionSeed("Which figure of speech uses a part to represent a whole?",
                     ["Synecdoche", "Metonymy", "Litotes", "Anaphora"], 0,
                     "In synecdoche, a part can stand for a whole, as 'hands' can mean workers."),
        QuestionSeed("What does free indirect discourse blend?",
                     ["Third-person narration with a character's idiom", "Dialogue with stage directions", "Two first-person narrators in alternating chapters", "Verse with scholarly footnotes"], 0,
                     "Free indirect discourse presents a character's thoughts through third-person narration without a reporting clause."),
        QuestionSeed("In classical drama, what is anagnorisis?",
                     ["A moment of recognition", "The opening invocation", "A comic interruption", "The final stage exit"], 0,
                     "Anagnorisis is the discovery or recognition that transforms a character's understanding of events."),
        QuestionSeed("What does the term pathetic fallacy describe?",
                     ["Giving nature human feelings", "Using deliberately faulty logic", "Mocking a tragic hero", "Ending a poem with a question"], 0,
                     "The pathetic fallacy attributes human emotion or intention to weather, landscape, or other natural things."),
        QuestionSeed("Which critic popularized the term objective correlative?",
                     ["T. S. Eliot", "I. A. Richards", "Northrop Frye", "Cleanth Brooks"], 0,
                     "T. S. Eliot used the term for external facts or events that evoke a particular emotion."),
        QuestionSeed("What is metonymy?",
                     ["Naming something through a related concept", "Comparing two things with like or as", "Replacing a whole with one of its parts", "Repeating an opening consonant"], 0,
                     "Metonymy substitutes an associated term, as 'the crown' can stand for monarchical authority."),
        QuestionSeed("What did Fernando Pessoa mean by a heteronym?",
                     ["A fully developed alternate authorial identity", "A translation published without permission", "A character shared by several unrelated novels", "A word with two opposite meanings"], 0,
                     "Pessoa's heteronyms had distinct biographies, styles, philosophies, and bodies of work."),
        QuestionSeed("What is Oulipo known for?",
                     ["Writing under formal constraints", "Reviving medieval mystery plays", "Publishing anonymous manifestos", "Translating epics into invented languages"], 0,
                     "Oulipo writers explore structures and constraints such as lipograms and mathematical patterns."),
        QuestionSeed("What is a roman à clef?",
                     ["A novel disguising real people as fictional characters", "A novel assembled from newspaper clippings", "A romance written in linked sonnets", "A book whose pages must be read out of order"], 0,
                     "A roman à clef fictionalizes recognizable people or events behind altered names."),
        QuestionSeed("What does beginning a story in medias res mean?",
                     ["Opening in the middle of the action", "Starting with the narrator's birth", "Beginning after the final event", "Opening with a list of characters"], 0,
                     "In medias res opens after important events have already begun, supplying earlier context later."),
        QuestionSeed("What is a manuscript page reused after its earlier writing was erased?",
                     ["A palimpsest", "An incunabulum", "A facsimile", "A chapbook"], 0,
                     "A palimpsest is writing material reused after an earlier text was removed, often leaving traces."),
        QuestionSeed("What is an incunabulum?",
                     ["A European book printed before 1501", "A handwritten scroll from antiquity", "A book banned by a royal court", "An author's corrected proof copy"], 0,
                     "Incunabula are works printed during Europe's earliest period of movable-type printing, through 1500."),
        QuestionSeed("In traditional bookmaking, how is a folio sheet folded?",
                     ["Once", "Twice", "Three times", "Not at all"], 0,
                     "Folding a full sheet once creates two leaves, or four pages, in folio format."),
        QuestionSeed("What information does a traditional colophon provide?",
                     ["Details of a book's production", "Definitions of uncommon words", "Corrections added after printing", "A list of cited passages"], 0,
                     "A colophon records production information such as printer, place, date, typeface, or edition."),
        QuestionSeed("In what year was Shakespeare's First Folio published?",
                     ["1603", "1616", "1623", "1642"], 2,
                     "John Heminges and Henry Condell published the First Folio in 1623, seven years after Shakespeare's death."),
        QuestionSeed("During which Japanese period was The Tale of Genji written?",
                     ["Heian", "Kamakura", "Muromachi", "Edo"], 0,
                     "Murasaki Shikibu wrote at the imperial court during Japan's Heian period."),
        QuestionSeed("In which ancient language is the standard Babylonian Epic of Gilgamesh written?",
                     ["Akkadian", "Sumerian", "Hittite", "Aramaic"], 0,
                     "The standard Babylonian version is Akkadian, although earlier Gilgamesh poems survive in Sumerian."),
        QuestionSeed("In which language was the Panchatantra originally composed?",
                     ["Sanskrit", "Pali", "Persian", "Tamil"], 0,
                     "The Sanskrit Panchatantra uses linked animal fables to teach practical wisdom and statecraft."),
        QuestionSeed("Who wrote the Persian epic Shahnameh?",
                     ["Ferdowsi", "Saadi", "Rumi", "Attar"], 0,
                     "Ferdowsi completed the Shahnameh, or Book of Kings, in the early eleventh century."),
        QuestionSeed("Who is generally credited as the principal author of Dream of the Red Chamber?",
                     ["Cao Xueqin", "Luo Guanzhong", "Wu Cheng'en", "Shi Nai'an"], 0,
                     "Cao Xueqin is credited with the novel's first eighty chapters; its final form has a complex publication history.")
    ]
}
