import Foundation

enum MoviesQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("Who directed the 1975 thriller Jaws?",
                     ["George Lucas", "Steven Spielberg", "James Cameron", "Martin Scorsese"], 1,
                     "It was Spielberg's second theatrical feature and is often called the first summer blockbuster."),
        QuestionSeed("Which animated film features the kingdom of Arendelle?",
                     ["Moana", "Frozen", "Brave", "Tangled"], 1,
                     "Arendelle is the home of sisters Anna and Elsa."),
        QuestionSeed("What colour pill does Neo take in The Matrix?",
                     ["Blue", "Green", "Red", "White"], 2,
                     "The red pill reveals the truth; the blue one would have returned him to the simulation."),
        QuestionSeed("Which film series features a DeLorean converted into a time machine?",
                     ["Star Wars", "Back to the Future", "The Terminator", "Indiana Jones"], 1,
                     "Doc Brown chose the DeLorean partly for its stainless steel body."),
        QuestionSeed("Who is Simba's father in The Lion King?",
                     ["Scar", "Rafiki", "Mufasa", "Zazu"], 2,
                     "Mufasa rules the Pride Lands before his brother Scar seizes the throne."),
        QuestionSeed("Which actor wrote and starred in the 1976 film Rocky?",
                     ["Sylvester Stallone", "Arnold Schwarzenegger", "Bruce Willis", "Burt Reynolds"], 0,
                     "Stallone wrote the screenplay in a few days and insisted on playing the lead."),
        QuestionSeed("What is the name of the cowboy doll in Toy Story?",
                     ["Buzz", "Woody", "Rex", "Slinky"], 1,
                     "Sheriff Woody is Andy's favourite toy until Buzz Lightyear arrives."),
        QuestionSeed("What kind of fish is Nemo?",
                     ["A clownfish", "A blue tang", "An angelfish", "A goldfish"], 0,
                     "Dory, who helps search for him, is a blue tang."),
        QuestionSeed("Which fictional metal powers Black Panther's suit?",
                     ["Adamantium", "Kryptonite", "Vibranium", "Unobtainium"], 2,
                     "Wakanda's entire technological advantage is built on vibranium."),
        QuestionSeed("Who composed the score for Star Wars?",
                     ["Hans Zimmer", "John Williams", "Ennio Morricone", "Howard Shore"], 1,
                     "Williams also scored Jaws, Jurassic Park, and the Indiana Jones films."),
        QuestionSeed("In which film does a character say they are 'king of the world' on a ship's bow?",
                     ["Titanic", "The Perfect Storm", "Master and Commander", "Life of Pi"], 0,
                     "Jack Dawson shouts the line early in James Cameron's 1997 film."),
        QuestionSeed("Which wizarding school does Harry Potter attend?",
                     ["Beauxbatons", "Durmstrang", "Hogwarts", "Ilvermorny"], 2,
                     "Hogwarts School of Witchcraft and Wizardry is in Scotland in the books."),
        QuestionSeed("What is the name of the ogre in the 2001 DreamWorks film?",
                     ["Shrek", "Fiona", "Donkey", "Farquaad"], 0,
                     "Shrek was the first film to win the Academy Award for Best Animated Feature."),
        QuestionSeed("Which film features a shark hunter named Quint?",
                     ["Jaws", "The Meg", "Deep Blue Sea", "Open Water"], 0,
                     "Quint's monologue about the USS Indianapolis is one of the film's best-known scenes."),
        QuestionSeed("Who plays the title role in the Indiana Jones films?",
                     ["Harrison Ford", "Tom Selleck", "Kurt Russell", "Mel Gibson"], 0,
                     "Tom Selleck was originally considered but was committed to a television series."),
        QuestionSeed("Which animated studio made Toy Story?",
                     ["Pixar", "DreamWorks", "Illumination", "Studio Ghibli"], 0,
                     "Toy Story was the first feature film animated entirely with computers."),
        QuestionSeed("What is the name of the hobbit who carries the One Ring to Mordor?",
                     ["Bilbo Baggins", "Frodo Baggins", "Samwise Gamgee", "Peregrin Took"], 1,
                     "Frodo inherits the Ring from Bilbo at the start of The Fellowship of the Ring."),
        QuestionSeed("Which superhero is also known as the Dark Knight?",
                     ["Superman", "Batman", "Spider-Man", "Iron Man"], 1,
                     "The nickname reflects Gotham City's shadowy setting and Batman's methods."),
        QuestionSeed("What is the highest award at the Academy Awards called?",
                     ["Best Picture", "Best Director", "Best Feature", "Best Production"], 0,
                     "It is presented last and awarded to the film's producers."),
        QuestionSeed("Which film features the character Forrest Gump?",
                     ["Forrest Gump", "Big Fish", "Cast Away", "The Green Mile"], 0,
                     "Tom Hanks won the Academy Award for Best Actor for the role."),
        QuestionSeed("What animal is Simba?",
                     ["A tiger", "A lion", "A leopard", "A cheetah"], 1,
                     "His name means lion in Swahili."),
        QuestionSeed("Which film introduced the character Darth Vader?",
                     ["A New Hope", "The Empire Strikes Back", "Return of the Jedi", "The Phantom Menace"], 0,
                     "The 1977 original was later retitled Episode IV: A New Hope."),
        QuestionSeed("Who directed Jurassic Park?",
                     ["Steven Spielberg", "Ridley Scott", "Robert Zemeckis", "James Cameron"], 0,
                     "The 1993 film combined animatronics with then-new computer-generated imagery."),
        QuestionSeed("Which film features the song 'Let It Go'?",
                     ["Moana", "Frozen", "Encanto", "Tangled"], 1,
                     "It won the Academy Award for Best Original Song in 2014."),
        QuestionSeed("What does the acronym 'IMAX' refer to?",
                     ["A large-format film projection system", "A studio", "An awards body", "A film rating"], 0,
                     "IMAX uses a larger frame and screen than standard cinema formats."),
        QuestionSeed("Which actor played Jack Sparrow?",
                     ["Johnny Depp", "Orlando Bloom", "Geoffrey Rush", "Javier Bardem"], 0,
                     "The character debuted in Pirates of the Caribbean: The Curse of the Black Pearl."),
        QuestionSeed("Which city does Spider-Man protect?",
                     ["Metropolis", "New York City", "Gotham City", "Central City"], 1,
                     "Peter Parker's New York setting has always distinguished him from Gotham and Metropolis."),
        QuestionSeed("What is a film's 'sequel'?",
                     ["A film continuing an earlier story", "A film shown before the main feature", "A shortened version", "A foreign-language remake"], 0,
                     "A prequel, by contrast, is set before the events of the original."),
        QuestionSeed("Which studio is associated with the Marvel Cinematic Universe?",
                     ["Marvel Studios", "Warner Bros. Animation", "Lionsgate", "A24"], 0,
                     "The shared universe began with Iron Man in 2008."),
        QuestionSeed("Which film features a young girl named Dorothy and a yellow brick road?",
                     ["The Wizard of Oz", "Alice in Wonderland", "Mary Poppins", "The NeverEnding Story"], 0,
                     "The 1939 film famously shifts from sepia to Technicolor when Dorothy reaches Oz."),
        QuestionSeed("What kind of being is E.T. in E.T. the Extra-Terrestrial?",
                     ["An alien", "A robot", "A ghost", "A dinosaur"], 0,
                     "The stranded visitor befriends Elliott while trying to contact his home world."),
        QuestionSeed("Which child is accidentally left behind in Home Alone?",
                     ["Kevin McCallister", "Charlie Bucket", "Marty McFly", "Daniel LaRusso"], 0,
                     "Kevin defends his family's house after the McCallisters fly to Paris without him."),
        QuestionSeed("What is the name of Nemo's father in Finding Nemo?",
                     ["Marlin", "Gill", "Bruce", "Crush"], 0,
                     "Marlin crosses the ocean with Dory while searching for his son."),
        QuestionSeed("What do the heroes of Ghostbusters investigate and capture?",
                     ["Ghosts", "Aliens", "Dinosaurs", "Robots"], 0,
                     "Their New York business uses fictional particle-beam equipment and containment traps."),
        QuestionSeed("What attraction is being built in Jurassic Park?",
                     ["A dinosaur theme park", "A space station", "An underwater city", "A robot factory"], 0,
                     "The park's cloned dinosaurs escape after its security systems fail."),
        QuestionSeed("Which superhero carries a circular shield marked with a star?",
                     ["Captain America", "Iron Man", "Thor", "Hawkeye"], 0,
                     "Captain America's shield serves as both protection and a thrown weapon."),
        QuestionSeed("Who is Shrek's talkative travelling companion?",
                     ["Donkey", "Puss in Boots", "Farquaad", "Pinocchio"], 0,
                     "Donkey accompanies Shrek on the mission to rescue Princess Fiona."),
        QuestionSeed("Who directed Titanic, released in 1997?",
                     ["James Cameron", "Steven Spielberg", "Ridley Scott", "Ron Howard"], 0,
                     "Cameron also wrote, co-produced, and co-edited the historical romance and disaster film."),
        QuestionSeed("Whose emotions are the central characters in Inside Out?",
                     ["Riley's", "Elsa's", "Moana's", "Boo's"], 0,
                     "Joy, Sadness, Fear, Anger, and Disgust operate inside eleven-year-old Riley's mind."),
        QuestionSeed("What is Indiana Jones's academic profession?",
                     ["Archaeologist", "Astronomer", "Biologist", "Architect"], 0,
                     "Between adventures, Indiana Jones teaches archaeology at a university."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("Which film won the first Academy Award for Outstanding Picture?",
                     ["Wings", "Metropolis", "The Jazz Singer", "The Crowd"], 0,
                     "Wings won at the 1929 ceremony for the 1927-28 season and is recognized as the first Best Picture."),
        QuestionSeed("Who directed Pulp Fiction?",
                     ["Quentin Tarantino", "Martin Scorsese", "Paul Thomas Anderson", "Coen brothers"], 0,
                     "It won the Palme d'Or at Cannes in 1994."),
        QuestionSeed("What is the nickname for Mumbai's Hindi-language film industry?",
                     ["Bollywood", "Nollywood", "Tollywood", "Hollywood"], 0,
                     "Bollywood blends Bombay, now Mumbai, with Hollywood and refers specifically to Hindi-language cinema rather than all Indian film."),
        QuestionSeed("What is the term for the person who oversees a film's visual look and camera work?",
                     ["The cinematographer", "The gaffer", "The producer", "The editor"], 0,
                     "Also called the director of photography, or DP."),
        QuestionSeed("Which film features the character Hannibal Lecter opposite Clarice Starling?",
                     ["The Silence of the Lambs", "Se7en", "Zodiac", "Manhunter"], 0,
                     "It is one of only three films to win all five major Academy Awards."),
        QuestionSeed("Who directed Spirited Away?",
                     ["Hayao Miyazaki", "Isao Takahata", "Makoto Shinkai", "Mamoru Hosoda"], 0,
                     "It won the Academy Award for Best Animated Feature in 2003."),
        QuestionSeed("What does a film's 'director's cut' usually mean?",
                     ["A version reflecting the director's preferred edit", "The shortest version", "A version without music", "The theatrical release"], 0,
                     "It often restores material removed for the theatrical running time."),
        QuestionSeed("Which actor has played James Bond in the most official films?",
                     ["Roger Moore", "Sean Connery", "Daniel Craig", "Pierce Brosnan"], 0,
                     "Moore appeared in seven official Eon Productions films."),
        QuestionSeed("Which acting approach associated with Lee Strasberg uses affective memory and personal experience?",
                     ["Method acting", "Presentational acting", "Viewpoints", "Commedia dell'arte"], 0,
                     "Strasberg's Method adapted ideas from Stanislavski but is only one branch of the broader family of approaches often called method acting."),
        QuestionSeed("Which festival awards the Palme d'Or?",
                     ["Cannes", "Venice", "Berlin", "Sundance"], 0,
                     "Venice awards the Golden Lion and Berlin the Golden Bear."),
        QuestionSeed("Who directed Citizen Kane?",
                     ["Orson Welles", "Alfred Hitchcock", "John Ford", "Billy Wilder"], 0,
                     "Welles was twenty-five when the film was released in 1941."),
        QuestionSeed("What is the name of the sled in Citizen Kane?",
                     ["Rosebud", "Bluebell", "Snowdrop", "Daisy"], 0,
                     "The word is Kane's dying utterance and the film's central mystery."),
        QuestionSeed("Which film franchise features the Xenomorph?",
                     ["Alien", "Predator", "The Thing", "Starship Troopers"], 0,
                     "The creature was designed by the Swiss artist H. R. Giger."),
        QuestionSeed("What is a 'green screen' used for?",
                     ["Replacing a background with other footage", "Colour correction", "Lighting an actor's face", "Displaying a script"], 0,
                     "The technique is called chroma keying, and blue screens work the same way."),
        QuestionSeed("Which director is known for cameo appearances in his own films?",
                     ["Alfred Hitchcock", "Stanley Kubrick", "Akira Kurosawa", "Federico Fellini"], 0,
                     "Spotting the Hitchcock cameo became a game for audiences."),
        QuestionSeed("What does 'CGI' stand for?",
                     ["Computer-Generated Imagery", "Cinema Graphics Interface", "Composite Group Imaging", "Colour Grading Instrument"], 0,
                     "CGI covers everything from creatures to invisible set extensions."),
        QuestionSeed("Which 1972 film centres on the Corleone family?",
                     ["The Godfather", "Goodfellas", "Scarface", "Casino"], 0,
                     "It won Best Picture and its sequel won the award again two years later."),
        QuestionSeed("What is 'final cut privilege' in film production?",
                     ["The contractual right to approve the finished edit", "The closing scene", "The trailer's final shot", "The premiere print"], 0,
                     "Final cut is the finished version; final cut privilege is the authority to approve or control that version."),
        QuestionSeed("Which film opens with a scrolling text crawl in space?",
                     ["Star Wars", "Star Trek", "Dune", "Interstellar"], 0,
                     "The crawl has opened every numbered Star Wars film since 1977."),
        QuestionSeed("Who directed Parasite, the first non-English-language Best Picture winner?",
                     ["Bong Joon-ho", "Park Chan-wook", "Kim Ki-duk", "Lee Chang-dong"], 0,
                     "Parasite won four Academy Awards in 2020, including Best Director."),
        QuestionSeed("What is a 'blockbuster'?",
                     ["A film with very large commercial success", "A film festival prize", "A low-budget independent film", "A director's first feature"], 0,
                     "The term came from wartime slang for a bomb powerful enough to destroy a city block."),
        QuestionSeed("Which actress has received the most Academy Award acting nominations?",
                     ["Meryl Streep", "Katharine Hepburn", "Bette Davis", "Judi Dench"], 0,
                     "Katharine Hepburn holds the record for wins, with four."),
        QuestionSeed("What is 'foley' in filmmaking?",
                     ["Recording everyday sound effects in sync with picture", "Colour timing", "Set construction", "Script supervision"], 0,
                     "Footsteps, cloth rustle, and door handles are typically foley work."),
        QuestionSeed("Which studio's logo features a mountain surrounded by stars?",
                     ["Paramount Pictures", "Universal Pictures", "Columbia Pictures", "20th Century Studios"], 0,
                     "Paramount has used a mountain-and-stars emblem since the silent-film era, with the design evolving over time."),
        QuestionSeed("What is a 'MacGuffin'?",
                     ["An object that drives the plot but matters little in itself", "A camera movement", "A type of lens", "A closing credit"], 0,
                     "Hitchcock popularized the term to describe the thing everyone is chasing."),
        QuestionSeed("Which film features the line 'Here's looking at you, kid'?",
                     ["Casablanca", "Gone with the Wind", "The Maltese Falcon", "Key Largo"], 0,
                     "Humphrey Bogart says it to Ingrid Bergman in the 1942 film."),
        QuestionSeed("What does a film 'editor' do?",
                     ["Assemble shots into the finished sequence", "Write the screenplay", "Design the sets", "Cast the actors"], 0,
                     "Editing shapes pacing, performance, and often the meaning of a scene."),
        QuestionSeed("Which animated feature was the first produced by Walt Disney?",
                     ["Snow White and the Seven Dwarfs", "Pinocchio", "Fantasia", "Bambi"], 0,
                     "Released in 1937, it was the first full-length cel-animated feature in English."),
        QuestionSeed("What is 'practical effects' shorthand for?",
                     ["Effects achieved on set rather than digitally", "Cheap effects", "Sound effects", "Effects added in the trailer"], 0,
                     "Miniatures, prosthetics, and pyrotechnics are all practical effects."),
        QuestionSeed("Which film's protagonist is a boxer named Jake LaMotta?",
                     ["Raging Bull", "Rocky", "The Fighter", "Cinderella Man"], 0,
                     "Martin Scorsese directed and Robert De Niro won an Academy Award for the role."),
        QuestionSeed("Where does most of 12 Angry Men take place?",
                     ["A jury room", "A courtroom", "A police station", "A prison cell"], 0,
                     "The jurors debate a murder verdict in a confined room during a hot day in New York."),
        QuestionSeed("Who directed Goodfellas?",
                     ["Martin Scorsese", "Francis Ford Coppola", "Brian De Palma", "Michael Mann"], 0,
                     "Scorsese adapted the gangster film from Nicholas Pileggi's nonfiction book Wiseguy."),
        QuestionSeed("In which city is Amélie primarily set?",
                     ["Paris", "Rome", "Vienna", "Brussels"], 0,
                     "Much of the story unfolds around the Montmartre neighbourhood of Paris."),
        QuestionSeed("Who directed No Country for Old Men?",
                     ["Joel and Ethan Coen", "David Fincher", "Paul Thomas Anderson", "Sam Mendes"], 0,
                     "The Coen brothers adapted Cormac McCarthy's novel and shared the directing credit."),
        QuestionSeed("How is the protagonist's life structured in Moonlight?",
                     ["Across three stages of his life", "As one continuous night", "Through four alternate endings", "As interviews with his family"], 0,
                     "Different actors portray Chiron as a child, teenager, and adult."),
        QuestionSeed("Who directed Pan's Labyrinth?",
                     ["Guillermo del Toro", "Pedro Almodóvar", "Alfonso Cuarón", "Alejandro González Iñárritu"], 0,
                     "Del Toro blends dark fantasy with the violence of Francoist Spain in 1944."),
        QuestionSeed("Who directed Mad Max: Fury Road?",
                     ["George Miller", "Peter Jackson", "Baz Luhrmann", "Neill Blomkamp"], 0,
                     "Miller also co-created the original Mad Max film series in Australia."),
        QuestionSeed("Which director made The Grand Budapest Hotel?",
                     ["Wes Anderson", "Richard Linklater", "Sofia Coppola", "Alexander Payne"], 0,
                     "The film uses nested narrators and changing aspect ratios to distinguish its time periods."),
        QuestionSeed("What procedure drives the plot of Eternal Sunshine of the Spotless Mind?",
                     ["Erasing memories of a relationship", "Travelling into the future", "Swapping bodies", "Entering a shared dream"], 0,
                     "Joel undergoes memory erasure after learning that Clementine has already removed him from her memories."),
        QuestionSeed("What instrument does Andrew study in Whiplash?",
                     ["Jazz drums", "Classical piano", "Trumpet", "Double bass"], 0,
                     "Andrew is a conservatory drummer pushed by the abusive bandleader Terence Fletcher."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("What is the Kuleshov effect?",
                     ["Meaning created by the juxtaposition of shots", "A lighting technique", "A lens distortion", "A sound mixing method"], 0,
                     "Lev Kuleshov showed audiences read different emotions into an identical face depending on the following shot."),
        QuestionSeed("What does 'diegetic sound' mean?",
                     ["Sound with a source within the story world", "Sound added in post-production", "Orchestral score", "Narration"], 0,
                     "A car radio is diegetic; the film's score usually is not."),
        QuestionSeed("Which film movement produced Bicycle Thieves and Rome, Open City?",
                     ["Italian neorealism", "The French New Wave", "German Expressionism", "Dogme 95"], 0,
                     "It used non-professional actors and real locations in postwar Italy."),
        QuestionSeed("What is a 2.39:1 theatrical image commonly called?",
                     ["Scope widescreen", "Academy ratio", "Full frame", "Vertical format"], 0,
                     "A 2.39:1 image is commonly called scope; it may be created with anamorphic lenses or other capture and cropping methods."),
        QuestionSeed("What was the Hays Code?",
                     ["A self-imposed American film content standard", "A union agreement", "A film stock format", "A distribution contract"], 0,
                     "It governed what American studios would depict from the 1930s until the late 1960s."),
        QuestionSeed("Which director founded the Dogme 95 movement with Thomas Vinterberg?",
                     ["Lars von Trier", "Ingmar Bergman", "Nicolas Winding Refn", "Susanne Bier"], 0,
                     "The manifesto banned artificial lighting, non-diegetic music, and credited directors."),
        QuestionSeed("What is a 'Dutch angle'?",
                     ["A deliberately tilted camera", "An extreme close-up", "A crane shot", "A rear projection"], 0,
                     "It is used to suggest unease or disorientation."),
        QuestionSeed("Which film is credited as the first feature-length film with synchronized dialogue?",
                     ["The Jazz Singer", "Don Juan", "The Lights of New York", "Sunrise"], 0,
                     "The 1927 film's spoken sequences helped end the silent era."),
        QuestionSeed("What does 'mise-en-scène' refer to?",
                     ["Everything arranged within the frame", "The editing rhythm", "The musical score", "The distribution plan"], 0,
                     "Set design, lighting, blocking, and costume are all part of it."),
        QuestionSeed("Which cinematographer shot Dune (2021)?",
                     ["Roger Deakins", "Emmanuel Lubezki", "Robert Richardson", "Greig Fraser"], 3,
                     "Greig Fraser won the Academy Award for Dune; Roger Deakins shot Blade Runner 2049."),
        QuestionSeed("What is 'day for night' shooting?",
                     ["Filming in daylight and treating it to look like night", "Shooting only after sunset", "Using practical moonlight", "Reshooting a scene the next day"], 0,
                     "Underexposure and filtration create the effect; the French title of a Truffaut film refers to it."),
        QuestionSeed("Which 1927 German film is a landmark of science fiction cinema?",
                     ["Metropolis", "Nosferatu", "The Cabinet of Dr. Caligari", "M"], 0,
                     "Fritz Lang's film pioneered visual ideas that science fiction still borrows."),
        QuestionSeed("What does the term 'auteur theory' propose?",
                     ["The director is the primary creative author of a film", "The screenwriter owns the work", "Studios shape films most", "Editors determine meaning"], 0,
                     "It emerged from French criticism in the 1950s, notably in Cahiers du Cinéma."),
        QuestionSeed("What is a 'match cut'?",
                     ["A cut linking two shots by visual or aural similarity", "A jump in time", "A fade to black", "A split screen"], 0,
                     "The bone-to-spacecraft cut in 2001: A Space Odyssey is a famous example."),
        QuestionSeed("Which award is presented by the Directors Guild of America?",
                     ["The DGA Award", "The Golden Globe", "The BAFTA", "The Palme d'Or"], 0,
                     "Its winner has historically been a strong predictor of the Best Director Oscar."),
        QuestionSeed("What is 'the 180-degree rule'?",
                     ["Keeping the camera on one side of an imaginary axis between subjects", "Rotating the camera fully", "Reversing the film", "Shooting in a semicircle"], 0,
                     "Crossing the line can make screen direction confusing for the audience."),
        QuestionSeed("Which film won the Academy Award for Best Picture and was directed by Kathryn Bigelow?",
                     ["The Hurt Locker", "Zero Dark Thirty", "Point Break", "Detroit"], 0,
                     "Bigelow became the first woman to win Best Director, in 2010."),
        QuestionSeed("What was the Technicolor three-strip process?",
                     ["A method recording three colour records on separate film strips", "An early sound system", "A widescreen format", "A projection lamp"], 0,
                     "It produced the saturated look of films such as The Wizard of Oz."),
        QuestionSeed("What is 'ADR' in post-production?",
                     ["Automated dialogue replacement", "Advanced digital rendering", "Audio dynamic range", "Ambient degree recording"], 0,
                     "Actors re-record lines in a studio to replace unusable production sound."),
        QuestionSeed("Which studio-era practice tied actors to one company through long exclusive deals?",
                     ["Long-term option contracts", "Four-walling", "Negative pickup deals", "Day-and-date releasing"], 0,
                     "Under the contract system, studios could repeatedly exercise options that kept performers under exclusive control."),
        QuestionSeed("What is a 'long take'?",
                     ["An unbroken shot of extended duration", "A slow-motion sequence", "A lengthy screenplay", "An extended credit roll"], 0,
                     "Films such as Children of Men and 1917 are known for elaborate long takes."),
        QuestionSeed("Which French director made Breathless in 1960?",
                     ["Jean-Luc Godard", "François Truffaut", "Éric Rohmer", "Claude Chabrol"], 0,
                     "Its jump cuts became a signature of the French New Wave."),
        QuestionSeed("What is colour grading?",
                     ["Adjusting a film's colour and contrast in post-production", "Choosing set paint", "Selecting film stock", "Lighting a scene"], 0,
                     "Modern grading usually occurs in a colour-grading suite as part of the digital-intermediate workflow."),
        QuestionSeed("What is a 'rough cut'?",
                     ["An early assembly of a film before fine editing", "The final release version", "A trailer", "A test screening report"], 0,
                     "It follows the assembly edit and precedes the fine cut and picture lock."),
        QuestionSeed("Which 1954 Japanese film follows villagers hiring warriors for protection?",
                     ["Seven Samurai", "Rashomon", "Yojimbo", "Ran"], 0,
                     "Akira Kurosawa's film was remade in the United States as The Magnificent Seven."),
        QuestionSeed("What does 'box office gross' mean?",
                     ["Total ticket revenue before deductions", "Studio profit", "Marketing spend", "Net earnings after tax"], 0,
                     "Studios typically receive only a share of gross, with exhibitors keeping the rest."),
        QuestionSeed("What is a 'steadicam'?",
                     ["A stabilizing camera rig worn by an operator", "A fixed tripod", "A drone", "A remote-controlled dolly"], 0,
                     "Garrett Brown invented it in the 1970s; Rocky and The Shining were early showcases."),
        QuestionSeed("Which film-theory concept examines how looking is structured by power, identity, and representation?",
                     ["The gaze", "Suture", "The Kuleshov effect", "Montage"], 0,
                     "Laura Mulvey's account of the male gaze is a prominent example; suture more specifically concerns how editing positions viewers within a film."),
        QuestionSeed("What was 'New Hollywood'?",
                     ["A period of director-driven American filmmaking from the late 1960s", "A studio", "A distribution company", "A film festival"], 0,
                     "Coppola, Scorsese, Altman, and Bogdanovich were among its central figures."),
        QuestionSeed("What is 'anamorphic' lensing?",
                     ["Squeezing a wide image onto standard film, then unsqueezing it", "Adding grain", "Shooting in black and white", "Filming underwater"], 0,
                     "It produces the characteristic oval bokeh and horizontal lens flares."),
        QuestionSeed("What does a 'Rashomon-style' narrative present?",
                     ["Conflicting accounts of the same event", "A story told entirely backwards", "A film with no spoken dialogue", "A documentary using hidden cameras"], 0,
                     "The term comes from Akira Kurosawa's Rashomon, in which witnesses give incompatible versions of an incident."),
        QuestionSeed("Which filmmaker is most associated with developing Soviet montage theory?",
                     ["Sergei Eisenstein", "Federico Fellini", "Satyajit Ray", "Ingmar Bergman"], 0,
                     "Eisenstein argued that collision between edited shots could create ideas not present in either image alone."),
        QuestionSeed("What is chiaroscuro lighting?",
                     ["Strong contrast between light and shadow", "Completely even illumination", "Lighting with coloured lasers", "Shooting only at sunrise"], 0,
                     "The technique models forms through dramatic light-dark contrast and is prominent in film noir."),
        QuestionSeed("What is the approximate shape of the Academy aspect ratio?",
                     ["1.37:1", "1.85:1", "2.39:1", "1.66:1"], 0,
                     "The Academy ratio standardized a nearly square 1.37:1 image for sound-era 35 mm filmmaking."),
        QuestionSeed("Which technique became strongly associated with the French New Wave?",
                     ["Jump cuts and location shooting", "Three-strip Technicolor musicals", "Stop-motion creatures", "Rear projection in studio westerns"], 0,
                     "New Wave filmmakers often used lightweight cameras, real locations, direct sound, and conspicuous editing."),
        QuestionSeed("What is an L-cut in film editing?",
                     ["Audio from the first shot continues over the next image", "A shot is rotated ninety degrees", "Two scenes end on identical frames", "The picture cuts before any sound begins"], 0,
                     "The sound overlap smooths the visual transition and can connect a reaction to the preceding speaker."),
        QuestionSeed("What does deep-focus cinematography achieve?",
                     ["Foreground and background remain sharply focused", "Only the nearest face is visible", "Motion blur increases with distance", "The image becomes darker at the edges"], 0,
                     "Deep focus lets viewers choose among actions occurring at different depths within the same shot."),
        QuestionSeed("What is rotoscoping?",
                     ["Tracing or referencing live-action footage frame by frame for animation", "Projecting scenery behind actors", "Recording dialogue after filming", "Shooting miniatures at high speed"], 0,
                     "Animators use filmed movement as a guide, though the resulting images may be highly stylized."),
        QuestionSeed("What does cinéma vérité seek to emphasize?",
                     ["Direct engagement with real people and events using lightweight documentary methods", "Elaborate studio spectacle", "Silent comedy performed on sets", "Animation without dialogue"], 0,
                     "The approach emerged alongside portable synchronized-sound equipment and often acknowledges the camera's presence."),
        QuestionSeed("What does 'pre-Code Hollywood' refer to?",
                     ["American films made before strict Production Code enforcement in 1934", "Films made before sound was invented", "Movies released before the first Academy Awards", "Independent films made outside California"], 0,
                     "Films of the early sound era could address sex, crime, and social issues more openly than later Code-era productions."),
    ]
}
