import Foundation

enum MoviesQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("Who directed the 1975 thriller Jaws?",
                     ["George Lucas", "Steven Spielberg", "James Cameron", "Martin Scorsese"], 1,
                     "It was Spielberg's second theatrical feature and is often called the first summer blockbuster."),
        QuestionSeed("Which animated film features the kingdom of Arendelle?",
                     ["Moana", "Frozen", "Brave", "Tangled"], 1,
                     "Arendelle is the home of sisters Anna and Elsa."),
        QuestionSeed("What colour pill does Neo take in The Matrix?",
                     ["Blue", "Green", "Red", "White"], 2,
                     "The red pill reveals the truth; the blue one would have returned him to the simulation."),
        QuestionSeed("Which film series features a DeLorean converted into a time machine?",
                     ["Star Wars", "Back to the Future", "The Terminator", "Indiana Jones"], 1,
                     "Doc Brown chose the DeLorean partly for its stainless steel body."),
        QuestionSeed("Who is Simba's father in The Lion King?",
                     ["Scar", "Rafiki", "Mufasa", "Zazu"], 2,
                     "Mufasa rules the Pride Lands before his brother Scar seizes the throne."),
        QuestionSeed("Which actor wrote and starred in the 1976 film Rocky?",
                     ["Sylvester Stallone", "Arnold Schwarzenegger", "Bruce Willis", "Burt Reynolds"], 0,
                     "Stallone wrote the screenplay in a few days and insisted on playing the lead."),
        QuestionSeed("What is the name of the cowboy doll in Toy Story?",
                     ["Buzz", "Woody", "Rex", "Slinky"], 1,
                     "Sheriff Woody is Andy's favourite toy until Buzz Lightyear arrives."),
        QuestionSeed("What kind of fish is Nemo?",
                     ["A clownfish", "A blue tang", "An angelfish", "A goldfish"], 0,
                     "Dory, who helps search for him, is a blue tang."),
        QuestionSeed("Which fictional metal powers Black Panther's suit?",
                     ["Adamantium", "Kryptonite", "Vibranium", "Unobtainium"], 2,
                     "Wakanda's entire technological advantage is built on vibranium."),
        QuestionSeed("Who composed the score for Star Wars?",
                     ["Hans Zimmer", "John Williams", "Ennio Morricone", "Howard Shore"], 1,
                     "Williams also scored Jaws, Jurassic Park, and the Indiana Jones films."),
        QuestionSeed("In which film does a character say they are 'king of the world' on a ship's bow?",
                     ["Titanic", "The Perfect Storm", "Master and Commander", "Life of Pi"], 0,
                     "Jack Dawson shouts the line early in James Cameron's 1997 film."),
        QuestionSeed("Which wizarding school does Harry Potter attend?",
                     ["Beauxbatons", "Durmstrang", "Hogwarts", "Ilvermorny"], 2,
                     "Hogwarts School of Witchcraft and Wizardry is in Scotland in the books."),
        QuestionSeed("What is the name of the ogre in the 2001 DreamWorks film?",
                     ["Shrek", "Fiona", "Donkey", "Farquaad"], 0,
                     "Shrek was the first film to win the Academy Award for Best Animated Feature."),
        QuestionSeed("Which film features a shark hunter named Quint?",
                     ["Jaws", "The Meg", "Deep Blue Sea", "Open Water"], 0,
                     "Quint's monologue about the USS Indianapolis is one of the film's best-known scenes."),
        QuestionSeed("Who plays the title role in the Indiana Jones films?",
                     ["Harrison Ford", "Tom Selleck", "Kurt Russell", "Mel Gibson"], 0,
                     "Tom Selleck was originally considered but was committed to a television series."),
        QuestionSeed("Which animated studio made Toy Story?",
                     ["Pixar", "DreamWorks", "Illumination", "Studio Ghibli"], 0,
                     "Toy Story was the first feature film animated entirely with computers."),
        QuestionSeed("What is the name of the hobbit who carries the One Ring to Mordor?",
                     ["Bilbo Baggins", "Frodo Baggins", "Samwise Gamgee", "Peregrin Took"], 1,
                     "Frodo inherits the Ring from Bilbo at the start of The Fellowship of the Ring."),
        QuestionSeed("Which superhero is also known as the Dark Knight?",
                     ["Superman", "Batman", "Spider-Man", "Iron Man"], 1,
                     "The nickname reflects Gotham City's shadowy setting and Batman's methods."),
        QuestionSeed("What is the highest award at the Academy Awards called?",
                     ["Best Picture", "Best Director", "Best Feature", "Best Production"], 0,
                     "It is presented last and awarded to the film's producers."),
        QuestionSeed("Which film features the character Forrest Gump?",
                     ["Forrest Gump", "Big Fish", "Cast Away", "The Green Mile"], 0,
                     "Tom Hanks won the Academy Award for Best Actor for the role."),
        QuestionSeed("What animal is Simba?",
                     ["A tiger", "A lion", "A leopard", "A cheetah"], 1,
                     "His name means lion in Swahili."),
        QuestionSeed("Which film introduced the character Darth Vader?",
                     ["A New Hope", "The Empire Strikes Back", "Return of the Jedi", "The Phantom Menace"], 0,
                     "The 1977 original was later retitled Episode IV: A New Hope."),
        QuestionSeed("Who directed Jurassic Park?",
                     ["Steven Spielberg", "Ridley Scott", "Robert Zemeckis", "James Cameron"], 0,
                     "The 1993 film combined animatronics with then-new computer-generated imagery."),
        QuestionSeed("Which film features the song 'Let It Go'?",
                     ["Moana", "Frozen", "Encanto", "Tangled"], 1,
                     "It won the Academy Award for Best Original Song in 2014."),
        QuestionSeed("What does the acronym 'IMAX' refer to?",
                     ["A large-format film projection system", "A studio", "An awards body", "A film rating"], 0,
                     "IMAX uses a larger frame and screen than standard cinema formats."),
        QuestionSeed("Which actor played Jack Sparrow?",
                     ["Johnny Depp", "Orlando Bloom", "Geoffrey Rush", "Javier Bardem"], 0,
                     "The character debuted in Pirates of the Caribbean: The Curse of the Black Pearl."),
        QuestionSeed("Which city does Spider-Man protect?",
                     ["Metropolis", "New York City", "Gotham City", "Central City"], 1,
                     "Peter Parker's New York setting has always distinguished him from Gotham and Metropolis."),
        QuestionSeed("What is a film's 'sequel'?",
                     ["A film continuing an earlier story", "A film shown before the main feature", "A shortened version", "A foreign-language remake"], 0,
                     "A prequel, by contrast, is set before the events of the original."),
        QuestionSeed("Which studio is associated with the Marvel Cinematic Universe?",
                     ["Marvel Studios", "Warner Bros. Animation", "Lionsgate", "A24"], 0,
                     "The shared universe began with Iron Man in 2008."),
        QuestionSeed("Which film features a young girl named Dorothy and a yellow brick road?",
                     ["The Wizard of Oz", "Alice in Wonderland", "Mary Poppins", "The NeverEnding Story"], 0,
                     "The 1939 film famously shifts from sepia to Technicolor when Dorothy reaches Oz."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("Which film won the first Academy Award for Outstanding Picture?",
                     ["Wings", "Metropolis", "The Jazz Singer", "The Crowd"], 0,
                     "Wings won at the 1929 ceremony for the 1927-28 season and is recognized as the first Best Picture."),
        QuestionSeed("Who directed Pulp Fiction?",
                     ["Quentin Tarantino", "Martin Scorsese", "Paul Thomas Anderson", "Coen brothers"], 0,
                     "It won the Palme d'Or at Cannes in 1994."),
        QuestionSeed("Which country produces films in the industry nicknamed Bollywood?",
                     ["India", "Nigeria", "Pakistan", "Bangladesh"], 0,
                     "The name blends Bombay, now Mumbai, with Hollywood."),
        QuestionSeed("What is the term for the person who oversees a film's visual look and camera work?",
                     ["The cinematographer", "The gaffer", "The producer", "The editor"], 0,
                     "Also called the director of photography, or DP."),
        QuestionSeed("Which film features the character Hannibal Lecter opposite Clarice Starling?",
                     ["The Silence of the Lambs", "Se7en", "Zodiac", "Manhunter"], 0,
                     "It is one of only three films to win all five major Academy Awards."),
        QuestionSeed("Who directed Spirited Away?",
                     ["Hayao Miyazaki", "Isao Takahata", "Makoto Shinkai", "Mamoru Hosoda"], 0,
                     "It won the Academy Award for Best Animated Feature in 2003."),
        QuestionSeed("What does a film's 'director's cut' usually mean?",
                     ["A version reflecting the director's preferred edit", "The shortest version", "A version without music", "The theatrical release"], 0,
                     "It often restores material removed for the theatrical running time."),
        QuestionSeed("Which actor has played James Bond in the most official films?",
                     ["Roger Moore", "Sean Connery", "Daniel Craig", "Pierce Brosnan"], 0,
                     "Moore appeared in seven official Eon Productions films."),
        QuestionSeed("What is 'method acting'?",
                     ["An approach where actors draw deeply on personal emotion and immersion", "Reading lines from cue cards", "Improvising every scene", "Acting without rehearsal"], 0,
                     "It descends from the work of Konstantin Stanislavski and Lee Strasberg."),
        QuestionSeed("Which festival awards the Palme d'Or?",
                     ["Cannes", "Venice", "Berlin", "Sundance"], 0,
                     "Venice awards the Golden Lion and Berlin the Golden Bear."),
        QuestionSeed("Who directed Citizen Kane?",
                     ["Orson Welles", "Alfred Hitchcock", "John Ford", "Billy Wilder"], 0,
                     "Welles was twenty-five when the film was released in 1941."),
        QuestionSeed("What is the name of the sled in Citizen Kane?",
                     ["Rosebud", "Bluebell", "Snowdrop", "Daisy"], 0,
                     "The word is Kane's dying utterance and the film's central mystery."),
        QuestionSeed("Which film franchise features the Xenomorph?",
                     ["Alien", "Predator", "The Thing", "Starship Troopers"], 0,
                     "The creature was designed by the Swiss artist H. R. Giger."),
        QuestionSeed("What is a 'green screen' used for?",
                     ["Replacing a background with other footage", "Colour correction", "Lighting an actor's face", "Displaying a script"], 0,
                     "The technique is called chroma keying, and blue screens work the same way."),
        QuestionSeed("Which director is known for cameo appearances in his own films?",
                     ["Alfred Hitchcock", "Stanley Kubrick", "Akira Kurosawa", "Federico Fellini"], 0,
                     "Spotting the Hitchcock cameo became a game for audiences."),
        QuestionSeed("What does 'CGI' stand for?",
                     ["Computer-Generated Imagery", "Cinema Graphics Interface", "Composite Group Imaging", "Colour Grading Instrument"], 0,
                     "CGI covers everything from creatures to invisible set extensions."),
        QuestionSeed("Which 1972 film centres on the Corleone family?",
                     ["The Godfather", "Goodfellas", "Scarface", "Casino"], 0,
                     "It won Best Picture and its sequel won the award again two years later."),
        QuestionSeed("What is the 'final cut' in film production?",
                     ["The last editing decision authority", "The closing scene", "The trailer", "The premiere print"], 0,
                     "Which party holds final cut is one of the most negotiated points in a director's contract."),
        QuestionSeed("Which film opens with a scrolling text crawl in space?",
                     ["Star Wars", "Star Trek", "Dune", "Interstellar"], 0,
                     "The crawl has opened every numbered Star Wars film since 1977."),
        QuestionSeed("Who directed Parasite, the first non-English-language Best Picture winner?",
                     ["Bong Joon-ho", "Park Chan-wook", "Kim Ki-duk", "Lee Chang-dong"], 0,
                     "Parasite won four Academy Awards in 2020, including Best Director."),
        QuestionSeed("What is a 'blockbuster'?",
                     ["A film with very large commercial success", "A film festival prize", "A low-budget independent film", "A director's first feature"], 0,
                     "The term came from wartime slang for a bomb powerful enough to destroy a city block."),
        QuestionSeed("Which actress has received the most Academy Award acting nominations?",
                     ["Meryl Streep", "Katharine Hepburn", "Bette Davis", "Judi Dench"], 0,
                     "Katharine Hepburn holds the record for wins, with four."),
        QuestionSeed("What is 'foley' in filmmaking?",
                     ["Recording everyday sound effects in sync with picture", "Colour timing", "Set construction", "Script supervision"], 0,
                     "Footsteps, cloth rustle, and door handles are typically foley work."),
        QuestionSeed("Which studio's logo features a mountain surrounded by stars?",
                     ["Paramount Pictures", "Universal Pictures", "Columbia Pictures", "20th Century Studios"], 0,
                     "Paramount is the longest continuously operating film studio in the United States."),
        QuestionSeed("What is a 'MacGuffin'?",
                     ["An object that drives the plot but matters little in itself", "A camera movement", "A type of lens", "A closing credit"], 0,
                     "Hitchcock popularized the term to describe the thing everyone is chasing."),
        QuestionSeed("Which film features the line 'Here's looking at you, kid'?",
                     ["Casablanca", "Gone with the Wind", "The Maltese Falcon", "Key Largo"], 0,
                     "Humphrey Bogart says it to Ingrid Bergman in the 1942 film."),
        QuestionSeed("What does a film 'editor' do?",
                     ["Assemble shots into the finished sequence", "Write the screenplay", "Design the sets", "Cast the actors"], 0,
                     "Editing shapes pacing, performance, and often the meaning of a scene."),
        QuestionSeed("Which animated feature was the first produced by Walt Disney?",
                     ["Snow White and the Seven Dwarfs", "Pinocchio", "Fantasia", "Bambi"], 0,
                     "Released in 1937, it was the first full-length cel-animated feature in English."),
        QuestionSeed("What is 'practical effects' shorthand for?",
                     ["Effects achieved on set rather than digitally", "Cheap effects", "Sound effects", "Effects added in the trailer"], 0,
                     "Miniatures, prosthetics, and pyrotechnics are all practical effects."),
        QuestionSeed("Which film's protagonist is a boxer named Jake LaMotta?",
                     ["Raging Bull", "Rocky", "The Fighter", "Cinderella Man"], 0,
                     "Martin Scorsese directed and Robert De Niro won an Academy Award for the role."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("What is the Kuleshov effect?",
                     ["Meaning created by the juxtaposition of shots", "A lighting technique", "A lens distortion", "A sound mixing method"], 0,
                     "Lev Kuleshov showed audiences read different emotions into an identical face depending on the following shot."),
        QuestionSeed("What does 'diegetic sound' mean?",
                     ["Sound with a source within the story world", "Sound added in post-production", "Orchestral score", "Narration"], 0,
                     "A car radio is diegetic; the film's score usually is not."),
        QuestionSeed("Which film movement produced Bicycle Thieves and Rome, Open City?",
                     ["Italian neorealism", "The French New Wave", "German Expressionism", "Dogme 95"], 0,
                     "It used non-professional actors and real locations in postwar Italy."),
        QuestionSeed("What is an 'aspect ratio' of 2.39:1 commonly called?",
                     ["Anamorphic widescreen", "Academy ratio", "Full frame", "Vertical format"], 0,
                     "The Academy ratio is much narrower, around 1.37:1."),
        QuestionSeed("What was the Hays Code?",
                     ["A self-imposed American film content standard", "A union agreement", "A film stock format", "A distribution contract"], 0,
                     "It governed what American studios would depict from the 1930s until the late 1960s."),
        QuestionSeed("Which director founded the Dogme 95 movement with Thomas Vinterberg?",
                     ["Lars von Trier", "Ingmar Bergman", "Nicolas Winding Refn", "Susanne Bier"], 0,
                     "The manifesto banned artificial lighting, non-diegetic music, and credited directors."),
        QuestionSeed("What is a 'Dutch angle'?",
                     ["A deliberately tilted camera", "An extreme close-up", "A crane shot", "A rear projection"], 0,
                     "It is used to suggest unease or disorientation."),
        QuestionSeed("Which film is credited as the first feature-length film with synchronized dialogue?",
                     ["The Jazz Singer", "Don Juan", "The Lights of New York", "Sunrise"], 0,
                     "The 1927 film's spoken sequences helped end the silent era."),
        QuestionSeed("What does 'mise-en-scène' refer to?",
                     ["Everything arranged within the frame", "The editing rhythm", "The musical score", "The distribution plan"], 0,
                     "Set design, lighting, blocking, and costume are all part of it."),
        QuestionSeed("Which cinematographer is known for Blade Runner 2049 and Dune?",
                     ["Roger Deakins", "Emmanuel Lubezki", "Robert Richardson", "Greig Fraser"], 0,
                     "Deakins won his first Academy Award for Blade Runner 2049 after thirteen nominations."),
        QuestionSeed("What is 'day for night' shooting?",
                     ["Filming in daylight and treating it to look like night", "Shooting only after sunset", "Using practical moonlight", "Reshooting a scene the next day"], 0,
                     "Underexposure and filtration create the effect; the French title of a Truffaut film refers to it."),
        QuestionSeed("Which 1927 German film is a landmark of science fiction cinema?",
                     ["Metropolis", "Nosferatu", "The Cabinet of Dr. Caligari", "M"], 0,
                     "Fritz Lang's film pioneered visual ideas that science fiction still borrows."),
        QuestionSeed("What does the term 'auteur theory' propose?",
                     ["The director is the primary creative author of a film", "The screenwriter owns the work", "Studios shape films most", "Editors determine meaning"], 0,
                     "It emerged from French criticism in the 1950s, notably in Cahiers du Cinéma."),
        QuestionSeed("What is a 'match cut'?",
                     ["A cut linking two shots by visual or aural similarity", "A jump in time", "A fade to black", "A split screen"], 0,
                     "The bone-to-spacecraft cut in 2001: A Space Odyssey is a famous example."),
        QuestionSeed("Which award is presented by the Directors Guild of America?",
                     ["The DGA Award", "The Golden Globe", "The BAFTA", "The Palme d'Or"], 0,
                     "Its winner has historically been a strong predictor of the Best Director Oscar."),
        QuestionSeed("What is 'the 180-degree rule'?",
                     ["Keeping the camera on one side of an imaginary axis between subjects", "Rotating the camera fully", "Reversing the film", "Shooting in a semicircle"], 0,
                     "Crossing the line can make screen direction confusing for the audience."),
        QuestionSeed("Which film won the Academy Award for Best Picture and was directed by Kathryn Bigelow?",
                     ["The Hurt Locker", "Zero Dark Thirty", "Point Break", "Detroit"], 0,
                     "Bigelow became the first woman to win Best Director, in 2010."),
        QuestionSeed("What was the Technicolor three-strip process?",
                     ["A method recording three colour records on separate film strips", "An early sound system", "A widescreen format", "A projection lamp"], 0,
                     "It produced the saturated look of films such as The Wizard of Oz."),
        QuestionSeed("What is 'ADR' in post-production?",
                     ["Automated dialogue replacement", "Advanced digital rendering", "Audio dynamic range", "Ambient degree recording"], 0,
                     "Actors re-record lines in a studio to replace unusable production sound."),
        QuestionSeed("Which studio system practice tied actors to long exclusive contracts?",
                     ["The Hollywood studio system of the 1930s and 1940s", "The Dogme movement", "The New Hollywood era", "The independent boom"], 0,
                     "Studios controlled production, distribution, and exhibition until antitrust rulings intervened."),
        QuestionSeed("What is a 'long take'?",
                     ["An unbroken shot of extended duration", "A slow-motion sequence", "A lengthy screenplay", "An extended credit roll"], 0,
                     "Films such as Children of Men and 1917 are known for elaborate long takes."),
        QuestionSeed("Which French director made Breathless in 1960?",
                     ["Jean-Luc Godard", "François Truffaut", "Éric Rohmer", "Claude Chabrol"], 0,
                     "Its jump cuts became a signature of the French New Wave."),
        QuestionSeed("What is 'colour grading'?",
                     ["Adjusting a film's colour and contrast in post-production", "Choosing set paint", "Selecting film stock", "Lighting a scene"], 0,
                     "Modern grading is done digitally in a suite called a DI, or digital intermediate."),
        QuestionSeed("What is a 'rough cut'?",
                     ["An early assembly of a film before fine editing", "The final release version", "A trailer", "A test screening report"], 0,
                     "It follows the assembly edit and precedes the fine cut and picture lock."),
        QuestionSeed("Which 1954 Japanese film follows villagers hiring warriors for protection?",
                     ["Seven Samurai", "Rashomon", "Yojimbo", "Ran"], 0,
                     "Akira Kurosawa's film was remade in the United States as The Magnificent Seven."),
        QuestionSeed("What does 'box office gross' mean?",
                     ["Total ticket revenue before deductions", "Studio profit", "Marketing spend", "Net earnings after tax"], 0,
                     "Studios typically receive only a share of gross, with exhibitors keeping the rest."),
        QuestionSeed("What is a 'steadicam'?",
                     ["A stabilizing camera rig worn by an operator", "A fixed tripod", "A drone", "A remote-controlled dolly"], 0,
                     "Garrett Brown invented it in the 1970s; Rocky and The Shining were early showcases."),
        QuestionSeed("Which film theory term describes the viewer's identification with the camera?",
                     ["The gaze", "The cut", "The frame", "The take"], 0,
                     "Laura Mulvey's 1975 essay on the male gaze is the best-known treatment."),
        QuestionSeed("What was 'New Hollywood'?",
                     ["A period of director-driven American filmmaking from the late 1960s", "A studio", "A distribution company", "A film festival"], 0,
                     "Coppola, Scorsese, Altman, and Bogdanovich were among its central figures."),
        QuestionSeed("What is 'anamorphic' lensing?",
                     ["Squeezing a wide image onto standard film, then unsqueezing it", "Adding grain", "Shooting in black and white", "Filming underwater"], 0,
                     "It produces the characteristic oval bokeh and horizontal lens flares."),
    ]
}
