import Foundation

enum MusicQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("How many strings does a standard guitar have?",
                     ["Four", "Five", "Six", "Seven"], 2,
                     "A bass guitar normally has four."),
        QuestionSeed("Which instrument has black and white keys?",
                     ["The violin", "The piano", "The flute", "The drum"], 1,
                     "A standard piano has eighty-eight keys."),
        QuestionSeed("Which band released the album Abbey Road?",
                     ["The Rolling Stones", "The Beatles", "The Who", "Led Zeppelin"], 1,
                     "Its cover photograph of the zebra crossing is one of the most imitated images in music."),
        QuestionSeed("How many musicians are in a quartet?",
                     ["Two", "Three", "Four", "Five"], 2,
                     "A trio has three and a quintet has five."),
        QuestionSeed("Which instrument is played with a bow and held under the chin?",
                     ["The cello", "The violin", "The harp", "The trumpet"], 1,
                     "The cello is larger and is played seated, resting on the floor."),
        QuestionSeed("Who is known as the King of Pop?",
                     ["Elvis Presley", "Michael Jackson", "Prince", "James Brown"], 1,
                     "The nickname became attached to Jackson in the 1980s after Thriller."),
        QuestionSeed("What does a conductor lead?",
                     ["An orchestra", "A choir only", "A recording studio", "A record label"], 0,
                     "Conductors also lead choirs and other large ensembles."),
        QuestionSeed("Which instrument family does the trumpet belong to?",
                     ["Strings", "Woodwind", "Brass", "Percussion"], 2,
                     "Brass instruments are sounded by buzzing the lips into a mouthpiece."),
        QuestionSeed("How many lines are in a standard musical staff?",
                     ["Three", "Four", "Five", "Six"], 2,
                     "Notes sit on the lines and in the spaces between them."),
        QuestionSeed("Which country is reggae music most associated with?",
                     ["Cuba", "Jamaica", "Brazil", "Trinidad"], 1,
                     "Reggae developed in Jamaica in the 1960s from ska and rocksteady."),
        QuestionSeed("Who sang 'Like a Rolling Stone'?",
                     ["Bob Dylan", "Neil Young", "Bruce Springsteen", "Tom Petty"], 0,
                     "Dylan released it in 1965 and later won the Nobel Prize in Literature."),
        QuestionSeed("Which drum is struck by the beater attached to a kick pedal?",
                     ["The snare drum", "The bass drum", "The floor tom", "The rack tom"], 1,
                     "The kick pedal drives a beater into the bass-drum head; a separate foot pedal commonly operates the hi-hat."),
        QuestionSeed("What is the term for how fast a piece of music is played?",
                     ["Pitch", "Tempo", "Timbre", "Dynamics"], 1,
                     "Tempo is often marked in beats per minute."),
        QuestionSeed("Which group performed 'Bohemian Rhapsody'?",
                     ["Queen", "The Kinks", "Pink Floyd", "Genesis"], 0,
                     "The 1975 song moves through ballad, opera, and hard rock sections."),
        QuestionSeed("How many notes are in a standard major scale before repeating?",
                     ["Five", "Six", "Seven", "Eight"], 2,
                     "Seven distinct notes, with the eighth repeating the first an octave higher."),
        QuestionSeed("Which instrument is Louis Armstrong best known for playing?",
                     ["The saxophone", "The trumpet", "The clarinet", "The piano"], 1,
                     "Armstrong was also one of the most influential vocalists in jazz."),
        QuestionSeed("What is a song's repeated main section usually called?",
                     ["The verse", "The chorus", "The bridge", "The intro"], 1,
                     "The bridge is the contrasting section that usually appears once."),
        QuestionSeed("Which genre is Nashville, Tennessee most associated with?",
                     ["Country", "Techno", "Opera", "Reggae"], 0,
                     "The Grand Ole Opry has broadcast from Nashville since 1925."),
        QuestionSeed("Which instrument has 47 strings and is plucked?",
                     ["The harp", "The lute", "The banjo", "The mandolin"], 0,
                     "A modern concert harp also has seven pedals to change key."),
        QuestionSeed("Who composed the Fifth Symphony beginning with four famous notes?",
                     ["Mozart", "Beethoven", "Bach", "Brahms"], 1,
                     "Beethoven completed it in 1808."),
        QuestionSeed("What is an a cappella performance?",
                     ["Singing without instrumental accompaniment", "Singing in a foreign language", "A solo instrumental", "An orchestral overture"], 0,
                     "The term is Italian and originally referred to chapel style."),
        QuestionSeed("Which instrument does a violinist use to produce sound?",
                     ["A pick", "A bow", "A mallet", "A reed"], 1,
                     "The bow is strung with horsehair treated with rosin."),
        QuestionSeed("Which decade is disco most associated with?",
                     ["The 1950s", "The 1960s", "The 1970s", "The 1990s"], 2,
                     "Disco dominated dance floors in the second half of the 1970s."),
        QuestionSeed("What does 'forte' mean in music?",
                     ["Loud", "Soft", "Fast", "Slow"], 0,
                     "Piano is the marking for soft, which is where the instrument's name comes from."),
        QuestionSeed("Which band is Mick Jagger the lead singer of?",
                     ["The Beatles", "The Rolling Stones", "The Doors", "The Byrds"], 1,
                     "The Rolling Stones formed in London in 1962."),
        QuestionSeed("What is the highest common female singing voice?",
                     ["Alto", "Soprano", "Tenor", "Bass"], 1,
                     "The order from high to low is soprano, mezzo-soprano, and alto."),
        QuestionSeed("Which instrument is central to a bagpipe's sound?",
                     ["A reed and a bag of air", "A hammer and strings", "A bow", "A keyboard"], 0,
                     "The bag maintains steady pressure so the sound never stops for breath."),
        QuestionSeed("What is a 'single' in the music industry?",
                     ["A song released on its own", "A live concert", "A solo artist", "A one-hour album"], 0,
                     "Singles are usually chosen to promote a larger album."),
        QuestionSeed("Which instrument does a cellist play sitting down?",
                     ["The cello", "The double bass", "The viola", "The violin"], 0,
                     "The cello rests on an endpin that supports it on the floor."),
        QuestionSeed("What does DJ stand for?",
                     ["Disc jockey", "Dance juggler", "Digital jammer", "Drum joiner"], 0,
                     "The name dates to radio presenters who played records on air."),
        QuestionSeed("Which instrument family includes drums and cymbals?",
                     ["Percussion", "Woodwind", "Brass", "Strings"], 0,
                     "Percussion instruments sound when struck, shaken, or scraped."),
        QuestionSeed("Who was the lead singer of Queen?",
                     ["Freddie Mercury", "David Bowie", "Elton John", "Robert Plant"], 0,
                     "Mercury also wrote Queen songs including 'Bohemian Rhapsody' and 'Somebody to Love.'"),
        QuestionSeed("What do you call a person who plays the piano?",
                     ["A pianist", "A violinist", "A percussionist", "A flautist"], 0,
                     "Pianists may perform solo, accompany singers, or play within ensembles."),
        QuestionSeed("How many strings does a standard violin have?",
                     ["Four", "Five", "Six", "Eight"], 0,
                     "The strings are normally tuned G, D, A, and E from lowest to highest."),
        QuestionSeed("What does a rest indicate in written music?",
                     ["A period of silence", "A repeated note", "A key change", "A louder passage"], 0,
                     "Different rest symbols specify how long the silence lasts."),
        QuestionSeed("How many performers take part in a duet?",
                     ["Two", "Three", "Four", "Five"], 0,
                     "A duet may be written for two singers, two instrumentalists, or one of each."),
        QuestionSeed("Which English city are the Beatles most associated with?",
                     ["Liverpool", "Manchester", "Birmingham", "Bristol"], 0,
                     "John Lennon, Paul McCartney, George Harrison, and Ringo Starr all came from Liverpool."),
        QuestionSeed("What is the lowest common adult male singing voice?",
                     ["Bass", "Tenor", "Baritone", "Countertenor"], 0,
                     "Bass lies below baritone and tenor in the usual classification of adult male voices."),
        QuestionSeed("Which clef is normally used for higher-pitched notes?",
                     ["Treble clef", "Bass clef", "Percussion clef", "Tablature"], 0,
                     "Treble clef places G above middle C on the second line of the staff."),
        QuestionSeed("What does the tempo marking 'allegro' usually mean?",
                     ["Fast and lively", "Very slow", "Gradually softer", "Smooth and connected"], 0,
                     "Exact tempo varies with style, but allegro indicates a brisk character."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("How many keys does a standard full-size piano have?",
                     ["76", "80", "88", "96"], 2,
                     "Fifty-two white keys and thirty-six black ones."),
        QuestionSeed("What does the term 'octave' describe?",
                     ["The interval between a note and one at double its frequency", "A group of eight musicians", "An eight-bar phrase", "A chord of eight notes"], 0,
                     "Notes an octave apart share a name because they sound so closely related."),
        QuestionSeed("Which composer wrote The Four Seasons?",
                     ["Antonio Vivaldi", "Johann Sebastian Bach", "George Frideric Handel", "Joseph Haydn"], 0,
                     "The four violin concertos were published around 1725."),
        QuestionSeed("What is a 'key signature'?",
                     ["Sharps or flats at the start of a staff indicating the key", "The composer's signature", "The tempo marking", "The time signature"], 0,
                     "It saves writing an accidental on every affected note."),
        QuestionSeed("Which genre did Robert Johnson help define in the 1930s?",
                     ["The blues", "Bebop", "Country", "Gospel"], 0,
                     "His Delta blues recordings influenced generations of rock guitarists."),
        QuestionSeed("What does a time signature of 3/4 indicate?",
                     ["Three quarter-note beats per bar", "Three bars per phrase", "Four beats in three bars", "A tempo of 34"], 0,
                     "3/4 is the waltz metre."),
        QuestionSeed("Which instrument is a member of the woodwind family despite being made of brass?",
                     ["The saxophone", "The trombone", "The French horn", "The tuba"], 0,
                     "It is classed by its single reed, not its material."),
        QuestionSeed("Who composed the opera The Magic Flute?",
                     ["Wolfgang Amadeus Mozart", "Giuseppe Verdi", "Richard Wagner", "Giacomo Puccini"], 0,
                     "Mozart completed it in 1791, the year he died."),
        QuestionSeed("What is 'syncopation'?",
                     ["Emphasis on normally weak beats", "Playing very quietly", "Repeating a phrase", "Slowing gradually"], 0,
                     "It is fundamental to jazz, funk, and much popular music."),
        QuestionSeed("Which record label was founded in Detroit and shaped 1960s soul?",
                     ["Motown", "Stax", "Atlantic", "Chess"], 0,
                     "Berry Gordy founded it in 1959."),
        QuestionSeed("What is a 'minor key' often described as sounding?",
                     ["Darker or sadder than major", "Louder", "Faster", "Higher"], 0,
                     "The difference comes largely from the lowered third degree of the scale."),
        QuestionSeed("Which instrument did Jimi Hendrix famously play?",
                     ["Electric guitar", "Bass guitar", "Drums", "Keyboard"], 0,
                     "He often played a right-handed Stratocaster restrung and flipped for left hand."),
        QuestionSeed("What is an 'arpeggio'?",
                     ["The notes of a chord played in sequence", "A rapid drum roll", "A key change", "A vocal run"], 0,
                     "The word comes from the Italian for harp-like."),
        QuestionSeed("Which musical form is associated with a repeated twelve-bar chord pattern?",
                     ["The blues", "The sonata", "The fugue", "The rondo"], 0,
                     "The twelve-bar structure underpins a huge amount of blues and early rock."),
        QuestionSeed("What does 'crescendo' instruct a performer to do?",
                     ["Gradually get louder", "Gradually get quieter", "Speed up", "Stop"], 0,
                     "Diminuendo, or decrescendo, is the opposite."),
        QuestionSeed("Which instrument sits at the centre of a classical string quartet alongside two violins and a cello?",
                     ["The viola", "The double bass", "The harp", "The guitar"], 0,
                     "The viola is tuned a fifth below the violin."),
        QuestionSeed("Who wrote the musical Hamilton?",
                     ["Lin-Manuel Miranda", "Stephen Sondheim", "Andrew Lloyd Webber", "Jonathan Larson"], 0,
                     "It opened on Broadway in 2015 and won eleven Tony Awards."),
        QuestionSeed("What is falsetto?",
                     ["A light vocal register produced with a different vocal-fold vibration pattern", "Singing off-key", "A whispered vocal", "A low chest register"], 0,
                     "Falsetto can overlap the pitch range of modal voice; it is defined by how the vocal folds vibrate rather than pitch alone."),
        QuestionSeed("Which genre emerged in the Bronx in the 1970s?",
                     ["Hip hop", "Grunge", "Ska", "Bluegrass"], 0,
                     "DJ Kool Herc's block parties are often cited as a starting point."),
        QuestionSeed("What is a concerto?",
                     ["A work usually featuring one or more soloists with an orchestra", "A piece only for solo piano", "An unaccompanied choral work", "A short dance"], 0,
                     "Many concertos feature one soloist, while forms such as the concerto grosso feature a group of soloists."),
        QuestionSeed("Which instrument produces sound by air passing over an opening rather than a reed?",
                     ["The flute", "The oboe", "The clarinet", "The bassoon"], 0,
                     "The others are all reed instruments."),
        QuestionSeed("What does 'a minor third' refer to?",
                     ["An interval of three semitones", "A third musician", "A third movement", "A three-beat bar"], 0,
                     "A major third spans four semitones."),
        QuestionSeed("Which composer continued writing after losing his hearing?",
                     ["Ludwig van Beethoven", "Franz Schubert", "Frédéric Chopin", "Robert Schumann"], 0,
                     "His late string quartets were written when he was almost completely deaf."),
        QuestionSeed("What is 'sampling' in music production?",
                     ["Reusing a portion of an existing recording", "Testing studio equipment", "Recording a demo", "Mixing live sound"], 0,
                     "It became central to hip hop and electronic music."),
        QuestionSeed("Which instrument has pedals that change the pitch of its strings?",
                     ["The harp", "The guitar", "The banjo", "The mandolin"], 0,
                     "Each of the seven pedals adjusts all strings of one note name."),
        QuestionSeed("What does 'legato' mean?",
                     ["Smoothly connected", "Sharply detached", "Very loud", "Very slow"], 0,
                     "Staccato is the opposite, with each note shortened and separated."),
        QuestionSeed("Which festival held in 1969 became a landmark of the counterculture era?",
                     ["Woodstock", "Glastonbury", "Coachella", "Monterey Pop"], 0,
                     "It drew several hundred thousand people to a dairy farm in New York State."),
        QuestionSeed("What is a 'capo' used for on a guitar?",
                     ["Raising the pitch of all strings", "Muting the strings", "Tuning the low E", "Amplifying the sound"], 0,
                     "It clamps across a fret, effectively shortening every string at once."),
        QuestionSeed("Which vocal range sits between tenor and bass?",
                     ["Baritone", "Alto", "Mezzo-soprano", "Countertenor"], 0,
                     "Baritone is the most common adult male voice type."),
        QuestionSeed("What is 'polyphony'?",
                     ["Multiple independent melodic lines sounding together", "A single melody", "A drum pattern", "An electronic effect"], 0,
                     "Renaissance choral music and Bach's fugues are classic examples."),
        QuestionSeed("What is a leitmotif?",
                     ["A recurring musical idea associated with a character, place, or concept", "A repeated drum fill", "The final chord of a symphony", "An improvised solo introduction"], 0,
                     "Richard Wagner used interconnected leitmotifs extensively in his operas."),
        QuestionSeed("What is a blue note?",
                     ["A pitch deliberately lowered or bent for expressive effect", "Any note played by a saxophone", "The tonic of a major scale", "A silent beat in a blues song"], 0,
                     "Flattened or flexible thirds, fifths, and sevenths are characteristic of blues expression."),
        QuestionSeed("What do numbers represent in the Nashville Number System?",
                     ["Chords built on scale degrees", "Fingerings for guitar strings", "Studio track numbers", "Beats per minute"], 0,
                     "Because the numbers describe harmonic function, musicians can transpose a song without rewriting the chart."),
        QuestionSeed("How is a theremin played?",
                     ["By moving the hands near antennas without touching them", "By striking tuned metal bars", "By blowing across glass tubes", "By turning a hand crank"], 0,
                     "One antenna controls pitch and the other volume through the player's hand position."),
        QuestionSeed("What is a prepared piano?",
                     ["A piano whose sound is altered by objects placed on or between its strings", "A piano tuned before every movement", "A keyboard connected only to headphones", "A piano built without pedals"], 0,
                     "John Cage made the technique famous by using screws, bolts, rubber, and other materials."),
        QuestionSeed("What is a pedal point?",
                     ["A sustained or repeated note beneath changing harmony", "A note played only with the sustain pedal", "The highest note of a melody", "A sudden pause before a cadence"], 0,
                     "A pedal point often remains on the dominant or tonic while tension accumulates above it."),
        QuestionSeed("What structural feature defines a rondo?",
                     ["A principal section returns between contrasting episodes", "Every section uses a new key and melody", "Two themes are developed without return", "The piece repeats one chord continuously"], 0,
                     "A common rondo outline is ABACA, with A serving as the recurring refrain."),
        QuestionSeed("What is clave in Afro-Cuban music?",
                     ["A recurring organizing rhythm", "A type of brass mute", "A vocal range", "A twelve-string guitar"], 0,
                     "Two-bar patterns such as son clave guide the relationship among percussion, bass, and melody."),
        QuestionSeed("What does 'the head' mean in a jazz performance?",
                     ["The composition's main melody", "The drummer's opening fill", "The highest improvised note", "The final audience bow"], 0,
                     "Players commonly state the head, improvise over its form, and return to the head at the end."),
        QuestionSeed("What is a bridge in a popular song?",
                     ["A contrasting section connecting or interrupting repeated sections", "The first beat of every bar", "An instrumental tuning pause", "A repeated chorus with identical words"], 0,
                     "A bridge introduces new harmony, melody, or perspective before the song returns to familiar material."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("What is a 'tritone' historically nicknamed?",
                     ["The devil in music", "The golden interval", "The perfect gate", "The lost fifth"], 0,
                     "Its unstable sound made it a defining feature of later blues and jazz harmony."),
        QuestionSeed("What does 'twelve-tone technique' involve?",
                     ["Using all twelve chromatic pitches in a fixed order", "Twelve-bar blues", "A twelve-note scale", "Twelve instruments"], 0,
                     "Arnold Schoenberg developed it in the 1920s to avoid a tonal centre."),
        QuestionSeed("What is a 'fugue'?",
                     ["A contrapuntal work where a theme is imitated across voices", "A slow introduction", "A dance movement", "A vocal solo"], 0,
                     "Bach's The Art of Fugue is the best-known study of the form."),
        QuestionSeed("What is 'equal temperament'?",
                     ["Dividing the octave into twelve equal semitones", "Tuning to pure ratios", "A dynamic marking", "A tempo system"], 0,
                     "It makes every key usable at the cost of slightly impure intervals."),
        QuestionSeed("What does 'Köchel number' identify?",
                     ["A catalogue number for Mozart's works", "A tempo scale", "A tuning standard", "A German copyright code"], 0,
                     "Ludwig von Köchel compiled the chronological catalogue in 1862."),
        QuestionSeed("What is 'sonata form' built around?",
                     ["Exposition, development, and recapitulation", "Verse and chorus", "A repeated ground bass", "A single theme repeated"], 0,
                     "It became the standard first-movement structure in the classical era."),
        QuestionSeed("Which frequency is the modern standard concert pitch for A above middle C?",
                     ["440 Hz", "432 Hz", "415 Hz", "460 Hz"], 0,
                     "A440 was adopted as an international standard in the twentieth century."),
        QuestionSeed("What is a 'Neapolitan sixth' chord?",
                     ["A major chord built on the flattened second degree", "A diminished seventh", "An inverted dominant", "A suspended fourth"], 0,
                     "It typically appears in first inversion, moving toward the dominant."),
        QuestionSeed("What is 'musique concrète'?",
                     ["Composition built from recorded natural sounds", "Concrete-hall acoustics", "Minimalist piano writing", "Serial vocal music"], 0,
                     "Pierre Schaeffer pioneered it in Paris in the late 1940s."),
        QuestionSeed("What does 'ostinato' mean?",
                     ["A persistently repeated musical figure", "A sudden silence", "A rising scale", "A key change"], 0,
                     "Ravel's Boléro is built on an ostinato that runs the whole piece."),
        QuestionSeed("Which composer wrote The Rite of Spring, whose 1913 premiere provoked a famous audience disturbance?",
                     ["Igor Stravinsky", "Claude Debussy", "Maurice Ravel", "Béla Bartók"], 0,
                     "Accounts differ over the disturbance's scale and whether the music, choreography, or social rivalries caused it."),
        QuestionSeed("What is a 'plagal cadence'?",
                     ["A IV to I chord progression", "A V to I progression", "An unresolved ending", "A modulation"], 0,
                     "It is sometimes called the 'amen cadence' from its use in hymns."),
        QuestionSeed("What does 'rubato' instruct a performer to do?",
                     ["Flexibly stretch and compress the tempo", "Play strictly in time", "Play very loudly", "Repeat a section"], 0,
                     "The term literally means 'stolen' time."),
        QuestionSeed("What is the 'circle of fifths' used for?",
                     ["Showing relationships between keys and their signatures", "Tuning drums", "Measuring tempo", "Naming intervals only"], 0,
                     "Moving clockwise adds a sharp; counterclockwise adds a flat."),
        QuestionSeed("What is 'counterpoint'?",
                     ["The relationship between independent simultaneous melodies", "A rhythmic accent", "A chord inversion", "A vocal technique"], 0,
                     "Species counterpoint is the traditional method of teaching it."),
        QuestionSeed("Which instrument's name means 'soft-loud' in Italian?",
                     ["The pianoforte", "The clavichord", "The harpsichord", "The organ"], 0,
                     "It was named for its ability to vary volume with touch, unlike the harpsichord."),
        QuestionSeed("What is an 'augmented sixth chord' typically used to approach?",
                     ["The dominant", "The tonic directly", "The subdominant", "The mediant"], 0,
                     "Italian, French, and German are the three standard varieties."),
        QuestionSeed("What does through-composed mean?",
                     ["Using new music for successive sections rather than repeating one stanza's music", "Built entirely on one chord", "Composed at the keyboard", "Written only for full orchestra"], 0,
                     "Through-composed works can repeat motives or passages, but they do not follow a simple repeated strophic setting."),
        QuestionSeed("What is just intonation?",
                     ["Tuning based on simple whole-number frequency ratios", "Tuning every note to A440", "Dividing the octave into equal semitones", "Randomly varying pitch"], 0,
                     "Fixed just-intonation tuning produces pure intervals in selected keys but problematic intervals after distant modulation; adaptive performers can retune."),
        QuestionSeed("What is a 'ground bass'?",
                     ["A repeating bass line over which the upper parts vary", "The lowest note of a chord", "A bass drum pattern", "An open string"], 0,
                     "Purcell's Dido's Lament is a famous example."),
        QuestionSeed("Which movement is Steve Reich associated with?",
                     ["Minimalism", "Serialism", "Neoclassicism", "Romanticism"], 0,
                     "Phasing and gradual process are hallmarks of his work."),
        QuestionSeed("What is 'timbre'?",
                     ["The tonal colour that distinguishes instruments", "The loudness", "The pitch", "The rhythm"], 0,
                     "It is why a violin and a trumpet playing the same note sound different."),
        QuestionSeed("What does a 'da capo' marking instruct?",
                     ["Return to the beginning", "Repeat the last bar", "Play an octave higher", "End immediately"], 0,
                     "Da capo aria form uses it to return to the opening section."),
        QuestionSeed("What is 'modal interchange'?",
                     ["Borrowing chords from a parallel key", "Changing time signature", "Switching instruments", "Transposing a whole piece"], 0,
                     "Borrowing from the parallel minor is especially common in popular music."),
        QuestionSeed("Bebop moved away from which dominant swing-era performance format?",
                     ["Large dance-oriented big bands", "Classical opera companies", "Rock power trios", "Folk string bands"], 0,
                     "Bebop developed in small groups and emphasized fast tempos, complex harmony, and improvisation; changing economics and artistic goals both contributed."),
        QuestionSeed("What is a 'motet'?",
                     ["A polyphonic choral composition, often sacred", "A solo song with lute", "An orchestral overture", "A folk dance"], 0,
                     "The form was central to Renaissance sacred music."),
        QuestionSeed("What does 'enharmonic' mean?",
                     ["Two note names for the same pitch", "A dissonant chord", "A microtonal interval", "A modulation"], 0,
                     "F sharp and G flat are enharmonic equivalents in equal temperament."),
        QuestionSeed("What is 'the Mixolydian mode' characterized by?",
                     ["A major scale with a flattened seventh", "A minor scale with a raised sixth", "Six equal whole tones", "A five-note scale"], 0,
                     "It is common in rock, folk, and Celtic music."),
        QuestionSeed("What does 'MIDI' transmit between electronic instruments?",
                     ["Performance data rather than audio", "Recorded audio", "Video sync", "Sheet music images"], 0,
                     "Note, velocity, and timing messages let one device control another."),
        QuestionSeed("What is 'the Tristan chord' significant for?",
                     ["Its ambiguous harmony pointing toward modern tonality", "Being the loudest chord written", "Its use in jazz only", "Being a folk cadence"], 0,
                     "Wagner opened Tristan und Isolde with it in 1865."),
        QuestionSeed("What is a hemiola?",
                     ["A rhythmic regrouping that sets two groups of three against three groups of two", "A melody repeated an octave higher", "A chord containing six notes", "A cadence ending on the dominant"], 0,
                     "Hemiola temporarily changes the perceived pulse without necessarily changing the written metre."),
        QuestionSeed("What does Klangfarbenmelodie distribute among instruments?",
                     ["Successive notes of a melodic line", "Only the bass rhythm", "Identical chords in unison", "The beats of a drum pattern"], 0,
                     "The changing tone colours become part of how the melody is perceived."),
        QuestionSeed("What does figured bass notation tell a continuo player?",
                     ["Which intervals or chords to realize above a bass line", "The exact orchestral instrumentation", "How loudly the singer should perform", "The words of each verse"], 0,
                     "Numbers and accidentals beneath the bass guide an improvised harmonic accompaniment."),
        QuestionSeed("Which interval pattern characterizes the Phrygian dominant scale?",
                     ["A flattened second with a major third", "A raised second with a minor third", "Only whole tones", "A flattened fourth with no seventh"], 0,
                     "Its close minor-second opening and major third create a characteristic sound found in several musical traditions."),
        QuestionSeed("What is isorhythm in medieval music?",
                     ["A repeating rhythmic pattern applied to a melodic sequence", "Improvisation without metre", "Two choirs singing in different keys", "A dance in alternating tempos"], 0,
                     "Composers combined a repeating rhythm called the talea with a repeating pitch sequence called the color."),
        QuestionSeed("What does spectral music use as a major compositional resource?",
                     ["The acoustic overtone spectrum of sound", "Only twelve-tone rows", "Recorded political speeches", "Traditional dance steps"], 0,
                     "Spectral composers analyse timbre and derive harmony or form from the internal components of sound."),
        QuestionSeed("What is Sprechstimme?",
                     ["A vocal delivery between speaking and singing", "A silent choral passage", "A bass drum roll", "A melody played backwards"], 0,
                     "The performer follows notated contours but leaves pitches in a speech-like manner."),
        QuestionSeed("What is hocket?",
                     ["A melody split between voices that alternate notes or phrases", "A sustained drone under a melody", "A chord built only from fifths", "A solo added before a chorus"], 0,
                     "The rapid exchange can make one line seem to jump between performers."),
        QuestionSeed("What is quartal harmony built from?",
                     ["Intervals of a fourth", "Intervals of a third", "Alternating whole and half steps", "Only perfect octaves"], 0,
                     "Stacked fourths create a more open sonority than conventional triads built from thirds."),
        QuestionSeed("What was mensural notation designed to represent?",
                     ["Rhythmic durations and metre in late medieval and Renaissance music", "Electronic synthesizer settings", "Guitar chord diagrams", "Only the pitches of plainchant"], 0,
                     "Its note shapes and signs allowed composers to specify complex rhythmic relationships."),
    ]
}
