import Foundation

enum MythologyQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("Who is the king of the gods in Greek mythology?",
                     ["Zeus", "Apollo", "Hermes", "Hades"], 0,
                     "Zeus ruled from Mount Olympus and carried the thunderbolt as his weapon."),
        QuestionSeed("Which Norse god wields the hammer Mjolnir?",
                     ["Odin", "Thor", "Balder", "Tyr"], 1,
                     "Thor swung Mjolnir against giants, and the hammer always returned to his hand."),
        QuestionSeed("Whose gaze turned onlookers to stone?",
                     ["Circe", "Echo", "Medusa", "Calypso"], 2,
                     "Medusa was a Gorgon whose snake-covered head turned anyone who looked at her to stone."),
        QuestionSeed("Which Greek hero completed twelve labors?",
                     ["Jason", "Perseus", "Theseus", "Heracles"], 3,
                     "Heracles performed twelve labors as penance, a story the Romans retold as Hercules."),
        QuestionSeed("What is a Cyclops best known for having?",
                     ["A single eye", "Three heads", "Iron wings", "A fish tail"], 0,
                     "A Cyclops was a giant with a single eye set in the middle of its forehead."),
        QuestionSeed("What kind of creature is Pegasus?",
                     ["A fire lizard", "A winged horse", "A giant serpent", "A stone lion"], 1,
                     "Pegasus is a winged horse that sprang from Medusa's blood in Greek myth."),
        QuestionSeed("How many heads does Cerberus traditionally have?",
                     ["One", "Two", "Three", "Seven"], 2,
                     "Cerberus is the three-headed dog that guarded the entrance to the Greek underworld."),
        QuestionSeed("Which Greek god rules the sea?",
                     ["Ares", "Hermes", "Hephaestus", "Poseidon"], 3,
                     "Poseidon ruled the sea and struck the water with a three-pronged trident."),
        QuestionSeed("Who rules the underworld in Greek mythology?",
                     ["Hades", "Apollo", "Helios", "Boreas"], 0,
                     "Hades ruled the underworld, the realm of the dead, which shares his name."),
        QuestionSeed("Which Greek goddess is associated with wisdom?",
                     ["Hera", "Athena", "Iris", "Selene"], 1,
                     "Athena was the goddess of wisdom and strategy, and the city of Athens honored her."),
        QuestionSeed("Which trickster god appears in Norse mythology?",
                     ["Njord", "Bragi", "Loki", "Forseti"], 2,
                     "Loki was the shape-shifting trickster whose schemes repeatedly endangered the Norse gods."),
        QuestionSeed("Who leads the Norse gods as the Allfather?",
                     ["Vidar", "Hodr", "Ullr", "Odin"], 3,
                     "Odin, called the Allfather, gave an eye in exchange for wisdom."),
        QuestionSeed("Where was Achilles said to be vulnerable?",
                     ["His heel", "His wrist", "His shoulder", "His knee"], 0,
                     "Achilles was invulnerable except at his heel, which gives us the phrase Achilles heel."),
        QuestionSeed("What did the Greeks hide inside to enter Troy?",
                     ["A stone chest", "A wooden horse", "A grain cart", "A bronze shield"], 1,
                     "A hollow wooden horse carried Greek soldiers through the gates of Troy."),
        QuestionSeed("What creature lived at the center of the Labyrinth?",
                     ["The Sphinx", "The Hydra", "The Minotaur", "The Chimera"], 2,
                     "The Minotaur, half man and half bull, was kept in the Labyrinth on Crete."),
        QuestionSeed("Which Egyptian god has the head of a jackal?",
                     ["Horus", "Thoth", "Sobek", "Anubis"], 3,
                     "Anubis, shown with a jackal head, guided the dead and oversaw mummification."),
        QuestionSeed("Which Egyptian god is associated with the sun?",
                     ["Ra", "Set", "Ptah", "Geb"], 0,
                     "Ra was the sun god, sailing his solar boat across the sky each day."),
        QuestionSeed("What does a phoenix famously do?",
                     ["Turn invisible", "Rise from ashes", "Freeze rivers", "Grant three wishes"], 1,
                     "A phoenix burns and then rises from its own ashes, reborn again and again."),
        QuestionSeed("What single feature defines a unicorn?",
                     ["Feathered wings", "A lion's tail", "One horn", "Glowing eyes"], 2,
                     "A unicorn is a horse-like creature with one horn rising from its forehead."),
        QuestionSeed("What is a mermaid usually described as?",
                     ["Half bird", "Half horse", "Half snake", "Half fish"], 3,
                     "A mermaid is described as half woman and half fish, living beneath the sea."),
        QuestionSeed("Which Titan is said to hold up the sky?",
                     ["Atlas", "Cronus", "Hyperion", "Oceanus"], 0,
                     "Atlas was condemned to hold up the sky, which is why map books bear his name."),
        QuestionSeed("What happened to everything King Midas touched?",
                     ["It vanished", "It turned to gold", "It caught fire", "It turned to stone"], 1,
                     "King Midas turned everything he touched to gold, including his own food."),
        QuestionSeed("What did Pandora famously open?",
                     ["A sealed gate", "A locked book", "A box", "A stone door"], 2,
                     "Pandora opened a box that released every trouble into the world, leaving only hope inside."),
        QuestionSeed("Why did Icarus fall from the sky?",
                     ["He lost his nerve", "A storm struck him", "A giant caught him", "He flew too near the sun"], 3,
                     "Icarus flew too near the sun, the wax in his wings melted, and he fell into the sea."),
        QuestionSeed("Which Roman god of love carries a bow?",
                     ["Cupid", "Mars", "Vulcan", "Mercury"], 0,
                     "Cupid shot arrows that made those they struck fall in love."),
        QuestionSeed("Where do slain Norse warriors feast in the afterlife?",
                     ["Asphodel", "Valhalla", "Avalon", "Duat"], 1,
                     "Valhalla is Odin's hall, where warriors killed in battle feast until Ragnarok."),
        QuestionSeed("What was the name of King Arthur's sword?",
                     ["Gram", "Durendal", "Excalibur", "Tyrfing"], 2,
                     "Excalibur was King Arthur's sword and the emblem of his right to rule."),
        QuestionSeed("Who is the wizard who advises King Arthur?",
                     ["Galahad", "Gawain", "Bedivere", "Merlin"], 3,
                     "Merlin was the wizard who guided King Arthur from boyhood through his reign."),
        QuestionSeed("Which creature is said to live in a Scottish lake?",
                     ["The Loch Ness Monster", "The Kraken", "The Wendigo", "The Chupacabra"], 0,
                     "The Loch Ness Monster is the creature reported to live in Loch Ness in Scotland."),
        QuestionSeed("What is a werewolf said to transform under?",
                     ["Heavy rain", "A full moon", "Total darkness", "The first frost"], 1,
                     "A werewolf is said to change from human to wolf under the light of a full moon."),
        QuestionSeed("What riddle-asking creature guarded the road to Thebes?",
                     ["The Harpy", "The Siren", "The Sphinx", "The Gorgon"], 2,
                     "The Sphinx asked travelers a riddle and destroyed those who answered it wrongly."),
        QuestionSeed("What happened when the Hydra lost a head?",
                     ["It fled", "It shrank", "It turned to stone", "More heads grew"], 3,
                     "The Hydra grew more heads whenever one was cut off, which made it hard to kill."),
        QuestionSeed("What was the home of the Greek gods?",
                     ["Mount Olympus", "Mount Etna", "Mount Ida", "Mount Athos"], 0,
                     "Mount Olympus was the home of Zeus and the other principal Greek gods."),
        QuestionSeed("Which Greek god is linked to music and prophecy?",
                     ["Pan", "Apollo", "Triton", "Morpheus"], 1,
                     "Apollo was the god of music, light, and prophecy, and the oracle at Delphi served him."),
        QuestionSeed("Which Greek god represents war?",
                     ["Hypnos", "Nereus", "Ares", "Zephyrus"], 2,
                     "Ares was the god of war, known for the violence of battle rather than its strategy."),
        QuestionSeed("What is a dragon most often depicted breathing?",
                     ["Ice", "Sand", "Smoke rings", "Fire"], 3,
                     "A dragon is most often shown as a winged, scaled creature that breathes fire."),
        QuestionSeed("Which Greek messenger god wears winged sandals?",
                     ["Hermes", "Charon", "Nestor", "Priam"], 0,
                     "Hermes carried messages for the gods and wore winged sandals to travel quickly."),
        QuestionSeed("Which Roman name matches the Greek god Zeus?",
                     ["Neptune", "Jupiter", "Saturn", "Pluto"], 1,
                     "Jupiter is the Roman name for Zeus, king of the gods and wielder of the thunderbolt."),
        QuestionSeed("What are the Sirens known for?",
                     ["Stealing gold", "Reading minds", "Luring sailors with song", "Controlling storms"], 2,
                     "The Sirens lured passing sailors onto the rocks with irresistible singing."),
        QuestionSeed("Which garden did Adam and Eve inhabit in the Bible?",
                     ["Babylon", "Canaan", "Sheba", "Eden"], 3,
                     "The Garden of Eden is where Adam and Eve lived before their expulsion."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("What did Persephone eat that bound her to the underworld?",
                     ["Pomegranate seeds", "A honeyed barley cake", "Bread from the fields", "Olives from the grove"], 0,
                     "Persephone ate pomegranate seeds, which required her to return to the underworld each year."),
        QuestionSeed("Which Greek god was the blacksmith of Olympus?",
                     ["Helios", "Hephaestus", "Momus", "Proteus"], 1,
                     "Hephaestus forged the weapons and armor of the gods at his divine smithy."),
        QuestionSeed("Which Greek goddess hunts with a bow?",
                     ["Hestia", "Tyche", "Artemis", "Eos"], 2,
                     "Artemis was the goddess of the hunt and the moon, always shown with her bow."),
        QuestionSeed("Which Greek goddess governs the harvest?",
                     ["Nike", "Hebe", "Themis", "Demeter"], 3,
                     "Demeter governed grain and the harvest, and her grief caused the barren winter."),
        QuestionSeed("Which Greek god is associated with wine?",
                     ["Dionysus", "Asclepius", "Aeolus", "Hypnos"], 0,
                     "Dionysus was the god of wine, festivity, and theater in the Greek world."),
        QuestionSeed("Who is the wife of Zeus in Greek mythology?",
                     ["Leto", "Hera", "Maia", "Rhea"], 1,
                     "Hera was the wife of Zeus and the goddess of marriage in Greek myth."),
        QuestionSeed("What did Prometheus steal for humanity?",
                     ["Iron", "Language", "Fire", "Bread"], 2,
                     "Prometheus stole fire from the gods and gave it to people, and was punished for it."),
        QuestionSeed("What is the endless task of Sisyphus?",
                     ["Filling a bottomless jar", "Counting every star nightly", "Chasing a stag forever", "Rolling a boulder uphill"], 3,
                     "Sisyphus must roll a boulder uphill forever, watching it roll back down each time."),
        QuestionSeed("Which musician tried to lead his wife out of the underworld?",
                     ["Orpheus", "Linus", "Amphion", "Thamyris"], 0,
                     "Orpheus charmed the underworld with music but looked back and lost Eurydice."),
        QuestionSeed("Which hero killed the Minotaur?",
                     ["Bellerophon", "Theseus", "Meleager", "Peleus"], 1,
                     "Theseus killed the Minotaur and used a thread to find his way out of the Labyrinth."),
        QuestionSeed("Which hero beheaded Medusa?",
                     ["Ajax", "Diomedes", "Perseus", "Idomeneus"], 2,
                     "Perseus beheaded Medusa using a polished shield so he never met her gaze directly."),
        QuestionSeed("What treasure did Jason and the Argonauts seek?",
                     ["The Silver Bough of Dagda", "The Iron Crown of Lombardy", "The Amber Cup", "The Golden Fleece"], 3,
                     "Jason and the Argonauts sailed in search of the Golden Fleece."),
        QuestionSeed("Whose ten-year voyage home is told in the Odyssey?",
                     ["Odysseus", "Menelaus", "Agamemnon", "Nestor"], 0,
                     "The Odyssey follows Odysseus on his ten-year journey home to Ithaca after Troy."),
        QuestionSeed("Which twins are said to have founded Rome?",
                     ["Castor and Pollux", "Romulus and Remus", "Amphion and Zethus", "Otus and Ephialtes"], 1,
                     "Romulus and Remus, raised by a she-wolf, are the legendary founders of Rome."),
        QuestionSeed("Which Roman god has two faces looking opposite ways?",
                     ["Faunus", "Silvanus", "Janus", "Portunus"], 2,
                     "Janus faced both forward and back, presiding over doorways and beginnings."),
        QuestionSeed("Which Norse goddess is linked to love and the necklace Brisingamen?",
                     ["Sif", "Idun", "Nanna", "Freya"], 3,
                     "Freya was the Norse goddess of love and war, and Brisingamen was her famous necklace."),
        QuestionSeed("Which Norse god guards the Bifrost bridge?",
                     ["Heimdall", "Hodr", "Magni", "Modi"], 0,
                     "Heimdall watched the Bifrost bridge and would sound his horn at the coming of Ragnarok."),
        QuestionSeed("What kind of creature is Fenrir in Norse myth?",
                     ["A raven", "A wolf", "A boar", "An eagle"], 1,
                     "Fenrir is the monstrous wolf bound by the gods until he breaks free at Ragnarok."),
        QuestionSeed("What is Yggdrasil in Norse mythology?",
                     ["A frozen sea", "A burning forge", "A world tree", "A golden hall"], 2,
                     "Yggdrasil is the immense world tree whose branches connect the Norse realms."),
        QuestionSeed("What does Ragnarok describe in Norse myth?",
                     ["A wedding feast", "The great migration south", "The first sunrise of all", "The end of the world"], 3,
                     "Ragnarok is the foretold battle that destroys the Norse gods and the world."),
        QuestionSeed("What role do the Valkyries play?",
                     ["Choosing the slain", "Forging weapons", "Guarding treasure", "Reading omens before battle"], 0,
                     "The Valkyries chose which slain warriors would be carried to Valhalla."),
        QuestionSeed("Which Egyptian god was killed and restored to rule the dead?",
                     ["Khnum", "Osiris", "Shu", "Nut"], 1,
                     "Osiris was killed by Set, restored by Isis, and became ruler of the dead."),
        QuestionSeed("Which Egyptian goddess gathered her husband's scattered body?",
                     ["Nephthys", "Hathor", "Isis", "Neith"], 2,
                     "Isis gathered the pieces of Osiris and restored him through her magic."),
        QuestionSeed("Which Egyptian god has the head of a falcon?",
                     ["Apep", "Bes", "Aten", "Horus"], 3,
                     "Horus, shown with a falcon head, avenged Osiris and became a symbol of kingship."),
        QuestionSeed("Which Egyptian god is credited with writing?",
                     ["Thoth", "Sokar", "Min", "Heka"], 0,
                     "Thoth was the ibis-headed god of writing, knowledge, and the measuring of time."),
        QuestionSeed("Which animal represents the Egyptian goddess Bastet?",
                     ["The ram", "The cat", "The crane", "The hare"], 1,
                     "Bastet was depicted as a cat, protecting the home and warding off evil."),
        QuestionSeed("Which Japanese deity is the goddess of the sun?",
                     ["Inari", "Benzaiten", "Amaterasu", "Konohana"], 2,
                     "Amaterasu is the sun goddess of Shinto belief and an ancestor of Japan's imperial line."),
        QuestionSeed("Which feathered serpent god appears in Mesoamerican myth?",
                     ["Tezcatlipoca", "Huitzilopochtli", "Tlaloc", "Quetzalcoatl"], 3,
                     "Quetzalcoatl, the feathered serpent, was linked to wind, learning, and creation."),
        QuestionSeed("Which West African trickster is often a spider?",
                     ["Anansi", "Mami Wata", "Eshu", "Oya"], 0,
                     "Anansi is the spider trickster of West African and Caribbean storytelling."),
        QuestionSeed("Which Slavic folklore figure lives in a hut on chicken legs?",
                     ["Rusalka", "Baba Yaga", "Domovoi", "Leshy"], 1,
                     "Baba Yaga is the witch of Slavic folklore whose hut walks on chicken legs."),
        QuestionSeed("What is the Kraken in Scandinavian legend?",
                     ["A snow giant", "A ghost ship", "A sea monster", "A cursed island"], 2,
                     "The Kraken is an enormous sea monster said to drag ships beneath the waves."),
        QuestionSeed("Which Greek figure fell in love with his reflection?",
                     ["Adonis", "Ganymede", "Hyacinth", "Narcissus"], 3,
                     "Narcissus fell in love with his own reflection, which is the root of the word narcissism."),
        QuestionSeed("Which nymph could only repeat the words of others?",
                     ["Echo", "Daphne", "Thetis", "Galatea"], 0,
                     "Echo was cursed to repeat the last words spoken to her, and her name became the term."),
        QuestionSeed("Which weaver was turned into a spider after a contest with Athena?",
                     ["Niobe", "Arachne", "Semele", "Danae"], 1,
                     "Arachne was transformed into a spider after out-weaving Athena, giving arachnids their name."),
        QuestionSeed("Which Greek river must the dead cross?",
                     ["The Peneus", "The Alpheus", "The Styx", "The Ilissus"], 2,
                     "The Styx is the river the dead cross to enter the Greek underworld."),
        QuestionSeed("What does the Greek titan Cronus rule over?",
                     ["The tides", "The forge", "The winds", "Time"], 3,
                     "Cronus led the Titans and is associated with time, and his name echoes in chronology."),
        QuestionSeed("Which sword did Arthur draw from a stone?",
                     ["The sword in the stone", "Joyeuse", "Hrunting", "Naegling"], 0,
                     "Arthur proved his kingship by drawing the sword in the stone, which no one else could move."),
        QuestionSeed("Which legendary island is Arthur carried to after his last battle?",
                     ["Lyonesse", "Avalon", "Hy-Brasil", "Thule"], 1,
                     "Arthur was borne to the island of Avalon to be healed after the battle of Camlann."),
        QuestionSeed("Which object did Arthur's knights famously seek?",
                     ["The Spear of Lugh", "The Stone of Scone", "The Holy Grail", "The Horn of Roland"], 2,
                     "The knights of the Round Table set out on a quest for the Holy Grail."),
        QuestionSeed("Which Irish hero is known for his battle frenzy?",
                     ["Fionn mac Cumhaill", "Oisin", "Bran", "Cu Chulainn"], 3,
                     "Cu Chulainn was the Irish hero whose battle frenzy made him unstoppable in combat."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("Whose severed head advised Odin from a well?",
                     ["Mimir", "Kvasir", "Vafthrudnir", "Hoenir"], 0,
                     "Mimir's preserved head gave Odin counsel, and Odin gave an eye to drink from Mimir's well."),
        QuestionSeed("How many legs does Odin's horse Sleipnir have?",
                     ["Six", "Eight", "Ten", "Twelve"], 1,
                     "Sleipnir, Odin's horse, has eight legs and can travel between the Norse worlds."),
        QuestionSeed("What is Gungnir in Norse mythology?",
                     ["A shield", "A helm", "A spear", "A drinking horn"], 2,
                     "Gungnir is Odin's spear, said never to miss the target it is thrown at."),
        QuestionSeed("What does Odin's ring Draupnir do every ninth night?",
                     ["It rings aloud", "It changes color", "It grows heavier", "It drips eight copies"], 3,
                     "Draupnir drips eight rings of equal weight every ninth night, multiplying Odin's wealth."),
        QuestionSeed("Which serpent encircles the world in Norse myth?",
                     ["Jormungandr", "Nidhogg", "Fafnir", "Gorm"], 0,
                     "Jormungandr, the Midgard Serpent, circles the world and is Thor's fated enemy."),
        QuestionSeed("Who rules the Norse realm of the dishonored dead?",
                     ["Skadi", "Hel", "Gefjon", "Ran"], 1,
                     "Hel, a daughter of Loki, rules the realm of the dead that carries her name."),
        QuestionSeed("Which Greek goddess personifies the night?",
                     ["Iris", "Aura", "Nyx", "Peitho"], 2,
                     "Nyx is the primordial goddess of night, old enough that even Zeus was wary of her."),
        QuestionSeed("Which Greek goddess is associated with witchcraft and crossroads?",
                     ["Ananke", "Adrasteia", "Enyo", "Hecate"], 3,
                     "Hecate presided over witchcraft, ghosts, and crossroads in Greek religion."),
        QuestionSeed("Which Greek goddess punishes excessive pride?",
                     ["Nemesis", "Harmonia", "Eirene", "Dike"], 0,
                     "Nemesis delivered retribution to those whose arrogance outgrew their place."),
        QuestionSeed("Which goddess threw the apple that started the Trojan War?",
                     ["Ate", "Eris", "Hebe", "Nike"], 1,
                     "Eris, goddess of discord, threw a golden apple that set the divine quarrel in motion."),
        QuestionSeed("Who ferries the dead across the Styx?",
                     ["Hypnos", "Thanatos", "Charon", "Morpheus"], 2,
                     "Charon ferried the dead across the river Styx in exchange for a coin."),
        QuestionSeed("What is Tartarus in Greek cosmology?",
                     ["A sacred grove", "A floating island", "A mountain forge", "A deep abyss"], 3,
                     "Tartarus is the deep abyss below the underworld where the Titans were imprisoned."),
        QuestionSeed("What did the three Moirai control?",
                     ["The threads of fate", "The ocean tides", "The seasons", "The winds"], 0,
                     "The Moirai, or Fates, spun, measured, and cut the thread of every mortal life."),
        QuestionSeed("How many Muses were there in classical Greek tradition?",
                     ["Three", "Nine", "Twelve", "Seven"], 1,
                     "Nine Muses presided over the arts and sciences in classical Greek tradition."),
        QuestionSeed("What did the three Graeae share among them?",
                     ["One cloak", "One throne", "One eye", "One name"], 2,
                     "The Graeae shared a single eye and a single tooth, which Perseus seized from them."),
        QuestionSeed("What animals combine to form the Chimera?",
                     ["Bull, eagle, and ram", "Horse, hawk, and boar", "Bear, stag, and crow", "Lion, goat, and serpent"], 3,
                     "The Chimera was a fire-breathing mixture of lion, goat, and serpent."),
        QuestionSeed("Which pair of hazards flanked a narrow strait in the Odyssey?",
                     ["Scylla and Charybdis", "Gog and Magog", "Symplegades and Planctae", "Cadmus and Harmonia"], 0,
                     "Scylla and Charybdis guarded a narrow strait, forcing Odysseus to choose which to risk."),
        QuestionSeed("What made the giant Argus an ideal watchman?",
                     ["He never aged", "He had a hundred eyes", "He could fly", "He read minds"], 1,
                     "Argus had a hundred eyes and never closed them all at once, making him a perfect guard."),
        QuestionSeed("What was Talos, the guardian of Crete, made from?",
                     ["Stone", "Ice", "Bronze", "Living wood"], 2,
                     "Talos was a bronze automaton that circled Crete and hurled rocks at approaching ships."),
        QuestionSeed("What concept does the Egyptian goddess Ma'at embody?",
                     ["Storms", "Fertility", "War", "Cosmic order"], 3,
                     "Ma'at embodied cosmic order and truth, and the dead were judged against her feather."),
        QuestionSeed("Which Egyptian goddess has the head of a lioness?",
                     ["Sekhmet", "Wadjet", "Seshat", "Tefnut"], 0,
                     "Sekhmet, the lion-headed goddess, embodied the destructive heat of the sun."),
        QuestionSeed("What is the Duat in Egyptian belief?",
                     ["A royal court", "The underworld", "A sacred river", "The first temple"], 1,
                     "The Duat is the Egyptian underworld the dead travel through before judgment."),
        QuestionSeed("What awaited hearts that failed the Egyptian weighing ceremony?",
                     ["Eternal sleep", "Rebirth as animals", "Ammit the devourer", "A second trial"], 2,
                     "Ammit the devourer consumed hearts that weighed heavier than the feather of Ma'at."),
        QuestionSeed("Which Egyptian god is depicted with a crocodile head?",
                     ["Khonsu", "Nefertum", "Anhur", "Sobek"], 3,
                     "Sobek, shown with a crocodile head, was linked to the Nile and to royal power."),
        QuestionSeed("Which Hindu deity is depicted with an elephant head?",
                     ["Ganesha", "Kartikeya", "Indra", "Varuna"], 0,
                     "Ganesha, the elephant-headed deity, is invoked as the remover of obstacles."),
        QuestionSeed("Which Hindu figure is the devoted monkey ally of Rama?",
                     ["Jatayu", "Hanuman", "Sugriva", "Vibhishana"], 1,
                     "Hanuman is the monkey deity whose devotion to Rama drives much of the Ramayana."),
        QuestionSeed("Which bird-like being serves as the mount of Vishnu?",
                     ["Nandi", "Airavata", "Garuda", "Uchchaihshravas"], 2,
                     "Garuda, an eagle-like being, carries Vishnu and is the enemy of serpents."),
        QuestionSeed("Which Mesopotamian king is the subject of the oldest known epic?",
                     ["Sargon", "Hammurabi", "Ashurbanipal", "Gilgamesh"], 3,
                     "Gilgamesh, king of Uruk, is the subject of the oldest surviving long epic poem."),
        QuestionSeed("Who becomes Gilgamesh's closest companion?",
                     ["Enkidu", "Humbaba", "Utnapishtim", "Shamhat"], 0,
                     "Enkidu, created as his rival, becomes Gilgamesh's closest companion in the epic."),
        QuestionSeed("Which Babylonian goddess is portrayed as a primordial sea?",
                     ["Ereshkigal", "Tiamat", "Ninhursag", "Nisaba"], 1,
                     "Tiamat is the primordial saltwater goddess whose body Marduk shapes into the world."),
        QuestionSeed("Which god defeats Tiamat in Babylonian myth?",
                     ["Nergal", "Enlil", "Marduk", "Nabu"], 2,
                     "Marduk defeats Tiamat and becomes chief god of the Babylonian pantheon."),
        QuestionSeed("Which pair created the Japanese islands in Shinto myth?",
                     ["Fujin and Raijin", "Ebisu and Daikoku", "Hachiman and Tenjin", "Izanagi and Izanami"], 3,
                     "Izanagi and Izanami stirred the sea with a spear and formed the islands of Japan."),
        QuestionSeed("What is a kitsune in Japanese folklore?",
                     ["A fox spirit", "A river troll", "A stone guardian", "A wind demon"], 0,
                     "A kitsune is a fox spirit said to gain wisdom and extra tails as it ages."),
        QuestionSeed("Which Japanese storm god was banished by Amaterasu?",
                     ["Tsukuyomi", "Susanoo", "Ninigi", "Omoikane"], 1,
                     "Susanoo, the storm god, was banished after his destructive behavior offended Amaterasu."),
        QuestionSeed("Which Slavic god wields thunder and an axe?",
                     ["Veles", "Svarog", "Perun", "Dazhbog"], 2,
                     "Perun is the Slavic thunder god, armed with an axe and opposed to Veles."),
        QuestionSeed("Which Irish goddess of war appears as a crow?",
                     ["Brigid", "Danu", "Aine", "The Morrigan"], 3,
                     "The Morrigan is the Irish war goddess who appears over battlefields as a crow."),
        QuestionSeed("What are the Tuatha De Danann in Irish myth?",
                     ["A race of gods", "A line of kings", "A band of poets", "A fleet of ships"], 0,
                     "The Tuatha De Danann are the godlike race said to have ruled Ireland before mortals."),
        QuestionSeed("Which Welsh collection preserves early British legends?",
                     ["The Elder Edda", "The Mabinogion", "The Kalevala", "The Nibelungenlied"], 1,
                     "The Mabinogion is the Welsh collection preserving the earliest British prose legends."),
        QuestionSeed("Which epic poem is the national folk epic of Finland?",
                     ["The Edda", "The Heliand", "The Kalevala", "The Beowulf"], 2,
                     "The Kalevala gathers Finnish oral poetry and became the national folk epic."),
        QuestionSeed("Which Greek hero is the ancestor claimed by Rome in the Aeneid?",
                     ["Hector", "Priam", "Paris", "Aeneas"], 3,
                     "Aeneas escapes Troy and founds the line that Rome claimed as its ancestry."),
    ]
}
