import Foundation

enum ScienceQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("Which planet is known as the Red Planet?",
                     ["Venus", "Mars", "Jupiter", "Mercury"], 1,
                     "Iron oxide in the Martian soil gives the surface its rusty colour."),
        QuestionSeed("What is the chemical symbol for gold?",
                     ["Ag", "Gd", "Au", "Go"], 2,
                     "Au comes from aurum, the Latin word for gold. Ag is silver."),
        QuestionSeed("How many bones are in a typical adult human body?",
                     ["186", "206", "226", "256"], 1,
                     "Babies are born with about 270, and many fuse together during growth."),
        QuestionSeed("Which gas do plants take in during photosynthesis?",
                     ["Oxygen", "Nitrogen", "Hydrogen", "Carbon dioxide"], 3,
                     "Plants absorb carbon dioxide and release oxygen as a by-product."),
        QuestionSeed("What is the largest planet in the solar system?",
                     ["Saturn", "Earth", "Jupiter", "Neptune"], 2,
                     "Jupiter is more massive than all the other planets combined."),
        QuestionSeed("At standard pressure, water boils at what Celsius temperature?",
                     ["90 degrees", "100 degrees", "110 degrees", "212 degrees"], 1,
                     "212 is the same temperature expressed in Fahrenheit."),
        QuestionSeed("What force keeps the planets in orbit around the Sun?",
                     ["Magnetism", "Friction", "Gravity", "Electricity"], 2,
                     "Gravity pulls the planets inward while their forward motion keeps them from falling in."),
        QuestionSeed("What is the centre of an atom called?",
                     ["The nucleus", "The orbit", "The shell", "The core beam"], 0,
                     "The nucleus holds protons and neutrons; electrons occupy the space around it."),
        QuestionSeed("Which organ pumps blood around the body?",
                     ["The liver", "The lungs", "The heart", "The kidneys"], 2,
                     "The heart beats roughly 100,000 times a day in an average adult."),
        QuestionSeed("What is Earth's only natural satellite?",
                     ["Titan", "The Moon", "Europa", "Phobos"], 1,
                     "The others listed orbit Saturn, Jupiter, and Mars."),
        QuestionSeed("Which naturally occurring material is the hardest?",
                     ["Quartz", "Iron", "Diamond", "Granite"], 2,
                     "Diamond sits at the top of the Mohs hardness scale."),
        QuestionSeed("Which subatomic particle carries a negative charge?",
                     ["The proton", "The neutron", "The electron", "The photon"], 2,
                     "Protons are positive and neutrons carry no charge."),
        QuestionSeed("How many legs does a spider have?",
                     ["Six", "Eight", "Ten", "Twelve"], 1,
                     "Spiders are arachnids, not insects, and insects are the ones with six."),
        QuestionSeed("What gas makes up most of Earth's atmosphere?",
                     ["Oxygen", "Nitrogen", "Carbon dioxide", "Argon"], 1,
                     "Nitrogen is about 78 percent of the air by volume; oxygen is about 21 percent."),
        QuestionSeed("What is H2O commonly known as?",
                     ["Salt", "Water", "Sugar", "Ammonia"], 1,
                     "Two hydrogen atoms bonded to one oxygen atom."),
        QuestionSeed("Which planet is closest to the Sun?",
                     ["Venus", "Mercury", "Earth", "Mars"], 1,
                     "Mercury completes an orbit in just 88 Earth days."),
        QuestionSeed("Which state of matter has a definite volume but takes the shape of its container?",
                     ["A solid", "A liquid", "A gas", "A plasma"], 1,
                     "A liquid keeps nearly the same volume while flowing to match the shape of its container."),
        QuestionSeed("What is the process by which water turns into vapour?",
                     ["Condensation", "Evaporation", "Precipitation", "Sublimation"], 1,
                     "Condensation is the reverse, when vapour cools back into liquid."),
        QuestionSeed("Which part of a plant absorbs water from the soil?",
                     ["The leaves", "The roots", "The flower", "The stem"], 1,
                     "Root hairs greatly increase the surface area available for absorption."),
        QuestionSeed("What is the human body's largest organ?",
                     ["The liver", "The skin", "The brain", "The lungs"], 1,
                     "Skin covers roughly two square metres in an average adult."),
        QuestionSeed("What does a thermometer measure?",
                     ["Pressure", "Temperature", "Humidity", "Wind speed"], 1,
                     "A barometer measures pressure and a hygrometer measures humidity."),
        QuestionSeed("Which planet has the most prominent ring system?",
                     ["Jupiter", "Saturn", "Uranus", "Neptune"], 1,
                     "All four giant planets have rings, but Saturn's are by far the brightest."),
        QuestionSeed("What is the basic unit of life?",
                     ["The atom", "The cell", "The molecule", "The organ"], 1,
                     "All living things are made of one or more cells."),
        QuestionSeed("Which vitamin does sunlight help the body produce?",
                     ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], 2,
                     "Ultraviolet B light triggers vitamin D synthesis in the skin."),
        QuestionSeed("What is the closest star to Earth?",
                     ["Sirius", "The Sun", "Proxima Centauri", "Polaris"], 1,
                     "The Sun is about 93 million miles away; the next nearest star is over four light years off."),
        QuestionSeed("Which liquid do honey bees collect from flowers and convert into honey?",
                     ["Nectar", "Sap", "Resin", "Water"], 0,
                     "Bees convert nectar into honey and also deliberately collect pollen as a protein-rich food."),
        QuestionSeed("What is the chemical symbol for oxygen?",
                     ["O", "Ox", "Og", "On"], 0,
                     "Oxygen gas in the air is O2, two oxygen atoms bonded together."),
        QuestionSeed("How many planets are in the solar system?",
                     ["Seven", "Eight", "Nine", "Ten"], 1,
                     "Pluto was reclassified as a dwarf planet in 2006, leaving eight."),
        QuestionSeed("What causes day and night on Earth?",
                     ["Earth's rotation on its axis", "Earth's orbit around the Sun", "The Moon's phases", "Solar flares"], 0,
                     "One full rotation takes about twenty-four hours."),
        QuestionSeed("Which blood cells carry oxygen?",
                     ["White blood cells", "Red blood cells", "Platelets", "Plasma cells"], 1,
                     "Haemoglobin inside red cells binds oxygen in the lungs and releases it in tissues."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("What is the chemical symbol for potassium?",
                     ["P", "Pt", "K", "Po"], 2,
                     "K comes from kalium, the Latin name derived from the Arabic for potash."),
        QuestionSeed("How long does light from the Sun take to reach Earth?",
                     ["About 8 seconds", "About 8 minutes", "About 8 hours", "About 8 days"], 1,
                     "Roughly eight minutes and twenty seconds at Earth's average distance."),
        QuestionSeed("What is the powerhouse of the cell?",
                     ["The nucleus", "The mitochondrion", "The ribosome", "The vacuole"], 1,
                     "Mitochondria generate most of the cell's chemical energy in the form of ATP."),
        QuestionSeed("Which scientist proposed the theory of general relativity?",
                     ["Isaac Newton", "Albert Einstein", "Niels Bohr", "Max Planck"], 1,
                     "Einstein published the general theory in 1915, describing gravity as curved spacetime."),
        QuestionSeed("What is the pH of a neutral solution at room temperature?",
                     ["0", "7", "10", "14"], 1,
                     "Below 7 is acidic and above 7 is basic."),
        QuestionSeed("Which element has the atomic number 1?",
                     ["Helium", "Hydrogen", "Lithium", "Carbon"], 1,
                     "Hydrogen has a single proton and is the most abundant element in the universe."),
        QuestionSeed("What is the speed of light in a vacuum, approximately?",
                     ["300,000 km per second", "300,000 km per hour", "3,000 km per second", "30,000 km per second"], 0,
                     "About 299,792 kilometres per second, a fixed constant in physics."),
        QuestionSeed("Which gas do humans exhale in greater quantity than they inhale?",
                     ["Nitrogen", "Carbon dioxide", "Oxygen", "Hydrogen"], 1,
                     "Respiration consumes oxygen and produces carbon dioxide."),
        QuestionSeed("What is the study of fossils called?",
                     ["Archaeology", "Palaeontology", "Geology", "Anthropology"], 1,
                     "Archaeology studies human artefacts; palaeontology studies ancient life."),
        QuestionSeed("What does DNA stand for?",
                     ["Deoxyribonucleic acid", "Dinucleic acid", "Diribose nucleic acid", "Deoxyribose nitrate"], 0,
                     "DNA carries the genetic instructions used in the growth and function of organisms."),
        QuestionSeed("Which planet rotates on its side relative to its orbit?",
                     ["Neptune", "Uranus", "Saturn", "Venus"], 1,
                     "Uranus has an axial tilt of about 98 degrees, which may have resulted from one or more ancient impacts."),
        QuestionSeed("What is the most abundant metal in Earth's crust?",
                     ["Iron", "Aluminium", "Copper", "Magnesium"], 1,
                     "Aluminium makes up about eight percent of the crust by mass."),
        QuestionSeed("What is Newton's third law of motion?",
                     ["Objects in motion stay in motion", "Force equals mass times acceleration", "Every action has an equal and opposite reaction", "Energy cannot be created or destroyed"], 2,
                     "Forces always occur in pairs acting on different objects."),
        QuestionSeed("What kind of energy does a moving object have?",
                     ["Potential energy", "Kinetic energy", "Thermal energy", "Chemical energy"], 1,
                     "Kinetic energy scales with the square of speed, so doubling speed quadruples it."),
        QuestionSeed("Which layer of Earth is the thickest?",
                     ["The crust", "The mantle", "The outer core", "The inner core"], 1,
                     "The mantle makes up roughly 84 percent of Earth's volume."),
        QuestionSeed("What is a light year a measure of?",
                     ["Time", "Distance", "Brightness", "Mass"], 1,
                     "It is the distance light travels in one year, about 9.5 trillion kilometres."),
        QuestionSeed("Which blood type is often called the universal donor for red cells?",
                     ["A positive", "B negative", "O negative", "AB positive"], 2,
                     "O negative red cells lack the A, B, and RhD antigens that trigger common reactions."),
        QuestionSeed("What is the chemical formula for table salt?",
                     ["NaCl", "KCl", "CaCO3", "NaHCO3"], 0,
                     "Sodium chloride. NaHCO3 is baking soda."),
        QuestionSeed("Which scientist developed the periodic table's early form?",
                     ["Dmitri Mendeleev", "Antoine Lavoisier", "John Dalton", "Robert Boyle"], 0,
                     "Mendeleev left gaps for elements not yet discovered and predicted their properties."),
        QuestionSeed("What process do cells use to divide for growth and repair?",
                     ["Meiosis", "Mitosis", "Osmosis", "Diffusion"], 1,
                     "Meiosis is the different process that produces sex cells."),
        QuestionSeed("Which particle was discovered at CERN in 2012?",
                     ["The neutrino", "The Higgs boson", "The quark", "The positron"], 1,
                     "Its discovery confirmed the mechanism that gives elementary particles mass."),
        QuestionSeed("What is the hottest planet in the solar system?",
                     ["Mercury", "Venus", "Mars", "Jupiter"], 1,
                     "Venus is hotter than Mercury despite being farther out, because of a runaway greenhouse effect."),
        QuestionSeed("What are the three states of matter most commonly taught?",
                     ["Solid, liquid, gas", "Hot, warm, cold", "Metal, mineral, gas", "Acid, base, salt"], 0,
                     "Plasma is often taught as a fourth state."),
        QuestionSeed("Which organ produces insulin?",
                     ["The liver", "The pancreas", "The spleen", "The thyroid"], 1,
                     "Beta cells in the pancreatic islets release insulin to regulate blood sugar."),
        QuestionSeed("What does a seismograph record?",
                     ["Rainfall", "Earthquakes", "Wind direction", "Solar activity"], 1,
                     "It measures ground motion, which is how earthquake magnitudes are determined."),
        QuestionSeed("What is the main component of natural gas?",
                     ["Methane", "Propane", "Butane", "Ethane"], 0,
                     "Methane is CH4, the simplest hydrocarbon."),
        QuestionSeed("Which type of rock forms from cooled magma or lava?",
                     ["Sedimentary", "Igneous", "Metamorphic", "Organic"], 1,
                     "Granite and basalt are common igneous rocks."),
        QuestionSeed("What is absolute zero on the Celsius scale?",
                     ["0 degrees", "-100 degrees", "-273.15 degrees", "-459 degrees"], 2,
                     "That is 0 kelvin, the point at which classical thermal motion stops."),
        QuestionSeed("Which scientist is credited with the laws of planetary motion?",
                     ["Johannes Kepler", "Tycho Brahe", "Galileo Galilei", "Nicolaus Copernicus"], 0,
                     "Kepler showed the orbits are ellipses, not perfect circles."),
        QuestionSeed("What does an ecosystem consist of?",
                     ["Living organisms and their physical environment", "Only plants", "Only animals", "Only the climate"], 0,
                     "The interactions between the living and non-living parts define the system."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("What is the Chandrasekhar limit?",
                     ["The maximum mass of a stable white dwarf", "The size of the observable universe", "The speed limit of a photon", "The minimum mass of a planet"], 0,
                     "Around 1.4 solar masses; above it a white dwarf collapses further."),
        QuestionSeed("Which enzyme unwinds the DNA double helix during replication?",
                     ["Helicase", "Ligase", "Polymerase", "Primase"], 0,
                     "Polymerase then builds the new strands along the separated templates."),
        QuestionSeed("What does the second law of thermodynamics state about entropy?",
                     ["It never decreases in an isolated system", "It is always zero", "It decreases over time", "It equals temperature"], 0,
                     "The law explains why heat flows from hot to cold and why perpetual motion is impossible."),
        QuestionSeed("What is a superconductor?",
                     ["A material with zero electrical resistance below a critical temperature", "A very fast semiconductor", "A magnetic insulator", "A high-voltage cable"], 0,
                     "Superconductors also expel magnetic fields through the Meissner–Ochsenfeld effect, commonly shortened to the Meissner effect."),
        QuestionSeed("Which element is the most electronegative?",
                     ["Fluorine", "Oxygen", "Chlorine", "Nitrogen"], 0,
                     "Fluorine sits at the top of the Pauling electronegativity scale."),
        QuestionSeed("What is the Doppler effect?",
                     ["A change in observed frequency due to relative motion", "The bending of light by gravity", "The scattering of blue light", "The decay of radioactive isotopes"], 0,
                     "It explains a passing siren's pitch shift and helps measure stellar radial motion; cosmological redshift additionally reflects expanding spacetime."),
        QuestionSeed("What are prokaryotic cells distinguished by?",
                     ["The absence of a membrane-bound nucleus", "The presence of chloroplasts", "Having two nuclei", "Being multicellular"], 0,
                     "Bacteria and archaea are prokaryotes; plants, animals, and fungi are eukaryotes."),
        QuestionSeed("What does the Heisenberg uncertainty principle describe?",
                     ["A limit on knowing position and momentum simultaneously", "The decay rate of neutrons", "The curvature of spacetime", "The charge of a quark"], 0,
                     "The more precisely one is known, the less precisely the other can be."),
        QuestionSeed("What is the half-life of carbon-14, approximately?",
                     ["5,730 years", "1,600 years", "24,000 years", "710 million years"], 0,
                     "That half-life makes it useful for dating organic material up to roughly 50,000 years old."),
        QuestionSeed("What is an isotope?",
                     ["An atom with the same protons but a different number of neutrons", "A charged atom", "A molecule with two elements", "An unstable molecule"], 0,
                     "Isotopes share chemical behaviour but differ in mass and sometimes in stability."),
        QuestionSeed("What is the event horizon of a black hole?",
                     ["The boundary beyond which nothing can escape", "The centre of the black hole", "The accretion disc", "The gravitational lens"], 0,
                     "The singularity is at the centre; the event horizon is the boundary around it."),
        QuestionSeed("Which process do stars use to convert hydrogen into helium?",
                     ["Nuclear fusion", "Nuclear fission", "Combustion", "Radioactive decay"], 0,
                     "Fusion in the core releases the energy that keeps a star from collapsing."),
        QuestionSeed("What is the function of ribosomes?",
                     ["Assembling proteins from amino acids", "Storing genetic material", "Producing energy", "Digesting waste"], 0,
                     "They read messenger RNA and link amino acids in the specified order."),
        QuestionSeed("What is the Coriolis effect responsible for?",
                     ["The deflection of moving air and water on a rotating Earth", "Ocean tides", "Volcanic eruptions", "Magnetic reversals"], 0,
                     "It is why large weather systems rotate in opposite directions in the two hemispheres."),
        QuestionSeed("Which type of radiation is stopped by a sheet of paper?",
                     ["Alpha", "Beta", "Gamma", "X-ray"], 0,
                     "Beta needs thin metal and gamma needs dense shielding such as lead."),
        QuestionSeed("What is CRISPR primarily used for?",
                     ["Editing genes at specific sequences", "Amplifying DNA", "Sequencing proteins", "Culturing bacteria"], 0,
                     "The technique adapts a bacterial immune mechanism into a precise editing tool."),
        QuestionSeed("What is the approximate age of the universe?",
                     ["13.8 billion years", "4.5 billion years", "100 billion years", "500 million years"], 0,
                     "4.5 billion years is roughly the age of Earth, not the universe."),
        QuestionSeed("What does a catalyst do in a chemical reaction?",
                     ["Speeds it up without being consumed", "Is consumed to release energy", "Raises the activation energy", "Stops the reaction"], 0,
                     "Catalysts lower the activation energy and emerge unchanged."),
        QuestionSeed("What is the difference between accuracy and precision?",
                     ["Accuracy is closeness to the true value; precision is repeatability", "They are identical", "Precision is closeness to the true value", "Accuracy applies only to averages"], 0,
                     "A measurement can be precise and consistently wrong."),
        QuestionSeed("Which force binds protons and neutrons in the nucleus?",
                     ["The strong nuclear force", "The weak nuclear force", "Electromagnetism", "Gravity"], 0,
                     "It overcomes the electrical repulsion between positively charged protons."),
        QuestionSeed("What is a mole in chemistry?",
                     ["A quantity containing Avogadro's number of particles", "A unit of mass", "A measure of concentration only", "A type of bond"], 0,
                     "One mole is about 6.022 times ten to the twenty-third particles."),
        QuestionSeed("What is horizontal gene transfer?",
                     ["Genetic material moving between organisms other than from parent to offspring", "Two species merging into one", "Chromosomes lining up during mitosis", "A trait disappearing through natural selection"], 0,
                     "Horizontal gene transfer is common among bacteria and can spread traits such as antibiotic resistance."),
        QuestionSeed("What is the primary greenhouse gas emitted by human activity?",
                     ["Carbon dioxide", "Ozone", "Nitrogen", "Argon"], 0,
                     "Methane is more potent per molecule but is emitted in far smaller quantities."),
        QuestionSeed("What does an electron's orbital describe?",
                     ["A probability distribution for the electron's location", "A fixed circular path", "The electron's mass", "The nucleus radius"], 0,
                     "Quantum mechanics replaced fixed orbits with probability clouds."),
        QuestionSeed("What is the cosmic microwave background?",
                     ["Residual radiation from the early universe", "Light from the nearest galaxy", "Solar wind", "Radiation from black holes"], 0,
                     "It is the oldest light we can observe, released about 380,000 years after the Big Bang."),
        QuestionSeed("What is homeostasis?",
                     ["Maintaining stable internal conditions", "Cell division", "Genetic mutation", "Energy production"], 0,
                     "Body temperature and blood glucose regulation are classic examples."),
        QuestionSeed("What is the difference between a virus and a bacterium?",
                     ["A virus is not a cell and needs a host to replicate", "A virus is larger", "A bacterium cannot reproduce", "They are the same"], 0,
                     "This is why antibiotics work on bacteria but not on viruses."),
        QuestionSeed("Which quantity is conserved in an elastic collision but not an inelastic one?",
                     ["Kinetic energy", "Momentum", "Mass", "Charge"], 0,
                     "Momentum is conserved in both; kinetic energy only in elastic collisions."),
        QuestionSeed("What is the Krebs cycle also known as?",
                     ["The citric acid cycle", "The Calvin cycle", "The nitrogen cycle", "The urea cycle"], 0,
                     "The cycle is central to aerobic respiration; it occurs in mitochondria in eukaryotes and in the cytosol of prokaryotes."),
        QuestionSeed("What is dark matter inferred from?",
                     ["Gravitational effects that visible matter cannot explain", "Direct telescope images", "Radio emissions", "Neutrino detectors"], 0,
                     "Galaxy rotation curves and gravitational lensing both point to unseen mass."),
    ]
}
