import Foundation

enum ScienceQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("Which planet is known as the Red Planet?",
                     ["Venus", "Mars", "Jupiter", "Mercury"], 1,
                     "Iron oxide in the Martian soil gives the surface its rusty colour."),
        QuestionSeed("What is the chemical symbol for gold?",
                     ["Ag", "Gd", "Au", "Pt"], 2,
                     "Au comes from aurum, the Latin word for gold. Ag is silver."),
        QuestionSeed("How many bones are in a typical adult human body?",
                     ["186", "206", "226", "256"], 1,
                     "Babies are born with about 270, and many fuse together during growth."),
        QuestionSeed("Which gas do plants take in during photosynthesis?",
                     ["Oxygen", "Nitrogen", "Hydrogen", "Carbon dioxide"], 3,
                     "Plants absorb carbon dioxide and release oxygen as a by-product."),
        QuestionSeed("What is the largest planet in the solar system?",
                     ["Saturn", "Earth", "Jupiter", "Neptune"], 2,
                     "Jupiter is more massive than all the other planets combined."),
        QuestionSeed("At standard pressure, water boils at what Celsius temperature?",
                     ["90 degrees", "100 degrees", "110 degrees", "212 degrees"], 1,
                     "212 is the same temperature expressed in Fahrenheit."),
        QuestionSeed("What force keeps the planets in orbit around the Sun?",
                     ["Magnetism", "Friction", "Gravity", "Electricity"], 2,
                     "Gravity pulls the planets inward while their forward motion keeps them from falling in."),
        QuestionSeed("What is the centre of an atom called?",
                     ["The nucleus", "The orbit", "The shell", "The core beam"], 0,
                     "The nucleus holds protons and neutrons; electrons occupy the space around it."),
        QuestionSeed("Which organ pumps blood around the body?",
                     ["The liver", "The lungs", "The heart", "The kidneys"], 2,
                     "The heart beats roughly 100,000 times a day in an average adult."),
        QuestionSeed("What is Earth's only natural satellite?",
                     ["Titan", "The Moon", "Europa", "Phobos"], 1,
                     "The others listed orbit Saturn, Jupiter, and Mars."),
        QuestionSeed("Which naturally occurring material is the hardest?",
                     ["Quartz", "Iron", "Diamond", "Granite"], 2,
                     "Diamond sits at the top of the Mohs hardness scale."),
        QuestionSeed("Which subatomic particle carries a negative charge?",
                     ["The proton", "The neutron", "The electron", "The photon"], 2,
                     "Protons are positive and neutrons carry no charge."),
        QuestionSeed("How many legs does a spider have?",
                     ["Six", "Eight", "Ten", "Twelve"], 1,
                     "Spiders are arachnids, not insects, and insects are the ones with six."),
        QuestionSeed("What gas makes up most of Earth's atmosphere?",
                     ["Oxygen", "Nitrogen", "Carbon dioxide", "Argon"], 1,
                     "Nitrogen is about 78 percent of the air by volume; oxygen is about 21 percent."),
        QuestionSeed("What is H2O commonly known as?",
                     ["Salt", "Water", "Sugar", "Ammonia"], 1,
                     "Two hydrogen atoms bonded to one oxygen atom."),
        QuestionSeed("Which planet is closest to the Sun?",
                     ["Venus", "Mercury", "Earth", "Mars"], 1,
                     "Mercury completes an orbit in just 88 Earth days."),
        QuestionSeed("Which state of matter has a definite volume but takes the shape of its container?",
                     ["A solid", "A liquid", "A gas", "A plasma"], 1,
                     "A liquid keeps nearly the same volume while flowing to match the shape of its container."),
        QuestionSeed("What is the process by which water turns into vapour?",
                     ["Condensation", "Evaporation", "Precipitation", "Sublimation"], 1,
                     "Condensation is the reverse, when vapour cools back into liquid."),
        QuestionSeed("Which part of a plant absorbs water from the soil?",
                     ["The leaves", "The roots", "The flower", "The stem"], 1,
                     "Root hairs greatly increase the surface area available for absorption."),
        QuestionSeed("What is the human body's largest organ?",
                     ["The liver", "The skin", "The brain", "The lungs"], 1,
                     "Skin covers roughly two square metres in an average adult."),
        QuestionSeed("What does a thermometer measure?",
                     ["Pressure", "Temperature", "Humidity", "Wind speed"], 1,
                     "A barometer measures pressure and a hygrometer measures humidity."),
        QuestionSeed("Which planet has the most prominent ring system?",
                     ["Jupiter", "Saturn", "Uranus", "Neptune"], 1,
                     "All four giant planets have rings, but Saturn's are by far the brightest."),
        QuestionSeed("What is the basic unit of life?",
                     ["The atom", "The cell", "The molecule", "The organ"], 1,
                     "All living things are made of one or more cells."),
        QuestionSeed("Which vitamin does sunlight help the body produce?",
                     ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], 2,
                     "Ultraviolet B light triggers vitamin D synthesis in the skin."),
        QuestionSeed("What is the closest star to Earth?",
                     ["Sirius", "The Sun", "Proxima Centauri", "Polaris"], 1,
                     "The Sun is about 93 million miles away; the next nearest star is over four light years off."),
        QuestionSeed("Which liquid do honey bees collect from flowers and convert into honey?",
                     ["Nectar", "Sap", "Resin", "Water"], 0,
                     "Bees convert nectar into honey and also deliberately collect pollen as a protein-rich food."),
        QuestionSeed("What is the chemical symbol for oxygen?",
                     ["O", "Ox", "Og", "On"], 0,
                     "Oxygen gas in the air is O2, two oxygen atoms bonded together."),
        QuestionSeed("How many planets are in the solar system?",
                     ["Seven", "Eight", "Nine", "Ten"], 1,
                     "Pluto was reclassified as a dwarf planet in 2006, leaving eight."),
        QuestionSeed("What causes day and night on Earth?",
                     ["Earth's rotation on its axis", "Earth's orbit around the Sun", "The Moon's phases", "Solar flares"], 0,
                     "One full rotation takes about twenty-four hours."),
        QuestionSeed("Which blood cells carry oxygen?",
                     ["White blood cells", "Red blood cells", "Platelets", "Plasma cells"], 1,
                     "Haemoglobin inside red cells binds oxygen in the lungs and releases it in tissues."),
        QuestionSeed("At standard atmospheric pressure, at what Celsius temperature does pure water freeze?",
                     ["0 degrees", "10 degrees", "32 degrees", "100 degrees"], 0,
                     "Zero degrees Celsius is the freezing point; 32 degrees is the same temperature in Fahrenheit."),
        QuestionSeed("Which planet is third from the Sun?",
                     ["Venus", "Earth", "Mars", "Jupiter"], 1,
                     "Earth orbits between Venus and Mars at an average distance of about 150 million kilometres from the Sun."),
        QuestionSeed("Which state of matter has both a definite shape and a definite volume?",
                     ["A solid", "A liquid", "A gas", "A plasma"], 0,
                     "Particles in a solid remain in closely packed positions while vibrating in place."),
        QuestionSeed("What supplies the energy for photosynthesis?",
                     ["Sunlight", "Gravity", "Wind", "Sound"], 0,
                     "Plants capture light energy and store it in chemical bonds."),
        QuestionSeed("Which organs exchange oxygen and carbon dioxide during human breathing?",
                     ["The kidneys", "The lungs", "The stomach", "The pancreas"], 1,
                     "Gas exchange occurs across the thin walls of tiny air sacs called alveoli."),
        QuestionSeed("What is the chemical symbol for iron?",
                     ["Ir", "I", "Fe", "In"], 2,
                     "Fe comes from ferrum, the Latin word for iron."),
        QuestionSeed("Which simple machine is a rigid bar that pivots around a fulcrum?",
                     ["A lever", "A pulley", "A wedge", "A screw"], 0,
                     "Changing the distances from the fulcrum lets a lever multiply force or movement."),
        QuestionSeed("About how long does Earth take to complete one orbit of the Sun?",
                     ["One day", "One month", "One year", "Ten years"], 2,
                     "The orbital period is about 365.24 days, which is why leap years are needed."),
        QuestionSeed("What produces sound in a material?",
                     ["Vibrations", "Shadows", "Static charge alone", "Vacuum pressure"], 0,
                     "Vibrations create pressure waves that travel through a medium such as air, water, or a solid."),
        QuestionSeed("What are the two ends of a magnet called?",
                     ["North and south poles", "Positive and negative cells", "East and west faces", "Anode and cathode"], 0,
                     "Opposite magnetic poles attract, while like poles repel."),
        QuestionSeed("How many chambers does the human heart have?",
                     ["Four", "Two", "Three", "Six"], 0,
                     "The human heart has four chambers: two atria on top and two ventricles below."),
        QuestionSeed("What is the chemical symbol for sodium?",
                     ["Na", "So", "Sd", "S"], 0,
                     "Sodium's symbol Na comes from natrium, the Latin name still used in several languages."),
        QuestionSeed("Which animal group do frogs belong to?",
                     ["Amphibians", "Reptiles", "Mammals", "Invertebrates"], 0,
                     "Frogs are amphibians, starting life in water as tadpoles before breathing air as adults."),
        QuestionSeed("What is the outermost layer of Earth called?",
                     ["The crust", "The mantle", "The outer core", "The inner core"], 0,
                     "The crust is Earth's thin rocky shell, floating on the far thicker mantle beneath."),
        QuestionSeed("Which gas do humans need to breathe in?",
                     ["Oxygen", "Helium", "Argon", "Hydrogen"], 0,
                     "Human cells need oxygen to release energy from food, which is why we breathe constantly."),
        QuestionSeed("What do we call animals that eat both plants and meat?",
                     ["Omnivores", "Herbivores", "Carnivores", "Detritivores"], 0,
                     "Omnivores such as bears and humans digest both plant material and animal protein."),
        QuestionSeed("Which part of the eye controls how much light enters?",
                     ["The iris", "The retina", "The cornea", "The lens"], 0,
                     "The iris is the colored ring of muscle that widens or narrows the pupil."),
        QuestionSeed("How many teeth does a typical adult human have?",
                     ["32", "28", "36", "24"], 0,
                     "A full adult set is 32 teeth, including the four wisdom teeth many people have removed."),
        QuestionSeed("What is the study of living things called?",
                     ["Biology", "Geology", "Ecology", "Astronomy"], 0,
                     "Biology is the study of living things, from single cells to whole ecosystems."),
        QuestionSeed("What happens to liquid water's volume when it freezes into ice?",
                     ["It expands", "It contracts", "It stays exactly the same", "It splits into gases"], 0,
                     "Water expands as it freezes because its molecules form an open crystal structure, which is why ice floats."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("What is the chemical symbol for potassium?",
                     ["P", "Pt", "K", "Po"], 2,
                     "K comes from kalium, the Latin name derived from the Arabic for potash."),
        QuestionSeed("How long does light from the Sun take to reach Earth?",
                     ["About 8 seconds", "About 8 minutes", "About 8 hours", "About 8 days"], 1,
                     "Roughly eight minutes and twenty seconds at Earth's average distance."),
        QuestionSeed("What is the powerhouse of the cell?",
                     ["The nucleus", "The mitochondrion", "The ribosome", "The vacuole"], 1,
                     "Mitochondria generate most of the cell's chemical energy in the form of ATP."),
        QuestionSeed("Which scientist proposed the theory of general relativity?",
                     ["Sir Isaac Newton", "Albert Einstein", "Niels Bohr", "Max Planck"], 1,
                     "Einstein published the general theory in 1915, describing gravity as curved spacetime."),
        QuestionSeed("What is the pH of a neutral solution at room temperature?",
                     ["0", "7", "10", "14"], 1,
                     "Below 7 is acidic and above 7 is basic."),
        QuestionSeed("Which element has the atomic number 1?",
                     ["Helium", "Hydrogen", "Lithium", "Carbon"], 1,
                     "Hydrogen has a single proton and is the most abundant element in the universe."),
        QuestionSeed("What is the speed of light in a vacuum, approximately?",
                     ["300,000 km per second", "300,000 km per hour", "3,000 km per second", "30,000 km per second"], 0,
                     "About 299,792 kilometres per second, a fixed constant in physics."),
        QuestionSeed("Which gas do humans exhale in greater quantity than they inhale?",
                     ["Nitrogen", "Carbon dioxide", "Oxygen", "Hydrogen"], 1,
                     "Respiration consumes oxygen and produces carbon dioxide."),
        QuestionSeed("What is the study of fossils called?",
                     ["Archaeology", "Palaeontology", "Geology", "Anthropology"], 1,
                     "Archaeology studies human artefacts; palaeontology studies ancient life."),
        QuestionSeed("What does DNA stand for?",
                     ["Deoxyribonucleic acid", "Dinucleic acid", "Diribose nucleic acid", "Deoxyribose nitrate"], 0,
                     "DNA carries the genetic instructions used in the growth and function of organisms."),
        QuestionSeed("Which planet rotates on its side relative to its orbit?",
                     ["Neptune", "Uranus", "Saturn", "Venus"], 1,
                     "Uranus has an axial tilt of about 98 degrees, which may have resulted from one or more ancient impacts."),
        QuestionSeed("What is the most abundant metal in Earth's crust?",
                     ["Iron", "Aluminium", "Copper", "Magnesium"], 1,
                     "Aluminium makes up about eight percent of the crust by mass."),
        QuestionSeed("What is Newton's third law of motion?",
                     ["Objects in motion stay in motion", "Force equals mass times acceleration", "Every action has an equal and opposite reaction", "Energy cannot be created or destroyed"], 2,
                     "Forces always occur in pairs acting on different objects."),
        QuestionSeed("What kind of energy does a moving object have?",
                     ["Potential energy", "Kinetic energy", "Thermal energy", "Chemical energy"], 1,
                     "Kinetic energy scales with the square of speed, so doubling speed quadruples it."),
        QuestionSeed("Which layer of Earth is the thickest?",
                     ["The crust", "The mantle", "The outer core", "The inner core"], 1,
                     "The mantle makes up roughly 84 percent of Earth's volume."),
        QuestionSeed("What is a light year a measure of?",
                     ["Time", "Distance", "Brightness", "Mass"], 1,
                     "It is the distance light travels in one year, about 9.5 trillion kilometres."),
        QuestionSeed("Which blood type is often called the universal donor for red cells?",
                     ["A positive", "B negative", "O negative", "AB positive"], 2,
                     "O negative red cells lack the A, B, and RhD antigens that trigger common reactions."),
        QuestionSeed("What is the chemical formula for table salt?",
                     ["NaCl", "KCl", "CaCO3", "NaHCO3"], 0,
                     "Sodium chloride. NaHCO3 is baking soda."),
        QuestionSeed("Which scientist developed the periodic table's early form?",
                     ["Dmitri Mendeleev", "Antoine Lavoisier", "John Dalton", "Robert Boyle"], 0,
                     "Mendeleev left gaps for elements not yet discovered and predicted their properties."),
        QuestionSeed("What process do cells use to divide for growth and repair?",
                     ["Meiosis", "Mitosis", "Osmosis", "Diffusion"], 1,
                     "Meiosis is the different process that produces sex cells."),
        QuestionSeed("Which particle was discovered at CERN in 2012?",
                     ["The electron neutrino", "The Higgs boson", "The quark", "The positron"], 1,
                     "Its discovery confirmed the mechanism that gives elementary particles mass."),
        QuestionSeed("What is the hottest planet in the solar system?",
                     ["Mercury", "Venus", "Mars", "Jupiter"], 1,
                     "Venus is hotter than Mercury despite being farther out, because of a runaway greenhouse effect."),
        QuestionSeed("What are the three states of matter most commonly taught?",
                     ["Solid, liquid, gas", "Hot, warm, cold", "Metal, mineral, gas", "Acid, base, salt"], 0,
                     "Plasma is often taught as a fourth state."),
        QuestionSeed("Which organ produces insulin?",
                     ["The liver", "The pancreas", "The pituitary gland", "The thyroid"], 1,
                     "Beta cells in the pancreatic islets release insulin to regulate blood sugar."),
        QuestionSeed("What does a seismograph directly record?",
                     ["Rainfall", "Ground motion", "Wind direction", "Solar activity"], 1,
                     "A seismograph records ground motion produced by seismic waves, including those from earthquakes."),
        QuestionSeed("What is the main component of natural gas?",
                     ["Methane", "Propane", "Butane", "Ethane"], 0,
                     "Methane is CH4, the simplest hydrocarbon."),
        QuestionSeed("Which type of rock forms from cooled magma or lava?",
                     ["Sedimentary", "Igneous", "Metamorphic", "Organic"], 1,
                     "Granite and basalt are common igneous rocks."),
        QuestionSeed("What is absolute zero on the Celsius scale?",
                     ["0 degrees", "-100 degrees", "-273.15 degrees", "-459 degrees"], 2,
                     "That is 0 kelvin, the point at which classical thermal motion stops."),
        QuestionSeed("Which scientist is credited with the laws of planetary motion?",
                     ["Johannes Kepler", "Tycho Brahe", "Galileo Galilei", "Nicolaus Copernicus"], 0,
                     "Kepler showed the orbits are ellipses, not perfect circles."),
        QuestionSeed("What does an ecosystem consist of?",
                     ["Living organisms and their physical environment", "Only plants", "Only animals", "Only the climate"], 0,
                     "The interactions between the living and non-living parts define the system."),
        QuestionSeed("Which organelle carries out photosynthesis in plant cells?",
                     ["The mitochondrion", "The chloroplast", "The lysosome", "The ribosome"], 1,
                     "Chloroplasts contain chlorophyll and convert light energy into chemical energy."),
        QuestionSeed("What is the SI unit of force?",
                     ["The joule", "The watt", "The newton", "The pascal"], 2,
                     "One newton accelerates a one-kilogram mass at one metre per second squared."),
        QuestionSeed("Which blood vessels generally carry blood away from the heart?",
                     ["Arteries", "Veins", "Capillaries", "Lymphatic vessels"], 0,
                     "Pulmonary arteries carry oxygen-poor blood, showing that direction rather than oxygen content defines an artery."),
        QuestionSeed("In which atmospheric layer is most of the ozone layer found?",
                     ["The troposphere", "The stratosphere", "The mesosphere", "The thermosphere"], 1,
                     "Stratospheric ozone absorbs much of the Sun's harmful ultraviolet radiation."),
        QuestionSeed("What is Earth's gravitational acceleration near sea level, approximately?",
                     ["0.98 metres per second squared", "9.8 metres per second squared", "98 metres per second squared", "980 metres per second squared"], 1,
                     "The value varies slightly with latitude and elevation but is commonly rounded to 9.8 m/s²."),
        QuestionSeed("At room temperature, what does a pH below 7 usually indicate?",
                     ["An acidic solution", "A neutral solution", "A basic solution", "A saturated solution"], 0,
                     "Lower pH corresponds to greater hydrogen-ion activity; a pH of 7 is neutral under ordinary conditions."),
        QuestionSeed("Which base in RNA replaces the thymine found in DNA?",
                     ["Uracil", "Cytosine", "Guanine", "Adenine"], 0,
                     "RNA commonly pairs adenine with uracil instead of thymine."),
        QuestionSeed("What is refraction?",
                     ["A change in a wave's direction as its speed changes between media", "The complete absorption of a wave", "The production of an electric charge", "The splitting of an atomic nucleus"], 0,
                     "Light bends at an interface because it travels at different speeds in the two materials."),
        QuestionSeed("What happens at a subduction zone?",
                     ["One tectonic plate sinks beneath another", "Two plates move apart and form a rift", "A continent stops moving", "Earth's magnetic poles reverse"], 0,
                     "Subduction recycles lithosphere into the mantle and is associated with trenches, earthquakes, and volcanic arcs."),
        QuestionSeed("In a saltwater solution, what is the solvent?",
                     ["The water", "The salt", "The dissolved ions only", "The container"], 0,
                     "The solvent is the component that dissolves the solute and is usually present in greater amount."),
        QuestionSeed("What does DNA's double helix structure resemble?",
                     ["A twisted ladder", "A flat ribbon", "A closed loop", "A branching tree diagram"], 0,
                     "DNA forms a double helix, often described as a twisted ladder of paired bases."),
        QuestionSeed("Which organs filter waste from the blood?",
                     ["The kidneys", "The liver", "The spleen", "The gallbladder"], 0,
                     "The kidneys filter blood continuously, sending waste and excess water out as urine."),
        QuestionSeed("What is the chemical symbol for silver?",
                     ["Ag", "Si", "Sv", "Au"], 0,
                     "Silver's symbol Ag comes from argentum, and the metal conducts electricity better than any other."),
        QuestionSeed("Which scientist formulated the three laws of motion?",
                     ["Isaac Newton", "Galileo Galilei", "Robert Hooke", "Christiaan Huygens"], 0,
                     "Isaac Newton published the three laws of motion and universal gravitation in the Principia."),
        QuestionSeed("What is the SI unit of electric current?",
                     ["The ampere", "The volt", "The ohm", "The coulomb"], 0,
                     "The ampere measures how much electric charge flows past a point each second."),
        QuestionSeed("Which process turns a gas directly into a solid?",
                     ["Deposition", "Sublimation", "Condensation", "Precipitation"], 0,
                     "Deposition skips the liquid stage entirely, as when water vapor forms frost on cold glass."),
        QuestionSeed("Which vitamin deficiency causes scurvy?",
                     ["Vitamin C", "Vitamin B12", "Vitamin K", "Vitamin A"], 0,
                     "Scurvy follows a lack of vitamin C, which the body needs to build collagen."),
        QuestionSeed("What is the largest artery in the human body?",
                     ["The aorta", "The vena cava", "The carotid", "The femoral artery"], 0,
                     "The aorta carries oxygenated blood out of the left ventricle to the rest of the body."),
        QuestionSeed("What does an ecosystem's food chain describe?",
                     ["Who eats whom", "Soil mineral content", "Seasonal rainfall totals", "Migration route distances"], 0,
                     "A food chain describes who eats whom, tracing energy from producers to predators."),
        QuestionSeed("Which galaxy contains our solar system?",
                     ["The Milky Way", "Andromeda", "The Triangulum Galaxy", "The Large Magellanic Cloud"], 0,
                     "The Milky Way is a barred spiral galaxy holding a few hundred billion stars."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("What is the Chandrasekhar limit?",
                     ["The maximum mass of a stable white dwarf", "The size of the observable universe", "The speed limit of a photon", "The minimum mass of a planet"], 0,
                     "Around 1.4 solar masses; above it a white dwarf collapses further."),
        QuestionSeed("Which enzyme unwinds the DNA double helix during replication?",
                     ["Helicase", "Ligase", "Polymerase", "Primase"], 0,
                     "Polymerase then builds the new strands along the separated templates."),
        QuestionSeed("What does the second law of thermodynamics state about entropy?",
                     ["It never decreases in an isolated system", "The entropy of every isolated system remains exactly equal to zero", "Entropy spontaneously declines as an isolated system grows older", "A system's entropy is numerically equal to its absolute temperature"], 0,
                     "The law explains why heat flows from hot to cold and why perpetual motion is impossible."),
        QuestionSeed("What is a superconductor?",
                     ["A material with zero electrical resistance below a critical temperature", "A very fast semiconductor", "A material that blocks magnetic fields while retaining ordinary resistance", "An insulated cable designed to transmit an extremely high voltage safely"], 0,
                     "Superconductors also expel magnetic fields through the Meissner–Ochsenfeld effect, commonly shortened to the Meissner effect."),
        QuestionSeed("Which element is the most electronegative?",
                     ["Fluorine", "Oxygen", "Chlorine", "Nitrogen"], 0,
                     "Fluorine sits at the top of the Pauling electronegativity scale."),
        QuestionSeed("What is the Doppler effect?",
                     ["A change in observed frequency due to relative motion", "The path of light curving as it travels close to a massive object", "Short blue wavelengths scattering preferentially through the atmosphere", "The decay of radioactive isotopes"], 0,
                     "It explains a passing siren's pitch shift and helps measure stellar radial motion; cosmological redshift additionally reflects expanding spacetime."),
        QuestionSeed("What are prokaryotic cells distinguished by?",
                     ["The absence of a membrane-bound nucleus", "The presence of chloroplasts", "Having two nuclei", "Being multicellular"], 0,
                     "Bacteria and archaea are prokaryotes; plants, animals, and fungi are eukaryotes."),
        QuestionSeed("What does the Heisenberg uncertainty principle describe?",
                     ["A limit on knowing position and momentum simultaneously", "The average lifetime of a free neutron before it undergoes beta decay", "The relationship between matter and the geometric curvature of spacetime", "The fractional electric charge carried by an individual quark"], 0,
                     "The more precisely one is known, the less precisely the other can be."),
        QuestionSeed("What is the half-life of carbon-14, approximately?",
                     ["5,730 years", "1,600 years", "24,000 years", "710 million years"], 0,
                     "That half-life makes it useful for dating organic material up to roughly 50,000 years old."),
        QuestionSeed("What is an isotope?",
                     ["An atom with the same protons but a different number of neutrons", "An atom that has gained or lost electrons and therefore carries a net charge", "A bonded group containing atoms belonging to two different elements", "A molecule whose chemical bonds break apart spontaneously because it is unstable"], 0,
                     "Isotopes share chemical behaviour but differ in mass and sometimes in stability."),
        QuestionSeed("What is the event horizon of a black hole?",
                     ["The boundary beyond which nothing can escape", "The centre of the black hole", "The disc of extremely hot gas orbiting outside a compact object", "A distorted image of a background source produced by intense gravity"], 0,
                     "The singularity is at the centre; the event horizon is the boundary around it."),
        QuestionSeed("Which process do stars use to convert hydrogen into helium?",
                     ["Nuclear fusion", "Nuclear fission", "Combustion", "Radioactive decay"], 0,
                     "Fusion in the core releases the energy that keeps a star from collapsing."),
        QuestionSeed("What is the function of ribosomes?",
                     ["Assembling proteins from amino acids", "Storing genetic material", "Converting energy from nutrients into ATP that a cell can use", "Breaking down damaged macromolecules inside cellular compartments"], 0,
                     "They read messenger RNA and link amino acids in the specified order."),
        QuestionSeed("What is the Coriolis effect responsible for?",
                     ["The deflection of moving air and water on a rotating Earth", "The periodic rise and fall of the oceans under the gravity of the Moon and Sun", "The release of magma, gas, and ash through openings in Earth's crust", "Reversals in the orientation of Earth's magnetic field preserved in rocks"], 0,
                     "It is why large weather systems rotate in opposite directions in the two hemispheres."),
        QuestionSeed("Which type of radiation is stopped by a sheet of paper?",
                     ["Alpha", "Beta", "Gamma", "X-ray"], 0,
                     "Beta needs thin metal and gamma needs dense shielding such as lead."),
        QuestionSeed("What is CRISPR primarily used for?",
                     ["Editing genes at specific sequences", "Copying a selected DNA segment into millions of laboratory duplicates", "Determining the order of amino acids in a completed protein", "Growing a population of bacteria in a controlled nutrient medium"], 0,
                     "The technique adapts a bacterial immune mechanism into a precise editing tool."),
        QuestionSeed("What is the approximate age of the universe?",
                     ["13.8 billion years", "4.5 billion years", "100 billion years", "500 million years"], 0,
                     "4.5 billion years is roughly the age of Earth, not the universe."),
        QuestionSeed("What does a catalyst do in a chemical reaction?",
                     ["Speeds it up without being consumed", "Is consumed to release energy", "Raises the activation energy", "Stops the reaction"], 0,
                     "Catalysts lower the activation energy and emerge unchanged."),
        QuestionSeed("What is the difference between accuracy and precision?",
                     ["Accuracy is closeness to the true value; precision is repeatability", "Accuracy and precision are two names for the same measurement property", "Precision is closeness to the true value", "Accuracy can describe only an average and never a single measurement"], 0,
                     "A measurement can be precise and consistently wrong."),
        QuestionSeed("Which force binds protons and neutrons in the nucleus?",
                     ["The strong nuclear force", "The weak nuclear force", "Electromagnetism", "Gravity"], 0,
                     "It overcomes the electrical repulsion between positively charged protons."),
        QuestionSeed("What is a mole in chemistry?",
                     ["A quantity containing Avogadro's number of particles", "A unit of mass used when weighing extremely small laboratory samples", "A measure of concentration only", "An attraction that holds atoms together through shared or transferred electrons"], 0,
                     "One mole is about 6.022 times ten to the twenty-third particles."),
        QuestionSeed("What is horizontal gene transfer?",
                     ["Genetic material moving between organisms other than from parent to offspring", "The complete genomes of two species combining during reproduction to create one hybrid lineage", "Chromosomes lining up during mitosis", "A trait disappearing through natural selection"], 0,
                     "Horizontal gene transfer is common among bacteria and can spread traits such as antibiotic resistance."),
        QuestionSeed("Which gas makes up the largest share of human-caused greenhouse-gas emissions by carbon-dioxide equivalent?",
                     ["Carbon dioxide", "Methane", "Nitrous oxide", "Fluorinated gases"], 0,
                     "Carbon dioxide accounts for the largest share of global human-caused greenhouse-gas emissions when gases are compared by carbon-dioxide equivalent."),
        QuestionSeed("What does an electron's orbital describe?",
                     ["A probability distribution for the electron's location", "The exact circular track an electron follows around the atomic nucleus", "The electron's mass", "The physical distance from the centre of a nucleus to its outer edge"], 0,
                     "Quantum mechanics replaced fixed orbits with probability clouds."),
        QuestionSeed("What is the cosmic microwave background?",
                     ["Residual radiation from the early universe", "Light from the nearest galaxy", "A stream of charged particles flowing outward from the surface of the Sun", "Radiation from black holes"], 0,
                     "It is the oldest light we can observe, released about 380,000 years after the Big Bang."),
        QuestionSeed("What is homeostasis?",
                     ["Maintaining stable internal conditions", "The process by which one parent cell separates into daughter cells", "A permanent alteration in the nucleotide sequence of genetic material", "Chemical reactions that release energy in a form the cell can use"], 0,
                     "Body temperature and blood glucose regulation are classic examples."),
        QuestionSeed("What is the difference between a virus and a bacterium?",
                     ["A virus is not a cell and needs a host to replicate", "A virus is larger", "A bacterium depends completely on a host cell in order to reproduce", "They are the same"], 0,
                     "This is why antibiotics work on bacteria but not on viruses."),
        QuestionSeed("Which quantity is conserved in an elastic collision but not an inelastic one?",
                     ["Kinetic energy", "Momentum", "Mass", "Charge"], 0,
                     "Momentum is conserved in both; kinetic energy only in elastic collisions."),
        QuestionSeed("What is the Krebs cycle also known as?",
                     ["The citric acid cycle", "The Calvin cycle", "The nitrogen cycle", "The urea cycle"], 0,
                     "The cycle is central to aerobic respiration; it occurs in mitochondria in eukaryotes and in the cytosol of prokaryotes."),
        QuestionSeed("What is dark matter inferred from?",
                     ["Gravitational effects that visible matter cannot explain", "Direct telescope photographs showing dark particles blocking distant stars", "Characteristic radio waves emitted by atoms that compose dark matter", "Neutrino detectors counting particles produced by the decay of dark matter"], 0,
                     "Galaxy rotation curves and gravitational lensing both point to unseen mass."),
        QuestionSeed("What does chirality mean in chemistry?",
                     ["A structure is not superimposable on its mirror image", "A molecule has no carbon atoms", "A chemical reaction releases some of its energy as visible light", "A bond contains shared electrons"], 0,
                     "Chiral molecules can exist as mirror-image forms called enantiomers."),
        QuestionSeed("What is a Lagrange point in orbital mechanics?",
                     ["A location where a small object can orbit in a constant pattern with two larger bodies", "The point where a planet's atmosphere ends", "The centre of a galaxy", "The closest point in any elliptical orbit to the Sun regardless of the body being orbited"], 0,
                     "The five Lagrange points arise where gravity and orbital motion balance in a rotating two-body system."),
        QuestionSeed("What is telomerase?",
                     ["An enzyme that extends chromosome-end sequences", "An enzyme that breaks glucose apart during cellular respiration", "A lipid in cell membranes", "A hormone controlling sleep"], 0,
                     "Telomerase adds repetitive DNA to telomeres and is active in germ cells, many stem cells, and many cancers."),
        QuestionSeed("Under what conditions can a Bose-Einstein condensate form?",
                     ["When certain bosons are cooled extremely close to absolute zero", "When a gas is heated into plasma", "When ions in a saturated salt solution arrange into a crystal lattice", "When nuclei undergo fission"], 0,
                     "At ultralow temperature, many particles occupy the same quantum state and behave collectively."),
        QuestionSeed("What does the Pauli exclusion principle state for identical fermions?",
                     ["No two can occupy the same quantum state simultaneously", "Every identical fermion must possess exactly zero rest mass", "Identical fermions always exert an attractive force on one another", "The energy possessed by an individual fermion can never change"], 0,
                     "The principle shapes electron configurations and the structure of the periodic table."),
        QuestionSeed("What is an operon?",
                     ["A group of genes regulated together under one control system", "A specialized cellular organelle enclosed by a lipid membrane", "A phase of mitosis during which duplicated chromosomes begin separating", "A protein that copies an RNA molecule into another identical RNA molecule"], 0,
                     "Operons are especially common in prokaryotes, where related genes may be transcribed into one messenger RNA."),
        QuestionSeed("For a process at constant temperature and pressure, what does a negative change in Gibbs free energy indicate?",
                     ["The process is thermodynamically spontaneous", "The process cannot take place under any possible physical conditions", "The total entropy of the system and its surroundings must decrease", "The system is unable to exchange either heat or work with its surroundings"], 0,
                     "A negative ΔG means the process is favourable under the specified conditions, not necessarily that it occurs quickly."),
        QuestionSeed("What does cosmic inflation propose?",
                     ["An extremely rapid early expansion of space", "A gradual increase in star size", "The slowing of all galaxies", "The creation of heavy elements in supernovae"], 0,
                     "Inflation helps explain the observable universe's large-scale uniformity and near-flat geometry."),
        QuestionSeed("What relationship does the Hubble-Lemaître law describe?",
                     ["More distant galaxies generally recede faster", "Hotter stars are always larger", "Planetary periods increase with mass", "Black holes emit visible light"], 0,
                     "A galaxy's recession speed is approximately proportional to its distance on sufficiently large scales."),
        QuestionSeed("What is epigenetic DNA methylation commonly associated with?",
                     ["Changes in gene regulation without changing the DNA sequence", "RNA molecules permanently replacing the DNA inside a chromosome", "Doubling the chromosome number", "Covalent bonds joining amino acids together being broken by hydrolysis"], 0,
                     "Adding methyl groups to DNA can alter transcription and help establish cell-specific patterns of gene activity."),
    ]
}
