import Foundation

enum SoccerQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("How many players does each team start with on the field?",
                     ["9", "10", "11", "12"], 2,
                     "Eleven per side, including the goalkeeper."),
        QuestionSeed("What colour card sends a player off the field?",
                     ["Blue", "Green", "Yellow", "Red"], 3,
                     "A red card means the player leaves and the team plays a man short."),
        QuestionSeed("How long is a standard match before stoppage time?",
                     ["60 minutes", "80 minutes", "90 minutes", "100 minutes"], 2,
                     "Two halves of forty-five minutes, plus whatever time the referee adds on."),
        QuestionSeed("Who is allowed to handle the ball inside their own penalty area?",
                     ["The captain", "The goalkeeper", "Any defender", "The striker"], 1,
                     "Only the goalkeeper, and only within their own penalty area."),
        QuestionSeed("What restarts play when the ball crosses the touchline?",
                     ["A throw-in", "A drop ball", "A goal kick", "A penalty"], 0,
                     "The team that did not touch it last takes the throw-in."),
        QuestionSeed("How often is the men's FIFA World Cup normally held?",
                     ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"], 2,
                     "The tournament runs on a four-year cycle."),
        QuestionSeed("What is it called when one player scores three goals in a match?",
                     ["A triple play", "A hat-trick", "A clean sheet", "A treble"], 1,
                     "The term was borrowed from cricket in the nineteenth century."),
        QuestionSeed("Which country won the first men's World Cup in 1930?",
                     ["Brazil", "Italy", "Argentina", "Uruguay"], 3,
                     "Hosts Uruguay beat Argentina 4-2 in the final in Montevideo."),
        QuestionSeed("What is a match in which a team concedes no goals called?",
                     ["A clean sheet", "A nil draw", "A shutout kick", "A blank"], 0,
                     "Goalkeepers and defences take particular pride in clean-sheet records."),
        QuestionSeed("From where is a penalty kick taken?",
                     ["The centre circle", "The six-yard box", "The penalty mark", "The corner arc"], 2,
                     "The mark sits twelve yards from the goal line."),
        QuestionSeed("Which body governs world soccer?",
                     ["UEFA", "FIFA", "IOC", "CONCACAF"], 1,
                     "FIFA organizes the World Cup and oversees the regional confederations."),
        QuestionSeed("Which body part may an outfield player not deliberately use?",
                     ["The head", "The chest", "The foot", "The hand"], 3,
                     "Deliberate handball by an outfield player is an offence."),
        QuestionSeed("What is the object of the game?",
                     ["To score more goals than the opponent", "To keep possession longest", "To take the most shots", "To win the most corners"], 0,
                     "Only goals decide the result, however one-sided the other statistics are."),
        QuestionSeed("What is awarded when a defender sends the ball over their own goal line outside the goal?",
                     ["A goal kick", "A corner kick", "A throw-in", "A free kick"], 1,
                     "The attacking team takes a corner from the nearest corner arc; a ball crossing between the posts and under the bar may instead be a goal."),
        QuestionSeed("How many halves are in a regulation match?",
                     ["One", "Two", "Three", "Four"], 1,
                     "Two halves separated by a halftime interval of about fifteen minutes."),
        QuestionSeed("What is the name of the player who defends the goal?",
                     ["The sweeper", "The goalkeeper", "The libero", "The winger"], 1,
                     "The goalkeeper wears a different shirt colour from every other player on the field."),
        QuestionSeed("What does a yellow card signify?",
                     ["A goal is disallowed", "A formal caution", "A substitution", "The end of a half"], 1,
                     "Two yellow cards in one match add up to a red."),
        QuestionSeed("What is the field of play usually called?",
                     ["The pitch", "The court", "The diamond", "The rink"], 0,
                     "Pitch is the standard term in most of the soccer-playing world."),
        QuestionSeed("What is a 'striker'?",
                     ["A forward whose main job is scoring", "A defensive midfielder", "A backup goalkeeper", "A referee's assistant"], 0,
                     "Strikers play highest up the field and take most of a team's shots."),
        QuestionSeed("How many substitutes are typically allowed in a competitive match today?",
                     ["One", "Three", "Five", "Unlimited"], 2,
                     "Five substitutions became standard in most competitions after 2020."),
        QuestionSeed("Which continent has won the most men's World Cups?",
                     ["Africa", "Asia", "Europe", "North America"], 2,
                     "European nations have won a majority of the tournaments, with South America second."),
        QuestionSeed("What is 'extra time'?",
                     ["Two additional periods in a knockout tie", "Stoppage time", "A halftime extension", "A substitution window"], 0,
                     "Two fifteen-minute periods, used when a knockout match is level after ninety minutes."),
        QuestionSeed("What resolves a knockout match still level after extra time?",
                     ["A coin toss", "A penalty shoot-out", "A replay the next day", "Shared victory"], 1,
                     "Each team takes five penalties, then sudden death if the score is still level."),
        QuestionSeed("What is the centre circle used for?",
                     ["Kick-offs", "Penalties", "Throw-ins", "Corner kicks"], 0,
                     "Opponents must stay outside the circle until the ball is in play."),
        QuestionSeed("Which competition is the biggest club tournament in Europe?",
                     ["The UEFA Champions League", "The Copa América", "The Africa Cup of Nations", "The World Cup"], 0,
                     "It brings together the leading clubs from Europe's domestic leagues each season."),
        QuestionSeed("What is a 'draw' in soccer?",
                     ["A match ending level", "A penalty award", "A red card", "A tactical formation"], 0,
                     "League tables usually award one point to each team for a draw."),
        QuestionSeed("Which match official keeps time and has final authority over decisions on the field?",
                     ["The referee", "The team captain", "The stadium announcer", "The fourth official"], 0,
                     "The referee enforces the Laws of the Game, keeps the official time, and makes the final on-field decisions."),
        QuestionSeed("What size ball is used in adult matches?",
                     ["Size 3", "Size 4", "Size 5", "Size 6"], 2,
                     "Size 5 is the regulation ball for players aged twelve and up."),
        QuestionSeed("Which country is nicknamed 'La Albiceleste'?",
                     ["Argentina", "Spain", "Chile", "Uruguay"], 0,
                     "The name refers to the white and sky-blue stripes of the Argentine shirt."),
        QuestionSeed("What is a 'free kick'?",
                     ["A restart awarded after a foul", "A penalty", "A throw-in", "A corner"], 0,
                     "Free kicks are direct or indirect depending on the offence committed."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("What is the offside rule primarily designed to prevent?",
                     ["Goal hanging near the opponent's goal", "Time wasting", "Rough tackling", "Excessive substitutions"], 0,
                     "At the relevant moment, an attacker in the opponents' half is in an offside position only if nearer the goal line than both the ball and the second-last opponent; an offence also requires involvement in play."),
        QuestionSeed("How far from the goal line is the penalty mark?",
                     ["10 yards", "12 yards", "15 yards", "18 yards"], 1,
                     "Twelve yards, or roughly eleven metres."),
        QuestionSeed("What is a 'brace'?",
                     ["Two goals by one player", "Two yellow cards", "Two substitutions", "Two clean sheets"], 0,
                     "Three goals is a hat-trick; two is a brace."),
        QuestionSeed("Which trophy do the English top-flight league champions receive?",
                     ["The Premier League Trophy", "The FA Cup", "The Champions League Trophy", "The Community Shield"], 0,
                     "The FA Cup is a separate knockout competition run by the Football Association."),
        QuestionSeed("What does VAR stand for?",
                     ["Video Assistant Referee", "Verified Attack Review", "Visual Analysis Report", "Variable Added Recovery"], 0,
                     "VAR reviews goals, penalties, red cards, and cases of mistaken identity."),
        QuestionSeed("How wide must a regulation goal be?",
                     ["6 yards", "8 yards", "10 yards", "12 yards"], 1,
                     "Eight yards wide and eight feet high."),
        QuestionSeed("What is a 'derby' in soccer?",
                     ["A match between local rivals", "A cup final", "A friendly match", "A relegation playoff"], 0,
                     "Derbies are often the most heated fixtures on a club's calendar."),
        QuestionSeed("What happens to a team whose player is sent off?",
                     ["A substitute replaces them", "They play with one fewer player", "The match is abandoned", "They lose a goal"], 1,
                     "The sent-off player cannot be replaced, so the team is down to ten."),
        QuestionSeed("What is 'relegation'?",
                     ["Dropping to a lower division", "Losing a cup tie", "A points deduction", "A transfer ban"], 0,
                     "The lowest-placed teams move down and are replaced by promoted clubs."),
        QuestionSeed("Which tournament is South America's national-team championship?",
                     ["The Copa América", "The Copa Libertadores", "The Gold Cup", "The Nations League"], 0,
                     "The Copa Libertadores is the equivalent club competition."),
        QuestionSeed("What is a 'nutmeg'?",
                     ["Playing the ball through an opponent's legs", "A diving header", "A long-range shot", "A defensive clearance"], 0,
                     "It is one of the game's most celebrated pieces of individual skill."),
        QuestionSeed("How many points does a win earn in most league systems today?",
                     ["One", "Two", "Three", "Four"], 2,
                     "Three points for a win replaced two in order to reward attacking play."),
        QuestionSeed("What is the 'six-yard box' used for?",
                     ["Goal kicks", "Penalties", "Corner kicks", "Throw-ins"], 0,
                     "Goal kicks are taken from anywhere inside it."),
        QuestionSeed("What is a 'direct free kick'?",
                     ["One that can be scored without another player touching the ball", "One taken from the corner", "One taken by the goalkeeper", "One that must be passed first"], 0,
                     "An indirect free kick requires a second touch before a goal can count."),
        QuestionSeed("What does the term 'the treble' mean for a club?",
                     ["Winning three major trophies in one season", "Scoring three goals", "Three consecutive titles", "Three clean sheets"], 0,
                     "The classic treble is the domestic league, the domestic cup, and the European title."),
        QuestionSeed("Which position sits between the defence and the attack?",
                     ["Midfielder", "Full-back", "Sweeper", "Goalkeeper"], 0,
                     "Midfielders link play and usually cover the most ground in a match."),
        QuestionSeed("What makes a tackle legal under the Laws of the Game?",
                     ["It is made without careless, reckless, or excessive force", "The tackler touches the ball first", "It is always a sliding challenge", "It comes only from the front"], 0,
                     "Touching the ball first does not excuse a challenge made carelessly, recklessly, or with excessive force."),
        QuestionSeed("What is the maximum number of defenders allowed in a free-kick wall?",
                     ["Three", "Five", "There is no fixed limit", "Ten"], 2,
                     "There is no fixed maximum; when a wall has three or more defenders, attacking players must remain at least one metre away until the ball is in play."),
        QuestionSeed("Which league is Spain's top division?",
                     ["La Liga", "Serie A", "Ligue 1", "The Bundesliga"], 0,
                     "Serie A is Italian, Ligue 1 French, and the Bundesliga German."),
        QuestionSeed("What is a 'through ball'?",
                     ["A pass split between defenders for a runner", "A goal kick", "A long clearance", "A backwards pass"], 0,
                     "Timing matters as much as weight of pass, because of the offside line."),
        QuestionSeed("How long is the halftime interval in a professional match?",
                     ["5 minutes", "10 minutes", "15 minutes", "20 minutes"], 2,
                     "Fifteen minutes is the standard, and players have a right to it."),
        QuestionSeed("What is 'stoppage time' meant to account for?",
                     ["Time lost to injuries, substitutions and delays", "Extra time", "Halftime", "Penalty shoot-outs"], 0,
                     "The fourth official displays the minimum number of added minutes."),
        QuestionSeed("What is a 'formation' such as 4-4-2 describing?",
                     ["Defenders, midfielders and forwards", "Substitution order", "Set-piece routines", "Squad numbers"], 0,
                     "The goalkeeper is assumed and never counted in the notation."),
        QuestionSeed("Which African tournament is contested by national teams?",
                     ["The Africa Cup of Nations", "The CAF Champions League", "The Gold Cup", "The Asian Cup"], 0,
                     "It is held every two years and organized by CAF."),
        QuestionSeed("What is the 'golden boot' awarded for?",
                     ["Being the leading goalscorer", "Best goalkeeper", "Best young player", "Fair play"], 0,
                     "It is presented in most major leagues and tournaments."),
        QuestionSeed("What is an 'own goal'?",
                     ["A goal accidentally scored against one's own team", "A penalty scored by the keeper", "A goal from kick-off", "A disallowed goal"], 0,
                     "It counts for the opposition and is credited as an own goal in the records."),
        QuestionSeed("Which country hosted and won the 1998 men's World Cup?",
                     ["France", "Brazil", "Italy", "Germany"], 0,
                     "France beat Brazil 3-0 in the final in Saint-Denis."),
        QuestionSeed("What is a 'cap' in international soccer?",
                     ["An appearance for the national team", "A transfer fee limit", "A squad size limit", "A wage restriction"], 0,
                     "The term comes from the caps once presented to players for each appearance."),
        QuestionSeed("What is the 'transfer window'?",
                     ["The period when clubs may register new signings", "The halftime interval", "A substitution period", "A loan repayment term"], 0,
                     "Most leagues run a long summer window and a shorter mid-season one."),
        QuestionSeed("What does 'CONCACAF' govern?",
                     ["North and Central American and Caribbean soccer", "South American soccer", "African soccer", "Asian soccer"], 0,
                     "CONMEBOL covers South America; CAF covers Africa."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("What is the 'Laws of the Game' document, and who maintains it?",
                     ["The rulebook maintained by IFAB", "A FIFA marketing charter", "A UEFA licensing code", "A players' union agreement"], 0,
                     "The International Football Association Board, not FIFA alone, decides changes to the laws."),
        QuestionSeed("What is a 'false nine'?",
                     ["A forward who drops deep into midfield", "A defensive midfielder", "An overlapping full-back", "A substitute goalkeeper"], 0,
                     "The role pulls a centre-back out of position and opens space for wide runners."),
        QuestionSeed("In what year was the offside law changed to require two opponents rather than three?",
                     ["1905", "1925", "1948", "1966"], 1,
                     "The 1925 change sharply increased scoring and helped prompt new defensive systems."),
        QuestionSeed("What is 'gegenpressing'?",
                     ["Pressing immediately after losing the ball", "Defending deep in a low block", "Man-marking the goalkeeper", "A set-piece routine"], 0,
                     "The idea is that a team is most vulnerable in the seconds just after it wins possession."),
        QuestionSeed("What is the 'Bosman ruling' known for?",
                     ["Allowing players to move freely at contract expiry", "Introducing goal-line technology", "Creating the Champions League", "Banning third-party ownership"], 0,
                     "The 1995 European Court decision transformed the transfer market."),
        QuestionSeed("What does 'xG' measure?",
                     ["Expected goals from the quality of chances created", "Extra game time", "Exit goals conceded", "Experience grade"], 0,
                     "Each shot is assigned a probability of scoring based on comparable historical attempts."),
        QuestionSeed("What is a 'libero'?",
                     ["A sweeper who plays behind the defensive line", "A wide forward", "A holding midfielder", "A reserve goalkeeper"], 0,
                     "The role was central to Italian catenaccio and to some German sides of the 1970s."),
        QuestionSeed("Which competition did the European Cup become in 1992?",
                     ["The UEFA Champions League", "The Europa League", "The Cup Winners' Cup", "The Super Cup"], 0,
                     "The rebrand introduced a group stage alongside the knockout rounds."),
        QuestionSeed("What is 'catenaccio'?",
                     ["A defensive Italian tactical system", "A Brazilian dribbling style", "A Dutch pressing scheme", "A set-piece routine"], 0,
                     "It emphasized a tight, layered defence with a sweeper behind the back line."),
        QuestionSeed("How many minutes must pass before an abandoned match is usually considered for a result rather than a replay?",
                     ["It varies by competition rules", "Exactly 45", "Exactly 60", "Exactly 75"], 0,
                     "There is no single global threshold; each competition sets its own regulations."),
        QuestionSeed("What is the 'away goals rule' historically used for?",
                     ["Breaking ties in two-legged knockout matches", "Awarding bonus league points", "Deciding penalty order", "Ranking group stages only"], 0,
                     "UEFA abolished it in its club competitions from the 2021-22 season."),
        QuestionSeed("What was 'Total Football' associated with?",
                     ["The Netherlands and Ajax in the 1970s", "Italy in the 1930s", "Brazil in the 1950s", "England in the 1960s"], 0,
                     "Players interchanged positions fluidly, with Rinus Michels and Johan Cruyff its best-known figures."),
        QuestionSeed("What is goal-line technology used to determine?",
                     ["Whether the whole ball crossed the line", "Offside positions", "Handball decisions", "Foul severity"], 0,
                     "It gives the referee an instant automated signal rather than a video review."),
        QuestionSeed("What is a 'panenka' penalty?",
                     ["A softly chipped kick down the middle", "A powerful strike into the roof of the net", "A two-touch penalty", "A left-footed penalty"], 0,
                     "Antonín Panenka scored one in the 1976 European Championship final shoot-out."),
        QuestionSeed("What do UEFA's financial sustainability regulations govern?",
                     ["Club solvency, financial stability, and squad costs", "Ticket prices only", "National-team selection", "Stadium capacity only"], 0,
                     "The current framework evolved from Financial Fair Play and includes solvency, stability, and squad-cost controls."),
        QuestionSeed("Which club competition did Real Madrid win in each of the first five seasons?",
                     ["The European Cup", "The UEFA Cup", "The Cup Winners' Cup", "The Intercontinental Cup"], 0,
                     "Real Madrid won the first five European Cups from 1956 to 1960."),
        QuestionSeed("What is a 'tifo'?",
                     ["A large choreographed supporters' display", "A tactical formation", "A transfer clause", "A type of free kick"], 0,
                     "The word comes from Italian supporter culture and spread across Europe."),
        QuestionSeed("How is the ball's circumference regulated for a size 5 ball?",
                     ["Between 68 and 70 centimetres", "Between 55 and 58 centimetres", "Between 75 and 80 centimetres", "Exactly 72 centimetres"], 0,
                     "The Laws of the Game also set weight and pressure ranges."),
        QuestionSeed("What is 'parking the bus'?",
                     ["Defending with nearly the whole team behind the ball", "Playing a high line", "Rotating the squad", "Time-wasting at corners"], 0,
                     "The phrase entered English soccer vocabulary in the mid-2000s."),
        QuestionSeed("Which country has appeared at every men's World Cup finals tournament?",
                     ["Brazil", "Germany", "Italy", "Argentina"], 0,
                     "Brazil is the only nation to have qualified for every edition."),
        QuestionSeed("What is an 'inverted winger'?",
                     ["A wide player on the opposite side to their stronger foot", "A defensive winger", "A false full-back", "A withdrawn striker"], 0,
                     "Cutting inside onto the stronger foot creates shooting angles rather than crossing angles."),
        QuestionSeed("What does the Ballon d'Or recognize?",
                     ["The best individual player over the award's assessment season", "The top goalscorer only", "The best club side", "The best young player only"], 0,
                     "The award has been presented since 1956 and, since 2022, evaluates performance over a football season rather than a calendar year."),
        QuestionSeed("What does a 'low block' describe?",
                     ["A compact defensive shape near one's own goal", "A blocked shot", "A short corner", "A defensive substitution"], 0,
                     "It cedes territory in exchange for denying space behind the defence."),
        QuestionSeed("What did the 1992 back-pass law prohibit?",
                     ["A goalkeeper handling a ball deliberately kicked by a teammate", "Any pass toward a team's own goal", "Goalkeepers kicking the ball", "Headers back to a goalkeeper"], 0,
                     "The offence is the goalkeeper's handling of a deliberate kick from a teammate, not the backward pass itself; defined exceptions apply."),
        QuestionSeed("What is aggregate score used for?",
                     ["Combining the scores from both legs of a two-legged tie", "Adding league points", "Calculating season goal difference", "Recording only shoot-out goals"], 0,
                     "Competition rules determine whether a level aggregate tie uses extra time, goes directly to penalties, or follows another procedure."),
        QuestionSeed("Which men's club has won the most UEFA Champions League and European Cup titles?",
                     ["Real Madrid", "AC Milan", "Bayern Munich", "Liverpool"], 0,
                     "Real Madrid's total is well clear of any other club."),
        QuestionSeed("What is a wing-back?",
                     ["A wide player with both defensive and attacking duties", "A central defender", "A false nine", "A goalkeeper's deputy"], 0,
                     "Wing-backs are especially common in formations with three central defenders, such as 3-5-2, but the role is not exclusive to them."),
        QuestionSeed("What extra substitution may competition rules permit during extra time?",
                     ["One additional substitution", "Two automatic substitutions", "No substitutions", "Unlimited substitutions"], 0,
                     "The Laws allow competitions to authorize one additional substitute in extra time; it is an option rather than a universal entitlement."),
        QuestionSeed("What is the 'technical area'?",
                     ["The marked zone where coaching staff may stand", "The referee's room", "The tunnel", "The VAR booth"], 0,
                     "Only one person at a time may give tactical instructions from within it."),
        QuestionSeed("What is 'tiki-taka' characterized by?",
                     ["Short passing and sustained possession", "Long direct balls", "Man-marking", "Counter-attacking only"], 0,
                     "It is associated with Barcelona and the Spanish national side of the late 2000s."),
    ]
}
