import Foundation

enum SoccerQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("How many players does each team start with on the field?",
                     ["9", "10", "11", "12"], 2,
                     "Eleven per side, including the goalkeeper."),
        QuestionSeed("What colour card sends a player off the field?",
                     ["Blue", "Green", "Yellow", "Red"], 3,
                     "A red card means the player leaves and the team plays a man short."),
        QuestionSeed("How long is a standard match before stoppage time?",
                     ["60 minutes", "80 minutes", "90 minutes", "100 minutes"], 2,
                     "Two halves of forty-five minutes, plus whatever time the referee adds on."),
        QuestionSeed("Who is allowed to handle the ball inside their own penalty area?",
                     ["The captain", "The goalkeeper", "Any defender", "The striker"], 1,
                     "Only the goalkeeper, and only within their own penalty area."),
        QuestionSeed("What restarts play when the ball crosses the touchline?",
                     ["A throw-in", "A drop ball", "A goal kick", "A penalty"], 0,
                     "The team that did not touch it last takes the throw-in."),
        QuestionSeed("How often is the men's FIFA World Cup normally held?",
                     ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"], 2,
                     "The tournament runs on a four-year cycle."),
        QuestionSeed("What is it called when one player scores three goals in a match?",
                     ["A triple play", "A hat-trick", "A clean sheet", "A treble"], 1,
                     "The term was borrowed from cricket in the nineteenth century."),
        QuestionSeed("Which country won the first men's World Cup in 1930?",
                     ["Brazil", "Italy", "Argentina", "Uruguay"], 3,
                     "Hosts Uruguay beat Argentina 4-2 in the final in Montevideo."),
        QuestionSeed("What is a match in which a team concedes no goals called?",
                     ["A clean sheet", "A nil draw", "A shutout kick", "A blank"], 0,
                     "Goalkeepers and defences take particular pride in clean-sheet records."),
        QuestionSeed("From where is a penalty kick taken?",
                     ["The centre circle", "The six-yard box", "The penalty mark", "The corner arc"], 2,
                     "The mark sits twelve yards from the goal line."),
        QuestionSeed("Which body governs world soccer?",
                     ["UEFA", "FIFA", "IOC", "CONCACAF"], 1,
                     "FIFA organizes the World Cup and oversees the regional confederations."),
        QuestionSeed("Which body area can cause a handball offence when an outfield player handles the ball unlawfully?",
                     ["The head or neck", "The chest or back", "The foot or ankle", "The hand or arm"], 3,
                     "The Laws of the Game define the relevant area as the hand or arm, with the arm's upper boundary at the bottom of the armpit."),
        QuestionSeed("What is the object of the game?",
                     ["To score more goals than the opponent", "To keep possession longest", "To take the most shots", "To win the most corners"], 0,
                     "Only goals decide the result, however one-sided the other statistics are."),
        QuestionSeed("What is awarded when a defender sends the ball over their own goal line outside the goal?",
                     ["A goal kick", "A corner kick", "A throw-in", "An indirect free kick"], 1,
                     "The attacking team takes a corner from the nearest corner arc; a ball crossing between the posts and under the bar may instead be a goal."),
        QuestionSeed("How many halves are in a regulation match?",
                     ["One", "Two", "Three", "Four"], 1,
                     "Two halves separated by a halftime interval of about fifteen minutes."),
        QuestionSeed("What is the name of the player who defends the goal?",
                     ["The sweeper", "The goalkeeper", "The libero", "The winger"], 1,
                     "The goalkeeper wears a different shirt colour from every other player on the field."),
        QuestionSeed("What does a yellow card signify?",
                     ["A goal is disallowed", "A formal caution", "A substitution", "The end of a half"], 1,
                     "Two yellow cards in one match add up to a red."),
        QuestionSeed("What is the field of play usually called?",
                     ["The pitch", "The court", "The diamond", "The rink"], 0,
                     "Pitch is the standard term in most of the soccer-playing world."),
        QuestionSeed("What is a 'striker'?",
                     ["A forward whose main job is scoring", "A defensive midfielder", "A backup goalkeeper", "A referee's assistant"], 0,
                     "Strikers play highest up the field and take most of a team's shots."),
        QuestionSeed("How many substitutes are typically allowed in a competitive match today?",
                     ["One", "Three", "Five", "Unlimited"], 2,
                     "Five substitutions became standard in most competitions after 2020."),
        QuestionSeed("Which continent has won the most men's World Cups?",
                     ["Africa", "Asia", "Europe", "North America"], 2,
                     "European nations have won a majority of the tournaments, with South America second."),
        QuestionSeed("What is 'extra time'?",
                     ["Two additional periods in a knockout tie", "Stoppage time", "A halftime extension", "A substitution window"], 0,
                     "Two fifteen-minute periods, used when a knockout match is level after ninety minutes."),
        QuestionSeed("What resolves a knockout match still level after extra time?",
                     ["A coin toss", "A penalty shoot-out", "A replay the next day", "Shared victory"], 1,
                     "Each team takes five penalties, then sudden death if the score is still level."),
        QuestionSeed("What is the centre circle used for?",
                     ["Kick-offs", "Penalties", "Throw-ins", "Corner kicks"], 0,
                     "Opponents must stay outside the circle until the ball is in play."),
        QuestionSeed("Which is UEFA's top men's club competition?",
                     ["The UEFA Champions League", "The UEFA Europa League", "The UEFA Conference League", "The UEFA Youth League"], 0,
                     "The UEFA Champions League brings together leading clubs from Europe's domestic leagues."),
        QuestionSeed("What is a 'draw' in soccer?",
                     ["A match ending level", "A penalty award", "A red card", "A tactical formation"], 0,
                     "League tables usually award one point to each team for a draw."),
        QuestionSeed("Which match official keeps time and has final authority over decisions on the field?",
                     ["The referee", "The team captain", "The stadium announcer", "The fourth official"], 0,
                     "The referee enforces the Laws of the Game, keeps the official time, and makes the final on-field decisions."),
        QuestionSeed("What size ball is used in adult matches?",
                     ["Size 3", "Size 4", "Size 5", "Size 6"], 2,
                     "Size 5 is the regulation ball for players aged twelve and up."),
        QuestionSeed("Which country is nicknamed 'La Albiceleste'?",
                     ["Argentina", "Spain", "Chile", "Uruguay"], 0,
                     "The name refers to the white and sky-blue stripes of the Argentine shirt."),
        QuestionSeed("What is a 'free kick'?",
                     ["A restart awarded after a foul", "A penalty", "A throw-in taken from the touchline", "A corner"], 0,
                     "Free kicks are direct or indirect depending on the offence committed."),
        QuestionSeed("What does each corner flag mark?",
                     ["A corner of the field", "The edge of the penalty area", "The halfway line", "The substitution zone"], 0,
                     "The corner arc is drawn around the flagpost and is used when taking a corner kick."),
        QuestionSeed("What usually identifies a team's captain on the field?",
                     ["An armband", "A different shirt number", "A whistle", "A coloured card"], 0,
                     "The captain wears an armband and serves as a team representative, but has no special authority under the Laws."),
        QuestionSeed("How is play restarted after a goal?",
                     ["A kick-off by the team that conceded", "A goal kick by the scorer", "A throw-in at halfway", "A dropped ball"], 0,
                     "The kick-off is taken from the centre mark after both teams return to their own halves."),
        QuestionSeed("When is a goal kick awarded?",
                     ["When an attacker last touches the ball before it crosses the defending goal line without a goal", "After every saved shot", "When a defender last touches the ball over the touchline", "After an offside offence at midfield"], 0,
                     "If a defender is the last to touch the ball over that goal line, the restart is normally a corner kick instead."),
        QuestionSeed("Which official commonly patrols a touchline with a flag?",
                     ["An assistant referee", "The fourth official", "The video assistant referee", "The team captain"], 0,
                     "Assistant referees help judge offside, ball-out-of-play decisions, and offences near their touchline."),
        QuestionSeed("What is a cross?",
                     ["A pass sent from a wide area toward the goalmouth", "A shot taken from the centre circle", "A backwards throw-in", "A tackle using both feet"], 0,
                     "Crosses aim to find attackers in or around the penalty area."),
        QuestionSeed("What is a header?",
                     ["Playing the ball with the head", "A pass along the ground", "A shot with the heel", "A goalkeeper throwing the ball from their hands"], 0,
                     "Players use headers to pass, clear, or shoot the ball."),
        QuestionSeed("What does it mean to dribble in soccer?",
                     ["Move while controlling the ball with repeated touches", "Throw the ball back into play", "Block a shot with both hands", "Challenge the referee"], 0,
                     "Close control lets a player change speed and direction while keeping the ball away from opponents."),
        QuestionSeed("What is the penalty area?",
                     ["The marked box where the goalkeeper may handle the ball and penalty offences can lead to a penalty kick", "The circle around the centre mark", "The space between the technical areas", "The arc used for corner kicks"], 0,
                     "The penalty area extends eighteen yards from the goal line in the standard field markings."),
        QuestionSeed("Which player most commonly wears padded gloves?",
                     ["The goalkeeper", "The centre forward", "The captain", "The assistant referee"], 0,
                     "Goalkeeper gloves improve grip and help cushion the impact of shots."),
        QuestionSeed("Which national team is nicknamed the Three Lions?",
                     ["England", "Brazil", "Germany", "The Netherlands"], 0,
                     "England are called the Three Lions after the crest worn on their shirts."),
        QuestionSeed("What protective equipment do players wear on their lower legs?",
                     ["Shin guards", "Knee braces", "Ankle plates", "Padded compression sleeves"], 0,
                     "Shin guards are required equipment, protecting the lower leg during tackles."),
        QuestionSeed("What is the horizontal bar across the top of the goal called?",
                     ["The crossbar", "The goal post", "The upper rail", "The frame stretcher"], 0,
                     "The crossbar joins the two posts and completes the frame of the goal."),
        QuestionSeed("What is it called to keep the ball airborne using repeated touches?",
                     ["Juggling", "Trapping", "Screening", "Shielding"], 0,
                     "Juggling keeps the ball airborne with repeated touches and is a common practice drill."),
        QuestionSeed("What are the traditional colors of a classic soccer ball?",
                     ["Black and white", "Red and blue", "Green and gold", "Silver and bronze"], 0,
                     "The classic ball is black and white, a pattern chosen to show clearly on television."),
        QuestionSeed("Which country won the 2018 men's World Cup?",
                     ["France", "Croatia", "Belgium", "England"], 0,
                     "France beat Croatia in the 2018 final to win their second men's World Cup."),
        QuestionSeed("What is the sport called in most countries outside the United States?",
                     ["Football", "Handball", "Kickball", "Association ball"], 0,
                     "Most countries call the sport football rather than soccer, which is a British abbreviation."),
        QuestionSeed("What does a referee use to signal a stoppage in play?",
                     ["A whistle", "A hand bell", "A raised banner", "An electronic buzzer"], 0,
                     "The referee blows a whistle to stop play and signal fouls or restarts."),
        QuestionSeed("What is awarded when an attacker is fouled inside the penalty area?",
                     ["A penalty kick", "A corner kick", "An indirect free kick", "A dropped ball restart"], 0,
                     "A penalty kick is awarded for a direct-free-kick foul committed inside the penalty area."),
        QuestionSeed("How many minutes long is each half of a standard match?",
                     ["Thirty", "Forty", "Forty-five", "Fifty-five"], 2,
                     "Each half runs forty-five minutes, with stoppage time added by the referee."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("What is the offside rule primarily designed to prevent?",
                     ["Goal hanging near the opponent's goal", "Players deliberately delaying restarts in order to consume playing time", "Defenders using careless or dangerous force when challenging an opponent", "Teams making more substitutions than the competition rules permit"], 0,
                     "At the relevant moment, an attacker in the opponents' half is in an offside position only if nearer the goal line than both the ball and the second-last opponent; an offence also requires involvement in play."),
        QuestionSeed("How far from the goal line is the penalty mark?",
                     ["10 yards", "12 yards", "15 yards", "18 yards"], 1,
                     "Twelve yards, or roughly eleven metres."),
        QuestionSeed("What is a 'brace'?",
                     ["Two goals by one player", "Two yellow cards", "Two substitutions", "Two clean sheets"], 0,
                     "Three goals is a hat-trick; two is a brace."),
        QuestionSeed("Which trophy do the English top-flight league champions receive?",
                     ["The Premier League Trophy", "The FA Cup", "The Champions League Trophy", "The Community Shield"], 0,
                     "The FA Cup is a separate knockout competition run by the Football Association."),
        QuestionSeed("What does VAR stand for?",
                     ["Video Assistant Referee", "Verified Attack Review", "Visual Analysis Report", "Variable Added Recovery"], 0,
                     "VAR reviews goals, penalties, red cards, and cases of mistaken identity."),
        QuestionSeed("How wide must a regulation goal be?",
                     ["6 yards", "8 yards", "10 yards", "12 yards"], 1,
                     "Eight yards wide and eight feet high."),
        QuestionSeed("What is a 'derby' in soccer?",
                     ["A match between local rivals", "A cup final", "A friendly match", "A relegation playoff"], 0,
                     "Derbies are often the most heated fixtures on a club's calendar."),
        QuestionSeed("What happens to a team whose player is sent off?",
                     ["A substitute replaces them", "They play with one fewer player", "The match is abandoned", "They lose a goal"], 1,
                     "The sent-off player cannot be replaced, so the team is down to ten."),
        QuestionSeed("What is 'relegation'?",
                     ["Dropping to a lower division", "Being eliminated after losing a match in a knockout cup competition", "Receiving a standings penalty that removes previously earned points", "Being temporarily forbidden from registering newly transferred players"], 0,
                     "The lowest-placed teams move down and are replaced by promoted clubs."),
        QuestionSeed("Which tournament is South America's national-team championship?",
                     ["The Copa América", "The Copa Libertadores", "The Gold Cup", "The Nations League"], 0,
                     "The Copa Libertadores is the equivalent club competition."),
        QuestionSeed("What is a 'nutmeg'?",
                     ["Playing the ball through an opponent's legs", "A header attempted while the player is diving forward through the air", "A shot struck from a position well outside the opponent's penalty area", "A defensive clearance"], 0,
                     "It is one of the game's most celebrated pieces of individual skill."),
        QuestionSeed("How many points does a win earn in most league systems today?",
                     ["One", "Two", "Three", "Four"], 2,
                     "Three points for a win replaced two in order to reward attacking play."),
        QuestionSeed("From which marked area may a goal kick be taken?",
                     ["The goal area", "The penalty area", "The centre circle", "The corner area"], 0,
                     "A goal kick may be taken from any point within the defending team's goal area, commonly called the six-yard box."),
        QuestionSeed("What is a 'direct free kick'?",
                     ["One that can be scored without another player touching the ball", "A restart taken from the corner arc after the ball crosses the goal line", "A set kick that the team's goalkeeper is specifically required to take", "A free kick from which another player must touch the ball before a goal"], 0,
                     "An indirect free kick requires a second touch before a goal can count."),
        QuestionSeed("What does the term 'the treble' mean for a club?",
                     ["Winning three major trophies in one season", "Scoring three goals", "Three consecutive titles", "A team completing three matches without conceding a single goal"], 0,
                     "The classic treble is the domestic league, the domestic cup, and the European title."),
        QuestionSeed("Which position sits between the defence and the attack?",
                     ["Midfielder", "Full-back", "Sweeper", "Goalkeeper"], 0,
                     "Midfielders link play and usually cover the most ground in a match."),
        QuestionSeed("What makes a tackle legal under the Laws of the Game?",
                     ["It is made without careless, reckless, or excessive force", "The tackler touches the ball first", "The challenge is performed as a slide with one leg extended", "It comes only from the front"], 0,
                     "Touching the ball first does not excuse a challenge made carelessly, recklessly, or with excessive force."),
        QuestionSeed("What is the maximum number of defenders allowed in a free-kick wall?",
                     ["Exactly three defenders in competitions that use video assistance", "No more than five defenders in any professional league match", "There is no fixed limit", "Ten"], 2,
                     "There is no fixed maximum; when a wall has three or more defenders, attacking players must remain at least one metre away until the ball is in play."),
        QuestionSeed("Which league is Spain's top division?",
                     ["La Liga", "Serie A", "Ligue 1", "The Bundesliga"], 0,
                     "Serie A is Italian, Ligue 1 French, and the Bundesliga German."),
        QuestionSeed("What is a 'through ball'?",
                     ["A pass split between defenders for a runner", "A restart from the goal area after an attacker last touched the ball", "A kick sent far away from the defence without an intended receiver", "A backwards pass"], 0,
                     "Timing matters as much as weight of pass, because of the offside line."),
        QuestionSeed("What is the maximum halftime interval permitted by the Laws of the Game?",
                     ["5 minutes", "10 minutes", "15 minutes", "20 minutes"], 2,
                     "The halftime interval must not exceed fifteen minutes; competition rules set its precise duration."),
        QuestionSeed("What is 'stoppage time' meant to account for?",
                     ["Time lost to injuries, substitutions and delays", "The two additional fifteen-minute periods used in a tied knockout match", "The scheduled interval separating the first and second halves", "The sequence of penalty kicks used to decide a match that remains tied"], 0,
                     "The fourth official displays the minimum number of added minutes."),
        QuestionSeed("What is a 'formation' such as 4-4-2 describing?",
                     ["Defenders, midfielders and forwards", "Substitution order", "Planned movements used by the team during corners and free kicks", "Squad numbers"], 0,
                     "The goalkeeper is assumed and never counted in the notation."),
        QuestionSeed("Which African tournament is contested by national teams?",
                     ["The Africa Cup of Nations", "The CAF Champions League", "The Gold Cup", "The Asian Cup"], 0,
                     "It is held every two years and organized by CAF."),
        QuestionSeed("What is the 'golden boot' awarded for?",
                     ["Being the leading goalscorer", "Being the goalkeeper who records the greatest number of clean sheets", "Best young player", "Fair play"], 0,
                     "It is presented in most major leagues and tournaments."),
        QuestionSeed("What is an 'own goal'?",
                     ["A goal accidentally scored against one's own team", "A penalty kick converted by the goalkeeper who takes the attempt", "A legal goal scored directly from the match's opening kick-off", "A goal cancelled after the referee identifies an earlier offence"], 0,
                     "It counts for the opposition and is credited as an own goal in the records."),
        QuestionSeed("Which country hosted and won the 1998 men's World Cup?",
                     ["France", "Brazil", "Italy", "Germany"], 0,
                     "France beat Brazil 3-0 in the final in Saint-Denis."),
        QuestionSeed("What is a 'cap' in international soccer?",
                     ["An appearance for the national team", "The maximum transfer fee that a club is permitted to pay", "The maximum number of players a team may register in its squad", "A wage restriction"], 0,
                     "The term comes from the caps once presented to players for each appearance."),
        QuestionSeed("What is the 'transfer window'?",
                     ["The period when clubs may register new signings", "The scheduled halftime interval separating the two periods of play", "A limited period during which teams are permitted to make substitutions", "The repayment term attached to a temporary loan agreement between clubs"], 0,
                     "Most leagues run a long summer window and a shorter mid-season one."),
        QuestionSeed("What does 'CONCACAF' govern?",
                     ["North and Central American and Caribbean soccer", "South American soccer", "The national teams and club competitions across Africa", "The national teams and club competitions throughout Asia"], 0,
                     "CONMEBOL covers South America; CAF covers Africa."),
        QuestionSeed("What does the referee signal by allowing advantage after a foul?",
                     ["Play continues because stopping it would benefit the offending team", "The fouled team has permanently declined every possible disciplinary sanction", "The official match clock must stop and remain stopped until the next restart", "The original foul is converted into a throw-in for the team in possession"], 0,
                     "The referee may return to caution or send off an offender at the next stoppage when appropriate."),
        QuestionSeed("How does a referee normally signal an indirect free kick?",
                     ["By holding one arm above the head", "By pointing to the penalty mark", "By raising both flags", "By showing a yellow card"], 0,
                     "The arm remains raised until another player touches the ball, the ball leaves play, or a direct goal is no longer possible."),
        QuestionSeed("What is an overlapping run?",
                     ["A run around the outside of a teammate with the ball", "Two central defenders exchanging their assigned positions and marks", "A striker moving into an offside position", "A goalkeeper leaving the penalty area to cover space behind the defence"], 0,
                     "Full-backs commonly overlap wingers to provide an extra wide passing option."),
        QuestionSeed("What is a counterattack?",
                     ["A rapid attack immediately after winning possession", "A restart after a disputed call", "A defence using every player near its goal", "A set play from a corner"], 0,
                     "Counterattacks exploit space before the opponent can recover its defensive shape."),
        QuestionSeed("What does a high press attempt to do?",
                     ["Win the ball near the opponent's goal", "Defend only inside one's own penalty area", "Keep the ball in the air", "Delay every restart"], 0,
                     "Attackers close down defenders and passing lanes as the opponent tries to build from the back."),
        QuestionSeed("What is a target forward expected to provide?",
                     ["A central outlet who can receive and hold up direct passes", "A full-back whose main task is marking the opponent's quickest winger", "A goalkeeper whose accurate distribution begins attacks from the back", "A midfielder designated exclusively to take the team's corner kicks"], 0,
                     "The target forward uses positioning and physical presence to bring teammates into the attack."),
        QuestionSeed("What is the main role of a holding midfielder?",
                     ["Protect the defence and link possession from deep", "Stay permanently beside the opposing goalkeeper", "Take every throw-in", "Play only on the touchline"], 0,
                     "Holding midfielders screen central spaces, recover loose balls, and offer a safe passing option."),
        QuestionSeed("Which official usually displays the electronic board for substitutions and added time?",
                     ["The fourth official", "The video assistant referee", "The senior assistant referee", "The team captain"], 0,
                     "The fourth official also manages the technical areas and assists with administrative duties."),
        QuestionSeed("What is man-marking?",
                     ["Assigning a defender to track a particular opponent", "Defending fixed areas regardless of movement", "Keeping every player behind the ball", "Marking the field before kickoff"], 0,
                     "The marker follows the opponent's movement rather than guarding only a zone."),
        QuestionSeed("What is a switch of play?",
                     ["Moving the ball quickly from one side of the field to the other", "Replacing the current goalkeeper with another player during live play", "Changing from the home uniform to the away uniform during halftime", "Moving an attacker into a defensive role while making a substitution"], 0,
                     "A switch can escape pressure and exploit space on the far side."),
        QuestionSeed("How long is each period of extra time in a knockout match?",
                     ["Fifteen minutes", "Ten minutes", "Twenty-five minutes", "Thirty minutes"], 0,
                     "Extra time runs two halves of fifteen minutes each before a penalty shootout decides matters."),
        QuestionSeed("What does tiki-taka describe?",
                     ["Short passing and movement", "Long direct clearances", "Aggressive man-marking", "Defending with a deep block"], 0,
                     "Tiki-taka describes short passing and constant movement to keep possession."),
        QuestionSeed("Which league is Germany's top division?",
                     ["The Bundesliga", "The Eredivisie", "The Primeira Liga", "The Championship"], 0,
                     "The Bundesliga is Germany's top division, contested by clubs including Bayern Munich."),
        QuestionSeed("Which league is Italy's top division?",
                     ["Serie A", "Ligue 1", "La Liga", "The Primeira Liga"], 0,
                     "Serie A is Italy's top division, home to clubs such as Juventus and Milan."),
        QuestionSeed("What is a nutmeg in soccer?",
                     ["A ball through the legs", "A shot off the crossbar", "A pass with the heel", "A header from a corner"], 0,
                     "A nutmeg slips the ball through an opponent's legs and collects it on the other side."),
        QuestionSeed("What does parking the bus describe?",
                     ["Defending with everyone behind the ball", "Pressing high up the pitch", "Rotating the squad heavily", "Playing three strikers at once from kickoff"], 0,
                     "Parking the bus describes defending with nearly everyone behind the ball."),
        QuestionSeed("Which clubs contest El Clasico?",
                     ["Real Madrid and Barcelona", "Milan and Inter", "Celtic and Rangers", "Boca Juniors and River Plate"], 0,
                     "El Clasico is the meeting of Real Madrid and Barcelona, Spanish soccer's biggest fixture."),
        QuestionSeed("What is a playmaker expected to do?",
                     ["Create chances for others", "Mark the opposing striker", "Defend set pieces", "Organize the defensive line"], 0,
                     "A playmaker creates chances for others, dictating tempo from midfield or just behind."),
        QuestionSeed("What does goal difference compare in a league table?",
                     ["Goals for minus goals against", "Total matches won overall", "Points earned in away games", "Head-to-head results between clubs"], 0,
                     "Goal difference subtracts goals against from goals for, separating teams level on points."),
        QuestionSeed("What is a set piece in soccer?",
                     ["A restart from a dead ball", "A rehearsed substitution", "A fixed defensive formation", "A designated penalty specialist"], 0,
                     "A set piece is a restart from a dead ball, such as a corner or free kick."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("What is the 'Laws of the Game' document, and who maintains it?",
                     ["The rulebook maintained by IFAB", "A FIFA marketing charter", "A UEFA licensing code", "A players' union agreement"], 0,
                     "The International Football Association Board, not FIFA alone, decides changes to the laws."),
        QuestionSeed("What is a 'false nine'?",
                     ["A forward who drops deep into midfield", "A defensive midfielder", "An overlapping full-back", "A substitute goalkeeper"], 0,
                     "The role pulls a centre-back out of position and opens space for wide runners."),
        QuestionSeed("In what year was the offside law changed to require two opponents rather than three?",
                     ["1905", "1925", "1948", "1966"], 1,
                     "The 1925 change sharply increased scoring and helped prompt new defensive systems."),
        QuestionSeed("What is 'gegenpressing'?",
                     ["Pressing immediately after losing the ball", "Defending deep in a low block", "Man-marking the goalkeeper", "A set-piece routine"], 0,
                     "The idea is that a team is most vulnerable in the seconds just after it wins possession."),
        QuestionSeed("What is the 'Bosman ruling' known for?",
                     ["Allowing players to move freely at contract expiry", "Requiring electronic sensors to verify whether the ball crossed the goal line", "Restructuring Europe's leading club tournament as the Champions League", "Prohibiting outside investors from owning part of a player's transfer rights"], 0,
                     "The 1995 European Court decision transformed the transfer market."),
        QuestionSeed("What does 'xG' measure?",
                     ["Expected goals from the quality of chances created", "Extra minutes scheduled when a knockout match remains level after regulation", "Exit goals conceded", "Experience grade"], 0,
                     "Each shot is assigned a probability of scoring based on comparable historical attempts."),
        QuestionSeed("What is a 'libero'?",
                     ["A sweeper who plays behind the defensive line", "A winger who begins near the touchline and cuts inward toward goal", "A holding midfielder", "A reserve goalkeeper selected as a substitute in the match squad"], 0,
                     "The role was central to Italian catenaccio and to some German sides of the 1970s."),
        QuestionSeed("Which competition did the European Cup become in 1992?",
                     ["The UEFA Champions League", "The Europa League", "The Cup Winners' Cup", "The Super Cup"], 0,
                     "The rebrand introduced a group stage alongside the knockout rounds."),
        QuestionSeed("What is 'catenaccio'?",
                     ["A defensive Italian tactical system", "A Brazilian dribbling style", "A Dutch pressing scheme", "A set-piece routine"], 0,
                     "It emphasized a tight, layered defence with a sweeper behind the back line."),
        QuestionSeed("How many minutes must pass before an abandoned match is usually considered for a result rather than a replay?",
                     ["It varies by competition rules", "A fixed total of 45 minutes in every competition", "A fixed total of 60 minutes in every competition", "A fixed total of 75 minutes in every competition"], 0,
                     "There is no single global threshold; each competition sets its own regulations."),
        QuestionSeed("What is the 'away goals rule' historically used for?",
                     ["Breaking ties in two-legged knockout matches", "Awarding an additional league point whenever the visiting team scores", "Setting the sequence in which players must take kicks in a penalty shoot-out", "Ranking teams that finish level on points within a tournament group"], 0,
                     "UEFA abolished it in its club competitions from the 2021-22 season."),
        QuestionSeed("What was 'Total Football' associated with?",
                     ["The Netherlands and Ajax in the 1970s", "The Italian national team and leading Italian clubs during the 1930s", "The Brazilian national team and Santos during the 1950s", "England in the 1960s"], 0,
                     "Players interchanged positions fluidly, with Rinus Michels and Johan Cruyff its best-known figures."),
        QuestionSeed("What is goal-line technology used to determine?",
                     ["Whether the whole ball crossed the line", "Offside positions", "Handball decisions", "How severe a foul was and which disciplinary sanction it warrants"], 0,
                     "It gives the referee an instant automated signal rather than a video review."),
        QuestionSeed("What is a 'panenka' penalty?",
                     ["A softly chipped kick down the middle", "A powerful strike into the roof of the net", "A two-touch penalty", "A left-footed penalty"], 0,
                     "Antonín Panenka scored one in the 1976 European Championship final shoot-out."),
        QuestionSeed("What do UEFA's financial sustainability regulations govern?",
                     ["Club solvency, financial stability, and squad costs", "The maximum amount clubs may charge for general-admission tickets", "National-team selection", "Stadium capacity only"], 0,
                     "The current framework evolved from Financial Fair Play and includes solvency, stability, and squad-cost controls."),
        QuestionSeed("Which club competition did Real Madrid win in each of the first five seasons?",
                     ["The European Cup", "The UEFA Cup", "The Cup Winners' Cup", "The Intercontinental Cup"], 0,
                     "Real Madrid won the first five European Cups from 1956 to 1960."),
        QuestionSeed("What is a 'tifo'?",
                     ["A large choreographed supporters' display", "A team's positional system for organizing possession and defence", "A contractual provision setting the payment required to release a player", "A type of free-kick restart awarded after a specified defensive offence"], 0,
                     "The word comes from Italian supporter culture and spread across Europe."),
        QuestionSeed("How is the ball's circumference regulated for a size 5 ball?",
                     ["Between 68 and 70 centimetres", "Between 55 and 58 centimetres", "Between 75 and 80 centimetres", "Exactly 72 centimetres"], 0,
                     "The Laws of the Game also set weight and pressure ranges."),
        QuestionSeed("What is 'parking the bus'?",
                     ["Defending with nearly the whole team behind the ball", "Maintaining the defensive line near midfield to compress the available space", "Replacing regular starters across several fixtures to preserve their fitness", "Deliberately slowing restarts near the corner to protect a narrow lead"], 0,
                     "The phrase entered English soccer vocabulary in the mid-2000s."),
        QuestionSeed("Which country has appeared at every men's World Cup finals tournament?",
                     ["Brazil", "Germany", "Italy", "Argentina"], 0,
                     "Brazil is the only nation to have qualified for every edition."),
        QuestionSeed("What is an 'inverted winger'?",
                     ["A wide player on the opposite side to their stronger foot", "A wide player whose primary duty is tracking the opposing full-back", "A full-back who moves into central midfield whenever their team has possession", "A striker who withdraws into the space between the opposing lines"], 0,
                     "Cutting inside onto the stronger foot creates shooting angles rather than crossing angles."),
        QuestionSeed("What does the Ballon d'Or recognize?",
                     ["The best individual player over the award's assessment season", "The player who finishes the season with the most competitive goals", "The club that wins the highest-level team competition during the season", "The outstanding young player who remains below a specified age limit"], 0,
                     "The award has been presented since 1956 and, since 2022, evaluates performance over a football season rather than a calendar year."),
        QuestionSeed("What does a 'low block' describe?",
                     ["A compact defensive shape near one's own goal", "A defender physically stopping a shot before it can reach the goal", "A rehearsed corner routine played a short distance to a nearby teammate", "A defensive substitution"], 0,
                     "It cedes territory in exchange for denying space behind the defence."),
        QuestionSeed("What did the 1992 back-pass law prohibit?",
                     ["A goalkeeper handling a ball deliberately kicked by a teammate", "Any pass toward a team's own goal", "A goalkeeper kicking the ball after legally catching it with the hands", "A teammate deliberately heading the ball back for the goalkeeper to handle"], 0,
                     "The offence is the goalkeeper's handling of a deliberate kick from a teammate, not the backward pass itself; defined exceptions apply."),
        QuestionSeed("What is aggregate score used for?",
                     ["Combining the scores from both legs of a two-legged tie", "Adding together the league points earned across two consecutive matches", "Calculating season goal difference", "Recording only shoot-out goals"], 0,
                     "Competition rules determine whether a level aggregate tie uses extra time, goes directly to penalties, or follows another procedure."),
        QuestionSeed("Which men's club has won the most UEFA Champions League and European Cup titles?",
                     ["Real Madrid", "AC Milan", "Bayern Munich", "Liverpool"], 0,
                     "Real Madrid's total is well clear of any other club."),
        QuestionSeed("What is a wing-back?",
                     ["A wide player with both defensive and attacking duties", "A central defender who stays deepest and marks the opposing striker", "An attacker who leaves the forward line to link play in midfield", "The reserve goalkeeper named as the first substitute on the bench"], 0,
                     "Wing-backs are especially common in formations with three central defenders, such as 3-5-2, but the role is not exclusive to them."),
        QuestionSeed("What extra substitution may competition rules permit during extra time?",
                     ["One additional substitution", "Two automatic substitutions", "No substitutions", "Unlimited substitutions"], 0,
                     "The Laws allow competitions to authorize one additional substitute in extra time; it is an option rather than a universal entitlement."),
        QuestionSeed("What is the 'technical area'?",
                     ["The marked zone where coaching staff may stand", "The private room where match officials prepare and complete their report", "The enclosed passage connecting the dressing rooms with the playing field", "The remote video room where assistant referees review possible errors"], 0,
                     "Only one person at a time may give tactical instructions from within it."),
        QuestionSeed("What is 'tiki-taka' characterized by?",
                     ["Short passing and sustained possession", "Immediate forward passes and aerial balls intended to bypass midfield", "Assigning each defender to follow one particular opponent around the field", "Counter-attacking only"], 0,
                     "It is associated with Barcelona and the Spanish national side of the late 2000s."),
        QuestionSeed("What is a half-space in soccer tactics?",
                     ["The vertical channel between the centre and a wing", "The area behind each goal", "One half of the centre circle", "The zone between the penalty mark and goal line"], 0,
                     "Occupying a half-space can provide central passing angles without the congestion of the middle."),
        QuestionSeed("What does 'rest defence' describe?",
                     ["The structure kept behind the attack to stop counterattacks", "The defensive organization adopted immediately following the halftime break", "Squad players removed from a training exercise for a scheduled recovery period", "Deliberate time wasting near the corner"], 0,
                     "Even during sustained possession, selected players remain positioned to control clearances and transitions."),
        QuestionSeed("How does an underlapping run differ from an overlap?",
                     ["It passes inside the teammate with the ball", "It moves behind the team's own goal", "It is made only by a goalkeeper", "It always begins from an offside position"], 0,
                     "An underlap attacks an interior channel while an overlap goes around the outside."),
        QuestionSeed("What is a third-man run?",
                     ["A run by a player other than the passer and initial receiver", "A run made after a third substitution", "A defender leaving open play to join the required wall at a free kick", "A goalkeeper entering the opponent's half"], 0,
                     "The initial pass draws attention before the receiver releases the ball into the runner's path."),
        QuestionSeed("What is a cover shadow when pressing?",
                     ["The passing lane blocked behind the pressing player", "A portion of the field left unlit because it is beneath a roof or stand", "An area outside the goalkeeper's view close to the far goalpost", "A defensive zone jointly protected by the two central defenders"], 0,
                     "A presser angles the approach to pressure the ball carrier while screening another opponent."),
        QuestionSeed("What is a mezzala?",
                     ["A central midfielder who operates in a wide interior channel", "A defender positioned behind the main line to collect loose balls", "A striker who never leaves the penalty area", "A goalkeeper used in possession"], 0,
                     "The Italian term describes a midfielder who often advances through the half-space."),
        QuestionSeed("What is a regista?",
                     ["A deep-lying playmaker", "A purely defensive full-back", "A wide target forward", "A referee responsible for registration"], 0,
                     "A regista controls tempo and distribution from a position in front of the defence."),
        QuestionSeed("What is a rondo in training?",
                     ["A keep-away passing exercise with defenders in the middle", "A repeated sprint around the entire field", "A finishing drill in which players shoot unopposed at an empty goal", "A set-piece wall made of mannequins"], 0,
                     "Rondos develop quick passing, support angles, pressing, and decision-making in tight spaces."),
        QuestionSeed("What is an overload in soccer tactics?",
                     ["Creating a numerical advantage in a chosen area", "Using too many substitutes", "Crossing the ball beyond every attacker", "Committing two fouls at once"], 0,
                     "Extra players in one zone can help a team pass through pressure or free space elsewhere."),
        QuestionSeed("What do the numbers in a formation such as 4-2-3-1 represent?",
                     ["Outfield players arranged from defence to attack", "Expected goals in each half", "Substitutions available by position", "The dimensions of the penalty area"], 0,
                     "The goalkeeper is omitted, so 4-2-3-1 describes four defenders, two deeper midfielders, three attacking midfielders, and one forward."),
    ]
}
