import Foundation

enum TelevisionQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("In Friends, what is the name of the coffee shop the group visits?",
                     ["Central Perk", "Monk's Cafe", "Cafe Nervosa", "Luke's Diner"], 0,
                     "Central Perk is the Greenwich Village coffee shop where the six friends regularly gather."),
        QuestionSeed("In which town does The Simpsons take place?",
                     ["Quahog", "South Park", "Springfield", "Arlen"], 2,
                     "The show deliberately leaves Springfield's state unspecified."),
        QuestionSeed("What kind of company is Dunder Mifflin in the U.S. version of The Office?",
                     ["A paper company", "A law firm", "A hospital group", "A software company"], 0,
                     "The Scranton branch sells paper and, later, printers under the Dunder Mifflin name."),
        QuestionSeed("What number is used as the name of the girl with psychic powers in Stranger Things?",
                     ["Seven", "Eleven", "Thirteen", "Twenty-One"], 1,
                     "Eleven is the test-subject number tattooed on her arm."),
        QuestionSeed("What subject does Walter White teach at the start of Breaking Bad?",
                     ["Physics", "Biology", "Mathematics", "Chemistry"], 3,
                     "Walter is a high-school chemistry teacher before entering the drug trade."),
        QuestionSeed("What species is Spock in Star Trek on his father's side?",
                     ["Vulcan", "Klingon", "Romulan", "Andorian"], 0,
                     "Spock is half-Vulcan and half-human."),
        QuestionSeed("What is the name of the Doctor's time-and-space machine in Doctor Who?",
                     ["Serenity", "TARDIS", "Galactica", "Discovery One"], 1,
                     "TARDIS stands for Time And Relative Dimension In Space."),
        QuestionSeed("Which Sesame Street character is famous for counting?",
                     ["Oscar the Grouch", "Elmo", "The Count", "Grover"], 2,
                     "Count von Count turns counting into dramatic, thunder-filled fun."),
        QuestionSeed("Where does SpongeBob SquarePants live?",
                     ["In a pineapple", "In a lighthouse", "In a submarine", "In a sandcastle"], 0,
                     "SpongeBob's pineapple home is in the undersea city of Bikini Bottom."),
        QuestionSeed("Which Pokemon is Ash Ketchum's best-known partner?",
                     ["Charmander", "Squirtle", "Eevee", "Pikachu"], 3,
                     "Pikachu accompanies Ash throughout his long run as the animated series' lead trainer."),
        QuestionSeed("What breed of dog is Scooby-Doo?",
                     ["Bloodhound", "Great Dane", "Saint Bernard", "German shepherd"], 1,
                     "Scooby is an unusually expressive Great Dane who travels with Mystery Inc."),
        QuestionSeed("What is the name of the prehistoric town in The Flintstones?",
                     ["Orbit City", "Bedrock", "Jellystone", "Duckburg"], 1,
                     "Fred and Wilma Flintstone live in Bedrock with their neighbors, the Rubbles."),
        QuestionSeed("Which Muppet is a green frog?",
                     ["Kermit", "Fozzie", "Gonzo", "Animal"], 0,
                     "Kermit the Frog often serves as the Muppets' host and level-headed leader."),
        QuestionSeed("In which city do The Golden Girls live?",
                     ["Atlanta", "Los Angeles", "Miami", "New Orleans"], 2,
                     "Dorothy, Rose, Blanche, and Sophia share a home in Miami, Florida."),
        QuestionSeed("In which city is the bar in Cheers located?",
                     ["Boston", "Chicago", "Seattle", "Philadelphia"], 0,
                     "Cheers is a neighborhood bar in Boston where the regulars know one another's names."),
        QuestionSeed("Which city is the main setting of Seinfeld?",
                     ["Boston", "New York City", "San Francisco", "Washington, D.C."], 1,
                     "Jerry and his friends live on Manhattan's Upper West Side."),
        QuestionSeed("Pawnee, the setting of Parks and Recreation, is in which state?",
                     ["Ohio", "Wisconsin", "Indiana", "Iowa"], 2,
                     "Pawnee is a fictional Indiana city with a famously energetic parks department."),
        QuestionSeed("What kind of workplace is at the center of Brooklyn Nine-Nine?",
                     ["A fire station", "A courthouse", "A hospital", "A police precinct"], 3,
                     "The comedy follows detectives and staff in a fictional New York City police precinct."),
        QuestionSeed("What profession do Sheldon and Leonard share in The Big Bang Theory?",
                     ["Physicists", "Lawyers", "Architects", "Surgeons"], 0,
                     "Both work as physicists at Caltech, though in different specialties."),
        QuestionSeed("Which monarch is the central figure when The Crown begins?",
                     ["Queen Victoria", "Queen Elizabeth II", "Queen Anne", "Queen Mary I"], 1,
                     "The series begins around Elizabeth II's marriage and accession to the throne."),
        QuestionSeed("What kind of animal is Bluey?",
                     ["A rabbit", "A cat", "A blue heeler dog", "A koala"], 2,
                     "Bluey is an Australian blue heeler puppy, also called an Australian cattle dog."),
        QuestionSeed("In Wednesday, what is the name of the school Wednesday attends?",
                     ["Nevermore Academy", "Hogwarts", "Bayside High", "Riverdale High"], 0,
                     "Nevermore is the boarding school for outcasts where Wednesday is enrolled by her parents."),
        QuestionSeed("What type of workplace is central to The Bear?",
                     ["A restaurant", "A newspaper office", "A police station", "A television studio"], 0,
                     "Carmy returns to Chicago to run his family's struggling restaurant kitchen."),
        QuestionSeed("What is Dr. Gregory House's profession in House?",
                     ["Detective", "Professor", "Attorney", "Physician"], 3,
                     "House is a brilliant hospital diagnostician known for solving unusual medical cases."),
        QuestionSeed("Grey's Anatomy is primarily set in a hospital in which city?",
                     ["Seattle", "Denver", "Boston", "Phoenix"], 0,
                     "The surgeons work at a Seattle hospital whose name changes during the series."),
        QuestionSeed("In which U.S. state is South Park set?",
                     ["Utah", "Colorado", "Montana", "Wyoming"], 1,
                     "The fictional mountain town of South Park is located in Colorado."),
        QuestionSeed("What do characters commonly call the zombies in The Walking Dead?",
                     ["Walkers", "Clickers", "Hosts", "Reapers"], 0,
                     "Most survivors use terms such as walkers rather than the word zombies."),
        QuestionSeed("Which sport does Ted Lasso coach in England?",
                     ["Rugby", "Cricket", "Basketball", "Soccer"], 3,
                     "The American football coach is hired to manage the fictional soccer club AFC Richmond."),
        QuestionSeed("Which animal appears on House Stark's sigil in Game of Thrones?",
                     ["Lion", "Stag", "Direwolf", "Dragon"], 2,
                     "The direwolf represents House Stark of Winterfell."),
        QuestionSeed("What is the name of the small green child protected by the Mandalorian?",
                     ["Grogu", "Yoda", "Jabba", "Wicket"], 0,
                     "Fans initially called him the Child or Baby Yoda before the series revealed his name."),
        QuestionSeed("Which element can Aang bend at the beginning of Avatar: The Last Airbender?",
                     ["Fire", "Air", "Earth", "Water"], 1,
                     "Aang is an Air Nomad who must learn the other three elements as the Avatar."),
        QuestionSeed("From which city does Will move in The Fresh Prince of Bel-Air?",
                     ["Detroit", "Baltimore", "Philadelphia", "New York City"], 2,
                     "Will leaves West Philadelphia to live with relatives in Bel-Air, Los Angeles."),
        QuestionSeed("What is Ricky Ricardo's profession in I Love Lucy?",
                     ["Bandleader", "Airline pilot", "Sportswriter", "Police officer"], 0,
                     "Ricky sings and leads an orchestra at the Tropicana nightclub."),
        QuestionSeed("What is the name of the boat that strands the castaways in Gilligan's Island?",
                     ["The S.S. Minnow", "The Black Pearl", "The Andrea Gail", "The Orca"], 0,
                     "A three-hour sightseeing tour aboard the S.S. Minnow ends with seven castaways marooned."),
        QuestionSeed("On Jeopardy!, how must contestants normally phrase their responses?",
                     ["As a question", "As a command", "As a quotation", "As a complete sentence"], 0,
                     "The clue is presented as an answer, so the contestant supplies the matching question."),
        QuestionSeed("In Survivor, what meeting usually ends with a contestant being voted out?",
                     ["The Final Reckoning", "The Elimination Room", "The Judges' Table", "Tribal Council"], 3,
                     "Players cast secret votes at Tribal Council, where the host reveals the result."),
        QuestionSeed("What player number does Seong Gi-hun wear in Squid Game?",
                     ["001", "067", "218", "456"], 3,
                     "Gi-hun enters the deadly competition as Player 456."),
        QuestionSeed("What does the word sitcom shorten?",
                     ["Situational commentary", "Situation comedy", "Simulated comedy", "Single-take comedy"], 1,
                     "A sitcom builds recurring comedy around a regular cast and situation."),
        QuestionSeed("What is a television pilot mainly created to do?",
                     ["Test and demonstrate a proposed series", "Recap an entire completed series", "Replace commercial breaks", "Introduce a nightly news broadcast"], 0,
                     "A pilot presents a show's premise and characters so a network or service can evaluate it."),
        QuestionSeed("Which genre includes competition programs such as Survivor and The Amazing Race?",
                     ["Reality television", "Soap opera", "Sketch comedy", "Police procedural"], 0,
                     "Both programs use unscripted competition formats built around real participants."),
        QuestionSeed("What is a single installment of a television series called?",
                     ["An episode", "A chapter", "A reel", "A broadcast segment"], 0,
                     "An episode is one installment of a television series."),
        QuestionSeed("What is a group of episodes released together usually called?",
                     ["A season", "A cycle", "A volume", "A programming block"], 0,
                     "A season is a group of episodes released together under one production run."),
        QuestionSeed("Which streaming service released Stranger Things?",
                     ["Netflix", "Hulu", "Peacock", "Amazon Prime Video"], 0,
                     "Netflix released Stranger Things, which became one of its signature series."),
        QuestionSeed("Which device changes television channels from across the room?",
                     ["A remote control", "A set-top antenna", "A projector", "A satellite dish"], 0,
                     "A remote control sends infrared signals to the television, changing channels without leaving the couch."),
        QuestionSeed("Which award honors excellence in American television?",
                     ["The Emmy", "The Oscar", "The Tony", "The Golden Globe"], 0,
                     "The Emmy honors excellence in American television programming."),
        QuestionSeed("What is the opening sequence with a show's theme music called?",
                     ["The title sequence", "The cold open", "The end card", "The station identification"], 0,
                     "The title sequence opens an episode with the show's theme music and credits."),
        QuestionSeed("What is the first episode of a television series called?",
                     ["The pilot", "The finale", "The teaser", "The reunion"], 0,
                     "A pilot is the first episode, made to show a network whether a series works."),
        QuestionSeed("What is the yellow-skinned animated family from Springfield called?",
                     ["The Simpsons", "The Griffins", "The Belchers", "The Flintstones"], 0,
                     "The Simpsons live in Springfield and became the longest-running American sitcom."),
        QuestionSeed("What is watching many episodes in one sitting called?",
                     ["Binge-watching", "Channel surfing", "Time shifting", "Appointment viewing"], 0,
                     "Binge-watching means viewing many episodes of a series in a single sitting."),
        QuestionSeed("What is a program's regular broadcast time called?",
                     ["Its time slot", "Its call sign", "Its bandwidth", "Its transmission window"], 0,
                     "A time slot is the regular position a program occupies in the schedule."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("What is Jimmy's surname before he adopts the professional name Saul Goodman in Better Call Saul?",
                     ["Hamlin", "McGill", "Wexler", "Ehrmantraut"], 1,
                     "Jimmy McGill gradually remakes himself as the lawyer Saul Goodman."),
        QuestionSeed("Who is Tony Soprano's psychiatrist in The Sopranos?",
                     ["Dr. Jennifer Melfi", "Dr. Elliot Kupferberg", "Dr. Wendy Rhoades", "Dr. Lilian Thurman"], 0,
                     "Tony's sessions with Dr. Melfi frame much of the series' examination of his family and criminal life."),
        QuestionSeed("What is the advertising agency called at the beginning of Mad Men?",
                     ["Sterling Cooper", "McCann Erickson", "Waystar Royco", "Draper Pryce"], 0,
                     "Don Draper begins the series as creative director at Sterling Cooper in 1960."),
        QuestionSeed("Which institution becomes a major focus of The Wire's fourth season?",
                     ["Baltimore's public schools", "The city's hospitals", "The state legislature", "The port authority"], 0,
                     "Season four follows students, teachers, police, and politics surrounding the school system."),
        QuestionSeed("What is the flight number of the plane that crashes at the beginning of Lost?",
                     ["Oceanic 108", "Oceanic 224", "Oceanic 815", "Oceanic 407"], 2,
                     "The survivors were traveling from Sydney to Los Angeles aboard Oceanic Flight 815."),
        QuestionSeed("Whose death drives the central mystery at the beginning of Twin Peaks?",
                     ["Maddy Ferguson", "Audrey Horne", "Shelly Johnson", "Laura Palmer"], 3,
                     "FBI agent Dale Cooper comes to Twin Peaks to investigate Laura Palmer's murder."),
        QuestionSeed("Who is the U.S. president for most of The West Wing?",
                     ["Jed Bartlet", "Frank Underwood", "David Palmer", "Selina Meyer"], 0,
                     "Josiah Jed Bartlet is the fictional president whose administration the series follows."),
        QuestionSeed("What is the name of the regime in The Handmaid's Tale?",
                     ["Panem", "Gilead", "Oceania", "Luthadel"], 1,
                     "Gilead is the authoritarian theocracy that replaces much of the United States."),
        QuestionSeed("Which family is at the center of Arrested Development?",
                     ["The Roys", "The Roses", "The Bluths", "The Gallaghers"], 2,
                     "Michael Bluth tries to hold his wealthy but dysfunctional family together."),
        QuestionSeed("What is the surname of the family forced to move to Schitt's Creek?",
                     ["Rose", "Crane", "Brady", "Pearson"], 0,
                     "The formerly wealthy Rose family rebuilds its life in the town it once bought as a joke."),
        QuestionSeed("What is the name of the college in Community?",
                     ["Hearst College", "Greendale Community College", "California University", "Barden College"], 1,
                     "A Spanish study group becomes an unlikely family at Greendale Community College."),
        QuestionSeed("On 30 Rock, what is Liz Lemon's sketch show renamed after Jack adds a new star?",
                     ["Sports Night", "The Girlie Show", "TGS with Tracy Jordan", "Studio 60 on the Sunset Strip"], 2,
                     "Jack Donaghy rebrands The Girlie Show as TGS with Tracy Jordan after casting Tracy."),
        QuestionSeed("What company does the Roy family control in Succession?",
                     ["Lumon Industries", "E Corp", "Waystar Royco", "Pierce Global Media"], 2,
                     "The Roys battle over leadership of the media and entertainment conglomerate Waystar Royco."),
        QuestionSeed("Who created and stars in Fleabag?",
                     ["Phoebe Waller-Bridge", "Sharon Horgan", "Michaela Coel", "Sally Wainwright"], 0,
                     "Waller-Bridge adapted Fleabag from her one-woman stage play."),
        QuestionSeed("Whom does Larry David play in Curb Your Enthusiasm?",
                     ["A fictionalized version of himself", "A television news anchor", "A retired baseball manager", "A criminal defense lawyer"], 0,
                     "The comedy exaggerates Larry David's public persona and everyday social conflicts."),
        QuestionSeed("Which office does Selina Meyer hold when Veep begins?",
                     ["Secretary of State", "Vice President", "Senate majority leader", "White House chief of staff"], 1,
                     "The series begins with Selina frustrated by the limited influence of the vice presidency."),
        QuestionSeed("What is the name of Buffy's hometown in Buffy the Vampire Slayer?",
                     ["Mystic Falls", "Hawkins", "Sunnydale", "Bon Temps"], 2,
                     "Sunnydale sits above a Hellmouth that attracts supernatural danger."),
        QuestionSeed("Which federal agency employs Mulder and Scully in The X-Files?",
                     ["The CIA", "The FBI", "The NSA", "The U.S. Marshals Service"], 1,
                     "The two FBI agents investigate unusual cases filed under X."),
        QuestionSeed("What are humanity's machine-created enemies called in Battlestar Galactica?",
                     ["Cylons", "Borg", "Cybermen", "Replicators"], 0,
                     "The Cylons evolve from machines created by humans into humanity's near-destroyers."),
        QuestionSeed("What name does the crew give its salvaged warship in The Expanse?",
                     ["Nostromo", "Rocinante", "Serenity", "Daedalus"], 1,
                     "The crew renames the Martian ship Tachi after Don Quixote's horse."),
        QuestionSeed("Which British broadcaster originally aired Black Mirror?",
                     ["BBC Two", "ITV", "Channel 4", "Sky One"], 2,
                     "Black Mirror premiered on Channel 4 in 2011 before later seasons moved to Netflix."),
        QuestionSeed("Which family owns Downton Abbey in the series?",
                     ["The Crawleys", "The Featheringtons", "The Forsytes", "The Durrells"], 0,
                     "The aristocratic Crawley family lives at Downton with its household staff."),
        QuestionSeed("Bridgerton is based on novels by which author?",
                     ["Diana Gabaldon", "Julia Quinn", "Hilary Mantel", "Sally Rooney"], 1,
                     "Each of Julia Quinn's Bridgerton novels centers on a different sibling's romance."),
        QuestionSeed("What academic subject does Chidi teach in The Good Place?",
                     ["Economics", "Linguistics", "Moral philosophy", "Political history"], 2,
                     "Chidi's knowledge of ethics becomes central to the group's attempts to become better people."),
        QuestionSeed("What does the procedure in Severance separate?",
                     ["Work memories from personal memories", "Dreams from waking memories", "Childhood memories from adult memories", "Facts from emotions"], 0,
                     "The procedure creates separate consciousnesses for an employee's work and outside lives."),
        QuestionSeed("What is the name of the apartment building in Only Murders in the Building?",
                     ["The Dakota", "The Arconia", "The Ansonia", "The Belnord"], 1,
                     "Three residents of the fictional Arconia investigate deaths while recording a true-crime podcast."),
        QuestionSeed("Abbott Elementary is set in a public school in which city?",
                     ["Baltimore", "Chicago", "Philadelphia", "Detroit"], 2,
                     "The mockumentary follows teachers at an underfunded Philadelphia elementary school."),
        QuestionSeed("Which organism causes the pandemic in The Last of Us?",
                     ["Cordyceps fungus", "A bacterium", "An alien parasite", "A computer virus"], 0,
                     "The drama imagines a mutated Cordyceps fungus infecting humans."),
        QuestionSeed("Which hacker group recruits Elliot to help erase E Corp's debt records in Mr. Robot?",
                     ["Deus Group", "Lizard Squad", "fsociety", "Cicada 3301"], 2,
                     "Elliot is recruited by fsociety for a plan to erase consumer debt records."),
        QuestionSeed("The television anthology Fargo was inspired by a film made by which filmmaking duo?",
                     ["The Russo brothers", "The Coen brothers", "The Safdie brothers", "The Dardenne brothers"], 1,
                     "The series borrows the 1996 film's setting, tone, and title while telling new stories."),
        QuestionSeed("Which member of Monty Python was American-born?",
                     ["Terry Gilliam", "Terry Jones", "Eric Idle", "Michael Palin"], 0,
                     "Gilliam, born in Minnesota, made the troupe's cut-out animations before becoming a film director."),
        QuestionSeed("From which studio is Saturday Night Live broadcast?",
                     ["Studio 6B", "Studio 8H", "Studio 21", "Studio 54"], 1,
                     "Studio 8H is located at NBC's headquarters in 30 Rockefeller Plaza."),
        QuestionSeed("Who created and hosted the original The Twilight Zone?",
                     ["Rod Serling", "Alfred Hitchcock", "Gene Roddenberry", "Norman Lear"], 0,
                     "Serling wrote many episodes and delivered the show's famous on-screen introductions."),
        QuestionSeed("Which cable news channel launched in 1980 with a 24-hour news format?",
                     ["CNN", "CNBC", "MSNBC", "C-SPAN"], 0,
                     "CNN began broadcasting in June 1980 with a schedule devoted to news around the clock."),
        QuestionSeed("Which character is the outspoken head of the household in All in the Family?",
                     ["George Jefferson", "Archie Bunker", "Fred Sanford", "Howard Cunningham"], 1,
                     "The sitcom uses Archie's prejudices and family arguments to confront social issues."),
        QuestionSeed("At which fictional station does Mary work in The Mary Tyler Moore Show?",
                     ["WKRP", "WJM-TV", "KACL", "WNYX"], 1,
                     "Mary Richards produces the evening news at Minneapolis station WJM-TV."),
        QuestionSeed("What kind of code names do the robbers use in Money Heist?",
                     ["Names of cities", "Names of planets", "Names of composers", "Names of gemstones"], 0,
                     "The crew uses city names such as Tokyo, Berlin, Nairobi, and Rio to conceal real identities."),
        QuestionSeed("By what designation is the protagonist known in The Prisoner?",
                     ["Number One", "Number Six", "Number Nine", "Number Twelve"], 1,
                     "The imprisoned former agent insists that he is a free man, not merely Number Six."),
        QuestionSeed("The space station in Star Trek: Deep Space Nine is located near which planet?",
                     ["Vulcan", "Cardassia Prime", "Bajor", "Qo'noS"], 2,
                     "The station guards a stable wormhole near Bajor and becomes a center of diplomacy and conflict."),
        QuestionSeed("Who narrates the original BBC version of Planet Earth?",
                     ["David Attenborough", "Werner Herzog", "Morgan Freeman", "Brian Cox"], 0,
                     "Attenborough's narration accompanies the BBC nature series' global wildlife footage."),
        QuestionSeed("What is a showrunner responsible for?",
                     ["Leading the writing and production", "Selling advertising slots", "Operating the studio cameras", "Scheduling the entire network lineup"], 0,
                     "A showrunner leads the writing and production, holding creative authority over a series."),
        QuestionSeed("What is a cold open?",
                     ["A scene before the titles", "A silent closing shot", "An unaired pilot episode", "A season finale cliffhanger"], 0,
                     "A cold open is a scene that runs before the title sequence begins."),
        QuestionSeed("What does syndication mean for a television series?",
                     ["Selling reruns to stations", "Filming a spin-off series", "Airing live across networks", "Recording a studio audience"], 0,
                     "Syndication sells reruns of a series to individual stations, often the point where a show profits."),
        QuestionSeed("What does a pilot episode do?",
                     ["Tests a series concept", "Concludes a storyline", "Recaps the previous season", "Introduces a spin-off character"], 0,
                     "A pilot tests a series concept, and networks use it to decide on ordering more."),
        QuestionSeed("What is an anthology series?",
                     ["Each episode tells a new story", "Episodes air out of order", "One story spans every season", "Reruns are packaged and sold together"], 0,
                     "In an anthology series each episode or season tells a new self-contained story."),
        QuestionSeed("What is syndication in television?",
                     ["Selling reruns to many stations", "Filming in several countries", "Merging two networks", "Producing a live international simulcast"], 0,
                     "Syndication means selling reruns to many stations rather than a single network."),
        QuestionSeed("What does a laugh track add to a program?",
                     ["Recorded audience laughter", "A musical score", "Background crowd noise", "Prerecorded applause cues only"], 0,
                     "A laugh track adds recorded audience laughter to comedy that was not filmed live."),
        QuestionSeed("What is a spin-off series built from?",
                     ["Characters from another show", "A cancelled pilot script", "An unused film screenplay", "A rival network's competing format"], 0,
                     "A spin-off takes characters from another show and gives them their own series."),
        QuestionSeed("What does prime time refer to?",
                     ["Peak evening viewing hours", "Early morning programming", "Weekend afternoon slots", "Overnight repeat broadcasts"], 0,
                     "Prime time is the peak evening viewing block when audiences are largest."),
        QuestionSeed("What is a miniseries?",
                     ["A story told in few episodes", "A daily continuing drama", "A weekly variety program", "An unscripted travel documentary"], 0,
                     "A miniseries tells a complete story across a small, fixed number of episodes."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("The name Emmy developed from a nickname for which early television device?",
                     ["The image orthicon camera tube", "The cathode-ray picture tube", "The wireless remote control", "The videotape recorder"], 0,
                     "Immy was a nickname for the image orthicon camera; it was changed to Emmy for the statuette."),
        QuestionSeed("What does the Emmy statuette depict?",
                     ["A winged woman holding an atom", "A seated writer holding a script", "A camera operator beside a tripod", "A globe surrounded by radio waves"], 0,
                     "The wings represent art, while the atom represents the science of television."),
        QuestionSeed("Which university administers the Peabody Awards?",
                     ["Columbia University", "The University of Georgia", "The University of Southern California", "Northwestern University"], 1,
                     "The awards recognize distinguished work in broadcasting, audio, and digital media."),
        QuestionSeed("From which London venue did the BBC launch its television service in 1936?",
                     ["Alexandra Palace", "Royal Albert Hall", "Broadcasting House", "Crystal Palace"], 0,
                     "Studios and transmitters in Alexandra Palace supported the BBC Television Service's 1936 launch."),
        QuestionSeed("What was a kinescope used to do in early television?",
                     ["Record a live television image onto film", "Transmit color signals by satellite", "Measure a program's audience", "Add prerecorded laughter"], 0,
                     "A film camera aimed at a television monitor preserved broadcasts before videotape became practical."),
        QuestionSeed("Which technology can Nielsen use to identify television content in its panel homes?",
                     ["Inaudible audio watermarks", "Visible QR codes", "Satellite weather beacons", "Telephone caller ID"], 0,
                     "Meters can detect inaudible codes embedded in a broadcaster's audio and match viewing to the program."),
        QuestionSeed("What is a teleplay?",
                     ["A script written for a television production", "A rehearsal recorded without sound", "A live promotional interview", "A contract granting a network the right to rerun a program"], 0,
                     "Teleplay is the television counterpart to terms such as screenplay and stage play."),
        QuestionSeed("In U.S. scripted television, what does a showrunner usually oversee?",
                     ["The series' overall creative and production work", "Only the opening-title design", "The network's advertising sales and affiliate scheduling", "The maintenance of studio cameras"], 0,
                     "A showrunner is commonly a senior writer-producer with both creative and managerial authority."),
        QuestionSeed("What is a bottle episode?",
                     ["An episode using few sets and characters", "An episode released without dialogue", "An episode assembled entirely from earlier footage", "An episode filmed as a commercial"], 0,
                     "Bottle episodes contain production costs while often concentrating on character conflict."),
        QuestionSeed("What is a backdoor pilot?",
                     ["A regular series episode that introduces a possible spin-off", "A pilot released only outside its home country", "The final episode produced before cancellation", "A test broadcast hidden from network executives"], 0,
                     "The episode tests new characters or a premise within an already established program."),
        QuestionSeed("What does a television continuity announcer traditionally do?",
                     ["Introduce programs between scheduled broadcasts", "Select camera angles during a live studio production", "Rewrite scripts during rehearsal", "Measure the overnight audience"], 0,
                     "Continuity announcements guide viewers through junctions in a channel's schedule."),
        QuestionSeed("In television comedy post-production, what does sweetening most often refer to?",
                     ["Adding or enhancing audience laughter", "Shortening an episode for reruns", "Replacing dialogue for foreign release", "Brightening the image during colour grading"], 0,
                     "Producers may supplement or replace the laughter captured during a live taping."),
        QuestionSeed("What distinguishes first-run syndication from off-network syndication?",
                     ["It is made for syndication before any network run", "It is a network rerun sold only to local stations", "Every station broadcasts it live within its market", "It is distributed without local commercial breaks"], 0,
                     "First-run syndicated shows are offered directly to stations or outlets without an earlier network run."),
        QuestionSeed("What is a line cut in multi-camera television production?",
                     ["The live-switched edit made during recording", "A script shortened to accommodate commercial breaks", "A rehearsal recorded using only one camera", "A list of dialogue removed by censors"], 0,
                     "A director calls camera changes in real time, creating an immediate edit that can guide post-production."),
        QuestionSeed("How is a single-camera television comedy typically produced?",
                     ["Scenes are filmed setup by setup, much like a feature film", "Every episode is broadcast live from one fixed camera", "Only security-camera footage is used", "Actors perform each episode in chronological order"], 0,
                     "The label describes a production style, even when more than one physical camera is occasionally used."),
        QuestionSeed("What did overscan cause on many analog television sets?",
                     ["The outer edges of the transmitted picture were hidden", "Fast movement appeared in slow motion", "Black-and-white programs gained false color", "Stereo audio collapsed into silence"], 0,
                     "Because CRT displays varied, important action and titles were kept inside safe areas away from the edges."),
        QuestionSeed("What does NTSC stand for in U.S. television history?",
                     ["National Television System Committee", "Network Transmission Standards Council", "National Telecast Service Cooperative", "New Television Signal Code"], 0,
                     "The committee developed analog television standards used in the United States and several other countries."),
        QuestionSeed("Why did daytime serial dramas become known as soap operas?",
                     ["Soap manufacturers frequently sponsored them", "Their earliest stories were set in laundries", "They replaced radio advertisements for detergent", "They were originally performed during cleaning breaks"], 0,
                     "Consumer-goods companies marketed household products to the programs' largely daytime audiences."),
        QuestionSeed("What is strip programming in television scheduling?",
                     ["Scheduling one show in the same weekday slot", "Removing advertisements from premium broadcasts", "Alternating two programs within a single episode", "Running a season's episodes in reverse order"], 0,
                     "A weekday strip builds a predictable viewing habit and is common in daytime and syndication schedules."),
        QuestionSeed("What happens at a television network's upfront presentation?",
                     ["Advertisers preview the network's upcoming schedule", "Actors negotiate each episode's dialogue", "Critics vote on the year's Emmy nominees", "Affiliate stations test their emergency broadcast equipment"], 0,
                     "Networks traditionally use upfronts to promote coming programs and sell advertising commitments."),
        QuestionSeed("In The Twilight Zone episode Time Enough at Last, what does Henry Bemis most love to do?",
                     ["Read books", "Play chess", "Collect clocks", "Watch baseball"], 0,
                     "After finally finding time to read, Bemis breaks the glasses he needs to see the books."),
        QuestionSeed("What is the title of the feature-length series finale of M*A*S*H?",
                     ["Goodbye, Farewell and Amen", "Abyssinia, Henry", "The Long Goodbye", "Goodnight, Seattle"], 0,
                     "The 1983 finale follows the unit as the Korean War approaches its end."),
        QuestionSeed("What is the call sign of the radio station where Frasier Crane works in Frasier?",
                     ["WKRP", "WJM", "KACL", "KQED"], 2,
                     "Frasier hosts a call-in psychiatry program on the fictional Seattle station KACL."),
        QuestionSeed("The Breaking Bad episode title Ozymandias refers to a poem by whom?",
                     ["William Blake", "Walt Whitman", "Percy Bysshe Shelley", "Samuel Taylor Coleridge"], 2,
                     "Shelley's poem describes the ruins of a once-powerful ruler's monument."),
        QuestionSeed("What is Don Draper's birth name in Mad Men?",
                     ["Dick Whitman", "Don Whitaker", "Adam Draper", "Roger Dickson"], 0,
                     "He assumes the identity of Lieutenant Don Draper during the Korean War."),
        QuestionSeed("Which part of Baltimore becomes the main institutional focus of The Wire's second season?",
                     ["The docks and stevedores' union", "The public school system", "City Hall", "The newspaper newsroom"], 0,
                     "Season two examines smuggling and economic decline through workers at the port."),
        QuestionSeed("What is the name of the Dharma Initiative station inside the hatch in Lost?",
                     ["The Pearl", "The Orchid", "The Swan", "The Hydra"], 2,
                     "The Swan station requires its occupants to enter a code every 108 minutes."),
        QuestionSeed("What is the name of the Fisher family's business in Six Feet Under?",
                     ["Fisher & Sons Funeral Home", "Rosewood Memorial Chapel", "Diaz Family Mortuary", "Westwood Eternal Care"], 0,
                     "The Fishers live above and operate their Los Angeles funeral home."),
        QuestionSeed("Deadwood is set in which nineteenth-century U.S. territory?",
                     ["Oregon Territory", "Dakota Territory", "New Mexico Territory", "Utah Territory"], 1,
                     "The mining camp of Deadwood lies in the Black Hills before South Dakota became a state."),
        QuestionSeed("Boardwalk Empire's Nucky Thompson was modeled partly on which Atlantic City political boss?",
                     ["Enoch L. Johnson", "Boss Tweed", "Frank Hague", "Tom Pendergast"], 0,
                     "The fictional Nucky shares Johnson's nickname, political influence, and Prohibition-era setting."),
        QuestionSeed("What business provides the Jennings family's cover in The Americans?",
                     ["A travel agency", "A dental practice", "A hardware store", "An accounting firm"], 0,
                     "The Soviet spies pose as a suburban married couple who run Dupont Circle Travel."),
        QuestionSeed("What company employs Joe MacMillan and Gordon Clark at the beginning of Halt and Catch Fire?",
                     ["Mutiny", "Cardiff Electric", "Westgroup Energy", "NeXT Computer"], 1,
                     "At Cardiff Electric, they attempt to reverse-engineer an IBM PC and build a competing computer."),
        QuestionSeed("What is the name of the traveling theater and music troupe in Station Eleven?",
                     ["The Traveling Symphony", "The Wheel of Fire", "The Understudy Company", "The Lakeshore Players"], 0,
                     "The troupe circles the Great Lakes performing Shakespeare and music after the pandemic."),
        QuestionSeed("Who wrote the fictional book A Journey Through Time in Dark?",
                     ["H. G. Tannhaus", "Claudia Tiedemann", "Bernd Doppler", "Bartosz Tiedemann"], 0,
                     "Clockmaker H. G. Tannhaus becomes entangled in Winden's repeating cycles of time travel."),
        QuestionSeed("Which historical event is depicted at the beginning of Watchmen's first episode?",
                     ["The 1921 Tulsa Race Massacre", "The 1963 March on Washington", "The 1969 Stonewall uprising", "The 1992 Los Angeles riots"], 0,
                     "The opening connects the destruction of Tulsa's Greenwood district to the series' alternate-history story."),
        QuestionSeed("In The Leftovers, approximately what share of the world's population vanishes in the Sudden Departure?",
                     ["Two percent", "Ten percent", "Twenty-five percent", "Half"], 0,
                     "About 140 million people disappear without explanation on October 14."),
        QuestionSeed("What was the space station Babylon 5 built primarily to provide?",
                     ["Neutral ground for diplomacy and trade", "A prison for interstellar criminals", "A shipyard for a human invasion fleet", "A laboratory for time travel"], 0,
                     "The station brings multiple species together after a devastating interstellar war."),
        QuestionSeed("What is Moya in Farscape?",
                     ["A living spacecraft", "A wormhole weapon", "A prison planet", "A peacekeeping android"], 0,
                     "Moya is a Leviathan, a sentient bio-mechanical ship carrying the escaped crew."),
        QuestionSeed("Who created the android Data in Star Trek: The Next Generation?",
                     ["Dr. Noonien Soong", "Dr. Zefram Cochrane", "Dr. Lewis Zimmerman", "Dr. Richard Daystrom"], 0,
                     "Soong also created related androids including Lore and B-4."),
        QuestionSeed("What is the title of Buffy the Vampire Slayer's musical episode?",
                     ["Once More, with Feeling", "The Song Remains the Same", "A Musical Emergency", "Restless"], 0,
                     "A demon compels Sunnydale's residents to sing their hidden feelings aloud."),
    ]
}
