import Foundation

enum VideoGameQuestions {
    static let seeds = CategorySeeds(easy: easy, medium: medium, hard: hard)

    static let easy: [QuestionSeed] = [
        QuestionSeed("Which company created the Super Mario series?",
                     ["Nintendo", "Sega", "Capcom", "Konami"], 0,
                     "Nintendo created Super Mario, and the character became the company's mascot."),
        QuestionSeed("What is the name of Mario's brother?",
                     ["Wario", "Luigi", "Toad", "Waluigi"], 1,
                     "Luigi is Mario's taller brother and a playable character across the series."),
        QuestionSeed("Who is the hero of The Legend of Zelda series?",
                     ["Ganon", "Impa", "Link", "Sheik"], 2,
                     "Link is the green-clad hero of The Legend of Zelda, despite the series title."),
        QuestionSeed("Which yellow electric creature represents Pokemon?",
                     ["Eevee", "Charizard", "Snorlax", "Pikachu"], 3,
                     "Pikachu is the electric mouse that became the face of the Pokemon franchise."),
        QuestionSeed("Which blue hedgehog is Sega's mascot?",
                     ["Sonic", "Knuckles", "Shadow", "Tails"], 0,
                     "Sonic the Hedgehog is Sega's blue mascot, defined by his running speed."),
        QuestionSeed("Which game is built around mining and placing blocks?",
                     ["Terraria", "Minecraft", "Roblox", "Fortnite"], 1,
                     "Minecraft is the block-building game where players mine materials and construct worlds."),
        QuestionSeed("Which puzzle game has players fit falling shapes into rows?",
                     ["Bejeweled", "Columns", "Tetris", "Puyo Puyo"], 2,
                     "Tetris has players rotate falling blocks to complete and clear horizontal rows."),
        QuestionSeed("Which arcade character eats dots while avoiding ghosts?",
                     ["Dig Dug", "Q*bert", "Frogger", "Pac-Man"], 3,
                     "Pac-Man eats dots through a maze while four ghosts pursue him."),
        QuestionSeed("Which large ape is the title character of a classic arcade game?",
                     ["Donkey Kong", "King Kong", "Rampage", "Congo Bongo"], 0,
                     "Donkey Kong is the barrel-throwing ape from the 1981 arcade game of that name."),
        QuestionSeed("Which pink round Nintendo character swallows enemies?",
                     ["Jigglypuff", "Kirby", "Ness", "Olimar"], 1,
                     "Kirby is the pink character who inhales enemies and copies their abilities."),
        QuestionSeed("Which battle royale game features building structures?",
                     ["Apex Legends", "PUBG", "Fortnite", "Warzone"], 2,
                     "Fortnite pairs battle royale combat with the ability to build walls and ramps."),
        QuestionSeed("Which game has players launch birds at pigs?",
                     ["Cut the Rope", "Doodle Jump", "Fruit Ninja", "Angry Birds"], 3,
                     "Angry Birds has players launch birds from a slingshot at structures sheltering pigs."),
        QuestionSeed("Which arcade game has players shoot descending aliens?",
                     ["Space Invaders", "Galaga", "Asteroids", "Defender"], 0,
                     "Space Invaders has players shoot rows of aliens that descend steadily toward the base."),
        QuestionSeed("Which game character is a treasure-hunting archaeologist?",
                     ["Nathan Drake", "Lara Croft", "Rick Dangerous", "Indiana Jones"], 1,
                     "Lara Croft is the archaeologist at the center of the Tomb Raider series."),
        QuestionSeed("Which armored soldier is the hero of Halo?",
                     ["Cortana", "Sergeant Johnson", "Master Chief", "Arbiter"], 2,
                     "Master Chief is the armored super-soldier who leads the Halo series."),
        QuestionSeed("Which console did Sony release under the PlayStation name?",
                     ["Dreamcast", "Saturn", "Jaguar", "PlayStation 2"], 3,
                     "The PlayStation 2 is one of several consoles Sony released under the PlayStation name."),
        QuestionSeed("Which Nintendo console uses detachable Joy-Con controllers?",
                     ["Switch", "Wii U", "GameCube", "Game Boy"], 0,
                     "The Nintendo Switch uses detachable Joy-Con controllers and plays docked or handheld."),
        QuestionSeed("Which handheld console did Nintendo release in 1989?",
                     ["Game Gear", "Game Boy", "Lynx", "Neo Geo Pocket"], 1,
                     "The Game Boy was Nintendo's 1989 handheld and sold for years on its battery life."),
        QuestionSeed("Which company makes the Xbox console?",
                     ["Sony", "Nintendo", "Microsoft", "Atari"], 2,
                     "Microsoft makes the Xbox, which it first released in 2001."),
        QuestionSeed("Which game series features trainers catching creatures in balls?",
                     ["Digimon", "Yo-kai Watch", "Monster Rancher", "Pokemon"], 3,
                     "Pokemon has trainers catch creatures in Poke Balls and battle with them."),
        QuestionSeed("Who is Mario's spiky-shelled arch-enemy?",
                     ["Bowser", "Kamek", "Birdo", "Boom Boom"], 0,
                     "Bowser is the spiked turtle king who repeatedly kidnaps Princess Peach."),
        QuestionSeed("Which green dinosaur does Mario ride?",
                     ["Rex", "Yoshi", "Petey", "Dorrie"], 1,
                     "Yoshi is the green dinosaur Mario rides, able to swallow enemies with his tongue."),
        QuestionSeed("What does Mario collect throughout his games?",
                     ["Gems", "Rings", "Coins", "Stars"], 2,
                     "Mario collects coins, and gathering one hundred traditionally earns an extra life."),
        QuestionSeed("Which Nintendo racing game features item boxes and shells?",
                     ["F-Zero", "Excitebike", "Wave Race", "Mario Kart"], 3,
                     "Mario Kart is the racing series where drivers grab item boxes and fire shells."),
        QuestionSeed("Which early arcade game simulates table tennis?",
                     ["Pong", "Breakout", "Combat", "Tank"], 0,
                     "Pong is the early arcade game that simulates table tennis with two paddles and a dot."),
        QuestionSeed("Which fighting game features Ryu and Ken?",
                     ["Tekken", "Street Fighter", "Virtua Fighter", "Soulcalibur"], 1,
                     "Street Fighter features Ryu and Ken, rivals trained in the same martial art."),
        QuestionSeed("Which social deduction game asks players to find impostors?",
                     ["Fall Guys", "Rust", "Among Us", "Phasmophobia"], 2,
                     "Among Us asks a crew to identify the impostors hidden among them aboard a ship."),
        QuestionSeed("Which life simulation game has players build a household?",
                     ["Harvest Moon", "Animal Crossing", "Stardew Valley", "The Sims"], 3,
                     "The Sims has players build homes and guide the daily lives of simulated people."),
        QuestionSeed("Which Nintendo series has villagers living on your island?",
                     ["Animal Crossing", "Pikmin", "Splatoon", "Nintendogs"], 0,
                     "Animal Crossing has animal villagers share an island where time passes in real hours."),
        QuestionSeed("Which platform lets users publish and play user-made games?",
                     ["Steam", "Roblox", "Itch", "Origin"], 1,
                     "Roblox lets users build and publish their own games for other players."),
        QuestionSeed("What color are the ghosts chasing Pac-Man when he can eat them?",
                     ["Green", "Yellow", "Blue", "White"], 2,
                     "The ghosts turn blue after Pac-Man eats a power pellet, and can then be eaten."),
        QuestionSeed("Which sandbox series lets players roam a crime-filled city?",
                     ["Watch Dogs", "Saints Row", "Mafia", "Grand Theft Auto"], 3,
                     "Grand Theft Auto drops players into open cities built around crime and driving."),
        QuestionSeed("Which game has players guide a frog across a busy road?",
                     ["Frogger", "Crossy Road", "Toad Treasure", "Leap Day"], 0,
                     "Frogger has players guide a frog across traffic and a river to reach safety."),
        QuestionSeed("Which company published the Legend of Zelda series?",
                     ["Bandai", "Nintendo", "Square", "Enix"], 1,
                     "Nintendo published The Legend of Zelda, beginning with the 1986 original."),
        QuestionSeed("Which bounty hunter stars in the Metroid series?",
                     ["Bayonetta", "Zero Suit", "Samus Aran", "Ridley"], 2,
                     "Samus Aran is the armored bounty hunter at the center of the Metroid series."),
        QuestionSeed("Which fighting series is known for the phrase Finish Him?",
                     ["Killer Instinct", "Def Jam", "Bloody Roar", "Mortal Kombat"], 3,
                     "Mortal Kombat is known for the Finish Him prompt before a finishing move."),
        QuestionSeed("Which military shooter series began in 2003?",
                     ["Call of Duty", "Battlefield", "Medal of Honor", "Rainbow Six"], 0,
                     "Call of Duty began in 2003 and grew into an annual military shooter series."),
        QuestionSeed("Which match-three mobile game features colored candies?",
                     ["Bubble Witch", "Candy Crush Saga", "Gardenscapes", "Toon Blast"], 1,
                     "Candy Crush Saga is the match-three puzzle game built around swapping colored candies."),
        QuestionSeed("Which console did Nintendo release with motion controls in 2006?",
                     ["GameCube", "DS", "Wii", "3DS"], 2,
                     "The Wii launched in 2006 and used a motion-sensing remote as its main controller."),
        QuestionSeed("Which princess does Mario most often rescue?",
                     ["Daisy", "Rosalina", "Pauline", "Peach"], 3,
                     "Princess Peach rules the Mushroom Kingdom and is the one Mario most often rescues."),
    ]

    static let medium: [QuestionSeed] = [
        QuestionSeed("Which studio developed the Portal series?",
                     ["Valve", "Bungie", "Bethesda", "Arkane"], 0,
                     "Valve developed Portal, built around a gun that opens linked portals."),
        QuestionSeed("Which game series is set in the post-nuclear American wasteland?",
                     ["Rage", "Fallout", "Metro", "Wasteland"], 1,
                     "Fallout is set in a post-nuclear America styled after mid-century visions of the future."),
        QuestionSeed("Which Bethesda game is set in the province of Skyrim?",
                     ["Oblivion", "Morrowind", "The Elder Scrolls V", "Daggerfall"], 2,
                     "The Elder Scrolls V is subtitled Skyrim and is set in that northern province."),
        QuestionSeed("Which series follows assassins through historical settings?",
                     ["Dishonored", "Hitman", "Thief", "Assassin's Creed"], 3,
                     "Assassin's Creed sends players through historical cities as members of an assassin order."),
        QuestionSeed("Which series is known for punishing difficulty and bonfires?",
                     ["Dark Souls", "Nioh", "Bloodborne", "Sekiro"], 0,
                     "Dark Souls is known for punishing combat and bonfires that serve as checkpoints."),
        QuestionSeed("Which underwater city is the setting of BioShock?",
                     ["Columbia", "Rapture", "Atlantis", "Hydropolis"], 1,
                     "Rapture is the ruined undersea city where the first BioShock takes place."),
        QuestionSeed("Which Valve game stars physicist Gordon Freeman?",
                     ["Team Fortress", "Half-Life", "Left 4 Dead", "Counter-Strike"], 2,
                     "Half-Life stars Gordon Freeman, a physicist caught in a research facility disaster."),
        QuestionSeed("Which series follows Solid Snake on stealth missions?",
                     ["Splinter Cell", "Syphon Filter", "Tenchu", "Metal Gear"], 3,
                     "Metal Gear follows Solid Snake through stealth missions against walking nuclear tanks."),
        QuestionSeed("Which survival horror series features the Umbrella Corporation?",
                     ["Resident Evil", "Silent Hill", "Dead Space", "Outlast"], 0,
                     "Resident Evil centers on outbreaks engineered by the Umbrella Corporation."),
        QuestionSeed("Which farming game was largely made by one developer?",
                     ["Harvest Moon", "Stardew Valley", "Rune Factory", "My Time at Portia"], 1,
                     "Stardew Valley was built largely by a single developer, Eric Barone."),
        QuestionSeed("Which indie game features a child fallen into a monster-filled underground?",
                     ["Celeste", "Hollow Knight", "Undertale", "Ori"], 2,
                     "Undertale follows a child who falls underground and may spare every monster met."),
        QuestionSeed("Which hand-drawn game imitates 1930s cartoons?",
                     ["Gris", "Hollow Knight", "Rayman", "Cuphead"], 3,
                     "Cuphead imitates 1930s rubber-hose animation, drawn and inked by hand."),
        QuestionSeed("Which Nintendo game has teams cover a map in colored ink?",
                     ["Splatoon", "Arms", "Pikmin", "Nintendo Land"], 0,
                     "Splatoon has squid-like teams spread colored ink to claim territory."),
        QuestionSeed("Which crossover fighting series pits Nintendo characters together?",
                     ["Mario Party", "Super Smash Bros.", "Nintendo World", "Mario Sports"], 1,
                     "Super Smash Bros. is the crossover fighting series that gathers Nintendo characters."),
        QuestionSeed("Which strategy series asks players to build a civilization across history?",
                     ["Age of Empires", "Total War", "Civilization", "Anno"], 2,
                     "Civilization has players guide a nation from ancient settlement to the space age."),
        QuestionSeed("Which real-time strategy series features Terran, Zerg and Protoss?",
                     ["Command and Conquer", "Warcraft", "Homeworld", "StarCraft"], 3,
                     "StarCraft is built around three factions: Terran, Zerg, and Protoss."),
        QuestionSeed("Which team shooter features heroes such as Tracer and Reinhardt?",
                     ["Overwatch", "Paladins", "Valorant", "Apex Legends"], 0,
                     "Overwatch is the hero shooter whose roster includes Tracer and Reinhardt."),
        QuestionSeed("Which game popularized the term MOBA alongside Dota?",
                     ["Smite", "League of Legends", "Heroes of Newerth", "Battlerite"], 1,
                     "League of Legends helped popularize the MOBA genre alongside Dota."),
        QuestionSeed("Which series features the treasure hunter Nathan Drake?",
                     ["Tomb Raider", "Just Cause", "Uncharted", "Far Cry"], 2,
                     "Uncharted follows Nathan Drake, a treasure hunter pursuing historical mysteries."),
        QuestionSeed("Which western game series is set in the dying days of the frontier?",
                     ["Gun", "Call of Juarez", "Desperados", "Red Dead"], 3,
                     "Red Dead is set in the closing years of the American frontier."),
        QuestionSeed("Which role-playing series began with a game about crystals in 1987?",
                     ["Final Fantasy", "Dragon Quest", "Phantasy Star", "Ys"], 0,
                     "Final Fantasy began in 1987 and built its early stories around elemental crystals."),
        QuestionSeed("Which action role-playing series has players fight through hell?",
                     ["Torchlight", "Diablo", "Path of Exile", "Grim Dawn"], 1,
                     "Diablo sends players through dungeons and hell itself hunting demonic bosses."),
        QuestionSeed("Which city-building game did Will Wright design in 1989?",
                     ["Caesar", "Pharaoh", "SimCity", "Utopia"], 2,
                     "SimCity, designed by Will Wright in 1989, made city planning itself the game."),
        QuestionSeed("Which rolling game has players gather objects into a growing ball?",
                     ["Rock of Ages", "Marble Madness", "Super Monkey Ball", "Katamari Damacy"], 3,
                     "Katamari Damacy has players roll a ball that collects ever larger objects."),
        QuestionSeed("Which wordless game sends players toward a distant mountain?",
                     ["Journey", "Abzu", "Flower", "Rime"], 0,
                     "Journey sends a robed traveler toward a distant mountain without spoken dialogue."),
        QuestionSeed("Which platformer follows a climber ascending a mountain?",
                     ["Getting Over It", "Celeste", "Jump King", "Grow Home"], 1,
                     "Celeste follows Madeline as she climbs a mountain, with assist options for accessibility."),
        QuestionSeed("Which insect-filled game explores the ruined kingdom of Hallownest?",
                     ["Ori", "Axiom Verge", "Hollow Knight", "Blasphemous"], 2,
                     "Hollow Knight explores Hallownest, a fallen underground kingdom of insects."),
        QuestionSeed("Which Nintendo series has players command small plant-like creatures?",
                     ["Chibi-Robo", "Kirby", "Yoshi", "Pikmin"], 3,
                     "Pikmin has players direct swarms of small plant-like creatures to solve tasks."),
        QuestionSeed("Which Nintendo series features a squadron of animal pilots?",
                     ["Star Fox", "F-Zero", "Sin and Punishment", "Steel Diver"], 0,
                     "Star Fox follows Fox McCloud and his squadron of animal pilots in space combat."),
        QuestionSeed("Which racing series is known for extreme speed and anti-gravity craft?",
                     ["Ridge Racer", "F-Zero", "Wipeout", "Burnout"], 1,
                     "F-Zero is Nintendo's anti-gravity racing series known for extreme speed."),
        QuestionSeed("Which horror series is set in a fog-covered American town?",
                     ["Alan Wake", "Deadly Premonition", "Silent Hill", "Fatal Frame"], 2,
                     "Silent Hill is set in a fog-covered town where the environment shifts around the player."),
        QuestionSeed("Which puzzle game features a companion cube?",
                     ["The Witness", "Antichamber", "Talos Principle", "Portal"], 3,
                     "Portal features the Weighted Companion Cube, a puzzle object players carry."),
        QuestionSeed("Which rhythm series has players match notes on a plastic guitar?",
                     ["Guitar Hero", "Rock Band", "Dance Dance Revolution", "Amplitude"], 0,
                     "Guitar Hero has players match scrolling notes on a plastic guitar controller."),
        QuestionSeed("Which game series is set in the Mushroom Kingdom's board-game spinoffs?",
                     ["Mario Golf", "Mario Party", "Mario Tennis", "Mario Strikers"], 1,
                     "Mario Party turns the Mushroom Kingdom into a board game punctuated by minigames."),
        QuestionSeed("Which shooter series features the Covenant as enemies?",
                     ["Destiny", "Killzone", "Halo", "Gears of War"], 2,
                     "Halo pits humanity against the Covenant, an alliance of alien species."),
        QuestionSeed("Which game has players survive nights against animatronic characters?",
                     ["Bendy", "Poppy Playtime", "Dead by Daylight", "Five Nights at Freddy's"], 3,
                     "Five Nights at Freddy's has players survive night shifts watching hostile animatronics."),
        QuestionSeed("Which sports series is published annually under the FIFA or EA name?",
                     ["EA Sports soccer", "Pro Evolution", "Football Manager", "Sensible Soccer"], 0,
                     "EA Sports publishes the annual soccer series known for years under the FIFA name."),
        QuestionSeed("Which studio created the Uncharted and Last of Us series?",
                     ["Insomniac", "Naughty Dog", "Sucker Punch", "Guerrilla"], 1,
                     "Naughty Dog created both Uncharted and The Last of Us."),
        QuestionSeed("Which cooperative game has players prepare meals under time pressure?",
                     ["Cooking Mama", "Diner Dash", "Overcooked", "PlateUp"], 2,
                     "Overcooked has teams prepare and serve meals in kitchens that fall apart around them."),
        QuestionSeed("Which digital store did Valve launch in 2003?",
                     ["Origin", "GOG", "Epic Games Store", "Steam"], 3,
                     "Valve launched Steam in 2003, and it became the largest PC game storefront."),
    ]

    static let hard: [QuestionSeed] = [
        QuestionSeed("Who designed Super Mario Bros. and The Legend of Zelda?",
                     ["Shigeru Miyamoto", "Satoru Iwata", "Gunpei Yokoi", "Takashi Tezuka"], 0,
                     "Shigeru Miyamoto designed Super Mario Bros. and The Legend of Zelda for Nintendo."),
        QuestionSeed("Who created the Metal Gear series?",
                     ["Yoko Taro", "Hideo Kojima", "Goichi Suda", "Fumito Ueda"], 1,
                     "Hideo Kojima created Metal Gear and directed its stealth-focused sequels."),
        QuestionSeed("Which company did Nolan Bushnell co-found in 1972?",
                     ["Midway", "Namco", "Atari", "Taito"], 2,
                     "Nolan Bushnell co-founded Atari in 1972, the year Pong reached arcades."),
        QuestionSeed("Which 1972 device is considered the first home game console?",
                     ["Atari 2600", "Fairchild Channel F", "Intellivision", "Magnavox Odyssey"], 3,
                     "The Magnavox Odyssey reached homes in 1972 and is considered the first home console."),
        QuestionSeed("Who is credited with designing the Magnavox Odyssey?",
                     ["Ralph Baer", "Ted Dabney", "Al Alcorn", "Jerry Lawson"], 0,
                     "Ralph Baer designed the prototype that became the Magnavox Odyssey, earning him the title father of video games."),
        QuestionSeed("Which market collapse struck the North American game industry in 1983?",
                     ["The arcade freeze", "The video game crash", "The console embargo", "The software panic"], 1,
                     "The video game crash of 1983 wiped out much of the North American console market."),
        QuestionSeed("Which console revived the American market after 1983?",
                     ["Sega Master System", "Atari 7800", "Nintendo Entertainment System", "The Commodore 64 home computer"], 2,
                     "The Nintendo Entertainment System revived the American console market after the 1983 crash."),
        QuestionSeed("Which studio created Doom and Quake?",
                     ["3D Realms", "Epic", "Raven", "id Software"], 3,
                     "id Software created Doom and Quake, defining the early first-person shooter."),
        QuestionSeed("Which programmer was id Software's lead engine developer?",
                     ["John Carmack", "John Romero", "Tom Hall", "Adrian Carmack"], 0,
                     "John Carmack wrote the engines behind Doom and Quake at id Software."),
        QuestionSeed("Which 1992 id Software game preceded Doom?",
                     ["Catacomb", "Wolfenstein 3D", "Hovertank", "Rise of the Triad"], 1,
                     "Wolfenstein 3D arrived in 1992 and set the template Doom would refine."),
        QuestionSeed("Which 1993 adventure game became a landmark CD-ROM release?",
                     ["The 7th Guest", "Riven", "Myst", "Grim Fandango"], 2,
                     "Myst was a landmark CD-ROM adventure and a driver of early disc drive adoption."),
        QuestionSeed("Which Sega console launched in North America in 1999?",
                     ["Saturn", "32X", "Game Gear", "Dreamcast"], 3,
                     "The Dreamcast launched in 1999 and was Sega's final home console."),
        QuestionSeed("Which Nintendo console failed commercially after its 1995 release?",
                     ["Virtual Boy", "64DD", "Satellaview", "e-Reader"], 0,
                     "The Virtual Boy was pulled within a year of its 1995 release after poor sales."),
        QuestionSeed("Who created the Sims and SimCity?",
                     ["Peter Molyneux", "Will Wright", "Sid Meier", "Chris Sawyer"], 1,
                     "Will Wright created SimCity and later The Sims at Maxis."),
        QuestionSeed("Which designer's name appears in the Civilization series title?",
                     ["Brian Reynolds", "Bruce Shelley", "Sid Meier", "Soren Johnson"], 2,
                     "Sid Meier's name appears in the Civilization title, a branding habit of his publisher."),
        QuestionSeed("Who created the original Final Fantasy?",
                     ["Yuji Horii", "Tetsuya Nomura", "Yoshinori Kitase", "Hironobu Sakaguchi"], 3,
                     "Hironobu Sakaguchi created Final Fantasy, naming it for what he expected to be his last game."),
        QuestionSeed("Who led development of the original Sonic the Hedgehog?",
                     ["Yuji Naka", "Yu Suzuki", "Rieko Kodama", "Hirokazu Yasuhara"], 0,
                     "Yuji Naka led the programming on the original Sonic the Hedgehog at Sega."),
        QuestionSeed("Who designed the Game Boy for Nintendo?",
                     ["Masayuki Uemura", "Gunpei Yokoi", "Genyo Takeda", "Ken Kutaragi"], 1,
                     "Gunpei Yokoi designed the Game Boy, favoring proven cheap parts over cutting-edge ones."),
        QuestionSeed("Who is credited as the principal architect of the PlayStation?",
                     ["Shuhei Yoshida", "Kaz Hirai", "Ken Kutaragi", "Akira Sato"], 2,
                     "Ken Kutaragi drove the PlayStation project at Sony and is called its father."),
        QuestionSeed("Which Nintendo president led the company from 2002 to 2015?",
                     ["Hiroshi Yamauchi", "Tatsumi Kimishima", "Shuntaro Furukawa", "Satoru Iwata"], 3,
                     "Satoru Iwata led Nintendo from 2002 until his death in 2015, having begun as a programmer."),
        QuestionSeed("Who originally created Minecraft?",
                     ["Markus Persson", "Jens Bergensten", "Daniel Rosenfeld", "Carl Manneh"], 0,
                     "Markus Persson created Minecraft before Mojang was sold to Microsoft."),
        QuestionSeed("Which Soviet programmer created Tetris?",
                     ["Vladimir Pokhilko", "Alexey Pajitnov", "Nikolai Belikov", "Vadim Gerasimov"], 1,
                     "Alexey Pajitnov created Tetris in 1984 while working at a Soviet computing center."),
        QuestionSeed("Which 1980 game is the ancestor of the roguelike genre?",
                     ["NetHack", "Moria", "Rogue", "Angband"], 2,
                     "Rogue, released around 1980, gave the roguelike genre its name and its permadeath."),
        QuestionSeed("Which button sequence is known as the Konami Code?",
                     ["Down, down, left, right", "Left, right, left, right", "A, B, A, B, start", "Up, up, down, down"], 3,
                     "The Konami Code begins up, up, down, down and continues with left, right, left, right, B, A."),
        QuestionSeed("Which 1997 game is credited with popularizing the graphical MMORPG?",
                     ["Ultima Online", "EverQuest", "Meridian 59", "Asheron's Call"], 0,
                     "Ultima Online launched in 1997 and brought the graphical MMORPG to a wide audience."),
        QuestionSeed("Which Blizzard MMORPG launched in 2004?",
                     ["Guild Wars", "World of Warcraft", "City of Heroes", "Lineage II"], 1,
                     "World of Warcraft launched in 2004 and became the defining subscription MMORPG."),
        QuestionSeed("Which unsold Atari cartridges were famously buried in New Mexico?",
                     ["Pac-Man", "Pitfall", "E.T. the Extra-Terrestrial", "Yars' Revenge and Missile Command"], 2,
                     "Unsold E.T. the Extra-Terrestrial cartridges were buried in a New Mexico landfill in 1983."),
        QuestionSeed("Which Sega arcade designer made Virtua Fighter and Shenmue?",
                     ["Toshihiro Nagoshi", "Yuji Naka", "Hideki Sato", "Yu Suzuki"], 3,
                     "Yu Suzuki directed Virtua Fighter and Shenmue during Sega's arcade dominance."),
        QuestionSeed("Which term describes completing a game as fast as possible?",
                     ["Speedrunning", "Ghosting", "Rushing", "Sequence play"], 0,
                     "Speedrunning is the practice of completing a game as quickly as possible, often using glitches."),
        QuestionSeed("Which live streaming service became the main home of game broadcasting?",
                     ["Mixer", "Twitch", "Caffeine", "Ustream"], 1,
                     "Twitch became the primary platform for streaming games to a live audience."),
        QuestionSeed("Which 1998 Nintendo 64 release is often cited among the finest games made?",
                     ["Banjo-Kazooie", "GoldenEye 007", "Ocarina of Time", "Perfect Dark"], 2,
                     "Ocarina of Time arrived in 1998 and is routinely placed among the finest games made."),
        QuestionSeed("Which technique lets a game world load without visible level breaks?",
                     ["Frame pacing", "Sprite batching", "Occlusion mapping", "Streaming"], 3,
                     "Streaming loads world data continuously in the background so no loading screen interrupts play."),
        QuestionSeed("What does the term sandbox describe in game design?",
                     ["A free-form world", "A tutorial area", "A testing build", "A save and checkpoint system"], 0,
                     "A sandbox is a free-form world where players set their own goals rather than follow a fixed path."),
        QuestionSeed("Which genre name comes from combining two Nintendo series?",
                     ["Soulslike", "Metroidvania", "Roguelite", "Boomer shooter"], 1,
                     "Metroidvania combines Metroid and Castlevania, naming games built on interconnected maps."),
        QuestionSeed("What does the abbreviation NPC stand for?",
                     ["New player content", "Network play client", "Non-player character", "Native processing core"], 2,
                     "NPC stands for non-player character, meaning any character the game itself controls."),
        QuestionSeed("Which company developed the Souls series and Elden Ring?",
                     ["Atlus", "Platinum", "Capcom", "FromSoftware"], 3,
                     "FromSoftware developed the Souls series and Elden Ring under director Hidetaka Miyazaki."),
        QuestionSeed("Which 2001 game introduced the character Cortana?",
                     ["Halo: Combat Evolved", "Metroid Prime", "Deus Ex", "System Shock 2"], 0,
                     "Halo: Combat Evolved launched with the Xbox in 2001 and introduced Cortana."),
        QuestionSeed("Which Rockstar game popularized the modern open-world crime template?",
                     ["Driver", "Grand Theft Auto III", "True Crime", "The Getaway"], 1,
                     "Grand Theft Auto III moved the series into three dimensions and set the open-world crime template."),
        QuestionSeed("What does the term emulation mean in gaming?",
                     ["Copying an art style", "Sharing save files", "Running software for other hardware", "Testing a build for compatibility bugs"], 2,
                     "Emulation means running software written for one system on hardware it was never built for."),
        QuestionSeed("Which input delay measure matters most to competitive players?",
                     ["Bitrate", "Draw distance", "Texture depth", "Latency"], 3,
                     "Latency measures the delay between an input and its effect, and competitive players prize low latency."),
    ]
}
